In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

### 데이터 01

In [2]:
df11=pd.read_parquet(r'train/1.회원정보/201807_train_.parquet')
df12=pd.read_parquet(r'train/1.회원정보/201808_train_.parquet')
df13=pd.read_parquet(r'train/1.회원정보/201809_train_.parquet')
df14=pd.read_parquet(r'train/1.회원정보/201810_train_.parquet')
df15=pd.read_parquet(r'train/1.회원정보/201811_train_.parquet')
df16=pd.read_parquet(r'train/1.회원정보/201812_train_.parquet')

In [3]:
tg_df = pd.concat([df11['Segment'], df12['Segment'], df13['Segment'], df14['Segment'], df15['Segment'], df16['Segment']])
tg_df.reset_index(inplace=True, drop=True)
tg_df

0          D
1          E
2          C
3          D
4          E
          ..
2399995    E
2399996    D
2399997    C
2399998    E
2399999    E
Name: Segment, Length: 2400000, dtype: object

In [6]:
all_df1 = pd.concat([df11, df12, df13, df14, df15, df16])
all_df1.reset_index(inplace=True, drop=True)
all_df1

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,2,70대이상,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,노년생활,39
2399996,201812,TRAIN_399996,2,50대,D,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),24
2399997,201812,TRAIN_399997,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,18
2399998,201812,TRAIN_399998,1,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),27
2399999,201812,TRAIN_399999,2,40대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18

In [7]:
all_df1['Segment'].value_counts()

Segment
E    1922052
D     349242
C     127590
A        972
B        144
Name: count, dtype: int64

In [8]:
all_df1 = all_df1.drop(columns=all_df1.columns[all_df1.isna().sum() > 0])

In [9]:
all_df12=all_df1.copy()
all_df12 = all_df1[~all_df1['Segment'].isin(['A', 'B', 'C'])]

In [4]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, ttest_ind

pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² from t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan

# t-test 기반 효과 크기 계산 함수
def effect_sizes(df):
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수 → t-test + eta²
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            unique_segments = sorted(data['Segment'].unique())
            if len(unique_segments) != 2:
                continue  # t-test는 2개 그룹일 때만 가능

            group1 = data[data['Segment'] == unique_segments[0]][col]
            group2 = data[data['Segment'] == unique_segments[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수 → Cramér's V
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    if ttest_results:
        result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    else:
        result_df1 = pd.DataFrame(columns=['변수', '유형', '계수종류', '상관계수'])

    if chi_results:
        result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    else:
        result_df2 = pd.DataFrame(columns=['변수', '유형', '계수종류', '상관계수'])

    return result_df1, result_df2

In [11]:
result11, result12 = effect_sizes(all_df12)
display(result11)
display(result12)

                변수   유형  계수종류    상관계수
0    이용금액_R3M_신용체크  수치형  Eta² 0.14004
1       _1순위카드이용금액  수치형  Eta² 0.12031
2      이용금액_R3M_신용  수치형  Eta² 0.11275
3       이용카드수_신용체크  수치형  Eta² 0.09089
4         이용카드수_신용  수치형  Eta² 0.07443
..             ...  ...   ...     ...
56     이용카드수_체크_가족  수치형  Eta²     NaN
57  이용금액_R3M_체크_가족  수치형  Eta²     NaN
58    연회비할인카드수_B0M  수치형  Eta²     NaN
59  할인금액_기본연회비_B0M  수치형  Eta²     NaN
60  할인금액_제휴연회비_B0M  수치형  Eta²     NaN

[61 rows x 4 columns]

             변수   유형        계수종류    상관계수
0            ID  범주형  Cramér's V 1.00000
1    Life_Stage  범주형  Cramér's V 0.08091
2            연령  범주형  Cramér's V 0.07310
3         거주시도명  범주형  Cramér's V 0.04908
4  연회비발생카드수_B0M  범주형  Cramér's V 0.00153

In [12]:
with pd.ExcelWriter('1.회원정보_C,D.xlsx') as writer:
    result11.to_excel(writer, sheet_name='아노바', index=False)
    result12.to_excel(writer, sheet_name='카이제곱', index=False)

### 2번 데이터

In [13]:
df21=pd.read_parquet(r'train/2.신용정보/201807_train_.parquet')
df22=pd.read_parquet(r'train/2.신용정보/201808_train_.parquet')
df23=pd.read_parquet(r'train/2.신용정보/201809_train_.parquet')
df24=pd.read_parquet(r'train/2.신용정보/201810_train_.parquet')
df25=pd.read_parquet(r'train/2.신용정보/201811_train_.parquet')
df26=pd.read_parquet(r'train/2.신용정보/201812_train_.parquet')

In [14]:
all_df2 = pd.concat([df21, df22, df23, df24, df25, df26])
all_df2.reset_index(inplace=True, drop=True)
all_df2

,기준년월,ID,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,...,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일
0,201807,TRAIN_000000,0,19354,7270,0,0,22.99521,18.25498,17.26497,...,0,0회,0,3,3,0,0,0,0,99999999
1,201807,TRAIN_000001,0,9996,5718,41996,90611,14.79382,14.83487,10.62245,...,0,0회,0,3,3,0,0,0,0,322
2,201807,TRAIN_000002,0,88193,35207,0,0,22.01428,17.87532,17.15583,...,0,0회,0,3,3,0,0,0,0,2378
3,201807,TRAIN_000003,0,19062,6531,0,0,22.99801,22.99945,19.29367,...,0,0회,0,3,3,0,0,0,0,99999999
4,201807,TRAIN_000004,0,177222,47149,48000,155020,14.66195,10.89741,10.65459,...,0,0회,0,3,3,0,0,0,0,99999999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,20070,10167,0,54445,15.24367,11.90052,10.54588,...,0,0회,0,3,3,0,0,0,0,99999999
2399996,201812,TRAIN_399996,0,84217,31159,0,156800,14.84346,15.65206,11.10273,...,0,0회,0,3,3,0,0,0,0,99999999
2399997,201812,TRAIN_399997,0,52612,19429,0,0,17.03860,17.96621,13.27847,...,0,0회,0,3,3,0,0,0,0,99999999
2399998,201812,TRAIN_399998,0,10002,4228,90004,180906,15.18288,11.90109,10.59412,...,0,0회,0,3,3,0,0,0,0,99999999
2399999,201812,TRAIN_399999,0,86094,25133,0,0,14.84110,15.28712,11.40682,...,0,0회,0,3,3,0,0,0,0,99999999

In [15]:
all_df2 = all_df2.drop(columns=all_df2.columns[all_df2.isna().sum() > 0])

In [16]:
all_df2['Segment'] = tg_df

In [17]:
all_df2 = all_df2[~all_df2['Segment'].isin(['A', 'B', 'C'])]

In [18]:
result21, result22 = effect_sizes(all_df2)
display(result21)
display(result22)

                변수   유형  계수종류    상관계수
0           CA한도금액  수치형  Eta² 0.03279
1         카드이용한도금액  수치형  Eta² 0.03112
2     카드이용한도금액_B1M  수치형  Eta² 0.03067
3     카드이용한도금액_B2M  수치형  Eta² 0.03067
4       rv최초시작후경과일  수치형  Eta² 0.00565
5        CA이자율_할인전  수치형  Eta² 0.00530
6   RV현금서비스이자율_할인전  수치형  Eta² 0.00521
7      한도증액금액_R12M  수치형  Eta² 0.00398
8    강제한도감액금액_R12M  수치형  Eta² 0.00385
9          RV약정청구율  수치형  Eta² 0.00382
10    RV일시불이자율_할인전  수치형  Eta² 0.00324
11      상향가능CA한도금액  수치형  Eta² 0.00309
12       일시상환론한도금액  수치형  Eta² 0.00305
13          최초한도금액  수치형  Eta² 0.00301
14        상향가능한도금액  수치형  Eta² 0.00254
15      강제한도감액후경과월  수치형  Eta² 0.00245
16        한도증액후경과월  수치형  Eta² 0.00164
17        월상환론한도금액  수치형  Eta² 0.00157
18       CL이자율_할인전  수치형  Eta² 0.00079
19        RV최소결제비율  수치형  Eta² 0.00049
20      연체감액여부_R3M  수치형  Eta² 0.00029
21   강제한도감액횟수_R12M  수치형  Eta² 0.00019
22    월상환론상향가능한도금액  수치형  Eta² 0.00005
23    특별한도보유여부_R3M  수치형  Eta² 0.00002
24   일시불ONLY전환가능여부  수치형  Eta² 0.00002
25   자발한도감액금액_R12M  수치형  Eta² 0.00001
26      자발한도감액후경과월  수치형  Eta² 0.00000
27    시장단기연체여부_R3M  수치형  Eta² 0.00000
28    시장단기연체여부_R6M  수치형  Eta² 0.00000
29    시장연체상환여부_R6M  수치형  Eta² 0.00000
30      한도심사요청후경과월  수치형  Eta² 0.00000
31        한도요청거절건수  수치형  Eta² 0.00000
32      한도심사거절후경과월  수치형  Eta² 0.00000
33            기준년월  수치형  Eta² 0.00000
34    시장연체상환여부_R3M  수치형  Eta²     NaN

              변수   유형        계수종류    상관계수
0             ID  범주형  Cramér's V 1.00000
1    한도증액횟수_R12M  범주형  Cramér's V 0.06806
2        카드론동의여부  범주형  Cramér's V 0.01593
3  자발한도감액횟수_R12M  범주형  Cramér's V 0.00354
4       한도심사요청건수  범주형  Cramér's V 0.00059

In [19]:
with pd.ExcelWriter('2.신용정보_C,D.xlsx') as writer:
    result21.to_excel(writer, sheet_name='아노바', index=False)
    result22.to_excel(writer, sheet_name='카이제곱', index=False)

### 3번 (1~70번)

In [20]:
df311=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, :70]
df312=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, :70]
df313=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, :70]
df314=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, :70]
df315=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, :70]
df316=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, :70]

In [21]:
all_df31 = pd.concat([df311, df312, df313, df314, df315, df316])
all_df31.reset_index(inplace=True, drop=True)
all_df31

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,최대이용금액_CA_R12M,최대이용금액_체크_R12M,최대이용금액_카드론_R12M,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,이용개월수_할부_R12M,이용개월수_할부_유이자_R12M,이용개월수_할부_무이자_R12M,이용개월수_부분무이자_R12M
0,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,11,...,11710,1020,0,12,12,12,5,1,4,0
1,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,13,...,3377,0,41320,12,12,12,2,1,1,0
2,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,12,...,65977,0,0,9,9,9,2,0,2,0
3,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,6,...,19698,0,0,12,12,7,8,4,5,0
4,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,-2,...,0,3324,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,2,...,0,5072,0,3,0,0,0,0,0,0
2399996,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,10,...,0,0,0,12,12,12,1,0,1,0
2399997,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,10,...,0,0,0,12,12,12,4,0,4,0
2399998,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,-2,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,-1,...,0,0,0,9,8,7,7,3,5,0

In [22]:
all_df31 = all_df31.drop(columns=all_df31.columns[all_df31.isna().sum() > 0])

In [23]:
all_df31['Segment'] = tg_df

In [24]:
all_df31 = all_df31[~all_df31['Segment'].isin(['A', 'B', 'C'])]

In [25]:
result1, result2 = effect_sizes(all_df31)
display(result1)
display(result2)

                변수   유형  계수종류    상관계수
0    이용개월수_신용_R12M  수치형  Eta² 0.15073
1    이용개월수_신판_R12M  수치형  Eta² 0.14601
2   이용개월수_일시불_R12M  수치형  Eta² 0.14156
3     이용금액_일시불_B0M  수치형  Eta² 0.11720
4    이용금액_일시불_R12M  수치형  Eta² 0.11288
..             ...  ...   ...     ...
64    이용금액_카드론_B0M  수치형  Eta² 0.00000
65    이용건수_카드론_B0M  수치형  Eta² 0.00000
66            기준년월  수치형  Eta² 0.00000
67  이용건수_부분무이자_B0M  수치형  Eta²     NaN
68  이용금액_부분무이자_B0M  수치형  Eta²     NaN

[69 rows x 4 columns]

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000

In [26]:
with pd.ExcelWriter('3.승인매출정보(1)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

### 3번 데이터 (71 ~ 140번)

In [27]:
df321=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 71:140]
df322=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 71:140]
df323=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 71:140]
df324=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 71:140]
df325=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 71:140]
df326=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 71:140]

In [28]:
all_df32 = pd.concat([df321, df322, df323, df324, df325, df326])
all_df32.reset_index(inplace=True, drop=True)
all_df32

,이용개월수_체크_R12M,이용개월수_카드론_R12M,이용건수_신용_R6M,이용건수_신판_R6M,이용건수_일시불_R6M,이용건수_할부_R6M,이용건수_할부_유이자_R6M,이용건수_할부_무이자_R6M,이용건수_부분무이자_R6M,이용건수_CA_R6M,...,이용금액_해외,쇼핑_도소매_이용금액,쇼핑_백화점_이용금액,쇼핑_마트_이용금액,쇼핑_슈퍼마켓_이용금액,쇼핑_편의점_이용금액,쇼핑_아울렛_이용금액,쇼핑_온라인_이용금액,쇼핑_기타_이용금액,교통_주유이용금액
0,3,0,77,67,64,3,0,3,0,10,...,0,0,0,0,0,0,0,0,242,0
1,0,1,81,81,81,0,0,0,0,0,...,0,645,0,0,435,315,0,272,289,1215
2,0,0,62,56,54,2,0,2,0,6,...,0,1038,751,924,504,239,0,6094,0,1362
3,0,0,42,32,26,6,4,2,0,10,...,0,0,0,801,487,0,0,0,0,0
4,8,0,-2,-2,-2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,8,0,7,7,7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,0,0,101,101,101,0,0,0,0,0,...,0,1496,0,0,714,0,0,0,346,0
2399997,0,0,68,68,66,2,0,2,0,0,...,0,0,0,0,400,300,0,1458,305,1925
2399998,0,0,-7,-7,-7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,2,2,1,1,0,1,0,0,...,0,0,985,0,0,0,0,0,0,0

In [29]:
all_df32= all_df32.drop(columns=all_df32.columns[all_df32.isna().sum() > 0])

In [30]:
all_df32['Segment'] = tg_df

In [31]:
all_df32 = all_df32[~all_df32['Segment'].isin(['A', 'B', 'C'])]

In [32]:
result1, result2 = effect_sizes(all_df32)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(2)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                 변수   유형  계수종류    상관계수
0      이용금액_일시불_R6M  수치형  Eta² 0.11824
1      이용금액_일시불_R3M  수치형  Eta² 0.11550
2            이용가맹점수  수치형  Eta² 0.09737
3      이용개월수_신용_R6M  수치형  Eta² 0.08819
4       이용건수_신용_R6M  수치형  Eta² 0.08799
..              ...  ...   ...     ...
64    이용개월수_카드론_R3M  수치형  Eta² 0.00008
65     이용금액_카드론_R3M  수치형  Eta² 0.00007
66     이용건수_카드론_R3M  수치형  Eta² 0.00007
67  이용개월수_부분무이자_R3M  수치형  Eta² 0.00005
68   이용건수_부분무이자_R3M  수치형  Eta² 0.00004

[69 rows x 4 columns]

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (141~210번)

In [6]:
df331=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 141:210]
df332=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 141:210]
df333=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 141:210]
df334=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 141:210]
df335=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 141:210]
df336=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 141:210]

In [7]:
all_df33 = pd.concat([df331, df332, df333, df334, df335, df336])
all_df33.reset_index(inplace=True, drop=True)
all_df33

,교통_통행료이용금액,교통_버스지하철이용금액,교통_택시이용금액,교통_철도버스이용금액,여유_운동이용금액,여유_Pet이용금액,여유_공연이용금액,여유_공원이용금액,여유_숙박이용금액,여유_여행이용금액,...,할부건수_유이자_6M_R12M,할부건수_유이자_12M_R12M,할부건수_유이자_14M_R12M,할부금액_유이자_3M_R12M,할부금액_유이자_6M_R12M,할부금액_유이자_12M_R12M,할부금액_유이자_14M_R12M,할부건수_무이자_3M_R12M,할부건수_무이자_6M_R12M,할부건수_무이자_12M_R12M
0,0,105,200,0,0,0,0,0,0,0,...,0,0,0,3602,0,0,0,0,3,0
1,0,0,0,443,0,0,0,0,0,0,...,0,0,0,0,0,0,4058,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0
3,0,0,208,0,0,0,0,0,0,0,...,0,0,0,10031,0,0,0,6,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,0,632,192,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,0,0,0,0,834,0,0,0,0,0,...,0,0,0,0,0,0,0,5,0,0
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,10156,0,0,0,6,0,0

In [8]:
all_df33 = all_df33.drop(columns=all_df33.columns[all_df33.isna().sum() > 0])

In [9]:
all_df33['Segment'] = tg_df

In [10]:
all_df33 = all_df33[~all_df33['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df33)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(3)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                   변수   유형  계수종류    상관계수
0       _2순위쇼핑업종_이용금액  수치형  Eta² 0.09237
1         _3순위업종_이용금액  수치형  Eta² 0.08804
2       _3순위쇼핑업종_이용금액  수치형  Eta² 0.08364
3         _2순위업종_이용금액  수치형  Eta² 0.08112
4       _1순위교통업종_이용금액  수치형  Eta² 0.06661
5         _1순위업종_이용금액  수치형  Eta² 0.06208
6       _2순위교통업종_이용금액  수치형  Eta² 0.04925
7       _1순위쇼핑업종_이용금액  수치형  Eta² 0.03548
8        할부금액_6M_R12M  수치형  Eta² 0.03154
9       _3순위교통업종_이용금액  수치형  Eta² 0.03087
10       할부금액_3M_R12M  수치형  Eta² 0.03013
11      _1순위납부업종_이용금액  수치형  Eta² 0.02994
12       할부건수_3M_R12M  수치형  Eta² 0.02817
13          교통_택시이용금액  수치형  Eta² 0.02672
14   할부건수_무이자_3M_R12M  수치형  Eta² 0.02449
15       할부건수_6M_R12M  수치형  Eta² 0.02275
16          납부_기타이용금액  수치형  Eta² 0.02235
17   할부건수_무이자_6M_R12M  수치형  Eta² 0.02158
18      _1순위여유업종_이용금액  수치형  Eta² 0.02089
19         납부_통신비이용금액  수치형  Eta² 0.02035
20   할부금액_유이자_3M_R12M  수치형  Eta² 0.01924
21          여유_운동이용금액  수치형  Eta² 0.01580
22   할부건수_유이자_3M_R12M  수치형  Eta² 0.01443
23      _2순위납부업종_이용금액  수치형  Eta² 0.01384
24         납부_보험료이용금액  수치형  Eta² 0.01288
25       교통_버스지하철이용금액  수치형  Eta² 0.01150
26        교통_철도버스이용금액  수치형  Eta² 0.01142
27   할부금액_유이자_6M_R12M  수치형  Eta² 0.01088
28          여유_공연이용금액  수치형  Eta² 0.00854
29      _2순위여유업종_이용금액  수치형  Eta² 0.00652
30      할부금액_12M_R12M  수치형  Eta² 0.00559
31   할부건수_유이자_6M_R12M  수치형  Eta² 0.00535
32          여유_기타이용금액  수치형  Eta² 0.00500
33      _3순위납부업종_이용금액  수치형  Eta² 0.00388
34         납부_관리비이용금액  수치형  Eta² 0.00284
35          여유_숙박이용금액  수치형  Eta² 0.00219
36       납부_가스전기료이용금액  수치형  Eta² 0.00218
37  할부금액_유이자_12M_R12M  수치형  Eta² 0.00216
38         여유_Pet이용금액  수치형  Eta² 0.00209
39      _3순위여유업종_이용금액  수치형  Eta² 0.00197
40      할부건수_12M_R12M  수치형  Eta² 0.00152
41  할부건수_무이자_12M_R12M  수치형  Eta² 0.00079
42  할부건수_유이자_12M_R12M  수치형  Eta² 0.00077
43          여유_공원이용금액  수치형  Eta² 0.00067
44          여유_항공이용금액  수치형  Eta² 0.00057
45      할부금액_14M_R12M  수치형  Eta² 0.00040
46  할부금액_유이자_14M_R12M  수치형  Eta² 0.00025
47         교통_통행료이용금액  수치형  Eta² 0.00000
48  할부건수_유이자_14M_R12M  수치형  Eta² 0.00000
49      할부건수_14M_R12M  수치형  Eta² 0.00000
50          여유_여행이용금액  수치형  Eta²     NaN
51         납부_렌탈료이용금액  수치형  Eta²     NaN
52        납부_유선방송이용금액  수치형  Eta²     NaN
53        납부_건강연금이용금액  수치형  Eta²     NaN

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (211 ~ 280번)

In [11]:
df341=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 211:280]
df342=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 211:280]
df343=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 211:280]
df344=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 211:280]
df345=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 211:280]
df346=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 211:280]

In [12]:
all_df34 = pd.concat([df341, df342, df343, df344, df345, df346])
all_df34.reset_index(inplace=True, drop=True)
all_df34

,할부금액_무이자_3M_R12M,할부금액_무이자_6M_R12M,할부금액_무이자_12M_R12M,할부금액_무이자_14M_R12M,할부건수_부분_3M_R12M,할부건수_부분_6M_R12M,할부건수_부분_12M_R12M,할부건수_부분_14M_R12M,할부금액_부분_3M_R12M,할부금액_부분_6M_R12M,...,최종카드론_대출일자,최종카드론_대출월수,최종카드론_거치개월수,최종카드론_대출금액,이용개월수_온라인_R6M,이용개월수_오프라인_R6M,이용금액_온라인_R6M,이용금액_오프라인_R6M,이용건수_온라인_R6M,이용건수_오프라인_R6M
0,1314,4514,0,0,0,0,0,0,0,0,...,NaN,0,0,0,1,6,847,11097,0,54
1,2076,0,0,0,0,0,0,0,0,0,...,20170327.00000,24,6,76723,1,6,281,18638,4,95
2,0,10561,0,0,0,0,0,0,0,0,...,20151119.00000,36,6,95094,3,6,12559,29192,7,76
3,12098,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,0,18056,0,39
4,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,1,0,787,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,0,0,0,0,0
2399996,1888,0,0,0,0,0,0,0,0,0,...,20170112.00000,36,6,108036,0,6,0,60373,0,57
2399997,27617,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,3998,32036,0,69
2399998,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,0,0,0,0,0
2399999,13847,4309,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,0,4537,0,43

In [13]:
all_df34 = all_df34.drop(columns=all_df34.columns[all_df34.isna().sum() > 0])

In [14]:
all_df34['Segment'] = tg_df

In [15]:
all_df34 = all_df34[~all_df34['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df34)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(4)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                 변수   유형  계수종류    상관계수
0     이용금액_오프라인_R6M  수치형  Eta² 0.10316
1    이용개월수_오프라인_R6M  수치형  Eta² 0.08004
2     이용건수_오프라인_R6M  수치형  Eta² 0.07378
3     이용개월수_온라인_R6M  수치형  Eta² 0.06494
4      이용건수_온라인_R6M  수치형  Eta² 0.04453
..              ...  ...   ...     ...
61      RP건수_건강_B0M  수치형  Eta²     NaN
62      RP후경과월_유선방송  수치형  Eta²     NaN
63        RP후경과월_건강  수치형  Eta²     NaN
64  증감_RP건수_유선방송_전월  수치형  Eta²     NaN
65    증감_RP건수_건강_전월  수치형  Eta²     NaN

[66 rows x 4 columns]

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (281~350번)

In [16]:
df351=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 281:350]
df352=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 281:350]
df353=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 281:350]
df354=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 281:350]
df355=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 281:350]
df356=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 281:350]

In [17]:
all_df35 = pd.concat([df351, df352, df353, df354, df355, df356])
all_df35.reset_index(inplace=True, drop=True)
all_df35

,이용금액_오프라인_R3M,이용건수_온라인_R3M,이용건수_오프라인_R3M,이용금액_온라인_B0M,이용금액_오프라인_B0M,이용건수_온라인_B0M,이용건수_오프라인_B0M,이용개월수_페이_온라인_R6M,이용개월수_페이_오프라인_R6M,이용금액_페이_온라인_R6M,...,이용금액_A페이_B0M,이용금액_B페이_B0M,이용금액_C페이_B0M,이용금액_D페이_B0M,이용건수_간편결제_B0M,이용건수_당사페이_B0M,이용건수_당사기타_B0M,이용건수_A페이_B0M,이용건수_B페이_B0M,이용건수_C페이_B0M
0,4131,0,17,0,4043,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14339,0,51,0,3980,0,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,12250,7,33,1625,4524,0,12,2,0,5311,...,0,0,0,0,0,0,0,0,0,0
3,10408,0,19,0,3975,0,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,25205,0,24,0,4676,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,13267,0,32,671,4516,0,13,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,21,0,0,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
all_df35 = all_df35.drop(columns=all_df35.columns[all_df35.isna().sum() > 0])

In [19]:
all_df35['Segment'] = tg_df

In [20]:
all_df35 = all_df35[~all_df35['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df35)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(5)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                변수   유형  계수종류    상관계수
0    이용금액_오프라인_B0M  수치형  Eta² 0.16085
1    이용금액_오프라인_R3M  수치형  Eta² 0.12005
2    이용건수_오프라인_B0M  수치형  Eta² 0.08969
3    이용건수_오프라인_R3M  수치형  Eta² 0.07854
4   이용개월수_간편결제_R6M  수치형  Eta² 0.06073
..             ...  ...   ...     ...
64   이용건수_당사기타_R3M  수치형  Eta²     NaN
65   이용금액_당사페이_B0M  수치형  Eta²     NaN
66   이용금액_당사기타_B0M  수치형  Eta²     NaN
67   이용건수_당사페이_B0M  수치형  Eta²     NaN
68   이용건수_당사기타_B0M  수치형  Eta²     NaN

[69 rows x 4 columns]

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (351번 ~)

In [21]:
df361=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 351:]
df362=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 351:]
df363=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 351:]
df364=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 351:]
df365=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 351:]
df366=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 351:]

In [22]:
all_df36 = pd.concat([df361, df362, df363, df364, df365, df366])
all_df36.reset_index(inplace=True, drop=True)
all_df36

,이용개월수_선결제_R6M,이용횟수_선결제_R6M,이용금액_선결제_R6M,이용건수_선결제_R6M,이용횟수_선결제_R3M,이용금액_선결제_R3M,이용건수_선결제_R3M,이용횟수_선결제_B0M,이용금액_선결제_B0M,이용건수_선결제_B0M,...,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,01.100만원+
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,03.30만원+
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,01.100만원+
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,01.100만원+
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
2399996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,01.100만원+
2399997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,02.50만원+
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
2399999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,04.10만원+

In [23]:
all_df36 = all_df36.drop(columns=all_df36.columns[all_df36.isna().sum() > 0])

In [24]:
all_df36['Segment'] = tg_df

In [25]:
all_df36 = all_df36[~all_df36['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df36)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(6)_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                    변수   유형  계수종류    상관계수
0           정상청구원금_B5M  수치형  Eta² 0.15958
1           정상청구원금_B2M  수치형  Eta² 0.13338
2   연속유실적개월수_기본_24M_카드  수치형  Eta² 0.13271
3           정상청구원금_B0M  수치형  Eta² 0.13183
4         이용개월수_전체_R6M  수치형  Eta² 0.11029
5         이용개월수_전체_R3M  수치형  Eta² 0.09265
6           정상입금원금_B0M  수치형  Eta² 0.08868
7           정상입금원금_B5M  수치형  Eta² 0.08510
8           정상입금원금_B2M  수치형  Eta² 0.08291
9   연속무실적개월수_기본_24M_카드  수치형  Eta² 0.06503
10       이용개월수_결제일_R6M  수치형  Eta² 0.04110
11          연체입금원금_B5M  수치형  Eta² 0.03716
12       이용개월수_결제일_R3M  수치형  Eta² 0.03531
13          연체입금원금_B2M  수치형  Eta² 0.03298
14          연체입금원금_B0M  수치형  Eta² 0.03266
15           선입금원금_B5M  수치형  Eta² 0.00833
16        이용횟수_선결제_R6M  수치형  Eta² 0.00831
17           선입금원금_B2M  수치형  Eta² 0.00786
18           선입금원금_B0M  수치형  Eta² 0.00785
19        이용금액_선결제_R6M  수치형  Eta² 0.00777
20       이용개월수_선결제_R6M  수치형  Eta² 0.00739
21     신청건수_ATM_CA_R6M  수치형  Eta² 0.00724
22        이용금액_선결제_R3M  수치형  Eta² 0.00721
23        이용횟수_선결제_R3M  수치형  Eta² 0.00690
24        이용금액_선결제_B0M  수치형  Eta² 0.00646
25        이용횟수_선결제_B0M  수치형  Eta² 0.00602
26        이용건수_선결제_R6M  수치형  Eta² 0.00549
27      신청건수_ATM_CA_B0  수치형  Eta² 0.00418
28        이용건수_선결제_R3M  수치형  Eta² 0.00367
29         이용금액_연체_R6M  수치형  Eta² 0.00271
30        이용건수_선결제_B0M  수치형  Eta² 0.00236
31          승인거절건수_R3M  수치형  Eta² 0.00218
32         금액_할부전환_R6M  수치형  Eta² 0.00208
33         이용횟수_연체_R6M  수치형  Eta² 0.00206
34         건수_할부전환_R6M  수치형  Eta² 0.00205
35         금액_할부전환_R3M  수치형  Eta² 0.00200
36         건수_할부전환_R3M  수치형  Eta² 0.00199
37         이용금액_연체_R3M  수치형  Eta² 0.00191
38       승인거절건수_기타_R3M  수치형  Eta² 0.00126
39         이용횟수_연체_R3M  수치형  Eta² 0.00118
40         이용금액_연체_B0M  수치형  Eta² 0.00113
41     승인거절건수_한도초과_R3M  수치형  Eta² 0.00089
42         이용횟수_연체_B0M  수치형  Eta² 0.00066
43       승인거절건수_BL_R3M  수치형  Eta² 0.00062
44         가맹점매출금액_B1M  수치형  Eta² 0.00019
45         가맹점매출금액_B2M  수치형  Eta² 0.00018
46          승인거절건수_B0M  수치형  Eta² 0.00002
47     승인거절건수_한도초과_B0M  수치형  Eta² 0.00002
48       승인거절건수_BL_B0M  수치형  Eta² 0.00000
49     승인거절건수_입력오류_R3M  수치형  Eta² 0.00000
50     신청건수_ATM_CL_R6M  수치형  Eta² 0.00000
51      신청건수_ATM_CL_B0  수치형  Eta²     NaN
52     승인거절건수_입력오류_B0M  수치형  Eta²     NaN
53       승인거절건수_기타_B0M  수치형  Eta²     NaN

      변수   유형        계수종류    상관계수
0  이용금액대  범주형  Cramér's V 0.52071

### 4번 데이터

In [5]:
df41=pd.read_parquet(r'train/4.청구입금정보/201807_train_.parquet')
df42=pd.read_parquet(r'train/4.청구입금정보/201808_train_.parquet')
df43=pd.read_parquet(r'train/4.청구입금정보/201809_train_.parquet')
df44=pd.read_parquet(r'train/4.청구입금정보/201810_train_.parquet')
df45=pd.read_parquet(r'train/4.청구입금정보/201811_train_.parquet')
df46=pd.read_parquet(r'train/4.청구입금정보/201812_train_.parquet')

In [6]:
all_df4 = pd.concat([df41, df42, df43, df44, df45, df46])
all_df4.reset_index(inplace=True, drop=True)
all_df4

,기준년월,ID,대표결제일,대표결제방법코드,대표청구지고객주소구분코드,대표청구서수령지구분코드,청구서수령방법,청구서발송여부_B0,청구서발송여부_R3M,청구서발송여부_R6M,...,할인금액_청구서_B0M,상환개월수_결제일_R6M,상환개월수_결제일_R3M,선결제건수_R6M,선결제건수_R3M,연체건수_R6M,연체건수_R3M,혜택수혜금액_R3M,포인트_마일리지_환산_B0M,혜택수혜금액
0,201807,TRAIN_000000,27,자동이체,미확인,당사페이앱+이메일,문자메세지,1,1,1,...,0,5,3,0,0,1,0,3,0,0
1,201807,TRAIN_000001,13,자동이체,주거지,우편,우편,1,1,1,...,163,6,3,0,0,0,0,0,0,0
2,201807,TRAIN_000002,1,자동이체,미확인,이메일,이메일,1,1,1,...,0,6,3,0,0,0,0,121,0,50
3,201807,TRAIN_000003,5,자동이체,주거지,우편,우편,1,1,1,...,0,5,3,2,0,0,0,3,0,2
4,201807,TRAIN_000004,13,자동이체,주거지,우편,우편,0,1,1,...,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,25,자동이체,주거지,우편,우편,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,20,자동이체,미확인,이메일,이메일,1,1,1,...,0,6,3,0,0,0,0,164,0,53
2399997,201812,TRAIN_399997,20,자동이체,회사,우편,우편,1,1,1,...,0,6,3,0,0,0,0,0,0,0
2399998,201812,TRAIN_399998,20,자동이체,주거지,우편,우편,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,23,자동이체,주거지,우편,우편,1,1,1,...,0,6,3,0,0,0,0,0,0,0

In [7]:
all_df4 = all_df4.drop(columns=all_df4.columns[all_df4.isna().sum() > 0])

In [8]:
all_df4['Segment'] = tg_df

In [9]:
all_df4 = all_df4[~all_df4['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df4)
display(result1)
display(result2)

with pd.ExcelWriter('4.청구입금정보_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                  변수   유형  계수종류    상관계수
0           청구금액_R6M  수치형  Eta² 0.10999
1           청구금액_R3M  수치형  Eta² 0.10379
2            청구금액_B0  수치형  Eta² 0.09565
3         청구서발송여부_B0  수치형  Eta² 0.09358
4        청구서발송여부_R3M  수치형  Eta² 0.07247
5        청구서발송여부_R6M  수치형  Eta² 0.05009
6             혜택수혜금액  수치형  Eta² 0.03868
7         혜택수혜금액_R3M  수치형  Eta² 0.03777
8      상환개월수_결제일_R6M  수치형  Eta² 0.02741
9      상환개월수_결제일_R3M  수치형  Eta² 0.02206
10      할인금액_청구서_R3M  수치형  Eta² 0.01793
11      할인금액_청구서_B0M  수치형  Eta² 0.01730
12          할인금액_R3M  수치형  Eta² 0.01572
13          할인금액_B0M  수치형  Eta² 0.01480
14     포인트_적립포인트_R3M  수치형  Eta² 0.01248
15      마일_적립포인트_R3M  수치형  Eta² 0.01066
16   포인트_마일리지_환산_B0M  수치형  Eta² 0.01047
17     포인트_이용포인트_R3M  수치형  Eta² 0.01027
18         선결제건수_R6M  수치형  Eta² 0.01026
19    포인트_적립포인트_R12M  수치형  Eta² 0.00997
20         선결제건수_R3M  수치형  Eta² 0.00901
21    포인트_포인트_건별_R3M  수치형  Eta² 0.00821
22    포인트_포인트_건별_B0M  수치형  Eta² 0.00814
23   포인트_마일리지_건별_B0M  수치형  Eta² 0.00683
24   포인트_마일리지_건별_R3M  수치형  Eta² 0.00682
25     마일_이용포인트_R12M  수치형  Eta² 0.00669
26      마일_이용포인트_R3M  수치형  Eta² 0.00668
27    포인트_이용포인트_R12M  수치형  Eta² 0.00656
28     마일_적립포인트_R12M  수치형  Eta² 0.00652
29      마일_잔여포인트_B0M  수치형  Eta² 0.00478
30   포인트_포인트_월적립_R3M  수치형  Eta² 0.00473
31  포인트_마일리지_월적립_R3M  수치형  Eta² 0.00439
32  포인트_마일리지_월적립_B0M  수치형  Eta² 0.00426
33   포인트_포인트_월적립_B0M  수치형  Eta² 0.00373
34          연체건수_R6M  수치형  Eta² 0.00267
35          연체건수_R3M  수치형  Eta² 0.00222
36             대표결제일  수치형  Eta² 0.00017
37     포인트_잔여포인트_B0M  수치형  Eta² 0.00000
38              기준년월  수치형  Eta² 0.00000

              변수   유형        계수종류    상관계수
0             ID  범주형  Cramér's V 1.00000
1       할인건수_R3M  범주형  Cramér's V 0.24755
2       할인건수_B0M  범주형  Cramér's V 0.08637
3   대표청구서수령지구분코드  범주형  Cramér's V 0.07963
4        청구서수령방법  범주형  Cramér's V 0.07962
5  대표청구지고객주소구분코드  범주형  Cramér's V 0.07464

### 5번 데이터

In [10]:
df51=pd.read_parquet(r'train/5.잔액정보/201807_train_.parquet')
df52=pd.read_parquet(r'train/5.잔액정보/201808_train_.parquet')
df53=pd.read_parquet(r'train/5.잔액정보/201809_train_.parquet')
df54=pd.read_parquet(r'train/5.잔액정보/201810_train_.parquet')
df55=pd.read_parquet(r'train/5.잔액정보/201811_train_.parquet')
df56=pd.read_parquet(r'train/5.잔액정보/201812_train_.parquet')

In [11]:
all_df5 = pd.concat([df51, df52, df53, df54, df55, df56])
all_df5.reset_index(inplace=True, drop=True)
all_df5

,기준년월,ID,잔액_일시불_B0M,잔액_할부_B0M,잔액_현금서비스_B0M,잔액_리볼빙일시불이월_B0M,잔액_리볼빙CA이월_B0M,잔액_카드론_B0M,월중평잔_일시불_B0M,월중평잔_할부_B0M,...,평잔_6M,평잔_일시불_6M,평잔_일시불_해외_6M,평잔_RV일시불_6M,평잔_RV일시불_해외_6M,평잔_할부_6M,평잔_할부_해외_6M,평잔_CA_6M,평잔_CA_해외_6M,평잔_카드론_6M
0,201807,TRAIN_000000,998,962,22971,0,0,0,1084,547,...,15988,2440,0,0,0,572,0,17008,0,0
1,201807,TRAIN_000001,2565,2390,0,0,0,0,4090,2553,...,7045,2677,0,2830,0,2736,0,0,0,0
2,201807,TRAIN_000002,5312,5113,21531,6795,0,0,5006,8778,...,66549,9118,0,8870,0,4429,0,43351,0,0
3,201807,TRAIN_000003,730,5025,26284,0,0,0,487,5607,...,30139,884,0,0,0,5097,0,30697,0,0
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,28,21,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,3351,0,0,0,0,27337,4412,0,...,67826,12524,0,0,0,0,0,0,0,23031
2399997,201812,TRAIN_399997,2524,2960,0,0,0,0,2694,3374,...,8627,3241,0,0,0,3995,0,0,0,0
2399998,201812,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,1148,3452,0,0,0,0,980,1839,...,5463,1053,0,0,0,4373,0,0,0,0

In [12]:
all_df5 = all_df5.drop(columns=all_df5.columns[all_df5.isna().sum() > 0])

In [13]:
all_df5['Segment'] = tg_df

In [14]:
all_df5 = all_df5[~all_df5['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df5)
display(result1)
display(result2)

with pd.ExcelWriter('5.잔액정보_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                   변수   유형  계수종류    상관계수
0           평잔_일시불_6M  수치형  Eta² 0.05716
1           평잔_일시불_3M  수치형  Eta² 0.05148
2            월중평잔_일시불  수치형  Eta² 0.05144
3        월중평잔_일시불_B0M  수치형  Eta² 0.05066
4          잔액_일시불_B0M  수치형  Eta² 0.04483
..                ...  ...   ...     ...
75       RV잔액이월횟수_R3M  수치형  Eta²     NaN
76    연체잔액_일시불_해외_B0M  수치형  Eta²     NaN
77  연체잔액_RV일시불_해외_B0M  수치형  Eta²     NaN
78     연체잔액_할부_해외_B0M  수치형  Eta²     NaN
79     연체잔액_CA_해외_B0M  수치형  Eta²     NaN

[80 rows x 4 columns]

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000

### 6번 데이터

In [5]:
df61=pd.read_parquet(r'train/6.채널정보/201807_train_.parquet')
df62=pd.read_parquet(r'train/6.채널정보/201808_train_.parquet')
df63=pd.read_parquet(r'train/6.채널정보/201809_train_.parquet')
df64=pd.read_parquet(r'train/6.채널정보/201810_train_.parquet')
df65=pd.read_parquet(r'train/6.채널정보/201811_train_.parquet')
df66=pd.read_parquet(r'train/6.채널정보/201812_train_.parquet')

In [6]:
all_df6 = pd.concat([df61, df62, df63, df64, df65, df66])
all_df6.reset_index(inplace=True, drop=True)
all_df6

,기준년월,ID,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,인입일수_ARS_R6M,인입월수_ARS_R6M,인입후경과월_ARS,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,...,당사PAY_방문횟수_R6M,당사PAY_방문월수_R6M,당사멤버쉽_방문횟수_B0M,당사멤버쉽_방문횟수_R6M,당사멤버쉽_방문월수_R6M,OS구분코드,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M
0,201807,TRAIN_000000,10회 이상,10회 이상,8,6,0,2,6,2,...,0,0,22,221,6,Android,0,0,0,0
1,201807,TRAIN_000001,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2,201807,TRAIN_000002,1회 이상,1회 이상,1,1,0,2,5,1,...,0,0,0,0,0,Android,11,6,5,5
3,201807,TRAIN_000003,10회 이상,10회 이상,10,6,0,2,6,2,...,0,0,23,219,6,Android,0,0,0,0
4,201807,TRAIN_000004,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,Android,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399996,201812,TRAIN_399996,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,1,None,0,0,0,0
2399997,201812,TRAIN_399997,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399998,201812,TRAIN_399998,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399999,201812,TRAIN_399999,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0

In [7]:
all_df6 = all_df6.drop(columns=all_df6.columns[all_df6.isna().sum() > 0])

In [8]:
all_df6['Segment'] = tg_df

In [9]:
all_df6 = all_df6[~all_df6['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df6)
display(result1)
display(result2)

with pd.ExcelWriter('6.채널정보_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                변수   유형  계수종류    상관계수
0    불만제기후경과월_R12M  수치형  Eta² 0.02477
1     방문후경과월_앱_R6M  수치형  Eta² 0.01643
2       방문월수_앱_R6M  수치형  Eta² 0.01507
3       방문일수_앱_B0M  수치형  Eta² 0.01309
4       방문횟수_앱_B0M  수치형  Eta² 0.01299
..             ...  ...   ...     ...
93      불만제기건수_B0M  수치형  Eta²     NaN
94     불만제기건수_R12M  수치형  Eta²     NaN
95  당사PAY_방문횟수_B0M  수치형  Eta²     NaN
96  당사PAY_방문횟수_R6M  수치형  Eta²     NaN
97  당사PAY_방문월수_R6M  수치형  Eta²     NaN

[98 rows x 4 columns]

               변수   유형        계수종류    상관계수
0              ID  범주형  Cramér's V 1.00000
1      방문횟수_앱_R6M  범주형  Cramér's V 0.13545
2     방문횟수_PC_R6M  범주형  Cramér's V 0.11427
3     방문일수_PC_R6M  범주형  Cramér's V 0.10890
4  이용메뉴건수_ARS_R6M  범주형  Cramér's V 0.08842
5    인입횟수_ARS_R6M  범주형  Cramér's V 0.08819

### 7번 데이터

In [10]:
df71=pd.read_parquet(r'train/7.마케팅정보/201807_train_.parquet')
df72=pd.read_parquet(r'train/7.마케팅정보/201808_train_.parquet')
df73=pd.read_parquet(r'train/7.마케팅정보/201809_train_.parquet')
df74=pd.read_parquet(r'train/7.마케팅정보/201810_train_.parquet')
df75=pd.read_parquet(r'train/7.마케팅정보/201811_train_.parquet')
df76=pd.read_parquet(r'train/7.마케팅정보/201812_train_.parquet')

In [11]:
all_df7 = pd.concat([df71, df72, df73, df74, df75, df76])
all_df7.reset_index(inplace=True, drop=True)
all_df7

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
0,201807,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1,201807,TRAIN_000001,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,10일 이상
2,201807,TRAIN_000002,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
3,201807,TRAIN_000003,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399996,201812,TRAIN_399996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,20회 이상,15일 이상
2399997,201812,TRAIN_399997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399998,201812,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399999,201812,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [12]:
all_df7 = all_df7.drop(columns=all_df7.columns[all_df7.isna().sum() > 0])

In [13]:
all_df7['Segment'] = tg_df

In [14]:
all_df7 = all_df7[~all_df7['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df7)
display(result1)
display(result2)

with pd.ExcelWriter('7.마케팅정보_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                  변수   유형  계수종류    상관계수
0   컨택건수_이용유도_TM_R6M  수치형  Eta² 0.03337
1   컨택건수_이용유도_TM_B0M  수치형  Eta² 0.01460
2   컨택건수_이용유도_EM_R6M  수치형  Eta² 0.01342
3   컨택건수_이용유도_EM_B0M  수치형  Eta² 0.01140
4   컨택건수_신용발급_TM_R6M  수치형  Eta² 0.00674
..               ...  ...   ...     ...
56  컨택건수_카드론_당사앱_R6M  수치형  Eta²     NaN
57   컨택건수_CA_당사앱_R6M  수치형  Eta²     NaN
58  컨택건수_리볼빙_당사앱_R6M  수치형  Eta²     NaN
59      컨택건수_FDS_B0M  수치형  Eta²     NaN
60      컨택건수_FDS_R6M  수치형  Eta²     NaN

[61 rows x 4 columns]

             변수   유형        계수종류    상관계수
0            ID  범주형  Cramér's V 1.00000
1  캠페인접촉일수_R12M  범주형  Cramér's V 0.03175
2  캠페인접촉건수_R12M  범주형  Cramér's V 0.03098

### 8번 데이터

In [15]:
df81=pd.read_parquet(r'train/8.성과정보/201807_train_.parquet')
df82=pd.read_parquet(r'train/8.성과정보/201808_train_.parquet')
df83=pd.read_parquet(r'train/8.성과정보/201809_train_.parquet')
df84=pd.read_parquet(r'train/8.성과정보/201810_train_.parquet')
df85=pd.read_parquet(r'train/8.성과정보/201811_train_.parquet')
df86=pd.read_parquet(r'train/8.성과정보/201812_train_.parquet')

In [16]:
all_df8 = pd.concat([df81, df82, df83, df84, df85, df86])
all_df8.reset_index(inplace=True, drop=True)
all_df8

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M
0,201807,TRAIN_000000,0.45455,0.45455,0.36473,2.00000,0.00000,0.00000,0.00000,0.40977,...,1.00000,1.04281,0.99970,1.00000,1.00000,0.26189,0.27075,0.00000,1.04440,1.28054
1,201807,TRAIN_000001,-0.51181,-0.51181,-0.51181,0.00000,0.00000,0.00000,0.00000,-1.01082,...,1.09270,0.90566,1.00000,1.00000,1.00000,-0.56339,-0.67035,0.00000,0.00000,0.00000
2,201807,TRAIN_000002,-0.06272,-0.06272,0.06784,-2.00000,0.00000,0.00000,0.00000,-0.90217,...,1.00612,1.99359,0.85257,1.00000,1.00000,-0.04652,0.05811,-0.01419,0.52416,1.20842
3,201807,TRAIN_000003,0.13571,0.13571,0.15398,-2.00000,0.00000,0.00000,0.00000,-0.86605,...,1.00000,1.05065,0.99988,1.00000,1.00000,0.02382,0.25894,0.00000,0.88092,1.65712
4,201807,TRAIN_000004,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.00000,0.00000,0.00000,0.00000,0.00000,-0.08194,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN
2399996,201812,TRAIN_399996,0.07380,0.07380,0.07380,0.00000,0.00000,0.00000,0.00000,0.20710,...,1.00000,1.00000,1.00000,1.00000,0.92173,-0.20325,-0.15914,0.00000,1.37707,2.53381
2399997,201812,TRAIN_399997,-0.04043,-0.04043,-0.04043,0.00000,0.00000,0.00000,0.00000,0.25449,...,1.00000,0.34503,1.00000,1.00000,1.00000,0.02732,0.12658,0.00000,0.00000,0.00000
2399998,201812,TRAIN_399998,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN
2399999,201812,TRAIN_399999,0.18760,0.18760,0.18760,0.00000,0.00000,0.00000,0.00000,0.33227,...,1.00000,0.59316,1.00000,1.00000,1.00000,-0.03984,-0.00266,0.00000,0.00000,0.00000

In [17]:
all_df8 = all_df8.drop(columns=all_df8.columns[all_df8.isna().sum() > 0])

In [18]:
all_df8['Segment'] = tg_df

In [19]:
all_df8 = all_df8[~all_df8['Segment'].isin(['A', 'B', 'C'])]

result1, result2 = effect_sizes(all_df8)
display(result1)
display(result2)

with pd.ExcelWriter('8.성과정보_C,D.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                    변수   유형  계수종류    상관계수
0           변동률_RVCA평잔  수치형  Eta² 0.04209
1   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.04092
2          변동률_RV일시불평잔  수치형  Eta² 0.03913
3   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.03720
4   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.03445
5   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.03400
6     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.03111
7     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.02870
8     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.02693
9     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.02565
10           변동률_카드론평잔  수치형  Eta² 0.01002
11     증감율_이용금액_일시불_전월  수치형  Eta² 0.00647
12      증감율_이용금액_신판_전월  수치형  Eta² 0.00613
13           변동률_일시불평잔  수치형  Eta² 0.00564
14      증감율_이용금액_신용_전월  수치형  Eta² 0.00337
15      증감율_이용건수_체크_전월  수치형  Eta² 0.00319
16      증감율_이용건수_할부_전월  수치형  Eta² 0.00310
17            변동률_CA평잔  수치형  Eta² 0.00235
18      증감율_이용건수_할부_분기  수치형  Eta² 0.00137
19      증감율_이용건수_CA_전월  수치형  Eta² 0.00099
20      증감율_이용금액_할부_분기  수치형  Eta² 0.00086
21      증감율_이용금액_CA_분기  수치형  Eta² 0.00055
22      증감율_이용금액_신용_분기  수치형  Eta² 0.00047
23      증감율_이용금액_신판_분기  수치형  Eta² 0.00040
24      증감율_이용금액_체크_전월  수치형  Eta² 0.00037
25      증감율_이용금액_할부_전월  수치형  Eta² 0.00037
26     증감율_이용건수_카드론_분기  수치형  Eta² 0.00033
27     증감율_이용금액_카드론_분기  수치형  Eta² 0.00033
28      증감율_이용건수_CA_분기  수치형  Eta² 0.00029
29            변동률_할부평잔  수치형  Eta² 0.00016
30      증감율_이용금액_CA_전월  수치형  Eta² 0.00014
31      증감율_이용금액_체크_분기  수치형  Eta² 0.00014
32     증감율_이용금액_일시불_분기  수치형  Eta² 0.00014
33      증감율_이용건수_체크_분기  수치형  Eta² 0.00013
34       변동률_잔액_CA_B1M  수치형  Eta² 0.00007
35     증감율_이용건수_일시불_분기  수치형  Eta² 0.00006
36      증감율_이용건수_신판_분기  수치형  Eta² 0.00004
37      증감율_이용건수_신용_분기  수치형  Eta² 0.00004
38          변동률_잔액_B1M  수치형  Eta² 0.00002
39     증감율_이용금액_카드론_전월  수치형  Eta² 0.00002
40     증감율_이용건수_일시불_전월  수치형  Eta² 0.00002
41     증감율_이용건수_카드론_전월  수치형  Eta² 0.00002
42      증감율_이용건수_신판_전월  수치형  Eta² 0.00000
43      변동률_잔액_일시불_B1M  수치형  Eta² 0.00000
44      증감율_이용건수_신용_전월  수치형  Eta² 0.00000
45                기준년월  수치형  Eta² 0.00000

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000