In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

# Train

In [2]:
df11=pd.read_parquet(r'train/1.회원정보/201807_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df12=pd.read_parquet(r'train/1.회원정보/201808_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df13=pd.read_parquet(r'train/1.회원정보/201809_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df14=pd.read_parquet(r'train/1.회원정보/201810_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df15=pd.read_parquet(r'train/1.회원정보/201811_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df16=pd.read_parquet(r'train/1.회원정보/201812_train_.parquet',columns=['ID','기준년월','Segment','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])

In [3]:
all_df1 = pd.concat([df11, df12, df13, df14, df15, df16])
all_df1.reset_index(inplace=True, drop=True)
all_df1

,ID,기준년월,Segment,Life_Stage,연령,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수
0,TRAIN_000000,201807,D,자녀성장(2),40대,196,3681,196,1,1,26
1,TRAIN_000001,201807,E,자녀성장(1),30대,13475,13323,13475,1,1,46
2,TRAIN_000002,201807,C,자녀출산기,30대,23988,24493,23988,1,1,28
3,TRAIN_000003,201807,D,자녀성장(2),40대,3904,5933,3904,1,1,1
4,TRAIN_000004,201807,E,자녀성장(1),40대,1190,0,0,1,0,-2
...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,E,노년생활,70대이상,10755,5640,7267,1,0,3
2399996,TRAIN_399996,201812,D,자녀성장(2),50대,27636,26357,27636,1,1,38
2399997,TRAIN_399997,201812,C,자녀출산기,30대,23187,17171,23187,1,1,33
2399998,TRAIN_399998,201812,E,자녀성장(1),40대,0,0,0,0,0,-2
2399999,TRAIN_399999,201812,E,자녀성장(1),40대,21463,6984,21463,2,2,-2

In [4]:
df31=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df32=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df33=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df34=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df35=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df36=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])

In [5]:
all_df3 = pd.concat([df31, df32, df33, df34, df35, df36])
all_df3.reset_index(inplace=True, drop=True)
all_df3

,ID,기준년월,이용금액_오프라인_B0M,정상청구원금_B5M,정상청구원금_B0M,정상청구원금_B2M,이용개월수_신용_R12M,연속유실적개월수_기본_24M_카드,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,_3순위쇼핑업종_이용금액,정상입금원금_B0M,_3순위업종_이용금액,이용개월수_전체_R3M,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,정상입금원금_B5M
0,TRAIN_000000,201807,4043,14958,14440,16524,12,13,12,12,...,0,6335,672,3,17,0,1408,6,16125,9205
1,TRAIN_000001,201807,3980,3367,6024,2420,12,12,12,12,...,315,5198,1659,3,51,0,2083,6,2420,2546
2,TRAIN_000002,201807,4524,23963,21929,21826,9,8,9,9,...,924,12564,1362,3,33,0,1539,6,14448,16949
3,TRAIN_000003,201807,3975,19614,18563,19172,12,5,12,7,...,0,7639,774,3,19,0,2284,6,13043,8418
4,TRAIN_000004,201807,0,0,0,272,1,0,1,1,...,0,0,0,0,0,6,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,0,0,19,0,3,0,0,0,...,0,0,0,0,0,8,0,0,0,0
2399996,TRAIN_399996,201812,4676,23742,13462,14844,12,17,12,12,...,346,9705,1547,3,24,0,1810,6,10764,21831
2399997,TRAIN_399997,201812,4516,4125,7049,6862,12,24,12,12,...,305,5346,2302,3,32,1,2315,6,6106,3269
2399998,TRAIN_399998,201812,0,507,0,0,0,0,0,0,...,0,0,0,0,0,12,0,0,0,0
2399999,TRAIN_399999,201812,0,4514,3129,5357,9,5,8,7,...,0,2662,894,3,21,0,926,6,3173,3647

In [6]:
df41=pd.read_parquet(r'train/4.청구입금정보/201807_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df42=pd.read_parquet(r'train/4.청구입금정보/201808_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df43=pd.read_parquet(r'train/4.청구입금정보/201809_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df44=pd.read_parquet(r'train/4.청구입금정보/201810_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df45=pd.read_parquet(r'train/4.청구입금정보/201811_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df46=pd.read_parquet(r'train/4.청구입금정보/201812_train_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])

In [7]:
all_df4 = pd.concat([df41, df42, df43, df44, df45, df46])
all_df4.reset_index(inplace=True, drop=True)
all_df4

                   ID    기준년월  청구금액_R6M  청구금액_R3M  청구금액_B0  청구서발송여부_B0
0        TRAIN_000000  201807     88693     46588    12226           1
1        TRAIN_000001  201807     16861     10530     5834           1
2        TRAIN_000002  201807    165221     85931    21866           1
3        TRAIN_000003  201807    127371     61518    16356           1
4        TRAIN_000004  201807       155         0        0           0
...               ...     ...       ...       ...      ...         ...
2399995  TRAIN_399995  201812         0         0        0           0
2399996  TRAIN_399996  201812     99849     37515    14402           1
2399997  TRAIN_399997  201812     41073     22274     5731           1
2399998  TRAIN_399998  201812         0         0        0           0
2399999  TRAIN_399999  201812     19948      9704     3422           1

[2400000 rows x 6 columns]

In [8]:
merged_df = all_df1.merge(all_df3, on=['ID', '기준년월'], how='left') \
                   .merge(all_df4, on=['ID', '기준년월'], how='left')

In [9]:
merged_df

,ID,기준년월,Segment,Life_Stage,연령,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,이용카드수_신용,...,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,정상입금원금_B5M,청구금액_R6M,청구금액_R3M,청구금액_B0,청구서발송여부_B0
0,TRAIN_000000,201807,D,자녀성장(2),40대,196,3681,196,1,1,...,17,0,1408,6,16125,9205,88693,46588,12226,1
1,TRAIN_000001,201807,E,자녀성장(1),30대,13475,13323,13475,1,1,...,51,0,2083,6,2420,2546,16861,10530,5834,1
2,TRAIN_000002,201807,C,자녀출산기,30대,23988,24493,23988,1,1,...,33,0,1539,6,14448,16949,165221,85931,21866,1
3,TRAIN_000003,201807,D,자녀성장(2),40대,3904,5933,3904,1,1,...,19,0,2284,6,13043,8418,127371,61518,16356,1
4,TRAIN_000004,201807,E,자녀성장(1),40대,1190,0,0,1,0,...,0,6,0,1,0,0,155,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,201812,E,노년생활,70대이상,10755,5640,7267,1,0,...,0,8,0,0,0,0,0,0,0,0
2399996,TRAIN_399996,201812,D,자녀성장(2),50대,27636,26357,27636,1,1,...,24,0,1810,6,10764,21831,99849,37515,14402,1
2399997,TRAIN_399997,201812,C,자녀출산기,30대,23187,17171,23187,1,1,...,32,1,2315,6,6106,3269,41073,22274,5731,1
2399998,TRAIN_399998,201812,E,자녀성장(1),40대,0,0,0,0,0,...,0,12,0,0,0,0,0,0,0,0
2399999,TRAIN_399999,201812,E,자녀성장(1),40대,21463,6984,21463,2,2,...,21,0,926,6,3173,3647,19948,9704,3422,1

In [10]:
merged_df.to_csv('E,notE(train).csv', index=False, encoding='utf-8-sig')

### Test

In [11]:
df_test11=pd.read_parquet(r'test/1.회원정보/201807_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df_test12=pd.read_parquet(r'test/1.회원정보/201808_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df_test13=pd.read_parquet(r'test/1.회원정보/201809_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df_test14=pd.read_parquet(r'test/1.회원정보/201810_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df_test15=pd.read_parquet(r'test/1.회원정보/201811_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])
df_test16=pd.read_parquet(r'test/1.회원정보/201812_test_.parquet',columns=['ID','기준년월','Life_Stage','연령','이용금액_R3M_신용체크', '_1순위카드이용금액', '이용금액_R3M_신용', '이용카드수_신용체크', '이용카드수_신용', '_1순위카드이용건수'])

In [12]:
all_dftest1 = pd.concat([df_test11, df_test12, df_test13, df_test14, df_test15, df_test16])
all_dftest1.reset_index(inplace=True, drop=True)
all_dftest1

,ID,기준년월,Life_Stage,연령,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수
0,TEST_00000,201807,자녀성장(1),40대,21458,13852,21458,2,2,51
1,TEST_00001,201807,자녀독립기,60대,18681,11065,10759,2,1,40
2,TEST_00002,201807,자녀성장(1),40대,40758,27071,40758,2,2,154
3,TEST_00003,201807,자녀성장(1),40대,5255,4827,5255,1,1,105
4,TEST_00004,201807,자녀성장(1),40대,16148,8011,14290,3,2,52
...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,노년생활,60대,0,0,0,0,0,-2
599996,TEST_99996,201812,자녀출산기,30대,3110,1231,3110,1,1,4
599997,TEST_99997,201812,자녀성장(1),30대,0,0,0,0,0,6
599998,TEST_99998,201812,가족구축기,30대,173263,63592,113786,6,4,185
599999,TEST_99999,201812,자녀출산기,30대,3016,-574,3016,2,2,0

In [13]:
df_test31=pd.read_parquet(r'test/3.승인매출정보/201807_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df_test32=pd.read_parquet(r'test/3.승인매출정보/201808_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df_test33=pd.read_parquet(r'test/3.승인매출정보/201809_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df_test34=pd.read_parquet(r'test/3.승인매출정보/201810_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df_test35=pd.read_parquet(r'test/3.승인매출정보/201811_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])
df_test36=pd.read_parquet(r'test/3.승인매출정보/201812_test_.parquet', columns=['ID','기준년월','이용금액_오프라인_B0M', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M', '이용개월수_신용_R12M', '연속유실적개월수_기본_24M_카드', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용금액_일시불_R6M', '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용금액_오프라인_R3M', '이용건수_일시불_R12M', '이용가맹점수', '이용금액_일시불_R12M', '이용개월수_전체_R6M', '이용금액_오프라인_R6M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M', '_2순위쇼핑업종_이용금액', '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '_3순위쇼핑업종_이용금액', '정상입금원금_B0M', '_3순위업종_이용금액', '이용개월수_전체_R3M', '이용건수_오프라인_R3M', '이용후경과월_신용', '_2순위업종_이용금액', '이용개월수_신용_R6M', '정상입금원금_B2M', '정상입금원금_B5M'])

In [14]:
all_dftest3 = pd.concat([df_test31, df_test32, df_test33, df_test34, df_test35, df_test36])
all_dftest3.reset_index(inplace=True, drop=True)
all_dftest3

,ID,기준년월,이용금액_오프라인_B0M,정상청구원금_B5M,정상청구원금_B0M,정상청구원금_B2M,이용개월수_신용_R12M,연속유실적개월수_기본_24M_카드,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,_3순위쇼핑업종_이용금액,정상입금원금_B0M,_3순위업종_이용금액,이용개월수_전체_R3M,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,정상입금원금_B5M
0,TEST_00000,201807,9877,3919,6495,2012,10,5,10,10,...,643,3680,1880,2,48,0,2713,5,1172,1504
1,TEST_00001,201807,4006,5723,9644,5273,9,8,9,9,...,1033,8726,1278,3,14,0,1321,6,4509,2763
2,TEST_00002,201807,11298,11267,11519,11366,12,24,12,12,...,1094,11297,2680,3,151,1,7271,6,11366,11267
3,TEST_00003,201807,976,0,1375,1072,9,5,9,9,...,634,1375,605,3,27,0,2043,5,875,0
4,TEST_00004,201807,4017,1347,3951,1618,12,20,12,12,...,760,3951,1054,3,31,0,1364,6,1618,1347
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,0,0,0,0,0,0,0,0,...,0,0,0,0,0,12,0,0,0,0
599996,TEST_99996,201812,407,992,205,3736,10,8,9,9,...,0,205,0,3,13,0,0,6,252,302
599997,TEST_99997,201812,0,0,0,186,0,0,0,0,...,0,0,0,0,0,12,0,0,0,0
599998,TEST_99998,201812,15388,27335,26308,23261,12,24,12,12,...,1965,0,4612,3,197,0,16296,6,2751,6215
599999,TEST_99999,201812,8,25,20,18,12,24,12,12,...,0,20,0,3,4,2,0,6,18,16

In [15]:
df_test41=pd.read_parquet(r'test/4.청구입금정보/201807_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df_test42=pd.read_parquet(r'test/4.청구입금정보/201808_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df_test43=pd.read_parquet(r'test/4.청구입금정보/201809_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df_test44=pd.read_parquet(r'test/4.청구입금정보/201810_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df_test45=pd.read_parquet(r'test/4.청구입금정보/201811_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])
df_test46=pd.read_parquet(r'test/4.청구입금정보/201812_test_.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0', '청구서발송여부_B0'])

In [16]:
all_dftest4 = pd.concat([df_test41, df_test42, df_test43, df_test44, df_test45, df_test46])
all_dftest4.reset_index(inplace=True, drop=True)
all_dftest4

                ID    기준년월  청구금액_R6M  청구금액_R3M  청구금액_B0  청구서발송여부_B0
0       TEST_00000  201807     22151     11441     4931           1
1       TEST_00001  201807     32878     20522    10152           1
2       TEST_00002  201807     71867     50508    13223           1
3       TEST_00003  201807      4986      4604     2112           1
4       TEST_00004  201807     10758      6788     4406           1
...            ...     ...       ...       ...      ...         ...
599995  TEST_99995  201812         0         0        0           0
599996  TEST_99996  201812      2237      1256      359           1
599997  TEST_99997  201812         0         0        0           0
599998  TEST_99998  201812    108420     48141    21273           1
599999  TEST_99999  201812       105        56       18           1

[600000 rows x 6 columns]

In [18]:
merged_testdf = all_dftest1.merge(all_dftest3, on=['ID', '기준년월'], how='left') \
                   .merge(all_dftest4, on=['ID', '기준년월'], how='left')

In [19]:
merged_testdf.to_csv('E,notE(test).csv', index=False, encoding='utf-8-sig')