In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

In [9]:
df11=pd.read_parquet(r'train/1.회원정보/201807_train_.parquet')
df12=pd.read_parquet(r'train/1.회원정보/201808_train_.parquet')
df13=pd.read_parquet(r'train/1.회원정보/201809_train_.parquet')
df14=pd.read_parquet(r'train/1.회원정보/201810_train_.parquet')
df15=pd.read_parquet(r'train/1.회원정보/201811_train_.parquet')
df16=pd.read_parquet(r'train/1.회원정보/201812_train_.parquet')

In [14]:
df11.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

_2순위신용체크구분        157866
최종유효년월_신용_이용       79318
가입통신회사코드           67364
직장시도명              40807
최종유효년월_신용_이용가능     32828
최종카드발급일자            3007
_1순위신용체크구분          2147
dtype: int64

In [5]:
df_merged = pd.merge(df11, df12, on='ID', suffixes=('_7월', '_8월'))

In [6]:
import numpy as np

change_rate_df = pd.DataFrame()
change_rate_df['ID'] = df_merged['ID']

# 수치형 변수들에 대해서만
numerical_cols = [col.replace('_7월', '') for col in df_merged.columns if '_7월' in col and pd.api.types.is_numeric_dtype(df_merged[col])]

for col in numerical_cols:
    col_7 = f"{col}_7월"
    col_8 = f"{col}_8월"

    # 변화율 = (8월 - 7월) / abs(7월)
    change_rate_df[f"{col}_변화율"] = (df_merged[col_8] - df_merged[col_7]) / (np.abs(df_merged[col_7]) + 1e-6)

In [5]:
import pandas as pd
import numpy as np
from scipy.stats import f_oneway

def compute_change_anova(df1, df2, key='ID', target_col='Segment', alpha=0.05):
    # ID 기준으로 병합
    merged = pd.merge(df1, df2, on=[key, target_col], suffixes=('_7', '_8'))
    
    # 수치형 컬럼만 선택
    num_cols = df1.select_dtypes(include=[np.number]).columns.difference([key])
    
    results = []
    for col in num_cols:
        col_7 = f"{col}_7"
        col_8 = f"{col}_8"
        if col_7 in merged.columns and col_8 in merged.columns:
            # 변화율 계산 (분모가 0인 경우 대비)
            with np.errstate(divide='ignore', invalid='ignore'):
                change = (merged[col_8] - merged[col_7]) / merged[col_7].replace(0, np.nan)
            
            merged['change_rate'] = change
            
            # Segment 그룹별로 ANOVA
            group_data = [
                merged.loc[merged[target_col] == seg, 'change_rate'].dropna()
                for seg in merged[target_col].unique()
            ]
            
            # 그룹 수 2 이상, 데이터가 모두 있는 경우만
            if len(group_data) >= 2 and all(len(g) > 1 for g in group_data):
                stat, p = f_oneway(*group_data)
                results.append({
                    '변수명': col,
                    'p-value': p,
                    '유의함': p < alpha
                })

    result_df = pd.DataFrame(results).sort_values(by='p-value')
    return result_df

In [6]:
# 모든 행/열 출력 설정
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

In [7]:
result_df1 = compute_change_anova(df11, df12)
display(result_df1)

                   변수명        p-value    유의함
37          입회경과개월수_신용   0.000000e+00   True
33            이용카드수_신용  1.869196e-301   True
35          이용카드수_신용체크  3.616248e-283   True
31     이용여부_3M_해외겸용_본인  4.397582e-185   True
32  이용여부_3M_해외겸용_신용_본인  2.328154e-170   True
23          이용가능카드수_신용  4.740533e-136   True
17            유효카드수_신용  6.865518e-117   True
19          유효카드수_신용체크  3.226447e-103   True
0           _1순위카드이용건수  6.867703e-102   True
25        이용가능카드수_신용체크   1.594293e-79   True
10             소지여부_신용   1.118810e-64   True
9      보유여부_해외겸용_신용_본인   3.159740e-60   True
11         소지카드수_유효_신용   4.892350e-53   True
8         보유여부_해외겸용_본인   2.420083e-44   True
43            최종탈회후경과월   1.106301e-39   True
36            이용카드수_체크   6.272668e-28   True
47        회원여부_이용가능_CA   1.215262e-26   True
12       소지카드수_이용가능_신용   1.354785e-26   True
22   이용가능여부_해외겸용_신용_본인   1.573680e-25   True
21      이용가능여부_해외겸용_본인   1.157331e-15   True
46           회원여부_이용가능   9.060991e-15   True
45             탈회횟수_누적   4.483750e-12   True
30         이용금액_R3M_체크   1.208318e-10   True
48       회원여부_이용가능_카드론   7.242288e-08   True
16           수신거부여부_메일   7.954873e-06   True
7              마케팅동의여부   1.881637e-04   True
34         이용카드수_신용_가족   1.986099e-04   True
28      이용금액_R3M_신용_가족   7.716051e-04   True
15           수신거부여부_TM   1.616270e-03   True
24       이용가능카드수_신용_가족   1.714355e-03   True
18         유효카드수_신용_가족   1.773393e-03   True
41           최종카드발급경과월   3.274157e-03   True
13           수신거부여부_DM   4.370315e-03   True
6          동의여부_한도증액안내   4.407117e-03   True
14          수신거부여부_SMS   1.357154e-02   True
40      최종유효년월_신용_이용가능   7.746457e-02  False
39        최종유효년월_신용_이용   1.288986e-01  False
44              카드신청건수   3.498829e-01  False
42            최종카드발급일자   3.692886e-01  False
2           _2순위카드이용건수   4.796837e-01  False
27         이용금액_R3M_신용   5.879687e-01  False
20            유효카드수_체크   6.359986e-01  False
26          이용가능카드수_체크   6.994494e-01  False
29       이용금액_R3M_신용체크   7.151265e-01  False
3           _2순위카드이용금액   8.992651e-01  False
1           _1순위카드이용금액   9.873337e-01  False
4                 기준년월            NaN  False
5               남녀구분코드            NaN  False
38             입회일자_신용            NaN  False

In [8]:
result_df1.to_excel("01.회원정보(변화율).xlsx", index=False)
print('저장 완료')

저장 완료

In [2]:
import pandas as pd

def categorical_change_rate_per_id(df1, df2, id_col='ID'):
    # 범주형 변수만 추출 (숫자형 제외)
    cat_cols = df1.select_dtypes(exclude=['number']).columns.tolist()
    
    # ID 컬럼은 제외
    cat_cols = [col for col in cat_cols if col != id_col]
    
    # 두 데이터프레임에서 필요한 컬럼만 추출
    df1_sub = df1[[id_col] + cat_cols]
    df2_sub = df2[[id_col] + cat_cols]
    
    # 병합
    merged = pd.merge(df1_sub, df2_sub, on=id_col, suffixes=('_prev', '_curr'))
    
    # 변화율 계산
    change_rates = {}
    for col in cat_cols:
        changed = (merged[f"{col}_prev"] != merged[f"{col}_curr"]).mean()
        change_rates[col] = round(changed, 4)
    
    # 결과를 데이터프레임으로 정리
    result_df = pd.DataFrame({
        '컬럼명': list(change_rates.keys()),
        'ID 기준 변화율': list(change_rates.values())
    }).sort_values(by='ID 기준 변화율', ascending=False).reset_index(drop=True)
    
    return result_df

In [19]:
result_df = categorical_change_rate_per_id(df11, df12)
display(result_df)

              컬럼명  ID 기준 변화율
0      _2순위신용체크구분     0.3985
1           직장시도명     0.1858
2        가입통신회사코드     0.1709
3           거주시도명     0.0552
4      _1순위신용체크구분     0.0120
5    연회비발생카드수_B0M     0.0116
6      Life_Stage     0.0031
7         Segment     0.0000
8              연령     0.0000
9   상품관련면제카드수_B0M     0.0000
10   임직원면제카드수_B0M     0.0000
11  우수회원면제카드수_B0M     0.0000
12    기타면제카드수_B0M     0.0000

In [21]:
result_df = categorical_change_rate_per_id(df21, df22)
display(result_df)

             컬럼명  ID 기준 변화율
0       RV전환가능여부     0.0202
1  자발한도감액횟수_R12M     0.0018
2    한도증액횟수_R12M     0.0011
3        카드론동의여부     0.0011
4       한도심사요청건수     0.0001

---

In [15]:
df21=pd.read_parquet(r'train/2.신용정보/201807_train_.parquet')
df22=pd.read_parquet(r'train/2.신용정보/201808_train_.parquet')
df23=pd.read_parquet(r'train/2.신용정보/201809_train_.parquet')
df24=pd.read_parquet(r'train/2.신용정보/201810_train_.parquet')
df25=pd.read_parquet(r'train/2.신용정보/201811_train_.parquet')
df26=pd.read_parquet(r'train/2.신용정보/201812_train_.parquet')

In [16]:
df21.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

RV신청일자    325079
dtype: int64

In [10]:
tg1=pd.read_parquet(r'train/1.회원정보/201807_train_.parquet')
tg2=pd.read_parquet(r'train/1.회원정보/201808_train_.parquet')
tg3=pd.read_parquet(r'train/1.회원정보/201809_train_.parquet')
tg4=pd.read_parquet(r'train/1.회원정보/201810_train_.parquet')
tg5=pd.read_parquet(r'train/1.회원정보/201811_train_.parquet')
tg6=pd.read_parquet(r'train/1.회원정보/201812_train_.parquet')

In [11]:
df_merged2 = pd.merge(df21, df22, on='ID', suffixes=('_7월', '_8월'))

In [13]:
tg1 = pd.read_parquet(r'train/1.회원정보/201807_train_.parquet')
tg2 = pd.read_parquet(r'train/1.회원정보/201808_train_.parquet')

tg_df = pd.concat([tg1, tg2], ignore_index=True)

In [17]:
df21['Segment'] = tg1['Segment'].values
df22['Segment'] = tg2['Segment'].values

In [15]:
df_merged2['Segment'] = tg1['Segment'].values

In [18]:
result_df2 = compute_change_anova(df21, df22)
display(result_df2)

               변수명        p-value    유의함
26        한도증액후경과월  6.358981e-182   True
6         RV최소결제비율  5.382711e-121   True
11      강제한도감액후경과월  2.970899e-119   True
13      상향가능CA한도금액   1.030350e-69   True
21    카드이용한도금액_B1M   2.453686e-57   True
16   일시불ONLY전환가능여부   5.019215e-52   True
25     한도증액금액_R12M   3.721745e-49   True
0        CA이자율_할인전   7.007814e-24   True
14        상향가능한도금액   2.392432e-23   True
9    강제한도감액금액_R12M   7.065061e-22   True
7   RV현금서비스이자율_할인전   8.055795e-19   True
22    카드이용한도금액_B2M   1.358456e-17   True
2        CL이자율_할인전   3.122124e-10   True
17       일시상환론한도금액   2.541877e-08   True
4          RV약정청구율   1.003653e-06   True
20        카드이용한도금액   1.473936e-06   True
10   강제한도감액횟수_R12M   1.720604e-05   True
8       rv최초시작후경과일   3.747732e-04   True
1           CA한도금액   1.429928e-03   True
23      한도심사거절후경과월   1.650765e-03   True
15        월상환론한도금액   3.136394e-03   True
3           RV신청일자   6.653088e-02  False
24      한도심사요청후경과월   7.247386e-02  False
5     RV일시불이자율_할인전   8.829635e-02  False
18      자발한도감액후경과월   1.247367e-01  False
12            기준년월            NaN  False
19          최초한도금액            NaN  False

In [19]:
result_df2.to_excel("02.신용정보(변화율).xlsx", index=False)
print('저장 완료')

저장 완료

In [ ]:
result_df = categorical_change_rate_per_id(df21, df22)
display(result_df)

---

### 3번 데이터 (70까지)

In [2]:
df311=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, :70]
df312=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, :70]
df313=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, :70]
df314=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, :70]
df315=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, :70]
df316=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, :70]

In [3]:
df311.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [46]:
df_merged31 = pd.merge(df311, df312, on='ID', suffixes=('_7월', '_8월'))

In [47]:
df311['Segment'] = tg1['Segment'].values
df312['Segment'] = tg2['Segment'].values

In [48]:
result_df31 = compute_change_anova(df311, df312)
display(result_df31)

                   변수명        p-value    유의함
11         이용건수_신판_B0M   0.000000e+00   True
13        이용건수_일시불_B0M   0.000000e+00   True
9          이용건수_신용_B0M   0.000000e+00   True
35           이용후경과월_CA   0.000000e+00   True
3       이용개월수_일시불_R12M  8.478470e-289   True
32     이용금액_할부_무이자_B0M  7.144614e-287   True
30         이용금액_할부_B0M  1.005287e-268   True
14       이용건수_일시불_R12M  3.709533e-259   True
20     이용건수_할부_무이자_B0M  3.314648e-249   True
1        이용개월수_신용_R12M  3.239766e-246   True
10        이용건수_신용_R12M  1.658755e-232   True
18         이용건수_할부_B0M  1.901652e-231   True
12        이용건수_신판_R12M  3.135388e-222   True
2        이용개월수_신판_R12M  2.062311e-171   True
38          이용후경과월_카드론  2.051437e-143   True
15         이용건수_체크_B0M   1.499795e-40   True
7          이용건수_CA_B0M   4.746404e-37   True
43     최대이용금액_일시불_R12M   8.684229e-34   True
36        이용후경과월_부분무이자   1.808925e-29   True
39           이용후경과월_할부   5.994153e-23   True
37           이용후경과월_체크   4.815878e-21   True
23         이용금액_CA_B0M   1.621934e-20   True
40       이용후경과월_할부_무이자   2.085588e-20   True
44      최대이용금액_체크_R12M   2.001605e-11   True
41       이용후경과월_할부_유이자   4.766758e-11   True
8         이용건수_CA_R12M   1.946734e-10   True
24        이용금액_CA_R12M   1.176637e-09   True
52          최종이용일자_일시불   1.650830e-09   True
55           최종이용일자_할부   4.137860e-08   True
16        이용건수_체크_R12M   1.065405e-06   True
51           최종이용일자_신판   2.118577e-06   True
29       이용금액_카드론_R12M   4.687459e-06   True
50           최종이용일자_기본   6.709040e-06   True
42      최대이용금액_CA_R12M   1.642960e-05   True
33    이용금액_할부_무이자_R12M   1.516110e-04   True
21    이용건수_할부_무이자_R12M   1.661787e-04   True
31        이용금액_할부_R12M   5.308465e-03   True
34    이용금액_할부_유이자_R12M   7.729014e-03   True
47  최대이용금액_할부_무이자_R12M   3.633273e-02   True
46      최대이용금액_할부_R12M   1.807299e-01  False
4        이용개월수_할부_R12M   3.035724e-01  False
19        이용건수_할부_R12M   3.116669e-01  False
17       이용건수_카드론_R12M   3.606726e-01  False
22    이용건수_할부_유이자_R12M   3.718151e-01  False
45     최대이용금액_카드론_R12M   4.578705e-01  False
48  최대이용금액_할부_유이자_R12M   4.802394e-01  False
5    이용개월수_할부_무이자_R12M   5.853635e-01  False
27         이용금액_체크_B0M   7.015897e-01  False
53           최종이용일자_체크   8.568817e-01  False
25        이용금액_일시불_B0M   9.279129e-01  False
6    이용개월수_할부_유이자_R12M   9.492315e-01  False
54          최종이용일자_카드론   9.737605e-01  False
49           최종이용일자_CA   9.737735e-01  False
28        이용금액_체크_R12M   9.940974e-01  False
26       이용금액_일시불_R12M   9.975565e-01  False
0                 기준년월            NaN  False

In [49]:
result_df31.to_excel("03.승인매출정보(변화율)(1).xlsx", index=False)
print('저장 완료')

저장 완료

In [23]:
result_df = categorical_change_rate_per_id(df311, df312)
display(result_df)

Empty DataFrame
Columns: [컬럼명, ID 기준 변화율]
Index: []

### 3번 데이터 (71 ~ 140까지)

In [4]:
df321=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 71:140]
df322=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 71:140]
df323=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 71:140]
df324=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 71:140]
df325=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 71:140]
df326=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 71:140]

In [5]:
df321.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [13]:
df321['ID']=df311['ID'].values
df322['ID']=df312['ID'].values

In [52]:
df_merged32 = pd.merge(df321, df322, on='ID', suffixes=('_7월', '_8월'))

In [53]:
df321['Segment'] = tg1['Segment'].values
df322['Segment'] = tg2['Segment'].values

In [54]:
result_df32 = compute_change_anova(df321, df322)
display(result_df32)

                 변수명        p-value    유의함
22      이용개월수_할부_R3M  4.821067e-202   True
24  이용개월수_할부_무이자_R3M  2.582792e-187   True
33      이용건수_일시불_R6M  9.115426e-183   True
17     이용개월수_일시불_R6M  1.245099e-163   True
15      이용개월수_신판_R6M  3.298726e-157   True
29       이용건수_신용_R6M  9.091406e-152   True
13      이용개월수_신용_R6M  1.319366e-135   True
31       이용건수_신판_R6M  7.023265e-131   True
8        쇼핑_편의점_이용금액  4.642911e-100   True
32      이용건수_일시불_R3M   7.214742e-90   True
38   이용건수_할부_무이자_R3M   7.392242e-89   True
7        쇼핑_온라인_이용금액   5.805215e-79   True
28       이용건수_신용_R3M   2.144923e-74   True
30       이용건수_신판_R3M   1.116092e-68   True
36       이용건수_할부_R3M   2.211600e-59   True
10      이용개월수_CA_R3M   2.076851e-47   True
3         쇼핑_마트_이용금액   3.006300e-44   True
52           이용금액_해외   7.950204e-44   True
2        쇼핑_도소매_이용금액   2.378400e-39   True
0          교통_주유이용금액   1.260552e-31   True
6        쇼핑_아울렛_이용금액   1.835641e-28   True
19      이용개월수_체크_R3M   5.968520e-25   True
25  이용개월수_할부_무이자_R6M   1.319903e-17   True
4        쇼핑_백화점_이용금액   1.625954e-16   True
5       쇼핑_슈퍼마켓_이용금액   1.044386e-15   True
23      이용개월수_할부_R6M   1.255421e-13   True
1         쇼핑_기타_이용금액   3.366388e-09   True
40   이용건수_할부_유이자_R6M   9.991647e-08   True
43    이용금액_부분무이자_R3M   7.773149e-07   True
18     이용개월수_체크_R12M   3.489926e-06   True
39   이용건수_할부_무이자_R6M   3.666215e-06   True
42       이용금액_CA_R6M   9.523819e-06   True
21    이용개월수_카드론_R12M   4.125232e-05   True
37       이용건수_할부_R6M   2.914000e-04   True
27       이용건수_CA_R6M   3.661054e-04   True
9             이용가맹점수   5.982226e-04   True
34       이용건수_체크_R3M   1.552808e-03   True
26       이용건수_CA_R3M   2.145362e-03   True
16     이용개월수_일시불_R3M   5.230343e-03   True
14      이용개월수_신판_R3M   6.924229e-03   True
12      이용개월수_신용_R3M   1.336912e-02   True
35       이용건수_체크_R6M   2.724535e-02   True
11      이용개월수_CA_R6M   2.221749e-01  False
41       이용금액_CA_R3M   2.254497e-01  False
46       이용금액_체크_R3M   2.919152e-01  False
20      이용개월수_체크_R6M   2.948391e-01  False
50   이용금액_할부_무이자_R3M   3.402268e-01  False
48       이용금액_할부_R3M   7.451144e-01  False
44      이용금액_일시불_R3M   8.412679e-01  False
51   이용금액_할부_무이자_R6M   8.756840e-01  False
49       이용금액_할부_R6M   9.914457e-01  False
45      이용금액_일시불_R6M   9.936713e-01  False
47       이용금액_체크_R6M   9.941215e-01  False

In [55]:
result_df32.to_excel("03.승인매출정보(변화율)(2).xlsx", index=False)
print('저장 완료')

저장 완료

In [14]:
result_df = categorical_change_rate_per_id(df321, df322)
display(result_df)

Empty DataFrame
Columns: [컬럼명, ID 기준 변화율]
Index: []

### 3번 데이터 (141 ~ 210번까지)

In [6]:
df331=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 141:210]
df332=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 141:210]
df333=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 141:210]
df334=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 141:210]
df335=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 141:210]
df336=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 141:210]

In [7]:
df331.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

_3순위여유업종    390745
_3순위납부업종    384482
_2순위여유업종    366992
_2순위납부업종    336229
_3순위교통업종    335842
_1순위여유업종    297862
_2순위교통업종    269582
_3순위쇼핑업종    215290
_1순위납부업종    196673
_1순위교통업종    186099
_2순위쇼핑업종    184045
_3순위업종      175156
_1순위쇼핑업종    143665
_2순위업종      141819
_1순위업종       79580
dtype: int64

In [15]:
df331['ID']=df311['ID'].values
df332['ID']=df312['ID'].values

In [58]:
df_merged33 = pd.merge(df331, df332, on='ID', suffixes=('_7월', '_8월'))

In [59]:
df331['Segment'] = tg1['Segment'].values
df332['Segment'] = tg2['Segment'].values

In [60]:
result_df33 = compute_change_anova(df331, df332)
display(result_df33)

                  변수명       p-value    유의함
4       _1순위여유업종_이용금액  7.493249e-66   True
2       _1순위쇼핑업종_이용금액  2.639937e-63   True
17          교통_택시이용금액  2.795764e-56   True
25          여유_숙박이용금액  2.916640e-42   True
12      _3순위쇼핑업종_이용금액  1.409398e-37   True
7       _2순위쇼핑업종_이용금액  1.680973e-35   True
16        교통_철도버스이용금액  2.619285e-33   True
26          여유_운동이용금액  3.691897e-30   True
38  할부금액_유이자_14M_R12M  1.050789e-28   True
24          여유_기타이용금액  2.624450e-19   True
9       _2순위여유업종_이용금액  5.336761e-19   True
22         여유_Pet이용금액  1.252100e-15   True
36       할부금액_3M_R12M  4.868370e-15   True
39   할부금액_유이자_3M_R12M  3.775589e-12   True
23          여유_공연이용금액  3.995438e-12   True
35      할부금액_14M_R12M  3.850686e-11   True
19          납부_기타이용금액  3.678990e-10   True
14      _3순위여유업종_이용금액  4.688556e-08   True
27          여유_항공이용금액  3.908965e-07   True
30   할부건수_무이자_3M_R12M  3.348110e-06   True
5       _2순위교통업종_이용금액  2.820693e-05   True
0       _1순위교통업종_이용금액  4.687739e-04   True
18       납부_가스전기료이용금액  5.856446e-04   True
37       할부금액_6M_R12M  1.505178e-03   True
31   할부건수_무이자_6M_R12M  1.810549e-03   True
29       할부건수_6M_R12M  1.019197e-02   True
40   할부금액_유이자_6M_R12M  3.043432e-02   True
1       _1순위납부업종_이용금액  5.143900e-02  False
20         납부_보험료이용금액  5.331598e-02  False
15       교통_버스지하철이용금액  5.409404e-02  False
10      _3순위교통업종_이용금액  6.683099e-02  False
28       할부건수_3M_R12M  8.879602e-02  False
32   할부건수_유이자_3M_R12M  1.054984e-01  False
13        _3순위업종_이용금액  1.062313e-01  False
21         납부_통신비이용금액  1.540977e-01  False
6       _2순위납부업종_이용금액  2.554732e-01  False
3         _1순위업종_이용금액  4.308983e-01  False
11      _3순위납부업종_이용금액  4.367911e-01  False
8         _2순위업종_이용금액  5.101418e-01  False
34      할부금액_12M_R12M  5.570460e-01  False
33   할부건수_유이자_6M_R12M  6.014742e-01  False

In [61]:
result_df33.to_excel("03.승인매출정보(변화율)(3).xlsx", index=False)
print('저장 완료')

저장 완료

In [16]:
result_df = categorical_change_rate_per_id(df331, df332)
display(result_df)

         컬럼명  ID 기준 변화율
0   _3순위여유업종     0.9907
1   _3순위납부업종     0.9643
2   _2순위여유업종     0.9539
3   _3순위교통업종     0.8819
4   _2순위납부업종     0.8548
5   _1순위여유업종     0.7991
6   _2순위교통업종     0.7250
7   _3순위쇼핑업종     0.6834
8     _3순위업종     0.6408
9   _2순위쇼핑업종     0.6045
10    _2순위업종     0.5488
11  _1순위납부업종     0.5118
12  _1순위교통업종     0.5016
13  _1순위쇼핑업종     0.4475
14    _1순위업종     0.3085

### 3번 데이터 (211 ~ 280번까지)

In [17]:
df341=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 211:280]
df342=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 211:280]
df343=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 211:280]
df344=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 211:280]
df345=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 211:280]
df346=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 211:280]

In [18]:
df341['ID']=df311['ID'].values
df342['ID']=df312['ID'].values

In [64]:
df_merged34 = pd.merge(df341, df342, on='ID', suffixes=('_7월', '_8월'))

In [65]:
df341['Segment'] = tg1['Segment'].values
df342['Segment'] = tg2['Segment'].values

In [66]:
result_df34 = compute_change_anova(df341, df342)
display(result_df34)

                  변수명        p-value    유의함
33         최종카드론이용경과월  1.552719e-246   True
9           RP후경과월_교통  6.705255e-221   True
18     이용개월수_오프라인_R6M  1.936811e-134   True
22      이용금액_오프라인_R6M   7.270554e-70   True
21       이용건수_온라인_R6M   3.116811e-59   True
6              RP후경과월   1.907899e-54   True
1         RP건수_교통_B0M   3.166119e-22   True
0            RP건수_B0M   2.000225e-12   True
26       증감_RP유형건수_전월   1.255431e-11   True
4            RP금액_B0M   2.639676e-11   True
12         RP후경과월_아파트   5.658393e-10   True
39   할부금액_무이자_3M_R12M   1.542688e-08   True
19      이용개월수_온라인_R6M   1.154298e-07   True
15  RP후경과월_제휴사서비스직접판매   1.616183e-07   True
20      이용건수_오프라인_R6M   3.391410e-05   True
11          RP후경과월_보험   1.159528e-04   True
40   할부금액_무이자_6M_R12M   1.819725e-04   True
5          RP유형건수_B0M   7.244090e-04   True
16          RP후경과월_통신   9.855981e-04   True
23       이용금액_온라인_R6M   4.144226e-03   True
24      증감_RP건수_교통_전월   1.021988e-02   True
25         증감_RP건수_전월   6.987189e-02  False
17         RP후경과월_학습비   7.006275e-02  False
10          RP후경과월_렌탈   7.867270e-02  False
2         RP건수_보험_B0M   1.035801e-01  False
30         최종카드론_대출월수   2.819468e-01  False
31         최종카드론_대출이율   3.124251e-01  False
7           RP후경과월_가스   3.245462e-01  False
28     최종카드론_금융상환방식코드   5.916852e-01  False
29         최종카드론_대출금액   6.559275e-01  False
38  할부금액_무이자_12M_R12M   8.957078e-01  False
14          RP후경과월_전기   8.983056e-01  False
3         RP건수_통신_B0M   9.189637e-01  False
35         카드론이용건수_누적   9.768353e-01  False
37         카드론이용월수_누적   9.769449e-01  False
27        최종카드론_거치개월수   9.777010e-01  False
36         카드론이용금액_누적   9.784006e-01  False
32         최종카드론_대출일자   9.786421e-01  False
34         최초카드론이용경과월   9.918734e-01  False
8           RP후경과월_건강            NaN  False
13        RP후경과월_유선방송            NaN  False

In [67]:
result_df34.to_excel("03.승인매출정보(변화율)(4).xlsx", index=False)
print('저장 완료')

저장 완료

In [19]:
result_df = categorical_change_rate_per_id(df341, df342)
display(result_df)

            컬럼명  ID 기준 변화율
0  최종카드론_신청경로코드     0.8281

### 3번 데이터 (281~350번까지)

In [5]:
df351=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 281:350]
df352=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 281:350]
df353=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 281:350]
df354=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 281:350]
df355=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 281:350]
df356=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 281:350]

In [6]:
df351['ID']=df311['ID'].values
df352['ID']=df312['ID'].values

In [70]:
df_merged35 = pd.merge(df351, df352, on='ID', suffixes=('_7월', '_8월'))

In [71]:
df351['Segment'] = tg1['Segment'].values
df352['Segment'] = tg2['Segment'].values

In [72]:
result_df35 = compute_change_anova(df351, df352)
display(result_df35)

                  변수명        p-value    유의함
25    이용건수_페이_온라인_B0M  2.151957e-189   True
20       이용건수_온라인_B0M  3.352723e-189   True
36      이용금액_간편결제_B0M  1.528315e-188   True
46    이용금액_페이_온라인_R3M  4.639596e-180   True
45    이용금액_페이_온라인_B0M  4.233471e-171   True
21       이용건수_온라인_R3M  4.343630e-123   True
41       이용금액_온라인_B0M  2.448343e-121   True
37      이용금액_간편결제_R3M  9.536722e-115   True
17      이용건수_간편결제_R6M   5.240548e-66   True
3      이용개월수_간편결제_R6M   5.243673e-45   True
26    이용건수_페이_온라인_R3M   3.089661e-35   True
27    이용건수_페이_온라인_R6M   2.397599e-28   True
19      이용건수_오프라인_R3M   1.630874e-27   True
18      이용건수_오프라인_B0M   1.181944e-25   True
6    이용개월수_페이_온라인_R6M   1.214901e-21   True
16      이용건수_간편결제_R3M   1.130129e-19   True
42   이용금액_페이_오프라인_B0M   1.265213e-18   True
40      이용금액_오프라인_R3M   1.141420e-17   True
15      이용건수_간편결제_B0M   1.581190e-17   True
11       이용건수_C페이_R3M   5.783472e-15   True
28       이용금액_A페이_B0M   1.235605e-13   True
23   이용건수_페이_오프라인_R3M   1.195498e-11   True
47    이용금액_페이_온라인_R6M   2.183090e-09   True
29       이용금액_A페이_R3M   2.928500e-09   True
22   이용건수_페이_오프라인_B0M   3.497389e-09   True
7        이용건수_A페이_B0M   2.522502e-08   True
12       이용건수_C페이_R6M   1.291807e-07   True
1       이용개월수_C페이_R6M   1.291807e-07   True
10       이용건수_C페이_B0M   4.376925e-07   True
31       이용금액_C페이_R3M   1.330038e-06   True
43   이용금액_페이_오프라인_R3M   2.614500e-06   True
34       이용금액_D페이_R3M   1.797884e-05   True
38      이용금액_간편결제_R6M   5.366212e-05   True
2       이용개월수_D페이_R6M   9.128776e-05   True
14       이용건수_D페이_R6M   9.128776e-05   True
32       이용금액_C페이_R6M   1.624314e-04   True
4      이용개월수_당사기타_R6M   2.310791e-04   True
5   이용개월수_페이_오프라인_R6M   6.853890e-04   True
13       이용건수_D페이_R3M   8.057377e-04   True
33       이용금액_D페이_B0M   1.695838e-03   True
30       이용금액_A페이_R6M   3.638415e-03   True
24   이용건수_페이_오프라인_R6M   6.250256e-03   True
44   이용금액_페이_오프라인_R6M   7.867924e-03   True
0       이용개월수_A페이_R6M   6.950206e-02  False
9        이용건수_A페이_R6M   7.941889e-02  False
8        이용건수_A페이_R3M   1.097812e-01  False
35       이용금액_D페이_R6M   3.999359e-01  False
39      이용금액_오프라인_B0M   9.000587e-01  False

In [73]:
result_df35.to_excel("03.승인매출정보(변화율)(5).xlsx", index=False)
print('저장 완료')

저장 완료

In [7]:
result_df = categorical_change_rate_per_id(df351, df352)
display(result_df)

Empty DataFrame
Columns: [컬럼명, ID 기준 변화율]
Index: []

### 3번 데이터 (351~)

In [8]:
df361=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 351:]
df362=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 351:]
df363=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 351:]
df364=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 351:]
df365=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 351:]
df366=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 351:]

In [9]:
df361['ID']=df311['ID'].values
df362['ID']=df312['ID'].values

In [90]:
df_merged36 = pd.merge(df361, df362, on='ID', suffixes=('_7월', '_8월'))

In [91]:
df361['Segment'] = tg1['Segment'].values
df362['Segment'] = tg2['Segment'].values

In [92]:
result_df36 = compute_change_anova(df361, df362)
display(result_df36)

                   변수명        p-value    유의함
21        이용개월수_전체_R6M  8.801242e-175   True
13  연속유실적개월수_기본_24M_카드  4.974024e-154   True
34          정상입금원금_B0M  3.619375e-134   True
18       이용개월수_결제일_R6M  2.335739e-126   True
11      신청건수_ATM_CA_B0   5.992639e-77   True
9        승인거절건수_기타_R3M   1.073505e-73   True
35          정상입금원금_B2M   5.983262e-65   True
36          정상입금원금_B5M   4.723985e-60   True
4            선입금원금_B0M   1.670703e-30   True
17       이용개월수_결제일_R3M   5.918141e-21   True
20        이용개월수_전체_R3M   6.043022e-21   True
1          가맹점매출금액_B2M   3.502893e-19   True
38          정상청구원금_B2M   4.467542e-13   True
25        이용금액_선결제_R3M   1.072173e-12   True
37          정상청구원금_B0M   2.752207e-12   True
15          연체입금원금_B2M   3.471399e-10   True
8           승인거절건수_R3M   3.897003e-10   True
39          정상청구원금_B5M   2.289523e-08   True
5            선입금원금_B2M   8.466730e-07   True
27         이용금액_연체_R3M   1.153035e-06   True
32         이용횟수_연체_R3M   2.019392e-06   True
10     승인거절건수_한도초과_R3M   9.419843e-05   True
6            선입금원금_B5M   1.463847e-04   True
24        이용금액_선결제_B0M   4.479089e-04   True
7        승인거절건수_BL_R3M   4.229412e-03   True
0          가맹점매출금액_B1M   4.287102e-03   True
33         이용횟수_연체_R6M   6.493227e-03   True
22        이용건수_선결제_R3M   7.745413e-03   True
26        이용금액_선결제_R6M   1.729435e-02   True
28         이용금액_연체_R6M   2.822522e-02   True
19       이용개월수_선결제_R6M   3.419703e-02   True
30        이용횟수_선결제_R3M   6.000923e-02  False
14          연체입금원금_B0M   1.254389e-01  False
29        이용횟수_선결제_B0M   1.544243e-01  False
31        이용횟수_선결제_R6M   3.093375e-01  False
2          건수_할부전환_R6M   7.013213e-01  False
12     신청건수_ATM_CA_R6M   7.774392e-01  False
23        이용건수_선결제_R6M   8.618020e-01  False
3          금액_할부전환_R6M   9.117860e-01  False
16          연체입금원금_B5M   9.125869e-01  False

In [93]:
result_df36.to_excel("03.승인매출정보(변화율)(6).xlsx", index=False)
print('저장 완료')

저장 완료

In [10]:
result_df = categorical_change_rate_per_id(df361, df362)
display(result_df)

     컬럼명  ID 기준 변화율
0  이용금액대     0.1029

---

In [8]:
df41=pd.read_parquet(r'train/4.청구입금정보/201807_train_.parquet')
df42=pd.read_parquet(r'train/4.청구입금정보/201808_train_.parquet')
df43=pd.read_parquet(r'train/4.청구입금정보/201809_train_.parquet')
df44=pd.read_parquet(r'train/4.청구입금정보/201810_train_.parquet')
df45=pd.read_parquet(r'train/4.청구입금정보/201811_train_.parquet')
df46=pd.read_parquet(r'train/4.청구입금정보/201812_train_.parquet')

In [9]:
df41.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [95]:
df_merged4 = pd.merge(df41, df42, on='ID', suffixes=('_7월', '_8월'))

In [96]:
df41['Segment'] = tg1['Segment'].values
df42['Segment'] = tg2['Segment'].values

In [97]:
result_df4 = compute_change_anova(df41, df42)
display(result_df4)

                 변수명        p-value    유의함
16        청구서발송여부_B0   0.000000e+00   True
17       청구서발송여부_R3M  4.997803e-199   True
18       청구서발송여부_R6M  1.624499e-132   True
23   포인트_마일리지_환산_B0M   4.470884e-28   True
14          청구금액_R3M   1.733910e-26   True
30   포인트_포인트_월적립_R3M   1.969592e-25   True
8      상환개월수_결제일_R6M   1.751499e-24   True
5      마일_적립포인트_R12M   9.500996e-17   True
31          할인금액_B0M   1.270836e-16   True
25     포인트_이용포인트_R3M   6.250139e-15   True
24    포인트_이용포인트_R12M   9.794097e-12   True
15          청구금액_R6M   2.908603e-11   True
6       마일_적립포인트_R3M   1.060064e-09   True
9          선결제건수_R3M   7.278610e-06   True
28    포인트_포인트_건별_B0M   8.831872e-06   True
21  포인트_마일리지_월적립_B0M   9.254730e-06   True
19   포인트_마일리지_건별_B0M   2.675891e-05   True
32          할인금액_R3M   5.866346e-05   True
20   포인트_마일리지_건별_R3M   7.522830e-05   True
34      할인금액_청구서_R3M   1.026843e-04   True
26    포인트_적립포인트_R12M   5.092869e-04   True
33      할인금액_청구서_B0M   2.321193e-03   True
36        혜택수혜금액_R3M   2.543535e-03   True
3       마일_이용포인트_R3M   4.197760e-03   True
2      마일_이용포인트_R12M   1.876957e-02   True
13           청구금액_B0   4.819452e-02   True
1              대표결제일   5.183002e-02  False
22  포인트_마일리지_월적립_R3M   2.734449e-01  False
12          연체건수_R6M   3.059972e-01  False
7      상환개월수_결제일_R3M   5.218482e-01  False
10         선결제건수_R6M   5.792624e-01  False
27     포인트_적립포인트_R3M   7.397982e-01  False
11          연체건수_R3M   8.387089e-01  False
35            혜택수혜금액   8.983969e-01  False
29    포인트_포인트_건별_R3M   9.674057e-01  False
4       마일_잔여포인트_B0M   9.717255e-01  False
0               기준년월            NaN  False

In [104]:
result_df4.to_excel("04.청구입금정보.xlsx", index=False)
print('저장 완료')

저장 완료

In [12]:
result_df = categorical_change_rate_per_id(df41, df42)
display(result_df)

             컬럼명  ID 기준 변화율
0       할인건수_R3M     0.0300
1   대표청구서수령지구분코드     0.0157
2        청구서수령방법     0.0157
3  대표청구지고객주소구분코드     0.0054
4       할인건수_B0M     0.0025
5       대표결제방법코드     0.0000

---

In [10]:
df51=pd.read_parquet(r'train/5.잔액정보/201807_train_.parquet')
df52=pd.read_parquet(r'train/5.잔액정보/201808_train_.parquet')
df53=pd.read_parquet(r'train/5.잔액정보/201809_train_.parquet')
df54=pd.read_parquet(r'train/5.잔액정보/201810_train_.parquet')
df55=pd.read_parquet(r'train/5.잔액정보/201811_train_.parquet')
df56=pd.read_parquet(r'train/5.잔액정보/201812_train_.parquet')

In [11]:
df51.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

연체일자_B0M    398300
dtype: int64

In [100]:
df_merged5 = pd.merge(df51, df52, on='ID', suffixes=('_7월', '_8월'))

In [101]:
df51['Segment'] = tg1['Segment'].values
df52['Segment'] = tg2['Segment'].values

In [102]:
result_df5 = compute_change_anova(df51, df52)
display(result_df5)

                변수명        p-value    유의함
20       잔액_일시불_B0M  8.037874e-159   True
36     잔액_현금서비스_B2M  1.160159e-137   True
7          연체일수_B1M  5.990399e-114   True
32    잔액_할부_무이자_B0M   8.544107e-89   True
34     잔액_현금서비스_B0M   5.831520e-77   True
37           최종연체회차   1.175484e-65   True
31        잔액_할부_B2M   3.737798e-54   True
43      평잔_RV일시불_6M   9.661154e-42   True
30        잔액_할부_B1M   1.030501e-41   True
13       월중평잔_RV일시불   1.318603e-32   True
29        잔액_할부_B0M   1.869477e-32   True
42      평잔_RV일시불_3M   3.965140e-29   True
17          월중평잔_할부   1.650508e-27   True
18      월중평잔_할부_B0M   5.238658e-24   True
48     평잔_일시불_해외_3M   3.452662e-23   True
49     평잔_일시불_해외_6M   1.566631e-22   True
21       잔액_일시불_B1M   4.034895e-21   True
53         평잔_할부_6M   4.290838e-16   True
39            평잔_6M   2.357206e-14   True
50        평잔_카드론_3M   1.089096e-12   True
41         평잔_CA_6M   4.011866e-12   True
52         평잔_할부_3M   2.688899e-11   True
35     잔액_현금서비스_B1M   3.439251e-11   True
3      RV_평균잔액_R12M   5.773649e-10   True
22       잔액_일시불_B2M   2.941560e-09   True
0      RV_최대잔액_R12M   1.075019e-08   True
38            평잔_3M   1.331177e-07   True
12      월중평잔_CA_B0M   1.263632e-06   True
33    잔액_할부_유이자_B0M   1.484563e-06   True
51        평잔_카드론_6M   2.475288e-06   True
28       잔액_카드론_B5M   2.597330e-06   True
11          월중평잔_CA   8.204103e-06   True
27       잔액_카드론_B4M   2.578478e-05   True
44   평잔_RV일시불_해외_3M   5.260816e-05   True
15     월중평잔_일시불_B0M   7.051165e-05   True
26       잔액_카드론_B3M   2.272709e-04   True
5       RV_평균잔액_R6M   2.959633e-04   True
2       RV_최대잔액_R6M   4.500975e-04   True
45   평잔_RV일시불_해외_6M   5.952909e-04   True
46        평잔_일시불_3M   2.021835e-03   True
47        평잔_일시불_6M   2.129585e-03   True
19  잔액_리볼빙일시불이월_B0M   2.805472e-03   True
25       잔액_카드론_B2M   1.667827e-02   True
1       RV_최대잔액_R3M   3.640239e-02   True
4       RV_평균잔액_R3M   3.716292e-02   True
23       잔액_카드론_B0M   7.961666e-02  False
10             월중평잔   9.514050e-02  False
14         월중평잔_일시불   9.768267e-02  False
40         평잔_CA_3M   2.951763e-01  False
8          연체일수_B2M   3.286584e-01  False
24       잔액_카드론_B1M   4.902352e-01  False
9           연체일수_최근   6.061953e-01  False
16         월중평잔_카드론   6.078141e-01  False
6              기준년월            NaN  False

In [105]:
result_df5.to_excel("05.잔액정보.xlsx", index=False)
print('저장 완료')

저장 완료

In [15]:
result_df = categorical_change_rate_per_id(df51, df52)
display(result_df)

Empty DataFrame
Columns: [컬럼명, ID 기준 변화율]
Index: []

---

In [12]:
df61=pd.read_parquet(r'train/6.채널정보/201807_train_.parquet')
df62=pd.read_parquet(r'train/6.채널정보/201808_train_.parquet')
df63=pd.read_parquet(r'train/6.채널정보/201809_train_.parquet')
df64=pd.read_parquet(r'train/6.채널정보/201810_train_.parquet')
df65=pd.read_parquet(r'train/6.채널정보/201811_train_.parquet')
df66=pd.read_parquet(r'train/6.채널정보/201812_train_.parquet')

In [13]:
df61.isna().sum().loc[lambda x: x > 0].sort_values(ascending=False)

OS구분코드    272261
dtype: int64

In [107]:
df_merged6 = pd.merge(df61, df62, on='ID', suffixes=('_7월', '_8월'))

In [108]:
df61['Segment'] = tg1['Segment'].values
df62['Segment'] = tg2['Segment'].values

In [109]:
result_df6 = compute_change_anova(df61, df62)
display(result_df6)

                  변수명        p-value    유의함
15      방문후경과월_PC_R6M   0.000000e+00   True
35      인입후경과월_IB_R6M   0.000000e+00   True
21     이용메뉴건수_ARS_B0M  5.877203e-190   True
31       인입횟수_ARS_B0M  2.150864e-185   True
16    방문후경과월_모바일웹_R6M  3.954263e-165   True
27       인입일수_ARS_B0M  8.896239e-142   True
19           상담건수_B0M   1.378151e-45   True
32        인입횟수_IB_B0M   2.815416e-45   True
17       방문후경과월_앱_R6M   3.118893e-41   True
22      이용메뉴건수_IB_B0M   5.426736e-25   True
29        인입일수_IB_B0M   1.308064e-23   True
9          방문월수_앱_R6M   4.808556e-12   True
26        인입월수_IB_R6M   6.775674e-08   True
12         방문일수_앱_R6M   8.835204e-08   True
14         방문횟수_앱_B0M   1.536576e-07   True
11         방문일수_앱_B0M   3.984904e-07   True
10        방문일수_PC_B0M   2.201891e-06   True
25       인입월수_ARS_R6M   9.349853e-06   True
38     홈페이지_선결제건수_R3M   5.348782e-05   True
28       인입일수_ARS_R6M   1.619798e-04   True
5      당사멤버쉽_방문월수_R6M   3.175152e-04   True
1      IB문의건수_선결제_R6M   8.181152e-04   True
20           상담건수_R6M   1.193051e-03   True
36      홈페이지_금융건수_R3M   1.534682e-03   True
13        방문횟수_PC_B0M   2.894838e-03   True
39     홈페이지_선결제건수_R6M   3.079919e-03   True
23      이용메뉴건수_IB_R6M   8.722101e-03   True
33        인입횟수_IB_R6M   1.324421e-02   True
8         방문월수_PC_R6M   3.318044e-02   True
0   IB문의건수_사용승인내역_R6M   5.301686e-02  False
30        인입일수_IB_R6M   1.152593e-01  False
37      홈페이지_금융건수_R6M   2.480268e-01  False
2     IB문의건수_정보변경_R6M   3.097531e-01  False
3     IB문의건수_카드발급_R6M   4.813604e-01  False
34         인입후경과월_ARS   6.346666e-01  False
7      당사멤버쉽_방문횟수_R6M   6.728044e-01  False
6      당사멤버쉽_방문횟수_B0M   9.758370e-01  False
4                기준년월            NaN  False
18      불만제기후경과월_R12M            NaN  False
24    인입불만후경과월_IB_R6M            NaN  False

In [110]:
result_df6.to_excel("06.채널정보.xlsx", index=False)
print('저장 완료')

저장 완료

In [4]:
result_df = categorical_change_rate_per_id(df61, df62)
display(result_df)

              컬럼명  ID 기준 변화율
0          OS구분코드     0.6807
1      방문횟수_앱_R6M     0.0598
2     방문횟수_PC_R6M     0.0258
3     방문일수_PC_R6M     0.0186
4  이용메뉴건수_ARS_R6M     0.0059
5    인입횟수_ARS_R6M     0.0051

---

In [5]:
df71=pd.read_parquet(r'train/7.마케팅정보/201807_train_.parquet')
df72=pd.read_parquet(r'train/7.마케팅정보/201808_train_.parquet')
df73=pd.read_parquet(r'train/7.마케팅정보/201809_train_.parquet')
df74=pd.read_parquet(r'train/7.마케팅정보/201810_train_.parquet')
df75=pd.read_parquet(r'train/7.마케팅정보/201811_train_.parquet')
df76=pd.read_parquet(r'train/7.마케팅정보/201812_train_.parquet')

In [112]:
df_merged7 = pd.merge(df71, df72, on='ID', suffixes=('_7월', '_8월'))

In [113]:
df71['Segment'] = tg1['Segment'].values
df72['Segment'] = tg2['Segment'].values

In [114]:
result_df7 = compute_change_anova(df71, df72)
display(result_df7)

                  변수명        p-value    유의함
11  컨택건수_이용유도_인터넷_B0M   0.000000e+00   True
8   컨택건수_이용유도_LMS_B0M  3.213133e-183   True
14  컨택건수_이용유도_청구서_R6M  5.467036e-137   True
5   컨택건수_부대서비스_TM_R6M   1.776933e-45   True
13  컨택건수_이용유도_청구서_B0M   1.452570e-26   True
9   컨택건수_이용유도_LMS_R6M   6.073298e-25   True
18    컨택건수_카드론_TM_R6M   1.327176e-13   True
10   컨택건수_이용유도_TM_R6M   9.619041e-12   True
12  컨택건수_이용유도_인터넷_R6M   1.021604e-11   True
7    컨택건수_이용유도_EM_R6M   2.188299e-10   True
1     컨택건수_CA_LMS_R6M   1.931986e-07   True
19   컨택건수_카드론_청구서_R6M   4.454664e-05   True
3      컨택건수_보험_TM_B0M   2.099947e-03   True
17   컨택건수_카드론_LMS_R6M   2.374951e-03   True
6    컨택건수_이용유도_EM_B0M   4.397978e-03   True
16    컨택건수_카드론_EM_R6M   1.790007e-02   True
2     컨택건수_CA_청구서_R6M   3.955151e-01  False
15        컨택건수_채권_R6M   4.365976e-01  False
4      컨택건수_보험_TM_R6M   9.790775e-01  False
0                기준년월            NaN  False

In [115]:
result_df7.to_excel("07.마케팅정보.xlsx", index=False)
print('저장 완료')

저장 완료

In [6]:
result_df = categorical_change_rate_per_id(df71, df72)
display(result_df)

            컬럼명  ID 기준 변화율
0  캠페인접촉건수_R12M     0.0983
1  캠페인접촉일수_R12M     0.0909

---

In [7]:
df81=pd.read_parquet(r'train/8.성과정보/201807_train_.parquet')
df82=pd.read_parquet(r'train/8.성과정보/201808_train_.parquet')
df83=pd.read_parquet(r'train/8.성과정보/201809_train_.parquet')
df84=pd.read_parquet(r'train/8.성과정보/201810_train_.parquet')
df85=pd.read_parquet(r'train/8.성과정보/201811_train_.parquet')
df86=pd.read_parquet(r'train/8.성과정보/201812_train_.parquet')

In [118]:
df_merged8 = pd.merge(df81, df82, on='ID', suffixes=('_7월', '_8월'))

In [117]:
df81['Segment'] = tg1['Segment'].values
df82['Segment'] = tg2['Segment'].values

In [119]:
result_df8 = compute_change_anova(df81, df82)
display(result_df8)

                   변수명        p-value    유의함
28      증감율_이용건수_할부_전월  4.446591e-323   True
1             변동률_CA평잔   1.275082e-91   True
8            변동률_카드론평잔   3.127545e-40   True
18      증감율_이용건수_CA_분기   1.528786e-25   True
9             변동률_할부평잔   8.187084e-16   True
3          변동률_RV일시불평잔   9.347657e-11   True
4            변동률_일시불평잔   1.114251e-08   True
2           변동률_RVCA평잔   6.490196e-06   True
27      증감율_이용건수_할부_분기   6.514682e-06   True
12  잔액_신판ca평균한도소진율_r3m   5.152581e-03   True
10  잔액_신판ca최대한도소진율_r3m   1.315326e-02   True
14    잔액_신판최대한도소진율_r3m   1.363562e-02   True
26      증감율_이용건수_체크_전월   8.733803e-02  False
6        변동률_잔액_CA_B1M   3.801661e-01  False
15    잔액_신판최대한도소진율_r6m   5.200521e-01  False
30      증감율_이용금액_CA_전월   5.467663e-01  False
20      증감율_이용건수_신용_전월   5.501135e-01  False
29      증감율_이용금액_CA_분기   5.672685e-01  False
40      증감율_이용금액_할부_전월   5.727594e-01  False
7       변동률_잔액_일시불_B1M   6.056912e-01  False
22      증감율_이용건수_신판_전월   6.111631e-01  False
41           혜택수혜율_B0M   6.490882e-01  False
17    잔액_신판평균한도소진율_r6m   7.844093e-01  False
16    잔액_신판평균한도소진율_r3m   8.142978e-01  False
39      증감율_이용금액_할부_분기   8.608226e-01  False
24     증감율_이용건수_일시불_전월   9.274739e-01  False
13  잔액_신판ca평균한도소진율_r6m   9.350017e-01  False
31      증감율_이용금액_신용_분기   9.373994e-01  False
38      증감율_이용금액_체크_전월   9.395535e-01  False
11  잔액_신판ca최대한도소진율_r6m   9.420780e-01  False
33      증감율_이용금액_신판_분기   9.655664e-01  False
5           변동률_잔액_B1M   9.710947e-01  False
42           혜택수혜율_R3M   9.730695e-01  False
37      증감율_이용금액_체크_분기   9.747316e-01  False
36     증감율_이용금액_일시불_전월   9.817591e-01  False
19      증감율_이용건수_신용_분기   9.818437e-01  False
34      증감율_이용금액_신판_전월   9.884250e-01  False
25      증감율_이용건수_체크_분기   9.907550e-01  False
21      증감율_이용건수_신판_분기   9.923008e-01  False
32      증감율_이용금액_신용_전월   9.949356e-01  False
23     증감율_이용건수_일시불_분기   9.999554e-01  False
35     증감율_이용금액_일시불_분기   9.999651e-01  False
0                 기준년월            NaN  False

In [120]:
result_df8.to_excel("08.마케팅정보.xlsx", index=False)
print('저장 완료')

저장 완료

In [8]:
result_df = categorical_change_rate_per_id(df81, df82)
display(result_df)

Empty DataFrame
Columns: [컬럼명, ID 기준 변화율]
Index: []

---

In [122]:
# 결과 데이터프레임들을 리스트에 넣고 수직 방향으로 합치기
all_results = pd.concat(
    [result_df1, result_df2, result_df31, result_df32,
     result_df33, result_df34, result_df35, result_df36,
     result_df4, result_df5, result_df6, result_df7, result_df8],
    axis=0,
    ignore_index=True
)

# 결과 출력
display(all_results)

                    변수명        p-value    유의함
0            입회경과개월수_신용   0.000000e+00   True
1              이용카드수_신용  1.869196e-301   True
2            이용카드수_신용체크  3.616248e-283   True
3       이용여부_3M_해외겸용_본인  4.397582e-185   True
4    이용여부_3M_해외겸용_신용_본인  2.328154e-170   True
5            이용가능카드수_신용  4.740533e-136   True
6              유효카드수_신용  6.865518e-117   True
7            유효카드수_신용체크  3.226447e-103   True
8            _1순위카드이용건수  6.867703e-102   True
9          이용가능카드수_신용체크   1.594293e-79   True
10              소지여부_신용   1.118810e-64   True
11      보유여부_해외겸용_신용_본인   3.159740e-60   True
12          소지카드수_유효_신용   4.892350e-53   True
13         보유여부_해외겸용_본인   2.420083e-44   True
14             최종탈회후경과월   1.106301e-39   True
15             이용카드수_체크   6.272668e-28   True
16         회원여부_이용가능_CA   1.215262e-26   True
17        소지카드수_이용가능_신용   1.354785e-26   True
18    이용가능여부_해외겸용_신용_본인   1.573680e-25   True
19       이용가능여부_해외겸용_본인   1.157331e-15   True
20            회원여부_이용가능   9.060991e-15   True
21              탈회횟수_누적   4.483750e-12   True
22          이용금액_R3M_체크   1.208318e-10   True
23        회원여부_이용가능_카드론   7.242288e-08   True
24            수신거부여부_메일   7.954873e-06   True
25              마케팅동의여부   1.881637e-04   True
26          이용카드수_신용_가족   1.986099e-04   True
27       이용금액_R3M_신용_가족   7.716051e-04   True
28            수신거부여부_TM   1.616270e-03   True
29        이용가능카드수_신용_가족   1.714355e-03   True
30          유효카드수_신용_가족   1.773393e-03   True
31            최종카드발급경과월   3.274157e-03   True
32            수신거부여부_DM   4.370315e-03   True
33          동의여부_한도증액안내   4.407117e-03   True
34           수신거부여부_SMS   1.357154e-02   True
35       최종유효년월_신용_이용가능   7.746457e-02  False
36         최종유효년월_신용_이용   1.288986e-01  False
37               카드신청건수   3.498829e-01  False
38             최종카드발급일자   3.692886e-01  False
39           _2순위카드이용건수   4.796837e-01  False
40          이용금액_R3M_신용   5.879687e-01  False
41             유효카드수_체크   6.359986e-01  False
42           이용가능카드수_체크   6.994494e-01  False
43        이용금액_R3M_신용체크   7.151265e-01  False
44           _2순위카드이용금액   8.992651e-01  False
45           _1순위카드이용금액   9.873337e-01  False
46                 기준년월            NaN  False
47               남녀구분코드            NaN  False
48              입회일자_신용            NaN  False
49             한도증액후경과월  6.358981e-182   True
50             RV최소결제비율  5.382711e-121   True
51           강제한도감액후경과월  2.970899e-119   True
52           상향가능CA한도금액   1.030350e-69   True
53         카드이용한도금액_B1M   2.453686e-57   True
54        일시불ONLY전환가능여부   5.019215e-52   True
55          한도증액금액_R12M   3.721745e-49   True
56            CA이자율_할인전   7.007814e-24   True
57             상향가능한도금액   2.392432e-23   True
58        강제한도감액금액_R12M   7.065061e-22   True
59       RV현금서비스이자율_할인전   8.055795e-19   True
60         카드이용한도금액_B2M   1.358456e-17   True
61            CL이자율_할인전   3.122124e-10   True
62            일시상환론한도금액   2.541877e-08   True
63              RV약정청구율   1.003653e-06   True
64             카드이용한도금액   1.473936e-06   True
65        강제한도감액횟수_R12M   1.720604e-05   True
66           rv최초시작후경과일   3.747732e-04   True
67               CA한도금액   1.429928e-03   True
68           한도심사거절후경과월   1.650765e-03   True
69             월상환론한도금액   3.136394e-03   True
70               RV신청일자   6.653088e-02  False
71           한도심사요청후경과월   7.247386e-02  False
72         RV일시불이자율_할인전   8.829635e-02  False
73           자발한도감액후경과월   1.247367e-01  False
74                 기준년월            NaN  False
75               최초한도금액            NaN  False
76          이용건수_신판_B0M   0.000000e+00   True
77         이용건수_일시불_B0M   0.000000e+00   True
78          이용건수_신용_B0M   0.000000e+00   True
79            이용후경과월_CA   0.000000e+00   True
80       이용개월수_일시불_R12M  8.478470e-289   True
81      이용금액_할부_무이자_B0M  7.144614e-287   True
82          이용금액_할부_B0M  1.005287e-268   True
83        이용건수_일시불_R12M  3.709533e-259   True
84      이용건수_할부_무이자_B0M  3.314648e-249   True
85        이용개월수_신용_R12M  3.239766e-246   True
86         이용건수_신용_R12M  1.658755e-232   True
87          이용건수_할부_B0M  1.901652e-231   True
88         이용건수_신판_R12M  3.135388e-222   True
89        이용개월수_신판_R12M  2.062311e-171   True
90           이용후경과월_카드론  2.051437e-143   True
91          이용건수_체크_B0M   1.499795e-40   True
92          이용건수_CA_B0M   4.746404e-37   True
93      최대이용금액_일시불_R12M   8.684229e-34   True
94         이용후경과월_부분무이자   1.808925e-29   True
95            이용후경과월_할부   5.994153e-23   True
96            이용후경과월_체크   4.815878e-21   True
97          이용금액_CA_B0M   1.621934e-20   True
98        이용후경과월_할부_무이자   2.085588e-20   True
99       최대이용금액_체크_R12M   2.001605e-11   True
100       이용후경과월_할부_유이자   4.766758e-11   True
101        이용건수_CA_R12M   1.946734e-10   True
102        이용금액_CA_R12M   1.176637e-09   True
103          최종이용일자_일시불   1.650830e-09   True
104           최종이용일자_할부   4.137860e-08   True
105        이용건수_체크_R12M   1.065405e-06   True
106           최종이용일자_신판   2.118577e-06   True
107       이용금액_카드론_R12M   4.687459e-06   True
108           최종이용일자_기본   6.709040e-06   True
109      최대이용금액_CA_R12M   1.642960e-05   True
110    이용금액_할부_무이자_R12M   1.516110e-04   True
111    이용건수_할부_무이자_R12M   1.661787e-04   True
112        이용금액_할부_R12M   5.308465e-03   True
113    이용금액_할부_유이자_R12M   7.729014e-03   True
114  최대이용금액_할부_무이자_R12M   3.633273e-02   True
115      최대이용금액_할부_R12M   1.807299e-01  False
116       이용개월수_할부_R12M   3.035724e-01  False
117        이용건수_할부_R12M   3.116669e-01  False
118       이용건수_카드론_R12M   3.606726e-01  False
119    이용건수_할부_유이자_R12M   3.718151e-01  False
120     최대이용금액_카드론_R12M   4.578705e-01  False
121  최대이용금액_할부_유이자_R12M   4.802394e-01  False
122   이용개월수_할부_무이자_R12M   5.853635e-01  False
123         이용금액_체크_B0M   7.015897e-01  False
124           최종이용일자_체크   8.568817e-01  False
125        이용금액_일시불_B0M   9.279129e-01  False
126   이용개월수_할부_유이자_R12M   9.492315e-01  False
127          최종이용일자_카드론   9.737605e-01  False
128           최종이용일자_CA   9.737735e-01  False
129        이용금액_체크_R12M   9.940974e-01  False
130       이용금액_일시불_R12M   9.975565e-01  False
131                기준년월            NaN  False
132        이용개월수_할부_R3M  4.821067e-202   True
133    이용개월수_할부_무이자_R3M  2.582792e-187   True
134        이용건수_일시불_R6M  9.115426e-183   True
135       이용개월수_일시불_R6M  1.245099e-163   True
136        이용개월수_신판_R6M  3.298726e-157   True
137         이용건수_신용_R6M  9.091406e-152   True
138        이용개월수_신용_R6M  1.319366e-135   True
139         이용건수_신판_R6M  7.023265e-131   True
140         쇼핑_편의점_이용금액  4.642911e-100   True
141        이용건수_일시불_R3M   7.214742e-90   True
142     이용건수_할부_무이자_R3M   7.392242e-89   True
143         쇼핑_온라인_이용금액   5.805215e-79   True
144         이용건수_신용_R3M   2.144923e-74   True
145         이용건수_신판_R3M   1.116092e-68   True
146         이용건수_할부_R3M   2.211600e-59   True
147        이용개월수_CA_R3M   2.076851e-47   True
148          쇼핑_마트_이용금액   3.006300e-44   True
149             이용금액_해외   7.950204e-44   True
150         쇼핑_도소매_이용금액   2.378400e-39   True
151           교통_주유이용금액   1.260552e-31   True
152         쇼핑_아울렛_이용금액   1.835641e-28   True
153        이용개월수_체크_R3M   5.968520e-25   True
154    이용개월수_할부_무이자_R6M   1.319903e-17   True
155         쇼핑_백화점_이용금액   1.625954e-16   True
156        쇼핑_슈퍼마켓_이용금액   1.044386e-15   True
157        이용개월수_할부_R6M   1.255421e-13   True
158          쇼핑_기타_이용금액   3.366388e-09   True
159     이용건수_할부_유이자_R6M   9.991647e-08   True
160      이용금액_부분무이자_R3M   7.773149e-07   True
161       이용개월수_체크_R12M   3.489926e-06   True
162     이용건수_할부_무이자_R6M   3.666215e-06   True
163         이용금액_CA_R6M   9.523819e-06   True
164      이용개월수_카드론_R12M   4.125232e-05   True
165         이용건수_할부_R6M   2.914000e-04   True
166         이용건수_CA_R6M   3.661054e-04   True
167              이용가맹점수   5.982226e-04   True
168         이용건수_체크_R3M   1.552808e-03   True
169         이용건수_CA_R3M   2.145362e-03   True
170       이용개월수_일시불_R3M   5.230343e-03   True
171        이용개월수_신판_R3M   6.924229e-03   True
172        이용개월수_신용_R3M   1.336912e-02   True
173         이용건수_체크_R6M   2.724535e-02   True
174        이용개월수_CA_R6M   2.221749e-01  False
175         이용금액_CA_R3M   2.254497e-01  False
176         이용금액_체크_R3M   2.919152e-01  False
177        이용개월수_체크_R6M   2.948391e-01  False
178     이용금액_할부_무이자_R3M   3.402268e-01  False
179         이용금액_할부_R3M   7.451144e-01  False
180        이용금액_일시불_R3M   8.412679e-01  False
181     이용금액_할부_무이자_R6M   8.756840e-01  False
182         이용금액_할부_R6M   9.914457e-01  False
183        이용금액_일시불_R6M   9.936713e-01  False
184         이용금액_체크_R6M   9.941215e-01  False
185       _1순위여유업종_이용금액   7.493249e-66   True
186       _1순위쇼핑업종_이용금액   2.639937e-63   True
187           교통_택시이용금액   2.795764e-56   True
188           여유_숙박이용금액   2.916640e-42   True
189       _3순위쇼핑업종_이용금액   1.409398e-37   True
190       _2순위쇼핑업종_이용금액   1.680973e-35   True
191         교통_철도버스이용금액   2.619285e-33   True
192           여유_운동이용금액   3.691897e-30   True
193   할부금액_유이자_14M_R12M   1.050789e-28   True
194           여유_기타이용금액   2.624450e-19   True
195       _2순위여유업종_이용금액   5.336761e-19   True
196          여유_Pet이용금액   1.252100e-15   True
197        할부금액_3M_R12M   4.868370e-15   True
198    할부금액_유이자_3M_R12M   3.775589e-12   True
199           여유_공연이용금액   3.995438e-12   True
200       할부금액_14M_R12M   3.850686e-11   True
201           납부_기타이용금액   3.678990e-10   True
202       _3순위여유업종_이용금액   4.688556e-08   True
203           여유_항공이용금액   3.908965e-07   True
204    할부건수_무이자_3M_R12M   3.348110e-06   True
205       _2순위교통업종_이용금액   2.820693e-05   True
206       _1순위교통업종_이용금액   4.687739e-04   True
207        납부_가스전기료이용금액   5.856446e-04   True
208        할부금액_6M_R12M   1.505178e-03   True
209    할부건수_무이자_6M_R12M   1.810549e-03   True
210        할부건수_6M_R12M   1.019197e-02   True
211    할부금액_유이자_6M_R12M   3.043432e-02   True
212       _1순위납부업종_이용금액   5.143900e-02  False
213          납부_보험료이용금액   5.331598e-02  False
214        교통_버스지하철이용금액   5.409404e-02  False
215       _3순위교통업종_이용금액   6.683099e-02  False
216        할부건수_3M_R12M   8.879602e-02  False
217    할부건수_유이자_3M_R12M   1.054984e-01  False
218         _3순위업종_이용금액   1.062313e-01  False
219          납부_통신비이용금액   1.540977e-01  False
220       _2순위납부업종_이용금액   2.554732e-01  False
221         _1순위업종_이용금액   4.308983e-01  False
222       _3순위납부업종_이용금액   4.367911e-01  False
223         _2순위업종_이용금액   5.101418e-01  False
224       할부금액_12M_R12M   5.570460e-01  False
225    할부건수_유이자_6M_R12M   6.014742e-01  False
226          최종카드론이용경과월  1.552719e-246   True
227           RP후경과월_교통  6.705255e-221   True
228      이용개월수_오프라인_R6M  1.936811e-134   True
229       이용금액_오프라인_R6M   7.270554e-70   True
230        이용건수_온라인_R6M   3.116811e-59   True
231              RP후경과월   1.907899e-54   True
232         RP건수_교통_B0M   3.166119e-22   True
233            RP건수_B0M   2.000225e-12   True
234        증감_RP유형건수_전월   1.255431e-11   True
235            RP금액_B0M   2.639676e-11   True
236          RP후경과월_아파트   5.658393e-10   True
237    할부금액_무이자_3M_R12M   1.542688e-08   True
238       이용개월수_온라인_R6M   1.154298e-07   True
239   RP후경과월_제휴사서비스직접판매   1.616183e-07   True
240       이용건수_오프라인_R6M   3.391410e-05   True
241           RP후경과월_보험   1.159528e-04   True
242    할부금액_무이자_6M_R12M   1.819725e-04   True
243          RP유형건수_B0M   7.244090e-04   True
244           RP후경과월_통신   9.855981e-04   True
245        이용금액_온라인_R6M   4.144226e-03   True
246       증감_RP건수_교통_전월   1.021988e-02   True
247          증감_RP건수_전월   6.987189e-02  False
248          RP후경과월_학습비   7.006275e-02  False
249           RP후경과월_렌탈   7.867270e-02  False
250         RP건수_보험_B0M   1.035801e-01  False
251          최종카드론_대출월수   2.819468e-01  False
252          최종카드론_대출이율   3.124251e-01  False
253           RP후경과월_가스   3.245462e-01  False
254      최종카드론_금융상환방식코드   5.916852e-01  False
255          최종카드론_대출금액   6.559275e-01  False
256   할부금액_무이자_12M_R12M   8.957078e-01  False
257           RP후경과월_전기   8.983056e-01  False
258         RP건수_통신_B0M   9.189637e-01  False
259          카드론이용건수_누적   9.768353e-01  False
260          카드론이용월수_누적   9.769449e-01  False
261         최종카드론_거치개월수   9.777010e-01  False
262          카드론이용금액_누적   9.784006e-01  False
263          최종카드론_대출일자   9.786421e-01  False
264          최초카드론이용경과월   9.918734e-01  False
265           RP후경과월_건강            NaN  False
266         RP후경과월_유선방송            NaN  False
267     이용건수_페이_온라인_B0M  2.151957e-189   True
268        이용건수_온라인_B0M  3.352723e-189   True
269       이용금액_간편결제_B0M  1.528315e-188   True
270     이용금액_페이_온라인_R3M  4.639596e-180   True
271     이용금액_페이_온라인_B0M  4.233471e-171   True
272        이용건수_온라인_R3M  4.343630e-123   True
273        이용금액_온라인_B0M  2.448343e-121   True
274       이용금액_간편결제_R3M  9.536722e-115   True
275       이용건수_간편결제_R6M   5.240548e-66   True
276      이용개월수_간편결제_R6M   5.243673e-45   True
277     이용건수_페이_온라인_R3M   3.089661e-35   True
278     이용건수_페이_온라인_R6M   2.397599e-28   True
279       이용건수_오프라인_R3M   1.630874e-27   True
280       이용건수_오프라인_B0M   1.181944e-25   True
281    이용개월수_페이_온라인_R6M   1.214901e-21   True
282       이용건수_간편결제_R3M   1.130129e-19   True
283    이용금액_페이_오프라인_B0M   1.265213e-18   True
284       이용금액_오프라인_R3M   1.141420e-17   True
285       이용건수_간편결제_B0M   1.581190e-17   True
286        이용건수_C페이_R3M   5.783472e-15   True
287        이용금액_A페이_B0M   1.235605e-13   True
288    이용건수_페이_오프라인_R3M   1.195498e-11   True
289     이용금액_페이_온라인_R6M   2.183090e-09   True
290        이용금액_A페이_R3M   2.928500e-09   True
291    이용건수_페이_오프라인_B0M   3.497389e-09   True
292        이용건수_A페이_B0M   2.522502e-08   True
293        이용건수_C페이_R6M   1.291807e-07   True
294       이용개월수_C페이_R6M   1.291807e-07   True
295        이용건수_C페이_B0M   4.376925e-07   True
296        이용금액_C페이_R3M   1.330038e-06   True
297    이용금액_페이_오프라인_R3M   2.614500e-06   True
298        이용금액_D페이_R3M   1.797884e-05   True
299       이용금액_간편결제_R6M   5.366212e-05   True
300       이용개월수_D페이_R6M   9.128776e-05   True
301        이용건수_D페이_R6M   9.128776e-05   True
302        이용금액_C페이_R6M   1.624314e-04   True
303      이용개월수_당사기타_R6M   2.310791e-04   True
304   이용개월수_페이_오프라인_R6M   6.853890e-04   True
305        이용건수_D페이_R3M   8.057377e-04   True
306        이용금액_D페이_B0M   1.695838e-03   True
307        이용금액_A페이_R6M   3.638415e-03   True
308    이용건수_페이_오프라인_R6M   6.250256e-03   True
309    이용금액_페이_오프라인_R6M   7.867924e-03   True
310       이용개월수_A페이_R6M   6.950206e-02  False
311        이용건수_A페이_R6M   7.941889e-02  False
312        이용건수_A페이_R3M   1.097812e-01  False
313        이용금액_D페이_R6M   3.999359e-01  False
314       이용금액_오프라인_B0M   9.000587e-01  False
315        이용개월수_전체_R6M  8.801242e-175   True
316  연속유실적개월수_기본_24M_카드  4.974024e-154   True
317          정상입금원금_B0M  3.619375e-134   True
318       이용개월수_결제일_R6M  2.335739e-126   True
319      신청건수_ATM_CA_B0   5.992639e-77   True
320       승인거절건수_기타_R3M   1.073505e-73   True
321          정상입금원금_B2M   5.983262e-65   True
322          정상입금원금_B5M   4.723985e-60   True
323           선입금원금_B0M   1.670703e-30   True
324       이용개월수_결제일_R3M   5.918141e-21   True
325        이용개월수_전체_R3M   6.043022e-21   True
326         가맹점매출금액_B2M   3.502893e-19   True
327          정상청구원금_B2M   4.467542e-13   True
328        이용금액_선결제_R3M   1.072173e-12   True
329          정상청구원금_B0M   2.752207e-12   True
330          연체입금원금_B2M   3.471399e-10   True
331          승인거절건수_R3M   3.897003e-10   True
332          정상청구원금_B5M   2.289523e-08   True
333           선입금원금_B2M   8.466730e-07   True
334         이용금액_연체_R3M   1.153035e-06   True
335         이용횟수_연체_R3M   2.019392e-06   True
336     승인거절건수_한도초과_R3M   9.419843e-05   True
337           선입금원금_B5M   1.463847e-04   True
338        이용금액_선결제_B0M   4.479089e-04   True
339       승인거절건수_BL_R3M   4.229412e-03   True
340         가맹점매출금액_B1M   4.287102e-03   True
341         이용횟수_연체_R6M   6.493227e-03   True
342        이용건수_선결제_R3M   7.745413e-03   True
343        이용금액_선결제_R6M   1.729435e-02   True
344         이용금액_연체_R6M   2.822522e-02   True
345       이용개월수_선결제_R6M   3.419703e-02   True
346        이용횟수_선결제_R3M   6.000923e-02  False
347          연체입금원금_B0M   1.254389e-01  False
348        이용횟수_선결제_B0M   1.544243e-01  False
349        이용횟수_선결제_R6M   3.093375e-01  False
350         건수_할부전환_R6M   7.013213e-01  False
351     신청건수_ATM_CA_R6M   7.774392e-01  False
352        이용건수_선결제_R6M   8.618020e-01  False
353         금액_할부전환_R6M   9.117860e-01  False
354          연체입금원금_B5M   9.125869e-01  False
355          청구서발송여부_B0   0.000000e+00   True
356         청구서발송여부_R3M  4.997803e-199   True
357         청구서발송여부_R6M  1.624499e-132   True
358     포인트_마일리지_환산_B0M   4.470884e-28   True
359            청구금액_R3M   1.733910e-26   True
360     포인트_포인트_월적립_R3M   1.969592e-25   True
361       상환개월수_결제일_R6M   1.751499e-24   True
362       마일_적립포인트_R12M   9.500996e-17   True
363            할인금액_B0M   1.270836e-16   True
364       포인트_이용포인트_R3M   6.250139e-15   True
365      포인트_이용포인트_R12M   9.794097e-12   True
366            청구금액_R6M   2.908603e-11   True
367        마일_적립포인트_R3M   1.060064e-09   True
368           선결제건수_R3M   7.278610e-06   True
369      포인트_포인트_건별_B0M   8.831872e-06   True
370    포인트_마일리지_월적립_B0M   9.254730e-06   True
371     포인트_마일리지_건별_B0M   2.675891e-05   True
372            할인금액_R3M   5.866346e-05   True
373     포인트_마일리지_건별_R3M   7.522830e-05   True
374        할인금액_청구서_R3M   1.026843e-04   True
375      포인트_적립포인트_R12M   5.092869e-04   True
376        할인금액_청구서_B0M   2.321193e-03   True
377          혜택수혜금액_R3M   2.543535e-03   True
378        마일_이용포인트_R3M   4.197760e-03   True
379       마일_이용포인트_R12M   1.876957e-02   True
380             청구금액_B0   4.819452e-02   True
381               대표결제일   5.183002e-02  False
382    포인트_마일리지_월적립_R3M   2.734449e-01  False
383            연체건수_R6M   3.059972e-01  False
384       상환개월수_결제일_R3M   5.218482e-01  False
385           선결제건수_R6M   5.792624e-01  False
386       포인트_적립포인트_R3M   7.397982e-01  False
387            연체건수_R3M   8.387089e-01  False
388              혜택수혜금액   8.983969e-01  False
389      포인트_포인트_건별_R3M   9.674057e-01  False
390        마일_잔여포인트_B0M   9.717255e-01  False
391                기준년월            NaN  False
392          잔액_일시불_B0M  8.037874e-159   True
393        잔액_현금서비스_B2M  1.160159e-137   True
394            연체일수_B1M  5.990399e-114   True
395       잔액_할부_무이자_B0M   8.544107e-89   True
396        잔액_현금서비스_B0M   5.831520e-77   True
397              최종연체회차   1.175484e-65   True
398           잔액_할부_B2M   3.737798e-54   True
399         평잔_RV일시불_6M   9.661154e-42   True
400           잔액_할부_B1M   1.030501e-41   True
401          월중평잔_RV일시불   1.318603e-32   True
402           잔액_할부_B0M   1.869477e-32   True
403         평잔_RV일시불_3M   3.965140e-29   True
404             월중평잔_할부   1.650508e-27   True
405         월중평잔_할부_B0M   5.238658e-24   True
406        평잔_일시불_해외_3M   3.452662e-23   True
407        평잔_일시불_해외_6M   1.566631e-22   True
408          잔액_일시불_B1M   4.034895e-21   True
409            평잔_할부_6M   4.290838e-16   True
410               평잔_6M   2.357206e-14   True
411           평잔_카드론_3M   1.089096e-12   True
412            평잔_CA_6M   4.011866e-12   True
413            평잔_할부_3M   2.688899e-11   True
414        잔액_현금서비스_B1M   3.439251e-11   True
415        RV_평균잔액_R12M   5.773649e-10   True
416          잔액_일시불_B2M   2.941560e-09   True
417        RV_최대잔액_R12M   1.075019e-08   True
418               평잔_3M   1.331177e-07   True
419         월중평잔_CA_B0M   1.263632e-06   True
420       잔액_할부_유이자_B0M   1.484563e-06   True
421           평잔_카드론_6M   2.475288e-06   True
422          잔액_카드론_B5M   2.597330e-06   True
423             월중평잔_CA   8.204103e-06   True
424          잔액_카드론_B4M   2.578478e-05   True
425      평잔_RV일시불_해외_3M   5.260816e-05   True
426        월중평잔_일시불_B0M   7.051165e-05   True
427          잔액_카드론_B3M   2.272709e-04   True
428         RV_평균잔액_R6M   2.959633e-04   True
429         RV_최대잔액_R6M   4.500975e-04   True
430      평잔_RV일시불_해외_6M   5.952909e-04   True
431           평잔_일시불_3M   2.021835e-03   True
432           평잔_일시불_6M   2.129585e-03   True

In [123]:
# 유의하지 않은 컬럼만 필터링
not_significant_cols = all_results[all_results['유의함'] == False]['변수명'].tolist()

# 결과 확인
print(not_significant_cols)

['최종유효년월_신용_이용가능', '최종유효년월_신용_이용', '카드신청건수', '최종카드발급일자', '_2순위카드이용건수', '이용금액_R3M_신용', '유효카드수_체크', '이용가능카드수_체크', '이용금액_R3M_신용체크', '_2순위카드이용금액', '_1순위카드이용금액', '기준년월', '남녀구분코드', '입회일자_신용', 'RV신청일자', '한도심사요청후경과월', 'RV일시불이자율_할인전', '자발한도감액후경과월', '기준년월', '최초한도금액', '최대이용금액_할부_R12M', '이용개월수_할부_R12M', '이용건수_할부_R12M', '이용건수_카드론_R12M', '이용건수_할부_유이자_R12M', '최대이용금액_카드론_R12M', '최대이용금액_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용금액_체크_B0M', '최종이용일자_체크', '이용금액_일시불_B0M', '이용개월수_할부_유이자_R12M', '최종이용일자_카드론', '최종이용일자_CA', '이용금액_체크_R12M', '이용금액_일시불_R12M', '기준년월', '이용개월수_CA_R6M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용개월수_체크_R6M', '이용금액_할부_무이자_R3M', '이용금액_할부_R3M', '이용금액_일시불_R3M', '이용금액_할부_무이자_R6M', '이용금액_할부_R6M', '이용금액_일시불_R6M', '이용금액_체크_R6M', '_1순위납부업종_이용금액', '납부_보험료이용금액', '교통_버스지하철이용금액', '_3순위교통업종_이용금액', '할부건수_3M_R12M', '할부건수_유이자_3M_R12M', '_3순위업종_이용금액', '납부_통신비이용금액', '_2순위납부업종_이용금액', '_1순위업종_이용금액', '_3순위납부업종_이용금액', '_2순위업종_이용금액', '할부금액_12M_R12M', '할부건수_유이자_6M_R12M', '증감_RP건수_전월', 'RP후경과월_학습비', 'RP후경과월_렌탈', 'RP건수_보험_B0M', '최종카드론_대출월수', '최종카드론_대출이율', 'RP후경과월_가스', '최종카드론_금융상환방식코드', '최종카드론_대출금액', '할부금액_무이자_12M_R12M', 'RP후경과월_전기', 'RP건수_통신_B0M', '카드론이용건수_누적', '카드론이용월수_누적', '최종카드론_거치개월수', '카드론이용금액_누적', '최종카드론_대출일자', '최초카드론이용경과월', 'RP후경과월_건강', 'RP후경과월_유선방송', '이용개월수_A페이_R6M', '이용건수_A페이_R6M', '이용건수_A페이_R3M', '이용금액_D페이_R6M', '이용금액_오프라인_B0M', '이용횟수_선결제_R3M', '연체입금원금_B0M', '이용횟수_선결제_B0M', '이용횟수_선결제_R6M', '건수_할부전환_R6M', '신청건수_ATM_CA_R6M', '이용건수_선결제_R6M', '금액_할부전환_R6M', '연체입금원금_B5M', '대표결제일', '포인트_마일리지_월적립_R3M', '연체건수_R6M', '상환개월수_결제일_R3M', '선결제건수_R6M', '포인트_적립포인트_R3M', '연체건수_R3M', '혜택수혜금액', '포인트_포인트_건별_R3M', '마일_잔여포인트_B0M', '기준년월', '잔액_카드론_B0M', '월중평잔', '월중평잔_일시불', '평잔_CA_3M', '연체일수_B2M', '잔액_카드론_B1M', '연체일수_최근', '월중평잔_카드론', '기준년월', 'IB문의건수_사용승인내역_R6M', '인입일수_IB_R6M', '홈페이지_금융건수_R6M', 'IB문의건수_정보변경_R6M', 'IB문의건수_카드발급_R6M', '인입후경과월_ARS', '당사멤버쉽_방문횟수_R6M', '당사멤버쉽_방문횟수_B0M', '기준년월', '불만제기후경과월_R12M', '인입불만후경과월_IB_R6M', '컨택건수_CA_청구서_R6M', '컨택건수_채권_R6M', '컨택건수_보험_TM_R6M', '기준년월', '증감율_이용건수_체크_전월', '변동률_잔액_CA_B1M', '잔액_신판최대한도소진율_r6m', '증감율_이용금액_CA_전월', '증감율_이용건수_신용_전월', '증감율_이용금액_CA_분기', '증감율_이용금액_할부_전월', '변동률_잔액_일시불_B1M', '증감율_이용건수_신판_전월', '혜택수혜율_B0M', '잔액_신판평균한도소진율_r6m', '잔액_신판평균한도소진율_r3m', '증감율_이용금액_할부_분기', '증감율_이용건수_일시불_전월', '잔액_신판ca평균한도소진율_r6m', '증감율_이용금액_신용_분기', '증감율_이용금액_체크_전월', '잔액_신판ca최대한도소진율_r6m', '증감율_이용금액_신판_분기', '변동률_잔액_B1M', '혜택수혜율_R3M', '증감율_이용금액_체크_분기', '증감율_이용금액_일시불_전월', '증감율_이용건수_신용_분기', '증감율_이용금액_신판_전월', '증감율_이용건수_체크_분기', '증감율_이용건수_신판_분기', '증감율_이용금액_신용_전월', '증감율_이용건수_일시불_분기', '증감율_이용금액_일시불_분기', '기준년월']

In [124]:
# 유의하지 않은 컬럼만 추출한 데이터프레임
not_significant_df = all_results[all_results['유의함'] == False].reset_index(drop=True)

# 결과 출력
display(not_significant_df)

                    변수명   p-value    유의함
0        최종유효년월_신용_이용가능  0.077465  False
1          최종유효년월_신용_이용  0.128899  False
2                카드신청건수  0.349883  False
3              최종카드발급일자  0.369289  False
4            _2순위카드이용건수  0.479684  False
5           이용금액_R3M_신용  0.587969  False
6              유효카드수_체크  0.635999  False
7            이용가능카드수_체크  0.699449  False
8         이용금액_R3M_신용체크  0.715127  False
9            _2순위카드이용금액  0.899265  False
10           _1순위카드이용금액  0.987334  False
11                 기준년월       NaN  False
12               남녀구분코드       NaN  False
13              입회일자_신용       NaN  False
14               RV신청일자  0.066531  False
15           한도심사요청후경과월  0.072474  False
16         RV일시불이자율_할인전  0.088296  False
17           자발한도감액후경과월  0.124737  False
18                 기준년월       NaN  False
19               최초한도금액       NaN  False
20       최대이용금액_할부_R12M  0.180730  False
21        이용개월수_할부_R12M  0.303572  False
22         이용건수_할부_R12M  0.311667  False
23        이용건수_카드론_R12M  0.360673  False
24     이용건수_할부_유이자_R12M  0.371815  False
25      최대이용금액_카드론_R12M  0.457871  False
26   최대이용금액_할부_유이자_R12M  0.480239  False
27    이용개월수_할부_무이자_R12M  0.585364  False
28          이용금액_체크_B0M  0.701590  False
29            최종이용일자_체크  0.856882  False
30         이용금액_일시불_B0M  0.927913  False
31    이용개월수_할부_유이자_R12M  0.949231  False
32           최종이용일자_카드론  0.973760  False
33            최종이용일자_CA  0.973773  False
34         이용금액_체크_R12M  0.994097  False
35        이용금액_일시불_R12M  0.997556  False
36                 기준년월       NaN  False
37         이용개월수_CA_R6M  0.222175  False
38          이용금액_CA_R3M  0.225450  False
39          이용금액_체크_R3M  0.291915  False
40         이용개월수_체크_R6M  0.294839  False
41      이용금액_할부_무이자_R3M  0.340227  False
42          이용금액_할부_R3M  0.745114  False
43         이용금액_일시불_R3M  0.841268  False
44      이용금액_할부_무이자_R6M  0.875684  False
45          이용금액_할부_R6M  0.991446  False
46         이용금액_일시불_R6M  0.993671  False
47          이용금액_체크_R6M  0.994121  False
48        _1순위납부업종_이용금액  0.051439  False
49           납부_보험료이용금액  0.053316  False
50         교통_버스지하철이용금액  0.054094  False
51        _3순위교통업종_이용금액  0.066831  False
52         할부건수_3M_R12M  0.088796  False
53     할부건수_유이자_3M_R12M  0.105498  False
54          _3순위업종_이용금액  0.106231  False
55           납부_통신비이용금액  0.154098  False
56        _2순위납부업종_이용금액  0.255473  False
57          _1순위업종_이용금액  0.430898  False
58        _3순위납부업종_이용금액  0.436791  False
59          _2순위업종_이용금액  0.510142  False
60        할부금액_12M_R12M  0.557046  False
61     할부건수_유이자_6M_R12M  0.601474  False
62           증감_RP건수_전월  0.069872  False
63           RP후경과월_학습비  0.070063  False
64            RP후경과월_렌탈  0.078673  False
65          RP건수_보험_B0M  0.103580  False
66           최종카드론_대출월수  0.281947  False
67           최종카드론_대출이율  0.312425  False
68            RP후경과월_가스  0.324546  False
69       최종카드론_금융상환방식코드  0.591685  False
70           최종카드론_대출금액  0.655927  False
71    할부금액_무이자_12M_R12M  0.895708  False
72            RP후경과월_전기  0.898306  False
73          RP건수_통신_B0M  0.918964  False
74           카드론이용건수_누적  0.976835  False
75           카드론이용월수_누적  0.976945  False
76          최종카드론_거치개월수  0.977701  False
77           카드론이용금액_누적  0.978401  False
78           최종카드론_대출일자  0.978642  False
79           최초카드론이용경과월  0.991873  False
80            RP후경과월_건강       NaN  False
81          RP후경과월_유선방송       NaN  False
82        이용개월수_A페이_R6M  0.069502  False
83         이용건수_A페이_R6M  0.079419  False
84         이용건수_A페이_R3M  0.109781  False
85         이용금액_D페이_R6M  0.399936  False
86        이용금액_오프라인_B0M  0.900059  False
87         이용횟수_선결제_R3M  0.060009  False
88           연체입금원금_B0M  0.125439  False
89         이용횟수_선결제_B0M  0.154424  False
90         이용횟수_선결제_R6M  0.309337  False
91          건수_할부전환_R6M  0.701321  False
92      신청건수_ATM_CA_R6M  0.777439  False
93         이용건수_선결제_R6M  0.861802  False
94          금액_할부전환_R6M  0.911786  False
95           연체입금원금_B5M  0.912587  False
96                대표결제일  0.051830  False
97     포인트_마일리지_월적립_R3M  0.273445  False
98             연체건수_R6M  0.305997  False
99        상환개월수_결제일_R3M  0.521848  False
100           선결제건수_R6M  0.579262  False
101       포인트_적립포인트_R3M  0.739798  False
102            연체건수_R3M  0.838709  False
103              혜택수혜금액  0.898397  False
104      포인트_포인트_건별_R3M  0.967406  False
105        마일_잔여포인트_B0M  0.971726  False
106                기준년월       NaN  False
107          잔액_카드론_B0M  0.079617  False
108                월중평잔  0.095140  False
109            월중평잔_일시불  0.097683  False
110            평잔_CA_3M  0.295176  False
111            연체일수_B2M  0.328658  False
112          잔액_카드론_B1M  0.490235  False
113             연체일수_최근  0.606195  False
114            월중평잔_카드론  0.607814  False
115                기준년월       NaN  False
116   IB문의건수_사용승인내역_R6M  0.053017  False
117         인입일수_IB_R6M  0.115259  False
118       홈페이지_금융건수_R6M  0.248027  False
119     IB문의건수_정보변경_R6M  0.309753  False
120     IB문의건수_카드발급_R6M  0.481360  False
121          인입후경과월_ARS  0.634667  False
122      당사멤버쉽_방문횟수_R6M  0.672804  False
123      당사멤버쉽_방문횟수_B0M  0.975837  False
124                기준년월       NaN  False
125       불만제기후경과월_R12M       NaN  False
126     인입불만후경과월_IB_R6M       NaN  False
127     컨택건수_CA_청구서_R6M  0.395515  False
128         컨택건수_채권_R6M  0.436598  False
129      컨택건수_보험_TM_R6M  0.979077  False
130                기준년월       NaN  False
131      증감율_이용건수_체크_전월  0.087338  False
132       변동률_잔액_CA_B1M  0.380166  False
133    잔액_신판최대한도소진율_r6m  0.520052  False
134      증감율_이용금액_CA_전월  0.546766  False
135      증감율_이용건수_신용_전월  0.550113  False
136      증감율_이용금액_CA_분기  0.567269  False
137      증감율_이용금액_할부_전월  0.572759  False
138      변동률_잔액_일시불_B1M  0.605691  False
139      증감율_이용건수_신판_전월  0.611163  False
140           혜택수혜율_B0M  0.649088  False
141    잔액_신판평균한도소진율_r6m  0.784409  False
142    잔액_신판평균한도소진율_r3m  0.814298  False
143      증감율_이용금액_할부_분기  0.860823  False
144     증감율_이용건수_일시불_전월  0.927474  False
145  잔액_신판ca평균한도소진율_r6m  0.935002  False
146      증감율_이용금액_신용_분기  0.937399  False
147      증감율_이용금액_체크_전월  0.939554  False
148  잔액_신판ca최대한도소진율_r6m  0.942078  False
149      증감율_이용금액_신판_분기  0.965566  False
150          변동률_잔액_B1M  0.971095  False
151           혜택수혜율_R3M  0.973069  False
152      증감율_이용금액_체크_분기  0.974732  False
153     증감율_이용금액_일시불_전월  0.981759  False
154      증감율_이용건수_신용_분기  0.981844  False
155      증감율_이용금액_신판_전월  0.988425  False
156      증감율_이용건수_체크_분기  0.990755  False
157      증감율_이용건수_신판_분기  0.992301  False
158      증감율_이용금액_신용_전월  0.994936  False
159     증감율_이용건수_일시불_분기  0.999955  False
160     증감율_이용금액_일시불_분기  0.999965  False
161                기준년월       NaN  False

In [125]:
not_significant_df.to_excel("데이터 변화율 종합.xlsx", index=False)
print('저장 완료')

저장 완료