In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_15_16.dat'

In [3]:
with open(best_model_path, 'rb') as fp :
    best_model = pickle.load(fp)
    scalerX = pickle.load(fp)
    scaler_columns = pickle.load(fp)
    Encoder1 = pickle.load(fp)
    Encoder2 = pickle.load(fp)
    Encoder3 = pickle.load(fp)
    Encoder4 = pickle.load(fp)
    Encoder5 = pickle.load(fp)
    Encoder6 = pickle.load(fp)
    Encoder7 = pickle.load(fp)
    Encoder8 = pickle.load(fp)
    le = pickle.load(fp)
    
display(best_model)
display(scalerX)
display(Encoder1)
display(Encoder2)
display(Encoder3)
display(Encoder4)
display(Encoder5)
display(Encoder6)
display(Encoder7)
display(le)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

StandardScaler()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

LabelEncoder()

### Target

In [4]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [5]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df

        Segment
0             D
1             E
2             C
3             D
4             E
...         ...
2399995       E
2399996       D
2399997       C
2399998       E
2399999       E

[2400000 rows x 1 columns]

In [6]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_csv('C,D(16).csv')
df1

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자
0,201807,TEST_00000,21458,13852,21458,2,자녀성장(1),10,10,10,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,51,51,12
1,201807,TEST_00001,18681,11065,10759,2,자녀독립기,9,9,9,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,30,40,0
2,201807,TEST_00002,40758,27071,40758,2,자녀성장(1),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,5,154,3
3,201807,TEST_00003,5255,4827,5255,1,자녀성장(1),9,9,9,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,73,105,2
4,201807,TEST_00004,16148,8011,14290,3,자녀성장(1),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,176,52,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,노년생활,0,0,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,69,-2,12
599996,201812,TEST_99996,3110,1231,3110,1,자녀출산기,10,9,9,...,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,14,4,12
599997,201812,TEST_99997,0,0,0,0,자녀성장(1),0,0,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,6,6,12
599998,201812,TEST_99998,173263,63592,113786,6,가족구축기,12,12,12,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,82,185,2
599999,201812,TEST_99999,3016,-574,3016,2,자녀출산기,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,40,0,12

In [7]:
notE = pd.read_csv('model3_notE(2).csv')
notE

               ID Segment
0      TEST_00010   Not_E
1      TEST_00016   Not_E
2      TEST_00032   Not_E
3      TEST_00034   Not_E
4      TEST_00037   Not_E
...           ...     ...
16698  TEST_99947   Not_E
16699  TEST_99957   Not_E
16700  TEST_99961   Not_E
16701  TEST_99982   Not_E
16702  TEST_99998   Not_E

[16703 rows x 2 columns]

In [8]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids1 = notE[notE['Segment'] == 'Not_E']['ID']

# 2. df2에서 해당 ID만 골라오기
df2 = df1[df1['ID'].isin(filtered_ids1)]

In [9]:
df2

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자
10,201807,TEST_00010,45764,7544,7024,2,자녀성장(1),11,11,11,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,54,9,12
16,201807,TEST_00016,51440,42636,51440,2,자녀출산기,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,58,120,8
32,201807,TEST_00032,54632,3885,4259,2,자녀출산기,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,119,11,12
34,201807,TEST_00034,27781,28028,27781,1,자녀성장(2),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,275,110,8
37,201807,TEST_00037,80998,49528,80998,3,노년생활,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,170,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,201812,TEST_99947,87532,41465,87532,3,자녀성장(1),12,12,12,...,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상,93,122,6
599957,201812,TEST_99957,61148,38644,59950,4,자녀성장(1),12,12,12,...,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상,17,115,4
599961,201812,TEST_99961,30318,25961,30318,1,자녀성장(2),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,120,57,12
599982,201812,TEST_99982,94440,70955,94440,1,노년생활,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,92,101,12
599998,201812,TEST_99998,173263,63592,113786,6,가족구축기,12,12,12,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,82,185,2

In [10]:
notAB = pd.read_csv('data/model3_notAB(2).csv')
notAB

               ID Segment
0      TEST_00010   notAB
1      TEST_00016   notAB
2      TEST_00032   notAB
3      TEST_00034   notAB
4      TEST_00037   notAB
...           ...     ...
16683  TEST_99947   notAB
16684  TEST_99957   notAB
16685  TEST_99961   notAB
16686  TEST_99982   notAB
16687  TEST_99998   notAB

[16688 rows x 2 columns]

In [11]:
# 1. 'Not_E'인 ID만 필터링
filtered_ids2 = notAB[notAB['Segment'] == 'notAB']['ID']

# 2. df2에서 해당 ID만 골라오기
Xtest_df = df2[df2['ID'].isin(filtered_ids2)]

In [12]:
Xtest_df

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자
10,201807,TEST_00010,45764,7544,7024,2,자녀성장(1),11,11,11,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,54,9,12
16,201807,TEST_00016,51440,42636,51440,2,자녀출산기,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,58,120,8
32,201807,TEST_00032,54632,3885,4259,2,자녀출산기,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,119,11,12
34,201807,TEST_00034,27781,28028,27781,1,자녀성장(2),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,275,110,8
37,201807,TEST_00037,80998,49528,80998,3,노년생활,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,170,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,201812,TEST_99947,87532,41465,87532,3,자녀성장(1),12,12,12,...,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상,93,122,6
599957,201812,TEST_99957,61148,38644,59950,4,자녀성장(1),12,12,12,...,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상,17,115,4
599961,201812,TEST_99961,30318,25961,30318,1,자녀성장(2),12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,120,57,12
599982,201812,TEST_99982,94440,70955,94440,1,노년생활,12,12,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,92,101,12
599998,201812,TEST_99998,173263,63592,113786,6,가족구축기,12,12,12,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,82,185,2

In [13]:
X_test = Xtest_df.drop(columns=['기준년월','ID'])
X_test = X_test[scaler_columns]

In [14]:
X_test

,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,이용금액_일시불_R6M,이용금액_일시불_B0M,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자
10,45764,7544,7024,2,자녀성장(1),11,11,11,19540,3862,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,54,9,12
16,51440,42636,51440,2,자녀출산기,12,12,12,98761,17139,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,58,120,8
32,54632,3885,4259,2,자녀출산기,12,12,12,12229,1172,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,119,11,12
34,27781,28028,27781,1,자녀성장(2),12,12,12,64893,9917,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,275,110,8
37,80998,49528,80998,3,노년생활,12,12,12,92897,15061,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,170,85,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599947,87532,41465,87532,3,자녀성장(1),12,12,12,94378,17203,...,30회 이상,10회 이상,60회 이상,1회 이상,1회 이상,1회 이상,1회 이상,93,122,6
599957,61148,38644,59950,4,자녀성장(1),12,12,12,74022,12865,...,1회 이상,1회 이상,40회 이상,40회 이상,30회 이상,1회 이상,1회 이상,17,115,4
599961,30318,25961,30318,1,자녀성장(2),12,12,12,67949,8266,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,120,57,12
599982,94440,70955,94440,1,노년생활,12,12,12,129251,21254,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,92,101,12
599998,173263,63592,113786,6,가족구축기,12,12,12,133431,22617,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,82,185,2

In [15]:
X_test['할인건수_R3M'] = Encoder1.transform(X_test['할인건수_R3M'])
X_test['할인건수_B0M'] = Encoder2.transform(X_test['할인건수_B0M'])
X_test['방문횟수_앱_R6M'] = Encoder3.transform(X_test['방문횟수_앱_R6M'])
X_test['방문횟수_PC_R6M'] = Encoder4.transform(X_test['방문횟수_PC_R6M'])
X_test['인입횟수_ARS_R6M'] = Encoder5.transform(X_test['인입횟수_ARS_R6M'])
X_test['Life_Stage'] = Encoder6.transform(X_test['Life_Stage'])
X_test['이용메뉴건수_ARS_R6M'] = Encoder7.transform(X_test['이용메뉴건수_ARS_R6M'])
X_test['방문일수_PC_R6M'] = Encoder8.transform(X_test['방문일수_PC_R6M'])

In [16]:
# 데이터 표준화
scaled_data = scalerX.transform(X_test)
scaled_data

array([[ 5.43511906e-01, -5.59651224e-01, -6.52028663e-01, ...,
        -4.50819388e-01, -8.00363298e-01,  9.54927444e-01],
       [ 7.28848036e-01,  1.37740165e+00,  8.69997828e-01, ...,
        -3.98375213e-01,  1.05422483e+00,  1.17153740e-01],
       [ 8.33075119e-01, -7.61625362e-01, -7.46778376e-01, ...,
         4.01398456e-01, -7.66947296e-01,  9.54927444e-01],
       ...,
       [ 3.91599230e-02,  4.56953781e-01,  1.46199117e-01, ...,
         4.14509500e-01,  1.62075829e-03,  9.54927444e-01],
       [ 2.13290962e+00,  2.94058985e+00,  2.34350150e+00, ...,
         4.74002745e-02,  7.36772810e-01,  9.54927444e-01],
       [ 4.70668512e+00,  2.53415761e+00,  3.00644108e+00, ...,
        -8.37101630e-02,  2.14024491e+00, -1.13950681e+00]])

In [17]:
# 입력데이터를 test_X 변수에 담아준다.
X_text2 = scaled_data

In [18]:
# 예측한다.
y_pred = best_model.predict(X_text2)
y_pred_labels = le.inverse_transform(y_pred)
y_pred_labels

array(['D', 'D', 'D', ..., 'D', 'C', 'C'], dtype=object)

In [19]:
# 결과를 붙힌다음 저장한다.
# 예측할 데이터를 다시 불러온다.
result_df = Xtest_df
result_df['Segment'] = y_pred_labels

In [20]:
result_df2 = result_df[['ID', 'Segment']]

In [21]:
result_df2['Segment'].value_counts()

Segment
D    73771
C    26357
Name: count, dtype: int64

In [22]:
most_common_by_id = result_df2.groupby('ID')['Segment'] \
    .agg(lambda x: x.mode().iloc[0]) \
    .reset_index()

# 컬럼명 확인
most_common_by_id.columns = ['ID', 'Segment']

In [23]:
most_common_by_id

               ID Segment
0      TEST_00010       D
1      TEST_00016       D
2      TEST_00032       D
3      TEST_00034       D
4      TEST_00037       C
...           ...     ...
16683  TEST_99947       D
16684  TEST_99957       D
16685  TEST_99961       C
16686  TEST_99982       C
16687  TEST_99998       C

[16688 rows x 2 columns]

In [24]:
most_common_by_id['Segment'].value_counts()

Segment
D    12158
C     4530
Name: count, dtype: int64

In [25]:
most_common_by_id.to_csv('data/model3_16_2_C,D.csv', index=False, encoding='utf-8-sig')
print('저장완료')

저장완료