In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor


# 학습 모델 저장을 위한 라이브러리
import pickle

### 프로젝트 셋팅

In [2]:
# 학습이 완료된 모델을 저장할 파일 이름
best_model_path = 'model/best_model_15_6.dat'
# 교차검증 횟수
cv_count = 10
# 교차 검증
kfold = KFold(n_splits=cv_count, shuffle=True, random_state=1)
# 평가 결과를 담을 리스트
# 필요하다면 다른 것도 만들어주세요
f1_score_list = []
# 학습 모델 이름
model_name_list = []

### 변수 추가

In [6]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df12=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df13=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df14=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df15=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df16=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])

In [7]:
df_test11=pd.read_parquet(r'data/test/1.회원정보/201807_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df_test12=pd.read_parquet(r'data/test/1.회원정보/201808_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df_test13=pd.read_parquet(r'data/test/1.회원정보/201809_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df_test14=pd.read_parquet(r'data/test/1.회원정보/201810_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df_test15=pd.read_parquet(r'data/test/1.회원정보/201811_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])
df_test16=pd.read_parquet(r'data/test/1.회원정보/201812_test_.parquet',columns=['ID','기준년월','입회경과개월수_신용','_1순위카드이용건수'])

In [8]:
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df32=pd.read_parquet(r'data/train/3.승인매출정보/201808_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df33=pd.read_parquet(r'data/train/3.승인매출정보/201809_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df34=pd.read_parquet(r'data/train/3.승인매출정보/201810_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df35=pd.read_parquet(r'data/train/3.승인매출정보/201811_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df36=pd.read_parquet(r'data/train/3.승인매출정보/201812_train_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])

In [9]:
df_test31=pd.read_parquet(r'data/test/3.승인매출정보/201807_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df_test32=pd.read_parquet(r'data/test/3.승인매출정보/201808_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df_test33=pd.read_parquet(r'data/test/3.승인매출정보/201809_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df_test34=pd.read_parquet(r'data/test/3.승인매출정보/201810_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df_test35=pd.read_parquet(r'data/test/3.승인매출정보/201811_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])
df_test36=pd.read_parquet(r'data/test/3.승인매출정보/201812_test_.parquet',columns=['ID','기준년월','이용후경과월_할부_무이자'])

In [3]:
df81=pd.read_parquet(r'data/train/8.성과정보/201807_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df82=pd.read_parquet(r'data/train/8.성과정보/201808_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df83=pd.read_parquet(r'data/train/8.성과정보/201809_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df84=pd.read_parquet(r'data/train/8.성과정보/201810_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df85=pd.read_parquet(r'data/train/8.성과정보/201811_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df86=pd.read_parquet(r'data/train/8.성과정보/201812_train_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])

In [4]:
df_test81=pd.read_parquet(r'data/test/8.성과정보/201807_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df_test82=pd.read_parquet(r'data/test/8.성과정보/201808_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df_test83=pd.read_parquet(r'data/test/8.성과정보/201809_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df_test84=pd.read_parquet(r'data/test/8.성과정보/201810_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df_test85=pd.read_parquet(r'data/test/8.성과정보/201811_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])
df_test86=pd.read_parquet(r'data/test/8.성과정보/201812_test_.parquet',columns=['ID','기준년월','변동률_일시불평잔'])

In [10]:
all_df1 = pd.concat([df11, df12, df13, df14, df15, df16])
all_df1.reset_index(inplace=True, drop=True)
all_df1

                   ID    기준년월  입회경과개월수_신용  _1순위카드이용건수
0        TRAIN_000000  201807          67          26
1        TRAIN_000001  201807          12          46
2        TRAIN_000002  201807         124          28
3        TRAIN_000003  201807          27           1
4        TRAIN_000004  201807           2          -2
...               ...     ...         ...         ...
2399995  TRAIN_399995  201812         209           3
2399996  TRAIN_399996  201812          17          38
2399997  TRAIN_399997  201812         115          33
2399998  TRAIN_399998  201812          71          -2
2399999  TRAIN_399999  201812           7          -2

[2400000 rows x 4 columns]

In [11]:
all_df3 = pd.concat([df31, df32, df33, df34, df35, df36])
all_df3.reset_index(inplace=True, drop=True)
all_df3

                   ID    기준년월  이용후경과월_할부_무이자
0        TRAIN_000000  201807              2
1        TRAIN_000001  201807              9
2        TRAIN_000002  201807              0
3        TRAIN_000003  201807              1
4        TRAIN_000004  201807             12
...               ...     ...            ...
2399995  TRAIN_399995  201812             12
2399996  TRAIN_399996  201812              9
2399997  TRAIN_399997  201812              1
2399998  TRAIN_399998  201812             12
2399999  TRAIN_399999  201812              2

[2400000 rows x 3 columns]

In [12]:
all_df8 = pd.concat([df81, df82, df83, df84, df85, df86])
all_df8.reset_index(inplace=True, drop=True)
all_df8

                   ID    기준년월  변동률_일시불평잔
0        TRAIN_000000  201807   0.951930
1        TRAIN_000001  201807   1.290439
2        TRAIN_000002  201807   0.929196
3        TRAIN_000003  201807   1.020964
4        TRAIN_000004  201807   0.000000
...               ...     ...        ...
2399995  TRAIN_399995  201812   0.999998
2399996  TRAIN_399996  201812   0.615087
2399997  TRAIN_399997  201812   1.036370
2399998  TRAIN_399998  201812   0.999998
2399999  TRAIN_399999  201812   1.080614

[2400000 rows x 3 columns]

In [13]:
all_testdf1 = pd.concat([df_test11, df_test12, df_test13, df_test14, df_test15, df_test16])
all_testdf1.reset_index(inplace=True, drop=True)
all_testdf1

                ID    기준년월  입회경과개월수_신용  _1순위카드이용건수
0       TEST_00000  201807          51          51
1       TEST_00001  201807          30          40
2       TEST_00002  201807           5         154
3       TEST_00003  201807          73         105
4       TEST_00004  201807         176          52
...            ...     ...         ...         ...
599995  TEST_99995  201812          69          -2
599996  TEST_99996  201812          14           4
599997  TEST_99997  201812           6           6
599998  TEST_99998  201812          82         185
599999  TEST_99999  201812          40           0

[600000 rows x 4 columns]

In [14]:
all_testdf3 = pd.concat([df_test31, df_test32, df_test33, df_test34, df_test35, df_test36])
all_testdf3.reset_index(inplace=True, drop=True)
all_testdf3

                ID    기준년월  이용후경과월_할부_무이자
0       TEST_00000  201807             12
1       TEST_00001  201807              0
2       TEST_00002  201807              3
3       TEST_00003  201807              2
4       TEST_00004  201807              0
...            ...     ...            ...
599995  TEST_99995  201812             12
599996  TEST_99996  201812             12
599997  TEST_99997  201812             12
599998  TEST_99998  201812              2
599999  TEST_99999  201812             12

[600000 rows x 3 columns]

In [15]:
all_testdf8 = pd.concat([df_test81, df_test82, df_test83, df_test84, df_test85, df_test86])
all_testdf8.reset_index(inplace=True, drop=True)
all_testdf8

                ID    기준년월  변동률_일시불평잔
0       TEST_00000  201807   1.463214
1       TEST_00001  201807   1.315412
2       TEST_00002  201807   1.055927
3       TEST_00003  201807   1.488069
4       TEST_00004  201807   1.208739
...            ...     ...        ...
599995  TEST_99995  201812   0.999998
599996  TEST_99996  201812   0.894539
599997  TEST_99997  201812   0.000000
599998  TEST_99998  201812   0.809328
599999  TEST_99999  201812   0.949586

[600000 rows x 3 columns]

### 데이터 준비
- 데이터를 읽어오고 필요한 전처리까지 다 한다음 입력데이터는 train_X, 결과데이터는 train_y라는 변수에 담아서 준비해주세요

In [20]:
# 데이터를 읽어온다.
train_df = pd.read_csv('(C_D)_VIF_train(2).csv')
test_df = pd.read_csv('(C_D)_VIF_test(2).csv')

display(train_df)
display(test_df)

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,D,196,3681,1,자녀성장(2),12,8380,0,...,16125,6,88693,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,201807,TRAIN_000002,C,23988,24493,1,자녀출산기,9,35136,0,...,14448,5,165221,1,1회 이상,1회 이상,30회 이상,10회 이상,1회 이상,1회 이상
2,201807,TRAIN_000003,D,3904,5933,1,자녀성장(2),12,-7031,0,...,13043,6,127371,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
3,201807,TRAIN_000008,C,124967,68078,5,자녀출산기,12,131028,0,...,11685,6,94241,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TRAIN_000010,D,21001,18796,1,자녀성장(1),12,19802,0,...,0,6,35723,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476827,201812,TRAIN_399979,D,31187,27337,2,자녀성장(2),12,42049,0,...,13157,6,74153,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476828,201812,TRAIN_399987,C,42492,35751,1,자녀성장(2),12,53815,0,...,17814,6,132623,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,30회 이상
476829,201812,TRAIN_399993,C,72348,27792,4,자녀성장(1),12,94922,0,...,11092,6,72474,1,20회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
476830,201812,TRAIN_399996,D,27636,26357,1,자녀성장(2),12,58916,0,...,10764,6,99849,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476831,201812,TRAIN_399997,C,23187,17171,1,자녀출산기,12,26974,1,...,6106,6,41073,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,이용건수_신용_R12M,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,21458,13852,2,자녀성장(1),10,26595,0,150,...,1172,5,22151,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,18681,11065,2,자녀독립기,9,-7578,0,28,...,4509,6,32878,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,40758,27071,2,자녀성장(1),12,48483,1,650,...,11366,6,71867,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,5255,4827,1,자녀성장(1),9,403,0,361,...,875,4,4986,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,16148,8011,3,자녀성장(1),12,1238,0,227,...,1618,6,10758,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,노년생활,0,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,3110,1231,1,자녀출산기,10,3,0,7,...,252,6,2237,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상
599997,201812,TEST_99997,0,0,0,자녀성장(1),0,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,173263,63592,6,가족구축기,12,133431,0,933,...,2751,6,108420,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상
599999,201812,TEST_99999,3016,-574,2,자녀출산기,12,-4731,2,40,...,18,6,105,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [21]:
# ID와 기준년월 기준으로 join (왼쪽 기준으로 추가)
train_df = train_df.merge(all_df1, on=['ID', '기준년월'], how='left')
train_df = train_df.merge(all_df3, on=['ID', '기준년월'], how='left')
train_df = train_df.merge(all_df8, on=['ID', '기준년월'], how='left')

In [22]:
train_df

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자,변동률_일시불평잔
0,201807,TRAIN_000000,D,196,3681,1,자녀성장(2),12,8380,0,...,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,67,26,2,0.951930
1,201807,TRAIN_000002,C,23988,24493,1,자녀출산기,9,35136,0,...,1회 이상,1회 이상,30회 이상,10회 이상,1회 이상,1회 이상,124,28,0,0.929196
2,201807,TRAIN_000003,D,3904,5933,1,자녀성장(2),12,-7031,0,...,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,27,1,1,1.020964
3,201807,TRAIN_000008,C,124967,68078,5,자녀출산기,12,131028,0,...,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,137,176,5,1.198806
4,201807,TRAIN_000010,D,21001,18796,1,자녀성장(1),12,19802,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,70,-2,1,1.132491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476827,201812,TRAIN_399979,D,31187,27337,2,자녀성장(2),12,42049,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,248,52,1,0.743218
476828,201812,TRAIN_399987,C,42492,35751,1,자녀성장(2),12,53815,0,...,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,30회 이상,113,49,1,0.723456
476829,201812,TRAIN_399993,C,72348,27792,4,자녀성장(1),12,94922,0,...,20회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,127,177,12,0.967489
476830,201812,TRAIN_399996,D,27636,26357,1,자녀성장(2),12,58916,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,17,38,9,0.615087
476831,201812,TRAIN_399997,C,23187,17171,1,자녀출산기,12,26974,1,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,115,33,1,1.036370

In [23]:
# ID와 기준년월 기준으로 join (왼쪽 기준으로 추가)
test_df = test_df.merge(all_testdf1, on=['ID', '기준년월'], how='left')
test_df = test_df.merge(all_testdf3, on=['ID', '기준년월'], how='left')
test_df = test_df.merge(all_testdf8, on=['ID', '기준년월'], how='left')

In [24]:
test_df

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,이용건수_신용_R12M,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자,변동률_일시불평잔
0,201807,TEST_00000,21458,13852,2,자녀성장(1),10,26595,0,150,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,51,51,12,1.463214
1,201807,TEST_00001,18681,11065,2,자녀독립기,9,-7578,0,28,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,30,40,0,1.315412
2,201807,TEST_00002,40758,27071,2,자녀성장(1),12,48483,1,650,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,5,154,3,1.055927
3,201807,TEST_00003,5255,4827,1,자녀성장(1),9,403,0,361,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,73,105,2,1.488069
4,201807,TEST_00004,16148,8011,3,자녀성장(1),12,1238,0,227,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,176,52,0,1.208739
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,노년생활,0,0,12,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,69,-2,12,0.999998
599996,201812,TEST_99996,3110,1231,1,자녀출산기,10,3,0,7,...,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,14,4,12,0.894539
599997,201812,TEST_99997,0,0,0,자녀성장(1),0,0,12,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,6,6,12,0.000000
599998,201812,TEST_99998,173263,63592,6,가족구축기,12,133431,0,933,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,82,185,2,0.809328
599999,201812,TEST_99999,3016,-574,2,자녀출산기,12,-4731,2,40,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,40,0,12,0.949586

In [25]:
test_df.to_csv('C,D(6).csv', index=False, encoding='utf-8-sig')

In [26]:
# 데이터 프레임을 합친다.
all_df = pd.concat([train_df, test_df])
all_df.reset_index(inplace=True, drop=True)
all_df

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,...,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,입회경과개월수_신용,_1순위카드이용건수,이용후경과월_할부_무이자,변동률_일시불평잔
0,201807,TRAIN_000000,D,196,3681,1,자녀성장(2),12,8380,0,...,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,67,26,2,0.951930
1,201807,TRAIN_000002,C,23988,24493,1,자녀출산기,9,35136,0,...,1회 이상,1회 이상,30회 이상,10회 이상,1회 이상,1회 이상,124,28,0,0.929196
2,201807,TRAIN_000003,D,3904,5933,1,자녀성장(2),12,-7031,0,...,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상,27,1,1,1.020964
3,201807,TRAIN_000008,C,124967,68078,5,자녀출산기,12,131028,0,...,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,137,176,5,1.198806
4,201807,TRAIN_000010,D,21001,18796,1,자녀성장(1),12,19802,0,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,70,-2,1,1.132491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1076827,201812,TEST_99995,NaN,0,0,0,노년생활,0,0,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,69,-2,12,0.999998
1076828,201812,TEST_99996,NaN,3110,1231,1,자녀출산기,10,3,0,...,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,14,4,12,0.894539
1076829,201812,TEST_99997,NaN,0,0,0,자녀성장(1),0,0,12,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,6,6,12,0.000000
1076830,201812,TEST_99998,NaN,173263,63592,6,가족구축기,12,133431,0,...,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,82,185,2,0.809328
1076831,201812,TEST_99999,NaN,3016,-574,2,자녀출산기,12,-4731,2,...,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,40,0,12,0.949586

In [27]:
all_df.drop(columns=['Segment','ID','기준년월'], inplace=True)

In [28]:
all_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1076832 entries, 0 to 1076831
Data columns (total 35 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   이용금액_R3M_신용체크       1076832 non-null  int64
 1   _1순위카드이용금액          1076832 non-null  int64
 2   이용카드수_신용체크          1076832 non-null  int64
 3   Life_Stage          1076832 non-null  object
 4   이용개월수_신용_R12M       1076832 non-null  int64
 5   이용금액_일시불_R6M        1076832 non-null  int64
 6   이용후경과월_신판           1076832 non-null  int64
 7   이용건수_신용_R12M        1076832 non-null  int64
 8   이용후경과월_신용           1076832 non-null  int64
 9   이용금액_오프라인_B0M       1076832 non-null  int64
 10  이용금액_오프라인_R3M       1076832 non-null  int64
 11  _3순위업종_이용금액         1076832 non-null  int64
 12  _3순위쇼핑업종_이용금액       1076832 non-null  int64
 13  _2순위업종_이용금액         1076832 non-null  int64
 14  이용개월수_오프라인_R6M      1076832 non-null  int64
 15  이용금액_오프라인_R6M       1076832 non-null  int64
 16  _2순위쇼핑업종_이용금액       1076832 non-null  int64
 17  정상청구원금_B5M          1076832 non-null  int64
 18  연속유실적개월수_기본_24M_카드  1076832 non-null  int64
 19  정상입금원금_B0M          1076832 non-null  int64
 20  정상입금원금_B5M          1076832 non-null  int64
 21  정상입금원금_B2M          1076832 non-null  int64
 22  이용개월수_전체_R6M        1076832 non-null  int64
 23  청구금액_R6M            1076832 non-null  int64
 24  청구서발송여부_B0          1076832 non-null  int64
 25  할인건수_R3M            1076832 non-null  object
 26  할인건수_B0M            1076832 non-null  object
 27  방문횟수_앱_R6M          1076832 non-null  object
 28  방문횟수_PC_R6M         1076832 non-null  object
 29  인입횟수_ARS_R6M        1076832 non-null  object
 30  이용메뉴건수_ARS_R6M      1076832 non-null  object
 31  입회경과개월수_신용          1076832 non-null  int64
 32  _1순위카드이용건수          1076832 non-null  int64
 33  이용후경과월_할부_무이자       1076832 non-null  int64
 34  변동률_일시불평잔           1076832 non-null  float64
dtypes: float64(1), int64(27), object(7)
memory usage: 287.5+ MB

In [29]:
# LabelEncoder 학습
Encoder1 = LabelEncoder()
Encoder2 = LabelEncoder()
Encoder3 = LabelEncoder()
Encoder4 = LabelEncoder()
Encoder5 = LabelEncoder()
Encoder6 = LabelEncoder()
Encoder7 = LabelEncoder()

Encoder1.fit(all_df['할인건수_R3M'])
Encoder2.fit(all_df['할인건수_B0M'])
Encoder3.fit(all_df['방문횟수_앱_R6M'])
Encoder4.fit(all_df['방문횟수_PC_R6M'])
Encoder5.fit(all_df['인입횟수_ARS_R6M'])
Encoder6.fit(all_df['Life_Stage'])
Encoder7.fit(all_df['이용메뉴건수_ARS_R6M'])

LabelEncoder()

In [30]:
all_df['할인건수_R3M'] = Encoder1.transform(all_df['할인건수_R3M'])
all_df['할인건수_B0M'] = Encoder2.transform(all_df['할인건수_B0M'])
all_df['방문횟수_앱_R6M'] = Encoder3.transform(all_df['방문횟수_앱_R6M'])
all_df['방문횟수_PC_R6M'] = Encoder4.transform(all_df['방문횟수_PC_R6M'])
all_df['인입횟수_ARS_R6M'] = Encoder5.transform(all_df['인입횟수_ARS_R6M'])
all_df['Life_Stage'] = Encoder6.transform(all_df['Life_Stage'])
all_df['이용메뉴건수_ARS_R6M'] = Encoder7.transform(all_df['이용메뉴건수_ARS_R6M'])

In [31]:
# Scaler 학습
scalerX = StandardScaler()
scalerX.fit(all_df)

StandardScaler()

In [32]:
train_df['할인건수_R3M'] = Encoder1.transform(train_df['할인건수_R3M'])
train_df['할인건수_B0M'] = Encoder2.transform(train_df['할인건수_B0M'])
train_df['방문횟수_앱_R6M'] = Encoder3.transform(train_df['방문횟수_앱_R6M'])
train_df['방문횟수_PC_R6M'] = Encoder4.transform(train_df['방문횟수_PC_R6M'])
train_df['인입횟수_ARS_R6M'] = Encoder5.transform(train_df['인입횟수_ARS_R6M'])
train_df['Life_Stage'] = Encoder6.transform(train_df['Life_Stage'])
train_df['이용메뉴건수_ARS_R6M'] = Encoder7.transform(train_df['이용메뉴건수_ARS_R6M'])

In [33]:
target1=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet')
target2=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet')
target3=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet')
target4=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet')
target5=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet')
target6=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet')

In [34]:
tg_df = pd.concat([
    target1['Segment'],
    target2['Segment'],
    target3['Segment'],
    target4['Segment'],
    target5['Segment'],
    target6['Segment']
])

tg_df = tg_df.reset_index(drop=True).to_frame(name='Segment')
tg_df = tg_df[tg_df['Segment'].isin(['C', 'D'])].reset_index(drop=True)
tg_df

       Segment
0            D
1            C
2            D
3            C
4            D
...        ...
476827       D
476828       C
476829       C
476830       D
476831       C

[476832 rows x 1 columns]

In [35]:
# 라벨 인코더 생성
le = LabelEncoder()

# 문자열 y를 숫자로 변환
tg_df['Segment'] = le.fit_transform(tg_df['Segment'])

In [36]:
# 입력과 결과로 나눈다.
X = train_df.drop(columns=['Segment','ID','기준년월'])
y = tg_df

In [37]:
# 표준화
X2 = scalerX.transform(X)
X2

array([[-0.94440155, -0.77288601, -0.60574601, ..., -0.51632728,
        -1.13950681,  0.1143232 ],
       [-0.167531  ,  0.37592125, -0.60574601, ..., -0.48291128,
        -1.55839367,  0.03991714],
       [-0.82332572, -0.64857725, -0.60574601, ..., -0.93402731,
        -1.34895024,  0.3402664 ],
       ...,
       [ 1.41154849,  0.55802365,  2.03680254, ...,  2.0065809 ,
         0.95492744,  0.1652464 ],
       [-0.04841434,  0.47881269, -0.60574601, ..., -0.31583126,
         0.32659717, -0.9881293 ],
       [-0.19368573, -0.02824783, -0.60574601, ..., -0.39937127,
        -1.34895024,  0.39068875]])

In [38]:
scaler_columns = X.columns.tolist()
scaler_columns

['이용금액_R3M_신용체크',
 '_1순위카드이용금액',
 '이용카드수_신용체크',
 'Life_Stage',
 '이용개월수_신용_R12M',
 '이용금액_일시불_R6M',
 '이용후경과월_신판',
 '이용건수_신용_R12M',
 '이용후경과월_신용',
 '이용금액_오프라인_B0M',
 '이용금액_오프라인_R3M',
 '_3순위업종_이용금액',
 '_3순위쇼핑업종_이용금액',
 '_2순위업종_이용금액',
 '이용개월수_오프라인_R6M',
 '이용금액_오프라인_R6M',
 '_2순위쇼핑업종_이용금액',
 '정상청구원금_B5M',
 '연속유실적개월수_기본_24M_카드',
 '정상입금원금_B0M',
 '정상입금원금_B5M',
 '정상입금원금_B2M',
 '이용개월수_전체_R6M',
 '청구금액_R6M',
 '청구서발송여부_B0',
 '할인건수_R3M',
 '할인건수_B0M',
 '방문횟수_앱_R6M',
 '방문횟수_PC_R6M',
 '인입횟수_ARS_R6M',
 '이용메뉴건수_ARS_R6M',
 '입회경과개월수_신용',
 '_1순위카드이용건수',
 '이용후경과월_할부_무이자',
 '변동률_일시불평잔']

In [39]:
train_X = X2
train_y = y

### 기본 모델 사용하기
- 기본 모델 중에 만족하는 것을 찾았다면 하이퍼 파라미터 튜닝 과정은 생략하세요

In [40]:
# LGBM
lgbm_basic_model = LGBMClassifier(verbose=-1)
# 교차 검증을 수행한다
r1 = cross_val_score(lgbm_basic_model, train_X, train_y, scoring='f1', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("LGBM Basic")

print(f'평균 f1 Score : {r1.mean()}')

평균 f1 Score : 0.8950587948143482

In [41]:
# XGBoost
xgboost_basic_model = XGBClassifier(verbose=-1, silent=True)
# 교차 검증을 수행한다
r1 = cross_val_score(xgboost_basic_model, train_X, train_y, scoring='f1', cv=kfold)
# 평가 결과를 담아준다.
f1_score_list.append(r1.mean())
# 학습 모델 이름을 담아준다.
model_name_list.append("XGBoost Basic")

print(f'평균 f1 Score : {r1.mean()}')

평균 f1 Score : 0.9006698414767584

In [42]:
d1 = {
    'f1 score' : f1_score_list
}
result_df = pd.DataFrame(d1, index=model_name_list)
result_df.sort_values(by='f1 score', ascending=False, inplace=True)
result_df

               f1 score
XGBoost Basic  0.900670
LGBM Basic     0.895059

---

In [43]:
best_model=xgboost_basic_model.fit(train_X, train_y)

In [44]:
with open(best_model_path, 'wb') as fp:
    pickle.dump(best_model, fp)
    pickle.dump(scalerX, fp)
    pickle.dump(scaler_columns, fp)
    pickle.dump(Encoder1, fp)
    pickle.dump(Encoder2, fp)
    pickle.dump(Encoder3, fp)
    pickle.dump(Encoder4, fp)
    pickle.dump(Encoder5, fp)
    pickle.dump(Encoder6, fp)
    pickle.dump(Encoder7, fp)
    pickle.dump(le, fp)

print('저장완료')

저장완료

---
### 혼동행렬