In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False
import gc

# 인코더 추가
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

#VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
#상수항추가
from statsmodels.tools.tools import add_constant
# 카이제곱, ANOVA
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
#Turkeyhsd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 데이터 불러오기

In [3]:
# parquet 파일 데이터를 읽어온다.
# x 값으로 쓸 데이터
df1_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201807_train_성과정보.parquet')
df2_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201808_train_성과정보.parquet')
df3_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201809_train_성과정보.parquet')
df4_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201810_train_성과정보.parquet')
df5_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201811_train_성과정보.parquet')
df6_train = pd.read_parquet('/content/drive/MyDrive/8.성과정보/201812_train_성과정보.parquet')

combined_df = pd.concat([df1_train, df2_train, df3_train, df4_train, df5_train, df6_train], axis=0, ignore_index=True)
combined_df

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M
0,201807,TRAIN_000000,0.454548,0.454548,0.364727,1.999996,0.0,0.000000,0.0,0.409766,...,0.999998,1.042805,0.999700,0.999998,0.999998,0.261886,0.270752,0.000000,1.044401,1.280543
1,201807,TRAIN_000001,-0.511808,-0.511808,-0.511808,0.000000,0.0,0.000000,0.0,-1.010817,...,1.092698,0.905663,0.999998,0.999998,0.999998,-0.563388,-0.670348,0.000000,0.000000,0.000000
2,201807,TRAIN_000002,-0.062716,-0.062716,0.067843,-1.999996,0.0,0.000000,0.0,-0.902166,...,1.006124,1.993590,0.852567,0.999998,0.999998,-0.046516,0.058114,-0.014191,0.524159,1.208420
3,201807,TRAIN_000003,0.135707,0.135707,0.153975,-1.999996,0.0,0.000000,0.0,-0.866052,...,0.999998,1.050646,0.999877,0.999998,0.999998,0.023821,0.258943,0.000000,0.880925,1.657124
4,201807,TRAIN_000004,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000028,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.000000,0.000000,0.000000,0.000000,0.0,-0.081943,0.0,0.000027,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399996,201812,TRAIN_399996,0.073804,0.073804,0.073804,0.000000,0.0,0.000000,0.0,0.207099,...,0.999998,0.999998,0.999998,0.999998,0.921733,-0.203251,-0.159143,0.000000,1.377071,2.533815
2399997,201812,TRAIN_399997,-0.040432,-0.040432,-0.040432,0.000000,0.0,0.000000,0.0,0.254495,...,0.999998,0.345027,0.999998,0.999998,0.999998,0.027319,0.126581,0.000000,0.000000,0.000000
2399998,201812,TRAIN_399998,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000034,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399999,201812,TRAIN_399999,0.187598,0.187598,0.187598,0.000000,0.0,0.000000,0.0,0.332268,...,0.999998,0.593160,0.999998,0.999998,0.999998,-0.039845,-0.002659,0.000000,0.000000,0.000000

In [6]:
# 결과데이터를 불러온다.
segment_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
segment_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [7]:
# 둘을 합쳐준다.
# ID는 중복되는 값이 concat의 영향으로 6개씩 존재하므로
# 기준년월을 이용해 추가적인 기준을 만들어준다.
all_df = combined_df.merge(segment_df, on=['ID', '기준년월'], how='left')
all_df

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M,Segment
0,201807,TRAIN_000000,0.454548,0.454548,0.364727,1.999996,0.0,0.000000,0.0,0.409766,...,1.042805,0.999700,0.999998,0.999998,0.261886,0.270752,0.000000,1.044401,1.280543,D
1,201807,TRAIN_000001,-0.511808,-0.511808,-0.511808,0.000000,0.0,0.000000,0.0,-1.010817,...,0.905663,0.999998,0.999998,0.999998,-0.563388,-0.670348,0.000000,0.000000,0.000000,E
2,201807,TRAIN_000002,-0.062716,-0.062716,0.067843,-1.999996,0.0,0.000000,0.0,-0.902166,...,1.993590,0.852567,0.999998,0.999998,-0.046516,0.058114,-0.014191,0.524159,1.208420,C
3,201807,TRAIN_000003,0.135707,0.135707,0.153975,-1.999996,0.0,0.000000,0.0,-0.866052,...,1.050646,0.999877,0.999998,0.999998,0.023821,0.258943,0.000000,0.880925,1.657124,D
4,201807,TRAIN_000004,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000028,...,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.000000,0.000000,0.000000,0.000000,0.0,-0.081943,0.0,0.000027,...,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN,E
2399996,201812,TRAIN_399996,0.073804,0.073804,0.073804,0.000000,0.0,0.000000,0.0,0.207099,...,0.999998,0.999998,0.999998,0.921733,-0.203251,-0.159143,0.000000,1.377071,2.533815,D
2399997,201812,TRAIN_399997,-0.040432,-0.040432,-0.040432,0.000000,0.0,0.000000,0.0,0.254495,...,0.345027,0.999998,0.999998,0.999998,0.027319,0.126581,0.000000,0.000000,0.000000,C
2399998,201812,TRAIN_399998,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000034,...,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN,E
2399999,201812,TRAIN_399999,0.187598,0.187598,0.187598,0.000000,0.0,0.000000,0.0,0.332268,...,0.593160,0.999998,0.999998,0.999998,-0.039845,-0.002659,0.000000,0.000000,0.000000,E

In [8]:
# 컬럼들을 리스트에 담아 확인한다
column_list = all_df.columns.tolist()
column_list

['기준년월',
 'ID',
 '증감율_이용건수_신용_전월',
 '증감율_이용건수_신판_전월',
 '증감율_이용건수_일시불_전월',
 '증감율_이용건수_할부_전월',
 '증감율_이용건수_CA_전월',
 '증감율_이용건수_체크_전월',
 '증감율_이용건수_카드론_전월',
 '증감율_이용금액_신용_전월',
 '증감율_이용금액_신판_전월',
 '증감율_이용금액_일시불_전월',
 '증감율_이용금액_할부_전월',
 '증감율_이용금액_CA_전월',
 '증감율_이용금액_체크_전월',
 '증감율_이용금액_카드론_전월',
 '증감율_이용건수_신용_분기',
 '증감율_이용건수_신판_분기',
 '증감율_이용건수_일시불_분기',
 '증감율_이용건수_할부_분기',
 '증감율_이용건수_CA_분기',
 '증감율_이용건수_체크_분기',
 '증감율_이용건수_카드론_분기',
 '증감율_이용금액_신용_분기',
 '증감율_이용금액_신판_분기',
 '증감율_이용금액_일시불_분기',
 '증감율_이용금액_할부_분기',
 '증감율_이용금액_CA_분기',
 '증감율_이용금액_체크_분기',
 '증감율_이용금액_카드론_분기',
 '잔액_신판평균한도소진율_r6m',
 '잔액_신판최대한도소진율_r6m',
 '잔액_신판평균한도소진율_r3m',
 '잔액_신판최대한도소진율_r3m',
 '잔액_신판ca평균한도소진율_r6m',
 '잔액_신판ca최대한도소진율_r6m',
 '잔액_신판ca평균한도소진율_r3m',
 '잔액_신판ca최대한도소진율_r3m',
 '변동률_일시불평잔',
 '변동률_RV일시불평잔',
 '변동률_할부평잔',
 '변동률_CA평잔',
 '변동률_RVCA평잔',
 '변동률_카드론평잔',
 '변동률_잔액_B1M',
 '변동률_잔액_일시불_B1M',
 '변동률_잔액_CA_B1M',
 '혜택수혜율_R3M',
 '혜택수혜율_B0M',
 'Segment']

In [25]:
numerical_cols = ['증감율_이용건수_신용_전월',
 '증감율_이용건수_신판_전월',
 '증감율_이용건수_일시불_전월',
 '증감율_이용건수_할부_전월',
 '증감율_이용건수_CA_전월',
 '증감율_이용건수_체크_전월',

 '증감율_이용금액_신용_전월',
 '증감율_이용금액_신판_전월',
 '증감율_이용금액_일시불_전월',
 '증감율_이용금액_할부_전월',
 '증감율_이용금액_CA_전월',
 '증감율_이용금액_체크_전월',

 '증감율_이용건수_신용_분기',
 '증감율_이용건수_신판_분기',
 '증감율_이용건수_일시불_분기',
 '증감율_이용건수_할부_분기',
 '증감율_이용건수_CA_분기',
 '증감율_이용건수_체크_분기',

 '증감율_이용금액_신용_분기',
 '증감율_이용금액_신판_분기',
 '증감율_이용금액_일시불_분기',
 '증감율_이용금액_할부_분기',
 '증감율_이용금액_CA_분기',
 '증감율_이용금액_체크_분기',

 '잔액_신판평균한도소진율_r6m',
 '잔액_신판최대한도소진율_r6m',
 '잔액_신판평균한도소진율_r3m',
 '잔액_신판최대한도소진율_r3m',
 '잔액_신판ca평균한도소진율_r6m',
 '잔액_신판ca최대한도소진율_r6m',
 '잔액_신판ca평균한도소진율_r3m',
 '잔액_신판ca최대한도소진율_r3m',
 '변동률_일시불평잔',
 '변동률_RV일시불평잔',
 '변동률_할부평잔',
 '변동률_CA평잔',
 '변동률_RVCA평잔',
 '변동률_카드론평잔',
 '변동률_잔액_B1M',
 '변동률_잔액_일시불_B1M',
 '변동률_잔액_CA_B1M',
 '혜택수혜율_R3M',
 '혜택수혜율_B0M']

categorical_cols = ['증감율_이용건수_카드론_전월', '증감율_이용금액_카드론_전월', '증감율_이용건수_카드론_분기', '증감율_이용금액_카드론_분기']

### 변수간 관계파악
Anova -> ETA제곱
카이제곱 -> 크레이머스V

In [ ]:
# 수치형/범주형
num_cols = numerical_cols
cat_cols = categorical_cols

anova = []
chi = []

for col in all_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = all_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(all_df[col], all_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df1 = pd.DataFrame(anova)
result_df2 = pd.DataFrame(chi)
result_df1 = result_df1.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df2 = result_df2.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df1)
display(result_df2)

                    변수   유형  계수종류      상관계수
0   잔액_신판ca최대한도소진율_r6m  수치형  Eta²  0.075072
1   잔액_신판ca최대한도소진율_r3m  수치형  Eta²  0.072253
2   잔액_신판ca평균한도소진율_r3m  수치형  Eta²  0.069510
3   잔액_신판ca평균한도소진율_r6m  수치형  Eta²  0.066496
4     잔액_신판최대한도소진율_r6m  수치형  Eta²  0.044228
5     잔액_신판최대한도소진율_r3m  수치형  Eta²  0.042057
6     잔액_신판평균한도소진율_r3m  수치형  Eta²  0.040209
7     잔액_신판평균한도소진율_r6m  수치형  Eta²  0.037250
8          변동률_RV일시불평잔  수치형  Eta²  0.012765
9           변동률_RVCA평잔  수치형  Eta²  0.012526
10           혜택수혜율_B0M  수치형  Eta²  0.011331
11           혜택수혜율_R3M  수치형  Eta²  0.010069
12      증감율_이용건수_할부_전월  수치형  Eta²  0.007035
13           변동률_카드론평잔  수치형  Eta²  0.006208
14     증감율_이용금액_일시불_전월  수치형  Eta²  0.006013
15      증감율_이용금액_신판_전월  수치형  Eta²  0.005987
16      증감율_이용건수_체크_전월  수치형  Eta²  0.005129
17           변동률_일시불평잔  수치형  Eta²  0.003640
18      증감율_이용건수_CA_전월  수치형  Eta²  0.003239
19      증감율_이용금액_신용_전월  수치형  Eta²  0.002815
20            변동률_CA평잔  수치형  Eta²  0.002382
21      증감율_이용건수_할부_분기  수치형  Eta²  0.001854
22      증감율_이용금액_할부_분기  수치형  Eta²  0.001114
23      증감율_이용금액_CA_분기  수치형  Eta²  0.001097
24      증감율_이용금액_체크_전월  수치형  Eta²  0.000747
25      증감율_이용금액_할부_전월  수치형  Eta²  0.000600
26      증감율_이용건수_CA_분기  수치형  Eta²  0.000445
27            변동률_할부평잔  수치형  Eta²  0.000418
28      증감율_이용금액_신용_분기  수치형  Eta²  0.000317
29      증감율_이용금액_신판_분기  수치형  Eta²  0.000272
30      증감율_이용금액_CA_전월  수치형  Eta²  0.000247
31       변동률_잔액_CA_B1M  수치형  Eta²  0.000190
32      증감율_이용금액_체크_분기  수치형  Eta²  0.000161
33      증감율_이용건수_체크_분기  수치형  Eta²  0.000158
34     증감율_이용금액_일시불_분기  수치형  Eta²  0.000086
35     증감율_이용건수_일시불_전월  수치형  Eta²  0.000075
36     증감율_이용건수_일시불_분기  수치형  Eta²  0.000050
37      증감율_이용건수_신용_분기  수치형  Eta²  0.000046
38      증감율_이용건수_신판_분기  수치형  Eta²  0.000042
39      증감율_이용건수_신판_전월  수치형  Eta²  0.000042
40      증감율_이용건수_신용_전월  수치형  Eta²  0.000033
41          변동률_잔액_B1M  수치형  Eta²  0.000029
42      변동률_잔액_일시불_B1M  수치형  Eta²  0.000022

                변수   유형        계수종류      상관계수
0  증감율_이용금액_카드론_분기  범주형  Cramér's V  0.024366
1  증감율_이용건수_카드론_분기  범주형  Cramér's V  0.023935
2  증감율_이용금액_카드론_전월  범주형  Cramér's V  0.006537
3  증감율_이용건수_카드론_전월  범주형  Cramér's V  0.005659

In [ ]:
pd.to_excel

                변수   유형        계수종류      상관계수
0  증감율_이용금액_카드론_분기  범주형  Cramér's V  0.024366
1  증감율_이용건수_카드론_분기  범주형  Cramér's V  0.023935
2  증감율_이용금액_카드론_전월  범주형  Cramér's V  0.006537
3  증감율_이용건수_카드론_전월  범주형  Cramér's V  0.005659

ab와 cde로 나눈다

In [13]:
# all_df를 Segment를 기준으로 ab_df와 cde_df로 나눈다
ab_df = all_df[all_df['Segment'].isin(['A', 'B'])]
cde_df = all_df[all_df['Segment'].isin(['C', 'D', 'E'])]

In [24]:
### ab_df와 cde_df를 성과정보ab_df, 성과정보cde_df라는 이름의 parquet으로 내보낸다.
ab_df.to_parquet('/content/drive/MyDrive/성과정보ab_df.parquet')
cde_df.to_parquet('/content/drive/MyDrive/성과정보cde_df.parquet')

In [14]:
ab_df

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M,Segment
2898,201807,TRAIN_002898,-0.048790,-0.044057,-0.005017,-0.587482,1.999996,0.000000,0.0,-0.317022,...,1.061523,0.852816,0.999998,0.926784,-0.129833,-0.004090,0.001787,0.858735,1.699488,A
5253,201807,TRAIN_005253,0.002817,0.002817,0.009501,-0.587537,0.000000,0.000000,0.0,-0.301876,...,1.045397,0.855324,0.999998,0.999998,0.001441,0.042504,0.000000,-0.363363,-0.056497,A
8128,201807,TRAIN_008128,0.204403,0.204403,0.204403,0.000000,0.000000,0.000000,0.0,0.345565,...,1.058149,0.999998,0.999998,0.999998,0.231152,0.455868,0.000000,1.077981,0.773759,A
10808,201807,TRAIN_010808,-0.196222,-0.196222,-0.196222,0.000000,0.000000,0.000000,0.0,0.186170,...,1.987825,0.999998,0.999998,0.999998,-0.090059,-0.120669,0.000000,1.397872,1.349127,A
14951,201807,TRAIN_014951,-0.272386,-0.272386,-0.211869,-1.999996,0.000000,0.000000,0.0,-1.010781,...,1.533585,0.999998,0.999998,0.999998,-0.404796,-0.201554,0.000000,1.221645,2.409092,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2376373,201812,TRAIN_376373,-0.109617,-0.109617,0.104147,-0.571762,0.000000,0.000000,0.0,0.285203,...,1.050780,0.999998,0.999998,0.999998,-0.088829,0.038066,0.000000,0.270823,2.330960,A
2378479,201812,TRAIN_378479,-0.064364,-0.064364,-0.064364,0.000000,0.000000,0.000000,0.0,0.138543,...,0.000000,0.000000,0.999998,0.999998,0.010504,-0.079515,0.000000,1.500185,1.988579,A
2390620,201812,TRAIN_390620,0.072792,0.072792,0.133076,-0.579687,0.000000,0.000000,0.0,-0.254074,...,1.056075,1.006599,0.999998,0.000000,0.127296,0.265701,-0.040458,2.236381,3.835789,B
2393027,201812,TRAIN_393027,0.147352,0.147352,0.147352,0.000000,0.000000,-0.193414,0.0,0.193343,...,0.560264,0.999998,0.999998,0.999998,-0.162652,-0.175774,0.000000,1.410890,3.830137,A
2393888,201812,TRAIN_393888,-0.164267,-0.164267,-0.164267,0.000000,0.000000,0.000000,0.0,-0.855869,...,0.909139,0.999998,0.999998,0.999998,-0.197584,-0.178593,0.000000,2.344055,2.045318,A

In [15]:
from scipy.stats import ttest_ind
def cohen_d(x, y):
    """두 그룹 간 효과 크기(Cohen's d) 계산"""
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    pooled_std = np.sqrt(((nx - 1)*x.std()**2 + (ny - 1)*y.std()**2) / dof)
    return (x.mean() - y.mean()) / pooled_std

def ttest_ab_multiple_verbose_abs_sorted(df, feature_cols):
    """
    A vs B 그룹 간 연속형 변수들에 대해 t-test, p-value, Cohen's d, 유의성 표시 포함한 결과 반환
    Cohen's d 절댓값 기준 내림차순 정렬
    """
    results = []

    for col in feature_cols:
        group_a = df[df['Segment'] == 'A'][col].dropna()
        group_b = df[df['Segment'] == 'B'][col].dropna()

        t_stat, p_val = ttest_ind(group_a, group_b, equal_var=False)
        d = cohen_d(group_a, group_b)

        # 유의성 표시
        if p_val < 0.001:
            sig = '***'
        elif p_val < 0.01:
            sig = '**'
        elif p_val < 0.05:
            sig = '*'
        else:
            sig = 'ns'

        results.append({
            'feature': col,
            't-statistic': round(t_stat, 4),
            'p-value': round(p_val, 4),
            'Cohen\'s d': round(d, 4),
            'abs(Cohen\'s d)': abs(round(d, 4)),
            'significance': sig
        })

    df_result = pd.DataFrame(results)
    df_result = df_result.sort_values('abs(Cohen\'s d)', ascending=False).reset_index(drop=True)
    df_result = df_result.drop(columns=['abs(Cohen\'s d)'])  # 필요 없으면 제거

    return df_result

In [16]:
ttest_results = ttest_ab_multiple_verbose_abs_sorted(ab_df, num_cols)
ttest_results

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

               feature  t-statistic  p-value  Cohen's d significance
0   잔액_신판ca최대한도소진율_r3m      -9.2737   0.0000    -0.9248          ***
1   잔액_신판ca평균한도소진율_r6m      -9.3503   0.0000    -0.8958          ***
2   잔액_신판ca평균한도소진율_r3m      -9.1686   0.0000    -0.8714          ***
3   잔액_신판ca최대한도소진율_r6m      -8.6974   0.0000    -0.8671          ***
4     잔액_신판평균한도소진율_r3m      -9.5464   0.0000    -0.8428          ***
5     잔액_신판평균한도소진율_r6m      -9.2195   0.0000    -0.7939          ***
6     잔액_신판최대한도소진율_r3m      -8.3764   0.0000    -0.7695          ***
7     잔액_신판최대한도소진율_r6m      -7.0061   0.0000    -0.6376          ***
8       증감율_이용건수_체크_전월       3.7527   0.0002     0.4751          ***
9            변동률_카드론평잔       3.3526   0.0010     0.3927          ***
10      증감율_이용건수_체크_분기      -3.4784   0.0006    -0.3432          ***
11         변동률_RV일시불평잔      -2.3409   0.0205    -0.3226            *
12      증감율_이용금액_체크_분기      -3.3924   0.0009    -0.3211          ***
13          변동률_잔액_B1M      -3.2348   0.0014    -0.2741           **
14      변동률_잔액_일시불_B1M      -2.4304   0.0161    -0.2462            *
15     증감율_이용금액_일시불_전월      -3.1375   0.0019    -0.2332           **
16      증감율_이용건수_할부_분기      -2.9755   0.0032    -0.2176           **
17      증감율_이용건수_할부_전월       2.1622   0.0318     0.1830            *
18      증감율_이용금액_신판_전월      -2.1579   0.0321    -0.1800            *
19      증감율_이용금액_체크_전월       1.0750   0.2841     0.1461           ns
20      증감율_이용건수_CA_전월      -1.6767   0.0952    -0.1429           ns
21            변동률_할부평잔      -2.1483   0.0325    -0.1323            *
22      증감율_이용금액_신용_분기       1.7055   0.0895     0.1280           ns
23      증감율_이용금액_할부_분기      -2.2009   0.0284    -0.1211            *
24      증감율_이용금액_CA_전월      -0.9070   0.3657    -0.1095           ns
25          변동률_RVCA평잔      -2.3751   0.0177    -0.0816            *
26      증감율_이용건수_신용_전월       0.8938   0.3725     0.0697           ns
27      증감율_이용건수_신판_전월       0.9234   0.3567     0.0637           ns
28           변동률_일시불평잔      -0.7047   0.4818    -0.0557           ns
29      증감율_이용건수_신용_분기       0.7708   0.4416     0.0536           ns
30            변동률_CA평잔      -0.7648   0.4451    -0.0483           ns
31     증감율_이용건수_일시불_분기       0.7189   0.4729     0.0480           ns
32       변동률_잔액_CA_B1M      -0.9608   0.3369    -0.0395           ns
33     증감율_이용금액_일시불_분기      -0.4936   0.6221    -0.0353           ns
34           혜택수혜율_R3M       0.3224   0.7475     0.0328           ns
35      증감율_이용금액_할부_전월       0.3612   0.7184     0.0315           ns
36      증감율_이용금액_신용_전월      -0.3756   0.7076    -0.0309           ns
37     증감율_이용건수_일시불_전월      -0.3242   0.7461    -0.0249           ns
38      증감율_이용건수_신판_분기       0.3397   0.7344     0.0224           ns
39      증감율_이용건수_CA_분기       0.2381   0.8121     0.0196           ns
40      증감율_이용금액_CA_분기      -0.4820   0.6299    -0.0183           ns
41      증감율_이용금액_신판_분기      -0.2587   0.7961    -0.0179           ns
42           혜택수혜율_B0M       0.1289   0.8976     0.0123           ns

In [28]:
pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² / t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan


def effect_sizes(df):
    # 수치형/범주형
    num_cols = numerical_cols
    cat_cols = categorical_cols

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            group1 = data[data['Segment'] == data['Segment'].unique()[0]][col]
            group2 = data[data['Segment'] == data['Segment'].unique()[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)

    return result_df1, result_df2

In [29]:
result1, result2 = effect_sizes(ab_df)
display(result1)
display(result2)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                    변수   유형  계수종류    상관계수
0     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.07562
1   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.07277
2   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.07167
3     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.07089
4   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.07017
5   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.06359
6     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.05925
7     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.04220
8       증감율_이용건수_체크_전월  수치형  Eta² 0.01248
9       증감율_이용건수_체크_분기  수치형  Eta² 0.01074
10      증감율_이용금액_체크_분기  수치형  Eta² 0.01022
11           변동률_카드론평잔  수치형  Eta² 0.00999
12          변동률_잔액_B1M  수치형  Eta² 0.00931
13     증감율_이용금액_일시불_전월  수치형  Eta² 0.00876
14      증감율_이용건수_할부_분기  수치형  Eta² 0.00789
15      변동률_잔액_일시불_B1M  수치형  Eta² 0.00527
16          변동률_RVCA평잔  수치형  Eta² 0.00504
17         변동률_RV일시불평잔  수치형  Eta² 0.00490
18      증감율_이용금액_할부_분기  수치형  Eta² 0.00433
19      증감율_이용건수_할부_전월  수치형  Eta² 0.00418
20      증감율_이용금액_신판_전월  수치형  Eta² 0.00416
21            변동률_할부평잔  수치형  Eta² 0.00413
22      증감율_이용금액_신용_분기  수치형  Eta² 0.00260
23      증감율_이용건수_CA_전월  수치형  Eta² 0.00252
24      증감율_이용금액_체크_전월  수치형  Eta² 0.00104
25       변동률_잔액_CA_B1M  수치형  Eta² 0.00083
26      증감율_이용건수_신판_전월  수치형  Eta² 0.00076
27      증감율_이용금액_CA_전월  수치형  Eta² 0.00074
28      증감율_이용건수_신용_전월  수치형  Eta² 0.00072
29      증감율_이용건수_신용_분기  수치형  Eta² 0.00053
30            변동률_CA평잔  수치형  Eta² 0.00052
31     증감율_이용건수_일시불_분기  수치형  Eta² 0.00046
32           변동률_일시불평잔  수치형  Eta² 0.00045
33     증감율_이용금액_일시불_분기  수치형  Eta² 0.00022
34      증감율_이용금액_CA_분기  수치형  Eta² 0.00021
35      증감율_이용금액_신용_전월  수치형  Eta² 0.00013
36      증감율_이용금액_할부_전월  수치형  Eta² 0.00012
37      증감율_이용건수_신판_분기  수치형  Eta² 0.00010
38     증감율_이용건수_일시불_전월  수치형  Eta² 0.00009
39           혜택수혜율_R3M  수치형  Eta² 0.00009
40      증감율_이용금액_신판_분기  수치형  Eta² 0.00006
41      증감율_이용건수_CA_분기  수치형  Eta² 0.00005
42           혜택수혜율_B0M  수치형  Eta² 0.00002

                변수   유형        계수종류    상관계수
0  증감율_이용금액_카드론_분기  범주형  Cramér's V 0.08763
1  증감율_이용건수_카드론_분기  범주형  Cramér's V 0.08594
2  증감율_이용금액_카드론_전월  범주형  Cramér's V 0.00581
3  증감율_이용건수_카드론_전월  범주형  Cramér's V 0.00072

In [30]:
# 크레이머스V와 eta를 구하기 위한 함수
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

def eta_squared(anova_ss_between, total_ss):
    return anova_ss_between / total_ss if total_ss != 0 else np.nan

In [31]:
anova = []
chi = []

for col in ab_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = ab_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(ab_df[col], ab_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df11 = pd.DataFrame(anova)
result_df12 = pd.DataFrame(chi)
result_df11 = result_df11.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df12 = result_df12.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df11)
display(result_df12)

                    변수   유형  계수종류    상관계수
0   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.08784
1   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.08286
2   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.07876
3   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.07805
4     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.07405
5     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.06626
6     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.06250
7     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.04377
8       증감율_이용건수_체크_전월  수치형  Eta² 0.02479
9            변동률_카드론평잔  수치형  Eta² 0.01706
10      증감율_이용건수_체크_분기  수치형  Eta² 0.01309
11         변동률_RV일시불평잔  수치형  Eta² 0.01158
12      증감율_이용금액_체크_분기  수치형  Eta² 0.01148
13          변동률_잔액_B1M  수치형  Eta² 0.00839
14      변동률_잔액_일시불_B1M  수치형  Eta² 0.00678
15     증감율_이용금액_일시불_전월  수치형  Eta² 0.00609
16      증감율_이용건수_할부_분기  수치형  Eta² 0.00530
17      증감율_이용건수_할부_전월  수치형  Eta² 0.00376
18      증감율_이용금액_신판_전월  수치형  Eta² 0.00364
19      증감율_이용금액_체크_전월  수치형  Eta² 0.00240
20      증감율_이용건수_CA_전월  수치형  Eta² 0.00229
21            변동률_할부평잔  수치형  Eta² 0.00197
22      증감율_이용금액_신용_분기  수치형  Eta² 0.00184
23      증감율_이용금액_할부_분기  수치형  Eta² 0.00165
24      증감율_이용금액_CA_전월  수치형  Eta² 0.00135
25          변동률_RVCA평잔  수치형  Eta² 0.00075
26      증감율_이용건수_신용_전월  수치형  Eta² 0.00055
27      증감율_이용건수_신판_전월  수치형  Eta² 0.00046
28           변동률_일시불평잔  수치형  Eta² 0.00035
29      증감율_이용건수_신용_분기  수치형  Eta² 0.00032
30            변동률_CA평잔  수치형  Eta² 0.00026
31     증감율_이용건수_일시불_분기  수치형  Eta² 0.00026
32       변동률_잔액_CA_B1M  수치형  Eta² 0.00018
33     증감율_이용금액_일시불_분기  수치형  Eta² 0.00014
34           혜택수혜율_R3M  수치형  Eta² 0.00012
35      증감율_이용금액_할부_전월  수치형  Eta² 0.00011
36      증감율_이용금액_신용_전월  수치형  Eta² 0.00011
37     증감율_이용건수_일시불_전월  수치형  Eta² 0.00007
38      증감율_이용건수_신판_분기  수치형  Eta² 0.00006
39      증감율_이용건수_CA_분기  수치형  Eta² 0.00004
40      증감율_이용금액_CA_분기  수치형  Eta² 0.00004
41      증감율_이용금액_신판_분기  수치형  Eta² 0.00004
42           혜택수혜율_B0M  수치형  Eta² 0.00002

                변수   유형        계수종류    상관계수
0  증감율_이용금액_카드론_분기  범주형  Cramér's V 0.08763
1  증감율_이용건수_카드론_분기  범주형  Cramér's V 0.08594
2  증감율_이용금액_카드론_전월  범주형  Cramér's V 0.00581
3  증감율_이용건수_카드론_전월  범주형  Cramér's V 0.00072

In [32]:
anova = []
chi = []

for col in cde_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = cde_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(cde_df[col], cde_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df21 = pd.DataFrame(anova)
result_df22 = pd.DataFrame(chi)
result_df21 = result_df21.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df22 = result_df22.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df21)
display(result_df22)

                    변수   유형  계수종류    상관계수
0   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.07453
1   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.07174
2   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.06900
3   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.06602
4     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.04403
5     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.04190
6     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.04007
7     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.03711
8          변동률_RV일시불평잔  수치형  Eta² 0.01274
9           변동률_RVCA평잔  수치형  Eta² 0.01250
10           혜택수혜율_B0M  수치형  Eta² 0.01130
11           혜택수혜율_R3M  수치형  Eta² 0.01005
12      증감율_이용건수_할부_전월  수치형  Eta² 0.00689
13           변동률_카드론평잔  수치형  Eta² 0.00619
14     증감율_이용금액_일시불_전월  수치형  Eta² 0.00600
15      증감율_이용금액_신판_전월  수치형  Eta² 0.00597
16      증감율_이용건수_체크_전월  수치형  Eta² 0.00512
17           변동률_일시불평잔  수치형  Eta² 0.00364
18      증감율_이용건수_CA_전월  수치형  Eta² 0.00323
19      증감율_이용금액_신용_전월  수치형  Eta² 0.00282
20            변동률_CA평잔  수치형  Eta² 0.00237
21      증감율_이용건수_할부_분기  수치형  Eta² 0.00185
22      증감율_이용금액_할부_분기  수치형  Eta² 0.00111
23      증감율_이용금액_CA_분기  수치형  Eta² 0.00110
24      증감율_이용금액_체크_전월  수치형  Eta² 0.00074
25      증감율_이용금액_할부_전월  수치형  Eta² 0.00059
26      증감율_이용건수_CA_분기  수치형  Eta² 0.00044
27            변동률_할부평잔  수치형  Eta² 0.00041
28      증감율_이용금액_신용_분기  수치형  Eta² 0.00030
29      증감율_이용금액_신판_분기  수치형  Eta² 0.00026
30      증감율_이용금액_CA_전월  수치형  Eta² 0.00025
31       변동률_잔액_CA_B1M  수치형  Eta² 0.00018
32      증감율_이용금액_체크_분기  수치형  Eta² 0.00015
33      증감율_이용건수_체크_분기  수치형  Eta² 0.00015
34     증감율_이용금액_일시불_분기  수치형  Eta² 0.00008
35     증감율_이용건수_일시불_전월  수치형  Eta² 0.00008
36     증감율_이용건수_일시불_분기  수치형  Eta² 0.00005
37      증감율_이용건수_신용_분기  수치형  Eta² 0.00005
38      증감율_이용건수_신판_분기  수치형  Eta² 0.00004
39      증감율_이용건수_신판_전월  수치형  Eta² 0.00004
40      증감율_이용건수_신용_전월  수치형  Eta² 0.00003
41      변동률_잔액_일시불_B1M  수치형  Eta² 0.00002
42          변동률_잔액_B1M  수치형  Eta² 0.00002

                변수   유형        계수종류    상관계수
0  증감율_이용금액_카드론_분기  범주형  Cramér's V 0.02412
1  증감율_이용건수_카드론_분기  범주형  Cramér's V 0.02371
2  증감율_이용금액_카드론_전월  범주형  Cramér's V 0.00612
3  증감율_이용건수_카드론_전월  범주형  Cramér's V 0.00538

In [33]:
result_df21

                    변수   유형  계수종류    상관계수
0   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.07453
1   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.07174
2   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.06900
3   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.06602
4     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.04403
5     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.04190
6     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.04007
7     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.03711
8          변동률_RV일시불평잔  수치형  Eta² 0.01274
9           변동률_RVCA평잔  수치형  Eta² 0.01250
10           혜택수혜율_B0M  수치형  Eta² 0.01130
11           혜택수혜율_R3M  수치형  Eta² 0.01005
12      증감율_이용건수_할부_전월  수치형  Eta² 0.00689
13           변동률_카드론평잔  수치형  Eta² 0.00619
14     증감율_이용금액_일시불_전월  수치형  Eta² 0.00600
15      증감율_이용금액_신판_전월  수치형  Eta² 0.00597
16      증감율_이용건수_체크_전월  수치형  Eta² 0.00512
17           변동률_일시불평잔  수치형  Eta² 0.00364
18      증감율_이용건수_CA_전월  수치형  Eta² 0.00323
19      증감율_이용금액_신용_전월  수치형  Eta² 0.00282
20            변동률_CA평잔  수치형  Eta² 0.00237
21      증감율_이용건수_할부_분기  수치형  Eta² 0.00185
22      증감율_이용금액_할부_분기  수치형  Eta² 0.00111
23      증감율_이용금액_CA_분기  수치형  Eta² 0.00110
24      증감율_이용금액_체크_전월  수치형  Eta² 0.00074
25      증감율_이용금액_할부_전월  수치형  Eta² 0.00059
26      증감율_이용건수_CA_분기  수치형  Eta² 0.00044
27            변동률_할부평잔  수치형  Eta² 0.00041
28      증감율_이용금액_신용_분기  수치형  Eta² 0.00030
29      증감율_이용금액_신판_분기  수치형  Eta² 0.00026
30      증감율_이용금액_CA_전월  수치형  Eta² 0.00025
31       변동률_잔액_CA_B1M  수치형  Eta² 0.00018
32      증감율_이용금액_체크_분기  수치형  Eta² 0.00015
33      증감율_이용건수_체크_분기  수치형  Eta² 0.00015
34     증감율_이용금액_일시불_분기  수치형  Eta² 0.00008
35     증감율_이용건수_일시불_전월  수치형  Eta² 0.00008
36     증감율_이용건수_일시불_분기  수치형  Eta² 0.00005
37      증감율_이용건수_신용_분기  수치형  Eta² 0.00005
38      증감율_이용건수_신판_분기  수치형  Eta² 0.00004
39      증감율_이용건수_신판_전월  수치형  Eta² 0.00004
40      증감율_이용건수_신용_전월  수치형  Eta² 0.00003
41      변동률_잔액_일시불_B1M  수치형  Eta² 0.00002
42          변동률_잔액_B1M  수치형  Eta² 0.00002

In [35]:
#result1과 result2, 그리고 ttest_results를 각각 parquet으로 저장한다.
result1.to_parquet('/content/drive/MyDrive/성과정보ab_df8_설명력.parquet', index=False)
result2.to_parquet('/content/drive/MyDrive/성과정보ab_df8_크래머V.parquet', index=False)
ttest_results.to_parquet('/content/drive/MyDrive/ttest_results8.parquet', index=False)
# result_df21과 22도 똑같은 느낌으로 저장한다.
result_df21.to_parquet('/content/drive/MyDrive/성과정보cde_df8_설명력.parquet', index=False)
result_df21.to_parquet('/content/drive/MyDrive/성과정보cde_df8_크래머V.parquet', index=False)

In [36]:
# 불러와서 확인해본다.
df2423 = pd.read_parquet('/content/drive/MyDrive/성과정보cde_df.parquet')

In [37]:
df2423

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M,Segment
0,201807,TRAIN_000000,0.45455,0.45455,0.36473,2.00000,0.00000,0.00000,0.00000,0.40977,...,1.04281,0.99970,1.00000,1.00000,0.26189,0.27075,0.00000,1.04440,1.28054,D
1,201807,TRAIN_000001,-0.51181,-0.51181,-0.51181,0.00000,0.00000,0.00000,0.00000,-1.01082,...,0.90566,1.00000,1.00000,1.00000,-0.56339,-0.67035,0.00000,0.00000,0.00000,E
2,201807,TRAIN_000002,-0.06272,-0.06272,0.06784,-2.00000,0.00000,0.00000,0.00000,-0.90217,...,1.99359,0.85257,1.00000,1.00000,-0.04652,0.05811,-0.01419,0.52416,1.20842,C
3,201807,TRAIN_000003,0.13571,0.13571,0.15398,-2.00000,0.00000,0.00000,0.00000,-0.86605,...,1.05065,0.99988,1.00000,1.00000,0.02382,0.25894,0.00000,0.88092,1.65712,D
4,201807,TRAIN_000004,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.00000,0.00000,0.00000,0.00000,0.00000,-0.08194,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN,E
2399996,201812,TRAIN_399996,0.07380,0.07380,0.07380,0.00000,0.00000,0.00000,0.00000,0.20710,...,1.00000,1.00000,1.00000,0.92173,-0.20325,-0.15914,0.00000,1.37707,2.53381,D
2399997,201812,TRAIN_399997,-0.04043,-0.04043,-0.04043,0.00000,0.00000,0.00000,0.00000,0.25449,...,0.34503,1.00000,1.00000,1.00000,0.02732,0.12658,0.00000,0.00000,0.00000,C
2399998,201812,TRAIN_399998,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,0.00003,...,1.00000,1.00000,1.00000,1.00000,0.00000,0.00000,0.00000,NaN,NaN,E
2399999,201812,TRAIN_399999,0.18760,0.18760,0.18760,0.00000,0.00000,0.00000,0.00000,0.33227,...,0.59316,1.00000,1.00000,1.00000,-0.03984,-0.00266,0.00000,0.00000,0.00000,E