In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False
import gc


# 인코더 추가
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
#상수항추가
from statsmodels.tools.tools import add_constant
# 카이제곱, ANOVA
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
#Turkeyhsd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

### 데이터 불러오기

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
# parquet 파일 데이터를 읽어온다.
# x 값으로 쓸 데이터
df1_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201807_train_승인매출정보.parquet')
df2_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201808_train_승인매출정보.parquet')
df3_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201809_train_승인매출정보.parquet')
df4_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201810_train_승인매출정보.parquet')
df5_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201811_train_승인매출정보.parquet')
df6_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201812_train_승인매출정보.parquet')

In [4]:
# 결과데이터를 불러온다.
segment_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
segment_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [20]:
# 데이터프레임의 컬럼 이름을 리스트에 담는다.
column_list = df1_train.columns.tolist()

In [21]:
print(column_list)

['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M', '이용금액대']

In [22]:
# 슬라이싱
column_list = ['기준년월', 'ID', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [23]:
print(column_list)

['기준년월', 'ID', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [24]:
df1_train = df1_train[column_list]

In [25]:
df2_train = df2_train[column_list]
df3_train = df3_train[column_list]
df4_train = df4_train[column_list]
df5_train = df5_train[column_list]
df6_train = df6_train[column_list]

In [26]:
combined_df = pd.concat([df1_train, df2_train, df3_train, df4_train, df5_train, df6_train],
                         axis=0,        # 행 방향
                         ignore_index=True)  # 인덱스 초기화

In [34]:
segment_df = segment_df['Segment']

In [56]:
# 세그먼트와 데이터를 합쳐준다.

all_df = pd.concat([segment_df,combined_df], axis = 1)
all_df

,Segment,기준년월,ID,이용가맹점수,이용금액_해외,쇼핑_도소매_이용금액,쇼핑_백화점_이용금액,쇼핑_마트_이용금액,쇼핑_슈퍼마켓_이용금액,쇼핑_편의점_이용금액,...,할부금액_무이자_12M_R12M,할부금액_무이자_14M_R12M,할부건수_부분_3M_R12M,할부건수_부분_6M_R12M,할부건수_부분_12M_R12M,할부건수_부분_14M_R12M,할부금액_부분_3M_R12M,할부금액_부분_6M_R12M,할부금액_부분_12M_R12M,할부금액_부분_14M_R12M
0,D,201807,TRAIN_000000,6,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,E,201807,TRAIN_000001,32,0,645,0,0,435,315,...,0,0,0,0,0,0,0,0,0,0
2,C,201807,TRAIN_000002,27,0,1038,751,924,504,239,...,0,0,0,0,0,0,0,0,0,0
3,D,201807,TRAIN_000003,10,0,0,0,801,487,0,...,0,0,0,0,0,0,0,0,0,0
4,E,201807,TRAIN_000004,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,E,201812,TRAIN_399995,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,D,201812,TRAIN_399996,15,0,1496,0,0,714,0,...,0,0,0,0,0,0,0,0,0,0
2399997,C,201812,TRAIN_399997,27,0,0,0,0,400,300,...,0,0,0,0,0,0,0,0,0,0
2399998,E,201812,TRAIN_399998,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,E,201812,TRAIN_399999,3,0,0,985,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
print(all_df.isna().sum().to_string())

기준년월                       0
ID                         0
Segment                    0
이용가맹점수                     0
이용금액_해외                    0
쇼핑_도소매_이용금액                0
쇼핑_백화점_이용금액                0
쇼핑_마트_이용금액                 0
쇼핑_슈퍼마켓_이용금액               0
쇼핑_편의점_이용금액                0
쇼핑_아울렛_이용금액                0
쇼핑_온라인_이용금액                0
쇼핑_기타_이용금액                 0
교통_주유이용금액                  0
교통_정비이용금액                  0
교통_통행료이용금액                 0
교통_버스지하철이용금액               0
교통_택시이용금액                  0
교통_철도버스이용금액                0
여유_운동이용금액                  0
여유_Pet이용금액                 0
여유_공연이용금액                  0
여유_공원이용금액                  0
여유_숙박이용금액                  0
여유_여행이용금액                  0
여유_항공이용금액                  0
여유_기타이용금액                  0
납부_통신비이용금액                 0
납부_관리비이용금액                 0
납부_렌탈료이용금액                 0
납부_가스전기료이용금액               0
납부_보험료이용금액                 0
납부_유선방송이용금액                0
납부_건강연금이용금액                0
납부_기타이용금액                  0
_1순위업종                539992
_1순위업종_이용금액                0
_2순위업종                912725
_2순위업종_이용금액                0
_3순위업종               1107898
_3순위업종_이용금액                0
_1순위쇼핑업종              922663
_1순위쇼핑업종_이용금액              0
_2순위쇼핑업종             1135042
_2순위쇼핑업종_이용금액              0
_3순위쇼핑업종             1312267
_3순위쇼핑업종_이용금액              0
_1순위교통업종             1164494
_1순위교통업종_이용금액              0
_2순위교통업종             1656423
_2순위교통업종_이용금액              0
_3순위교통업종             2045455
_3순위교통업종_이용금액              0
_1순위여유업종             1987260
_1순위여유업종_이용금액              0
_2순위여유업종             2302286
_2순위여유업종_이용금액              0
_3순위여유업종             2377725
_3순위여유업종_이용금액              0
_1순위납부업종             1216263
_1순위납부업종_이용금액              0
_2순위납부업종             2033640
_2순위납부업종_이용금액              0
_3순위납부업종             2310187
_3순위납부업종_이용금액              0
할부건수_3M_R12M               0
할부건수_6M_R12M               0
할부건수_12M_R12M              0
할부건수_14M_R12M              0
할부금액_3M_R12M               0
할부금액_6M_R12M               0
할부금액_12M_R12M              0
할부금액_14M_R12M              0
할부건수_유이자_3M_R12M           0
할부건수_유이자_6M_R12M           0
할부건수_유이자_12M_R12M          0
할부건수_유이자_14M_R12M          0
할부금액_유이자_3M_R12M           0
할부금액_유이자_6M_R12M           0
할부금액_유이자_12M_R12M          0
할부금액_유이자_14M_R12M          0
할부건수_무이자_3M_R12M           0
할부건수_무이자_6M_R12M           0
할부건수_무이자_12M_R12M          0
할부건수_무이자_14M_R12M          0
할부금액_무이자_3M_R12M           0
할부금액_무이자_6M_R12M           0
할부금액_무이자_12M_R12M          0
할부금액_무이자_14M_R12M          0
할부건수_부분_3M_R12M            0
할부건수_부분_6M_R12M            0
할부건수_부분_12M_R12M           0
할부건수_부분_14M_R12M           0
할부금액_부분_3M_R12M            0
할부금액_부분_6M_R12M            0
할부금액_부분_12M_R12M           0
할부금액_부분_14M_R12M           0

_1순위업종                539992
_2순위업종                912725
_3순위업종               1107898
_1순위쇼핑업종              922663
_2순위쇼핑업종             1135042
_3순위쇼핑업종             1312267
_1순위교통업종             1164494
_2순위교통업종             1656423
_3순위교통업종             2045455
_1순위여유업종             1987260
_2순위여유업종             2302286
_3순위여유업종             2377725
_1순위납부업종             1216263
_2순위납부업종             2033640
_3순위납부업종             2310187

In [ ]:
for col in column_list:
    try:
        var_value = all_df[col].var()
        print(f"{col}: {var_value:.2f}")
    except TypeError:
        print(f"❌ 분산 계산 불가 (문자열 포함): {col}")

이용가맹점수: 620.33
이용금액_해외: 244947.96
쇼핑_도소매_이용금액: 544484.29
쇼핑_백화점_이용금액: 77740.47
쇼핑_마트_이용금액: 338766.64
쇼핑_슈퍼마켓_이용금액: 228902.32
쇼핑_편의점_이용금액: 114447.16
쇼핑_아울렛_이용금액: 21936.57
쇼핑_온라인_이용금액: 18827604.18
쇼핑_기타_이용금액: 21235.64
교통_주유이용금액: 1163692.50
교통_정비이용금액: 38359.46
교통_통행료이용금액: 2.75
교통_버스지하철이용금액: 128310.55
교통_택시이용금액: 13153.34
교통_철도버스이용금액: 18573.09
여유_운동이용금액: 99932.42
여유_Pet이용금액: 3211.95
여유_공연이용금액: 2226.47
여유_공원이용금액: 103.48
여유_숙박이용금액: 3802.57
여유_여행이용금액: 0.00
여유_항공이용금액: 18086.05
여유_기타이용금액: 1654.66
납부_통신비이용금액: 1110276.92
납부_관리비이용금액: 656954.84
납부_렌탈료이용금액: 0.00
납부_가스전기료이용금액: 7593.75
납부_보험료이용금액: 423363.85
납부_유선방송이용금액: 0.00
납부_건강연금이용금액: 0.00
납부_기타이용금액: 8414.30
❌ 분산 계산 불가 (문자열 포함): _1순위업종
_1순위업종_이용금액: 78376831.02
❌ 분산 계산 불가 (문자열 포함): _2순위업종
_2순위업종_이용금액: 8171160.65
❌ 분산 계산 불가 (문자열 포함): _3순위업종
_3순위업종_이용금액: 2717267.15
❌ 분산 계산 불가 (문자열 포함): _1순위쇼핑업종
_1순위쇼핑업종_이용금액: 18248816.94
❌ 분산 계산 불가 (문자열 포함): _2순위쇼핑업종
_2순위쇼핑업종_이용금액: 441931.88
❌ 분산 계산 불가 (문자열 포함): _3순위쇼핑업종
_3순위쇼핑업종_이용금액: 256998.47
❌ 분산 계산 불가 (문자열 포함): _1순위교통업종
_1순위교통업종_이용금액: 1098752.40
❌ 분산 계산 불가 (문자열 포함): _2순위교통업종
_2순위교통업종_이용금액: 71553.00
❌ 분산 계산 불가 (문자열 포함): _3순위교통업종
_3순위교통업종_이용금액: 16667.88
❌ 분산 계산 불가 (문자열 포함): _1순위여유업종
_1순위여유업종_이용금액: 117236.46
❌ 분산 계산 불가 (문자열 포함): _2순위여유업종
_2순위여유업종_이용금액: 5873.55
❌ 분산 계산 불가 (문자열 포함): _3순위여유업종
_3순위여유업종_이용금액: 695.48
❌ 분산 계산 불가 (문자열 포함): _1순위납부업종
_1순위납부업종_이용금액: 1613889.45
❌ 분산 계산 불가 (문자열 포함): _2순위납부업종
_2순위납부업종_이용금액: 284544.47
❌ 분산 계산 불가 (문자열 포함): _3순위납부업종
_3순위납부업종_이용금액: 23177.92
할부건수_3M_R12M: 23.38
할부건수_6M_R12M: 4.00
할부건수_12M_R12M: 0.12
할부건수_14M_R12M: 0.00
할부금액_3M_R12M: 89515265.53
할부금액_6M_R12M: 22569120.00
할부금액_12M_R12M: 5191073.44
할부금액_14M_R12M: 901824.55
할부건수_유이자_3M_R12M: 2.40
할부건수_유이자_6M_R12M: 0.39
할부건수_유이자_12M_R12M: 0.06
할부건수_유이자_14M_R12M: 0.00
할부금액_유이자_3M_R12M: 9805757.29
할부금액_유이자_6M_R12M: 3149946.07
할부금액_유이자_12M_R12M: 2500706.75
할부금액_유이자_14M_R12M: 477303.17
할부건수_무이자_3M_R12M: 15.94
할부건수_무이자_6M_R12M: 3.05
할부건수_무이자_12M_R12M: 0.05
할부건수_무이자_14M_R12M: 0.00
할부금액_무이자_3M_R12M: 64352215.01
할부금액_무이자_6M_R12M: 15766008.84
할부금액_무이자_12M_R12M: 521001.29
할부금액_무이자_14M_R12M: 425132.32
할부건수_부분_3M_R12M: 0.00
할부건수_부분_6M_R12M: 0.00
할부건수_부분_12M_R12M: 0.00
할부건수_부분_14M_R12M: 0.00
할부금액_부분_3M_R12M: 0.00
할부금액_부분_6M_R12M: 7.52
할부금액_부분_12M_R12M: 1211996.73
할부금액_부분_14M_R12M: 3282.35

In [ ]:
all_df['할부금액_부분_3M_R12M'].value_counts()

할부금액_부분_3M_R12M
0    2400000
Name: count, dtype: int64

In [ ]:
all_df['여유_여행이용금액'].value_counts()

여유_여행이용금액
0    2400000
Name: count, dtype: int64

- 분산이 0인 것들은 [할부건수_14M_R12M, 할부건수_유이자_14M_R12M, 할부건수_부분_12M_R12M, 할부건수_무이자_14M_R12M] 컬럼을 제외하면
- 모두 0 하나만을 데이터로 가지고 있다.
- [여유_여행이용금액, 납부_렌탈료이용금액, 납부_유선방송이용금액, 납부_건강연금이용금액, 할부건수_부분_3M_R12M, 할부건수_부분_6M_R12M, 할부건수_부분_14M_R12M, 할부금액_부분_3M_R12M]의 경우 0 하나만을 가진 데이터값이다.

- 0 하나만 가진 데이터값은 상관관계 분석이나 추후 학습에 방해되므로 drop

In [28]:
all_df.drop(['여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액',
             '납부_건강연금이용금액', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M'],
            axis=1, inplace=True)

In [29]:

all_df.drop(['할부금액_부분_3M_R12M'],
            axis=1, inplace=True)

### 변수간 관계파악
Anova -> ETA제곱
카이제곱 -> 크레이머스V

In [46]:
print(column_list)

['기준년월', 'ID', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [47]:
# 크레이머스V와 eta를 구하기 위한 함수
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

def eta_squared(anova_ss_between, total_ss):
    return anova_ss_between / total_ss if total_ss != 0 else np.nan

In [48]:
# 수치형/범주형 자동 구분
num_cols = all_df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = all_df.select_dtypes(exclude=[np.number]).columns.tolist()

In [49]:
print(cat_cols)

['Segment', 'ID', '_1순위업종', '_2순위업종', '_3순위업종', '_1순위쇼핑업종', '_2순위쇼핑업종', '_3순위쇼핑업종', '_1순위교통업종', '_2순위교통업종', '_3순위교통업종', '_1순위여유업종', '_2순위여유업종', '_3순위여유업종', '_1순위납부업종', '_2순위납부업종', '_3순위납부업종']

In [50]:
print(num_cols)

['기준년월', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종_이용금액', '_2순위업종_이용금액', '_3순위업종_이용금액', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종_이용금액', '_1순위교통업종_이용금액', '_2순위교통업종_이용금액', '_3순위교통업종_이용금액', '_1순위여유업종_이용금액', '_2순위여유업종_이용금액', '_3순위여유업종_이용금액', '_1순위납부업종_이용금액', '_2순위납부업종_이용금액', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [51]:
del num_cols[0]

In [52]:
print(num_cols)

['이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종_이용금액', '_2순위업종_이용금액', '_3순위업종_이용금액', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종_이용금액', '_1순위교통업종_이용금액', '_2순위교통업종_이용금액', '_3순위교통업종_이용금액', '_1순위여유업종_이용금액', '_2순위여유업종_이용금액', '_3순위여유업종_이용금액', '_1순위납부업종_이용금액', '_2순위납부업종_이용금액', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [53]:
# 제외할 컬럼 리스트
remove_cols = ['여유_여행이용금액', '납부_렌탈료이용금액', '납부_유선방송이용금액',
               '납부_건강연금이용금액', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M']

# 기존 숫자형 컬럼 리스트에서 제거
num_cols = [col for col in num_cols if col not in remove_cols]

In [54]:
print(num_cols)

['이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_기타이용금액', '_1순위업종_이용금액', '_2순위업종_이용금액', '_3순위업종_이용금액', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종_이용금액', '_1순위교통업종_이용금액', '_2순위교통업종_이용금액', '_3순위교통업종_이용금액', '_1순위여유업종_이용금액', '_2순위여유업종_이용금액', '_3순위여유업종_이용금액', '_1순위납부업종_이용금액', '_2순위납부업종_이용금액', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_12M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M']

In [58]:
target_col = ab_df['Segment']
feature_cols = ab_df.drop('Segment', axis=1)

In [61]:
from scipy.stats import f_oneway

def run_anova(df, target_col, feature_cols):
    """
    feature_cols 리스트에 있는 연속형 변수들을 대상으로
    target_col에 따라 그룹화하여 ANOVA F-test 수행
    """
    results = {}
    for col in feature_cols:
        groups = [df[df[target_col] == label][col] for label in df[target_col].unique()]
        f_stat, p_val = f_oneway(*groups)
        results[col] = {'F': round(f_stat, 4), 'p-value': round(p_val, 4)}
    return pd.DataFrame(results).T.sort_values('p-value')

In [67]:
run_anova(ab_df, 'Segment', num_cols)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)

                         F  p-value
납부_보험료이용금액         17.2635      0.0
납부_통신비이용금액         18.1840      0.0
할부건수_무이자_3M_R12M   88.2156      0.0
할부금액_무이자_3M_R12M   53.3384      0.0
할부건수_무이자_6M_R12M   24.8552      0.0
...                    ...      ...
할부건수_유이자_14M_R12M      NaN      NaN
할부건수_무이자_14M_R12M      NaN      NaN
할부건수_부분_12M_R12M       NaN      NaN
할부금액_부분_6M_R12M        NaN      NaN
할부금액_부분_14M_R12M       NaN      NaN

[71 rows x 2 columns]

In [68]:
run_anova(cde_df, 'Segment', num_cols)

                             F  p-value
이용가맹점수             327196.0055   0.0000
이용금액_해외            109376.1864   0.0000
쇼핑_도소매_이용금액        299536.1796   0.0000
쇼핑_백화점_이용금액         98816.4075   0.0000
쇼핑_마트_이용금액         221786.7769   0.0000
...                        ...      ...
할부금액_무이자_14M_R12M     124.4768   0.0000
할부건수_부분_12M_R12M       84.4369   0.0000
할부금액_부분_6M_R12M         2.9344   0.0532
할부건수_무이자_14M_R12M       0.3721   0.6893
할부금액_부분_14M_R12M        0.0102   0.9899

[71 rows x 2 columns]

### 기존의 코드

In [ ]:
anova = []
chi = []

for col in all_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = all_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(all_df[col], all_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df1 = pd.DataFrame(anova)
result_df2 = pd.DataFrame(chi)
result_df1 = result_df1.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df2 = result_df2.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df1)
display(result_df2)

                   변수   유형  계수종류          상관계수
0         _3순위업종_이용금액  수치형  Eta²  2.549372e-01
1         _2순위업종_이용금액  수치형  Eta²  2.429217e-01
2       _2순위쇼핑업종_이용금액  수치형  Eta²  2.387084e-01
3         _1순위업종_이용금액  수치형  Eta²  2.198912e-01
4       _3순위쇼핑업종_이용금액  수치형  Eta²  2.172726e-01
..                ...  ...   ...           ...
67      할부건수_14M_R12M  수치형  Eta²  1.375602e-05
68    할부금액_부분_6M_R12M  수치형  Eta²  2.446678e-06
69  할부건수_무이자_14M_R12M  수치형  Eta²  3.108322e-07
70   할부금액_부분_14M_R12M  수치형  Eta²  2.398594e-08
71               기준년월  수치형  Eta²  0.000000e+00

[72 rows x 4 columns]

          변수   유형        계수종류      상관계수
0         ID  범주형  Cramér's V  1.000000
1   _2순위여유업종  범주형  Cramér's V  0.131715
2     _1순위업종  범주형  Cramér's V  0.116062
3   _3순위여유업종  범주형  Cramér's V  0.105205
4     _2순위업종  범주형  Cramér's V  0.102366
5   _3순위쇼핑업종  범주형  Cramér's V  0.097754
6   _1순위쇼핑업종  범주형  Cramér's V  0.097296
7     _3순위업종  범주형  Cramér's V  0.091734
8   _1순위여유업종  범주형  Cramér's V  0.085033
9   _1순위교통업종  범주형  Cramér's V  0.084260
10  _2순위쇼핑업종  범주형  Cramér's V  0.080923
11  _2순위교통업종  범주형  Cramér's V  0.067434
12  _1순위납부업종  범주형  Cramér's V  0.066615
13  _3순위교통업종  범주형  Cramér's V  0.059368
14  _3순위납부업종  범주형  Cramér's V  0.050341
15  _2순위납부업종  범주형  Cramér's V  0.031200

In [ ]:
pd.set_option('display.max_rows', 100)
display(result_df1)

                   변수   유형  계수종류          상관계수
0         _3순위업종_이용금액  수치형  Eta²  2.549372e-01
1         _2순위업종_이용금액  수치형  Eta²  2.429217e-01
2       _2순위쇼핑업종_이용금액  수치형  Eta²  2.387084e-01
3         _1순위업종_이용금액  수치형  Eta²  2.198912e-01
4       _3순위쇼핑업종_이용금액  수치형  Eta²  2.172726e-01
5              이용가맹점수  수치형  Eta²  2.157008e-01
6         쇼핑_도소매_이용금액  수치형  Eta²  2.048195e-01
7       _1순위교통업종_이용금액  수치형  Eta²  1.715343e-01
8          쇼핑_마트_이용금액  수치형  Eta²  1.575289e-01
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  1.560192e-01
10          교통_주유이용금액  수치형  Eta²  1.534422e-01
11      _1순위쇼핑업종_이용금액  수치형  Eta²  1.416423e-01
12      _2순위교통업종_이용금액  수치형  Eta²  1.264717e-01
13        쇼핑_온라인_이용금액  수치형  Eta²  1.251935e-01
14          교통_정비이용금액  수치형  Eta²  1.152910e-01
15       할부금액_3M_R12M  수치형  Eta²  1.146496e-01
16        쇼핑_편의점_이용금액  수치형  Eta²  1.108649e-01
17   할부금액_무이자_3M_R12M  수치형  Eta²  1.095503e-01
18      _3순위교통업종_이용금액  수치형  Eta²  1.079877e-01
19          납부_기타이용금액  수치형  Eta²  9.976501e-02
20       할부금액_6M_R12M  수치형  Eta²  9.011536e-02
21         쇼핑_기타_이용금액  수치형  Eta²  8.941263e-02
22            이용금액_해외  수치형  Eta²  8.759255e-02
23       할부건수_3M_R12M  수치형  Eta²  8.220689e-02
24      _1순위여유업종_이용금액  수치형  Eta²  8.201874e-02
25   할부금액_무이자_6M_R12M  수치형  Eta²  8.003808e-02
26   할부건수_무이자_3M_R12M  수치형  Eta²  7.990661e-02
27        쇼핑_백화점_이용금액  수치형  Eta²  7.842607e-02
28          교통_택시이용금액  수치형  Eta²  6.645548e-02
29          여유_운동이용금액  수치형  Eta²  6.070089e-02
30       할부건수_6M_R12M  수치형  Eta²  6.006017e-02
31      _1순위납부업종_이용금액  수치형  Eta²  5.668454e-02
32   할부건수_무이자_6M_R12M  수치형  Eta²  5.590561e-02
33      _2순위여유업종_이용금액  수치형  Eta²  4.788675e-02
34   할부금액_유이자_3M_R12M  수치형  Eta²  4.166154e-02
35      _2순위납부업종_이용금액  수치형  Eta²  4.044062e-02
36         납부_통신비이용금액  수치형  Eta²  3.997435e-02
37         납부_보험료이용금액  수치형  Eta²  3.406799e-02
38        교통_철도버스이용금액  수치형  Eta²  3.364627e-02
39          여유_숙박이용금액  수치형  Eta²  3.250516e-02
40        쇼핑_아울렛_이용금액  수치형  Eta²  3.197465e-02
41   할부건수_유이자_3M_R12M  수치형  Eta²  3.156948e-02
42   할부금액_유이자_6M_R12M  수치형  Eta²  2.964685e-02
43          여유_공연이용금액  수치형  Eta²  2.720280e-02
44      _3순위여유업종_이용금액  수치형  Eta²  2.183659e-02
45       교통_버스지하철이용금액  수치형  Eta²  2.157895e-02
46      _3순위납부업종_이용금액  수치형  Eta²  1.702915e-02
47          여유_기타이용금액  수치형  Eta²  1.634331e-02
48   할부건수_유이자_6M_R12M  수치형  Eta²  1.555705e-02
49      할부금액_12M_R12M  수치형  Eta²  1.368153e-02
50  할부금액_무이자_12M_R12M  수치형  Eta²  1.182850e-02
51          여유_항공이용금액  수치형  Eta²  9.683946e-03
52         여유_Pet이용금액  수치형  Eta²  8.378419e-03
53         납부_관리비이용금액  수치형  Eta²  6.938032e-03
54          여유_공원이용금액  수치형  Eta²  5.403499e-03
55  할부금액_유이자_12M_R12M  수치형  Eta²  5.388438e-03
56       납부_가스전기료이용금액  수치형  Eta²  5.189205e-03
57      할부건수_12M_R12M  수치형  Eta²  4.687290e-03
58   할부금액_부분_12M_R12M  수치형  Eta²  4.354411e-03
59  할부건수_무이자_12M_R12M  수치형  Eta²  2.828204e-03
60  할부건수_유이자_12M_R12M  수치형  Eta²  2.173066e-03
61      할부금액_14M_R12M  수치형  Eta²  3.384175e-04
62  할부금액_유이자_14M_R12M  수치형  Eta²  2.303228e-04
63  할부금액_무이자_14M_R12M  수치형  Eta²  1.495791e-04
64   할부건수_부분_12M_R12M  수치형  Eta²  7.045953e-05
65         교통_통행료이용금액  수치형  Eta²  4.721707e-05
66  할부건수_유이자_14M_R12M  수치형  Eta²  1.419732e-05
67      할부건수_14M_R12M  수치형  Eta²  1.375602e-05
68    할부금액_부분_6M_R12M  수치형  Eta²  2.446678e-06
69  할부건수_무이자_14M_R12M  수치형  Eta²  3.108322e-07
70   할부금액_부분_14M_R12M  수치형  Eta²  2.398594e-08

In [ ]:
result_df1['상관계수'] = result_df1['상관계수'].round(4)

In [ ]:
display(result_df1)

                   변수   유형  계수종류    상관계수
0         _3순위업종_이용금액  수치형  Eta²  0.2549
1         _2순위업종_이용금액  수치형  Eta²  0.2429
2       _2순위쇼핑업종_이용금액  수치형  Eta²  0.2387
3         _1순위업종_이용금액  수치형  Eta²  0.2199
4       _3순위쇼핑업종_이용금액  수치형  Eta²  0.2173
5              이용가맹점수  수치형  Eta²  0.2157
6         쇼핑_도소매_이용금액  수치형  Eta²  0.2048
7       _1순위교통업종_이용금액  수치형  Eta²  0.1715
8          쇼핑_마트_이용금액  수치형  Eta²  0.1575
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  0.1560
10          교통_주유이용금액  수치형  Eta²  0.1534
11      _1순위쇼핑업종_이용금액  수치형  Eta²  0.1416
12      _2순위교통업종_이용금액  수치형  Eta²  0.1265
13        쇼핑_온라인_이용금액  수치형  Eta²  0.1252
14          교통_정비이용금액  수치형  Eta²  0.1153
15       할부금액_3M_R12M  수치형  Eta²  0.1146
16        쇼핑_편의점_이용금액  수치형  Eta²  0.1109
17   할부금액_무이자_3M_R12M  수치형  Eta²  0.1096
18      _3순위교통업종_이용금액  수치형  Eta²  0.1080
19          납부_기타이용금액  수치형  Eta²  0.0998
20       할부금액_6M_R12M  수치형  Eta²  0.0901
21         쇼핑_기타_이용금액  수치형  Eta²  0.0894
22            이용금액_해외  수치형  Eta²  0.0876
23       할부건수_3M_R12M  수치형  Eta²  0.0822
24      _1순위여유업종_이용금액  수치형  Eta²  0.0820
25   할부금액_무이자_6M_R12M  수치형  Eta²  0.0800
26   할부건수_무이자_3M_R12M  수치형  Eta²  0.0799
27        쇼핑_백화점_이용금액  수치형  Eta²  0.0784
28          교통_택시이용금액  수치형  Eta²  0.0665
29          여유_운동이용금액  수치형  Eta²  0.0607
30       할부건수_6M_R12M  수치형  Eta²  0.0601
31      _1순위납부업종_이용금액  수치형  Eta²  0.0567
32   할부건수_무이자_6M_R12M  수치형  Eta²  0.0559
33      _2순위여유업종_이용금액  수치형  Eta²  0.0479
34   할부금액_유이자_3M_R12M  수치형  Eta²  0.0417
35      _2순위납부업종_이용금액  수치형  Eta²  0.0404
36         납부_통신비이용금액  수치형  Eta²  0.0400
37         납부_보험료이용금액  수치형  Eta²  0.0341
38        교통_철도버스이용금액  수치형  Eta²  0.0336
39          여유_숙박이용금액  수치형  Eta²  0.0325
40        쇼핑_아울렛_이용금액  수치형  Eta²  0.0320
41   할부건수_유이자_3M_R12M  수치형  Eta²  0.0316
42   할부금액_유이자_6M_R12M  수치형  Eta²  0.0296
43          여유_공연이용금액  수치형  Eta²  0.0272
44      _3순위여유업종_이용금액  수치형  Eta²  0.0218
45       교통_버스지하철이용금액  수치형  Eta²  0.0216
46      _3순위납부업종_이용금액  수치형  Eta²  0.0170
47          여유_기타이용금액  수치형  Eta²  0.0163
48   할부건수_유이자_6M_R12M  수치형  Eta²  0.0156
49      할부금액_12M_R12M  수치형  Eta²  0.0137
50  할부금액_무이자_12M_R12M  수치형  Eta²  0.0118
51          여유_항공이용금액  수치형  Eta²  0.0097
52         여유_Pet이용금액  수치형  Eta²  0.0084
53         납부_관리비이용금액  수치형  Eta²  0.0069
54          여유_공원이용금액  수치형  Eta²  0.0054
55  할부금액_유이자_12M_R12M  수치형  Eta²  0.0054
56       납부_가스전기료이용금액  수치형  Eta²  0.0052
57      할부건수_12M_R12M  수치형  Eta²  0.0047
58   할부금액_부분_12M_R12M  수치형  Eta²  0.0044
59  할부건수_무이자_12M_R12M  수치형  Eta²  0.0028
60  할부건수_유이자_12M_R12M  수치형  Eta²  0.0022
61      할부금액_14M_R12M  수치형  Eta²  0.0003
62  할부금액_유이자_14M_R12M  수치형  Eta²  0.0002
63  할부금액_무이자_14M_R12M  수치형  Eta²  0.0001
64   할부건수_부분_12M_R12M  수치형  Eta²  0.0001
65         교통_통행료이용금액  수치형  Eta²  0.0000
66  할부건수_유이자_14M_R12M  수치형  Eta²  0.0000
67      할부건수_14M_R12M  수치형  Eta²  0.0000
68    할부금액_부분_6M_R12M  수치형  Eta²  0.0000
69  할부건수_무이자_14M_R12M  수치형  Eta²  0.0000
70   할부금액_부분_14M_R12M  수치형  Eta²  0.0000

### corr 상관계수

In [ ]:
# all_df에서 기준년월, ID 컬럼은 제거한다.
all_df = all_df.drop(['기준년월','ID'], axis=1)

In [ ]:
cat_cols

['Segment',
 '_1순위업종',
 '_2순위업종',
 '_3순위업종',
 '_1순위쇼핑업종',
 '_2순위쇼핑업종',
 '_3순위쇼핑업종',
 '_1순위교통업종',
 '_2순위교통업종',
 '_3순위교통업종',
 '_1순위여유업종',
 '_2순위여유업종',
 '_3순위여유업종',
 '_1순위납부업종',
 '_2순위납부업종',
 '_3순위납부업종']

In [ ]:
# A가 가장 높은 등급일 것이라 추측하고 세그먼트만 LabelEncoder가 아닌 map으로 진행

segment_order = {'E': 0, 'D': 1, 'C': 2, 'B': 3, 'A': 4}
all_df['Segment_e'] = all_df['Segment'].map(segment_order)

In [ ]:
# 인코딩 진행
# 인코딩할 컬럼만 선택
encoder = LabelEncoder()
all_df[''] = encoder.fit_transform(all_df[''])
all_df[''] = encoder.fit_transform(all_df[''])
all_df[''] = encoder.fit_transform(all_df[''])
all_df[''] = encoder.fit_transform(all_df[''])
all_df[''] = encoder.fit_transform(all_df[''])

In [ ]:
print(all_df['Segment_e'].unique())

[1 0 2 4 3]

In [ ]:
# 비교할 종속변수
target = 'Segment_e'
# 결과를 담을 리스트
corr_result = []
# 반복
for col in num_cols:
    if col in all_df.columns:
        corr = all_df[col].corr(all_df[target])
        corr_result.append({'변수': col, '상관계수': corr})

# 데이터프레임으로 정리한다
result_df3 = pd.DataFrame(corr_result).sort_values(by='상관계수', key=abs, ascending=False).reset_index(drop=True)

display(result_df3)

                   변수      상관계수
0         _3순위업종_이용금액  0.504268
1         _2순위업종_이용금액  0.492209
2       _2순위쇼핑업종_이용금액  0.487364
3         _1순위업종_이용금액  0.468099
4       _3순위쇼핑업종_이용금액  0.464139
5              이용가맹점수  0.456553
6         쇼핑_도소매_이용금액  0.452097
7       _1순위교통업종_이용금액  0.408528
8          쇼핑_마트_이용금액  0.395007
9        쇼핑_슈퍼마켓_이용금액  0.390990
10          교통_주유이용금액  0.387756
11      _1순위쇼핑업종_이용금액  0.375679
12        쇼핑_온라인_이용금액  0.353185
13      _2순위교통업종_이용금액  0.350393
14          교통_정비이용금액  0.338576
15       할부금액_3M_R12M  0.334950
16      _3순위교통업종_이용금액  0.327502
17        쇼핑_편의점_이용금액  0.326543
18   할부금액_무이자_3M_R12M  0.323400
19          납부_기타이용금액  0.314270
20       할부금액_6M_R12M  0.295831
21         쇼핑_기타_이용금액  0.295248
22            이용금액_해외  0.294269
23      _1순위여유업종_이용금액  0.285466
24       할부건수_3M_R12M  0.281473
25        쇼핑_백화점_이용금액  0.279770
26   할부건수_무이자_3M_R12M  0.279451
27   할부금액_무이자_6M_R12M  0.279384
28          교통_택시이용금액  0.253612
29          여유_운동이용금액  0.245944
30       할부건수_6M_R12M  0.237502
31      _1순위납부업종_이용금액  0.230848
32   할부건수_무이자_6M_R12M  0.229298
33      _2순위여유업종_이용금액  0.209964
34      _2순위납부업종_이용금액  0.198603
35         납부_통신비이용금액  0.193360
36   할부금액_유이자_3M_R12M  0.183528
37        교통_철도버스이용금액  0.181839
38         납부_보험료이용금액  0.181590
39        쇼핑_아울렛_이용금액  0.177455
40   할부금액_유이자_6M_R12M  0.166809
41          여유_숙박이용금액  0.164041
42          여유_공연이용금액  0.163621
43   할부건수_유이자_3M_R12M  0.158301
44       교통_버스지하철이용금액  0.138894
45      _3순위여유업종_이용금액  0.134882
46      _3순위납부업종_이용금액  0.130278
47          여유_기타이용금액  0.126732
48   할부건수_유이자_6M_R12M  0.120181
49      할부금액_12M_R12M  0.112694
50  할부금액_무이자_12M_R12M  0.106619
51         여유_Pet이용금액  0.091433
52          여유_항공이용금액  0.086369
53         납부_관리비이용금액  0.080332
54          여유_공원이용금액  0.072424
55  할부금액_유이자_12M_R12M  0.070547
56       납부_가스전기료이용금액  0.068985
57      할부건수_12M_R12M  0.067000
58   할부금액_부분_12M_R12M  0.061985
59  할부건수_무이자_12M_R12M  0.052485
60  할부건수_유이자_12M_R12M  0.044294
61      할부금액_14M_R12M -0.015489
62  할부금액_유이자_14M_R12M -0.013086
63  할부금액_무이자_14M_R12M -0.008688
64   할부건수_부분_12M_R12M  0.007991
65         교통_통행료이용금액  0.006401
66  할부건수_유이자_14M_R12M  0.003506
67      할부건수_14M_R12M  0.003439
68    할부금액_부분_6M_R12M  0.000878
69  할부건수_무이자_14M_R12M -0.000517
70   할부금액_부분_14M_R12M -0.000063

In [ ]:
result_AK = pd.concat(
    [result_df1, result_df2],
    axis=0,
    ignore_index=True
)
display(result_AK)

                   변수   유형        계수종류      상관계수
0         _3순위업종_이용금액  수치형        Eta²  0.254900
1         _2순위업종_이용금액  수치형        Eta²  0.242900
2       _2순위쇼핑업종_이용금액  수치형        Eta²  0.238700
3         _1순위업종_이용금액  수치형        Eta²  0.219900
4       _3순위쇼핑업종_이용금액  수치형        Eta²  0.217300
5              이용가맹점수  수치형        Eta²  0.215700
6         쇼핑_도소매_이용금액  수치형        Eta²  0.204800
7       _1순위교통업종_이용금액  수치형        Eta²  0.171500
8          쇼핑_마트_이용금액  수치형        Eta²  0.157500
9        쇼핑_슈퍼마켓_이용금액  수치형        Eta²  0.156000
10          교통_주유이용금액  수치형        Eta²  0.153400
11      _1순위쇼핑업종_이용금액  수치형        Eta²  0.141600
12      _2순위교통업종_이용금액  수치형        Eta²  0.126500
13        쇼핑_온라인_이용금액  수치형        Eta²  0.125200
14          교통_정비이용금액  수치형        Eta²  0.115300
15       할부금액_3M_R12M  수치형        Eta²  0.114600
16        쇼핑_편의점_이용금액  수치형        Eta²  0.110900
17   할부금액_무이자_3M_R12M  수치형        Eta²  0.109600
18      _3순위교통업종_이용금액  수치형        Eta²  0.108000
19          납부_기타이용금액  수치형        Eta²  0.099800
20       할부금액_6M_R12M  수치형        Eta²  0.090100
21         쇼핑_기타_이용금액  수치형        Eta²  0.089400
22            이용금액_해외  수치형        Eta²  0.087600
23       할부건수_3M_R12M  수치형        Eta²  0.082200
24      _1순위여유업종_이용금액  수치형        Eta²  0.082000
25   할부금액_무이자_6M_R12M  수치형        Eta²  0.080000
26   할부건수_무이자_3M_R12M  수치형        Eta²  0.079900
27        쇼핑_백화점_이용금액  수치형        Eta²  0.078400
28          교통_택시이용금액  수치형        Eta²  0.066500
29          여유_운동이용금액  수치형        Eta²  0.060700
30       할부건수_6M_R12M  수치형        Eta²  0.060100
31      _1순위납부업종_이용금액  수치형        Eta²  0.056700
32   할부건수_무이자_6M_R12M  수치형        Eta²  0.055900
33      _2순위여유업종_이용금액  수치형        Eta²  0.047900
34   할부금액_유이자_3M_R12M  수치형        Eta²  0.041700
35      _2순위납부업종_이용금액  수치형        Eta²  0.040400
36         납부_통신비이용금액  수치형        Eta²  0.040000
37         납부_보험료이용금액  수치형        Eta²  0.034100
38        교통_철도버스이용금액  수치형        Eta²  0.033600
39          여유_숙박이용금액  수치형        Eta²  0.032500
40        쇼핑_아울렛_이용금액  수치형        Eta²  0.032000
41   할부건수_유이자_3M_R12M  수치형        Eta²  0.031600
42   할부금액_유이자_6M_R12M  수치형        Eta²  0.029600
43          여유_공연이용금액  수치형        Eta²  0.027200
44      _3순위여유업종_이용금액  수치형        Eta²  0.021800
45       교통_버스지하철이용금액  수치형        Eta²  0.021600
46      _3순위납부업종_이용금액  수치형        Eta²  0.017000
47          여유_기타이용금액  수치형        Eta²  0.016300
48   할부건수_유이자_6M_R12M  수치형        Eta²  0.015600
49      할부금액_12M_R12M  수치형        Eta²  0.013700
50  할부금액_무이자_12M_R12M  수치형        Eta²  0.011800
51          여유_항공이용금액  수치형        Eta²  0.009700
52         여유_Pet이용금액  수치형        Eta²  0.008400
53         납부_관리비이용금액  수치형        Eta²  0.006900
54          여유_공원이용금액  수치형        Eta²  0.005400
55  할부금액_유이자_12M_R12M  수치형        Eta²  0.005400
56       납부_가스전기료이용금액  수치형        Eta²  0.005200
57      할부건수_12M_R12M  수치형        Eta²  0.004700
58   할부금액_부분_12M_R12M  수치형        Eta²  0.004400
59  할부건수_무이자_12M_R12M  수치형        Eta²  0.002800
60  할부건수_유이자_12M_R12M  수치형        Eta²  0.002200
61      할부금액_14M_R12M  수치형        Eta²  0.000300
62  할부금액_유이자_14M_R12M  수치형        Eta²  0.000200
63  할부금액_무이자_14M_R12M  수치형        Eta²  0.000100
64   할부건수_부분_12M_R12M  수치형        Eta²  0.000100
65         교통_통행료이용금액  수치형        Eta²  0.000000
66  할부건수_유이자_14M_R12M  수치형        Eta²  0.000000
67      할부건수_14M_R12M  수치형        Eta²  0.000000
68    할부금액_부분_6M_R12M  수치형        Eta²  0.000000
69  할부건수_무이자_14M_R12M  수치형        Eta²  0.000000
70   할부금액_부분_14M_R12M  수치형        Eta²  0.000000
71           _2순위여유업종  범주형  Cramér's V  0.131715
72             _1순위업종  범주형  Cramér's V  0.116062
73           _3순위여유업종  범주형  Cramér's V  0.105205
74             _2순위업종  범주형  Cramér's V  0.102366
75           _3순위쇼핑업종  범주형  Cramér's V  0.097754
76           _1순위쇼핑업종  범주형  Cramér's V  0.097296
77             _3순위업종  범주형  Cramér's V  0.091734
78           _1순위여유업종  범주형  Cramér's V  0.085033
79           _1순위교통업종  범주형  Cramér's V  0.084260
80           _2순위쇼핑업종  범주형  Cramér's V  0.080923
81           _2순위교통업종  범주형  Cramér's V  0.067434
82           _1순위납부업종  범주형  Cramér's V  0.066615
83           _3순위교통업종  범주형  Cramér's V  0.059368
84           _3순위납부업종  범주형  Cramér's V  0.050341
85           _2순위납부업종  범주형  Cramér's V  0.031200

### A,B 와 CDE나누기

In [33]:
all_df.columns

Index(['기준년월', 'ID', 'Segment', '기준년월', 'ID', '이용가맹점수', '이용금액_해외',
       '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액',
       '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액',
       '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액',
       '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액',
       '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_가스전기료이용금액',
       '납부_보험료이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종',
       '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액',
       '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종',
       '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종',
       '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종',
       '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종',
       '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종',
       '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M',
       '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M',
       '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M',
       '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M',
       '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M',
       '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M',
       '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M',
       '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_12M_R12M',
       '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M'],
      dtype='object')

In [57]:
# A, B 클래스만 필터링
ab_df = all_df[all_df['Segment'].isin(['A', 'B'])]

# C, D, E 클래스만 필터링
cde_df = all_df[all_df['Segment'].isin(['C', 'D', 'E'])]

In [37]:
ab_df

,Segment,기준년월,ID,이용가맹점수,이용금액_해외,쇼핑_도소매_이용금액,쇼핑_백화점_이용금액,쇼핑_마트_이용금액,쇼핑_슈퍼마켓_이용금액,쇼핑_편의점_이용금액,...,할부금액_무이자_12M_R12M,할부금액_무이자_14M_R12M,할부건수_부분_3M_R12M,할부건수_부분_6M_R12M,할부건수_부분_12M_R12M,할부건수_부분_14M_R12M,할부금액_부분_3M_R12M,할부금액_부분_6M_R12M,할부금액_부분_12M_R12M,할부금액_부분_14M_R12M
2898,A,201807,TRAIN_002898,43,0,3742,0,0,1083,381,...,0,0,0,0,0,0,0,0,0,0
5253,A,201807,TRAIN_005253,28,0,2216,986,1464,700,210,...,0,0,0,0,0,0,0,0,0,0
8128,A,201807,TRAIN_008128,80,1761,2272,975,0,894,519,...,4374,30882,0,0,0,0,0,0,0,0
10808,A,201807,TRAIN_010808,82,2716,3767,1297,2405,1364,447,...,0,0,0,0,0,0,0,0,0,0
14951,A,201807,TRAIN_014951,67,3490,6441,1619,1903,665,152,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2376373,A,201812,TRAIN_376373,86,1722,4897,1604,0,1055,490,...,0,0,0,0,0,0,0,0,0,0
2378479,A,201812,TRAIN_378479,102,1378,3426,1563,3279,1302,930,...,0,0,0,0,0,0,0,0,0,0
2390620,B,201812,TRAIN_390620,6,0,1425,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2393027,A,201812,TRAIN_393027,69,0,3641,0,2286,684,340,...,0,0,0,0,0,0,0,0,0,0
2393888,A,201812,TRAIN_393888,66,0,3316,0,1488,1069,494,...,3893,0,0,0,0,0,0,0,0,0

In [ ]:
cde_df

,ID,Segment,_1순위업종,_2순위업종,_3순위업종,_1순위쇼핑업종,_2순위쇼핑업종,_3순위쇼핑업종,_1순위교통업종,_2순위교통업종,...,할부건수_무이자_12M_R12M,할부건수_무이자_14M_R12M,할부금액_무이자_3M_R12M,할부금액_무이자_6M_R12M,할부금액_무이자_12M_R12M,할부금액_무이자_14M_R12M,할부건수_부분_12M_R12M,할부금액_부분_6M_R12M,할부금액_부분_12M_R12M,할부금액_부분_14M_R12M
0,TRAIN_000000,D,납부,쇼핑,사교활동,쇼핑기타,None,None,택시,버스지하철,...,0,0,1314,4514,0,0,0,0,0,0
1,TRAIN_000001,E,쇼핑,납부,교통,도소매,슈퍼마켓,편의점,주유,철도버스,...,0,0,2076,0,0,0,0,0,0,0
2,TRAIN_000002,C,쇼핑,사교활동,교통,온라인,도소매,마트,주유,None,...,0,0,0,10561,0,0,0,0,0,0
3,TRAIN_000003,D,쇼핑,납부,사교활동,마트,슈퍼마켓,None,택시,None,...,0,0,12098,0,0,0,0,0,0,0
4,TRAIN_000004,E,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,TRAIN_399995,E,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2399996,TRAIN_399996,D,쇼핑,의료,사교활동,도소매,슈퍼마켓,쇼핑기타,버스지하철,택시,...,0,0,1888,0,0,0,0,0,0,0
2399997,TRAIN_399997,C,쇼핑,사교활동,교통,온라인,슈퍼마켓,쇼핑기타,주유,정비,...,0,0,27617,0,0,0,0,0,0,0
2399998,TRAIN_399998,E,None,None,None,None,None,None,None,None,...,0,0,0,0,0,0,0,0,0,0
2399999,TRAIN_399999,E,쇼핑,의료,사교활동,백화점,None,None,None,None,...,0,0,13847,4309,0,0,0,0,0,0

In [41]:
anova = []
chi = []

for col in ab_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = ab_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(ab_df[col], ab_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df11 = pd.DataFrame(anova)
result_df12 = pd.DataFrame(chi)
result_df11 = result_df11.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df12 = result_df12.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df11)
display(result_df12)

NameError: name 'num_cols' is not defined

In [ ]:
anova = []
chi = []

for col in cde_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = cde_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(cde_df[col], cde_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df21 = pd.DataFrame(anova)
result_df22 = pd.DataFrame(chi)
result_df21 = result_df21.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df22 = result_df22.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df21)
display(result_df22)

                   변수   유형  계수종류          상관계수
0         _3순위업종_이용금액  수치형  Eta²  2.509779e-01
1         _2순위업종_이용금액  수치형  Eta²  2.390016e-01
2       _2순위쇼핑업종_이용금액  수치형  Eta²  2.345792e-01
3       _3순위쇼핑업종_이용금액  수치형  Eta²  2.150143e-01
4         _1순위업종_이용금액  수치형  Eta²  2.150013e-01
5              이용가맹점수  수치형  Eta²  2.143248e-01
6         쇼핑_도소매_이용금액  수치형  Eta²  1.998271e-01
7       _1순위교통업종_이용금액  수치형  Eta²  1.705684e-01
8          쇼핑_마트_이용금액  수치형  Eta²  1.560530e-01
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  1.546159e-01
10          교통_주유이용금액  수치형  Eta²  1.524349e-01
11      _1순위쇼핑업종_이용금액  수치형  Eta²  1.385844e-01
12      _2순위교통업종_이용금액  수치형  Eta²  1.256268e-01
13        쇼핑_온라인_이용금액  수치형  Eta²  1.223753e-01
14          교통_정비이용금액  수치형  Eta²  1.141834e-01
15        쇼핑_편의점_이용금액  수치형  Eta²  1.102432e-01
16       할부금액_3M_R12M  수치형  Eta²  1.080390e-01
17      _3순위교통업종_이용금액  수치형  Eta²  1.066997e-01
18   할부금액_무이자_3M_R12M  수치형  Eta²  9.984772e-02
19          납부_기타이용금액  수치형  Eta²  9.555046e-02
20         쇼핑_기타_이용금액  수치형  Eta²  8.835715e-02
21       할부금액_6M_R12M  수치형  Eta²  8.835400e-02
22            이용금액_해외  수치형  Eta²  8.356876e-02
23       할부건수_3M_R12M  수치형  Eta²  8.017678e-02
24      _1순위여유업종_이용금액  수치형  Eta²  7.876562e-02
25   할부금액_무이자_6M_R12M  수치형  Eta²  7.785275e-02
26   할부건수_무이자_3M_R12M  수치형  Eta²  7.677304e-02
27        쇼핑_백화점_이용금액  수치형  Eta²  7.611468e-02
28          교통_택시이용금액  수치형  Eta²  6.573702e-02
29       할부건수_6M_R12M  수치형  Eta²  5.950171e-02
30          여유_운동이용금액  수치형  Eta²  5.860081e-02
31      _1순위납부업종_이용금액  수치형  Eta²  5.640921e-02
32   할부건수_무이자_6M_R12M  수치형  Eta²  5.526509e-02
33      _2순위여유업종_이용금액  수치형  Eta²  4.247864e-02
34   할부금액_유이자_3M_R12M  수치형  Eta²  4.165469e-02
35      _2순위납부업종_이용금액  수치형  Eta²  4.012918e-02
36         납부_통신비이용금액  수치형  Eta²  3.971371e-02
37         납부_보험료이용금액  수치형  Eta²  3.380238e-02
38        교통_철도버스이용금액  수치형  Eta²  3.329975e-02
39        쇼핑_아울렛_이용금액  수치형  Eta²  3.159952e-02
40   할부건수_유이자_3M_R12M  수치형  Eta²  3.156688e-02
41   할부금액_유이자_6M_R12M  수치형  Eta²  2.957020e-02
42          여유_숙박이용금액  수치형  Eta²  2.697851e-02
43          여유_공연이용금액  수치형  Eta²  2.666505e-02
44       교통_버스지하철이용금액  수치형  Eta²  2.153526e-02
45      _3순위여유업종_이용금액  수치형  Eta²  1.759459e-02
46      _3순위납부업종_이용금액  수치형  Eta²  1.681839e-02
47          여유_기타이용금액  수치형  Eta²  1.596312e-02
48   할부건수_유이자_6M_R12M  수치형  Eta²  1.553174e-02
49      할부금액_12M_R12M  수치형  Eta²  1.363950e-02
50  할부금액_무이자_12M_R12M  수치형  Eta²  1.163393e-02
51         여유_Pet이용금액  수치형  Eta²  8.297323e-03
52          여유_항공이용금액  수치형  Eta²  7.299869e-03
53         납부_관리비이용금액  수치형  Eta²  6.937200e-03
54  할부금액_유이자_12M_R12M  수치형  Eta²  5.387735e-03
55          여유_공원이용금액  수치형  Eta²  5.382196e-03
56       납부_가스전기료이용금액  수치형  Eta²  5.153048e-03
57      할부건수_12M_R12M  수치형  Eta²  4.620539e-03
58   할부금액_부분_12M_R12M  수치형  Eta²  4.344692e-03
59  할부건수_무이자_12M_R12M  수치형  Eta²  2.665075e-03
60  할부건수_유이자_12M_R12M  수치형  Eta²  2.173743e-03
61      할부금액_14M_R12M  수치형  Eta²  3.208396e-04
62  할부금액_유이자_14M_R12M  수치형  Eta²  2.292242e-04
63  할부금액_무이자_14M_R12M  수치형  Eta²  1.037683e-04
64   할부건수_부분_12M_R12M  수치형  Eta²  7.039192e-05
65         교통_통행료이용금액  수치형  Eta²  4.720202e-05
66  할부건수_유이자_14M_R12M  수치형  Eta²  1.417360e-05
67      할부건수_14M_R12M  수치형  Eta²  1.373180e-05
68    할부금액_부분_6M_R12M  수치형  Eta²  2.446485e-06
69  할부건수_무이자_14M_R12M  수치형  Eta²  3.102507e-07
70   할부금액_부분_14M_R12M  수치형  Eta²  8.496610e-09
71               기준년월  수치형  Eta²  0.000000e+00

          변수   유형        계수종류      상관계수
0         ID  범주형  Cramér's V  1.000000
1   _2순위여유업종  범주형  Cramér's V  0.173881
2     _1순위업종  범주형  Cramér's V  0.163681
3     _2순위업종  범주형  Cramér's V  0.143127
4   _1순위쇼핑업종  범주형  Cramér's V  0.137188
5   _3순위쇼핑업종  범주형  Cramér's V  0.136489
6   _3순위여유업종  범주형  Cramér's V  0.134254
7     _3순위업종  범주형  Cramér's V  0.127779
8   _1순위교통업종  범주형  Cramér's V  0.118610
9   _1순위여유업종  범주형  Cramér's V  0.113846
10  _2순위쇼핑업종  범주형  Cramér's V  0.113195
11  _2순위교통업종  범주형  Cramér's V  0.094968
12  _1순위납부업종  범주형  Cramér's V  0.094032
13  _3순위교통업종  범주형  Cramér's V  0.083709
14  _3순위납부업종  범주형  Cramér's V  0.059999
15  _2순위납부업종  범주형  Cramér's V  0.042870

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
result_df1['상관계수'] = result_df1['상관계수'].round(4)
result_df11['상관계수'] = result_df11['상관계수'].round(4)
result_df21['상관계수'] = result_df21['상관계수'].round(4)

In [ ]:
result_df1

                   변수   유형  계수종류    상관계수
0         _3순위업종_이용금액  수치형  Eta²  0.2549
1         _2순위업종_이용금액  수치형  Eta²  0.2429
2       _2순위쇼핑업종_이용금액  수치형  Eta²  0.2387
3         _1순위업종_이용금액  수치형  Eta²  0.2199
4       _3순위쇼핑업종_이용금액  수치형  Eta²  0.2173
5              이용가맹점수  수치형  Eta²  0.2157
6         쇼핑_도소매_이용금액  수치형  Eta²  0.2048
7       _1순위교통업종_이용금액  수치형  Eta²  0.1715
8          쇼핑_마트_이용금액  수치형  Eta²  0.1575
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  0.1560
10          교통_주유이용금액  수치형  Eta²  0.1534
11      _1순위쇼핑업종_이용금액  수치형  Eta²  0.1416
12      _2순위교통업종_이용금액  수치형  Eta²  0.1265
13        쇼핑_온라인_이용금액  수치형  Eta²  0.1252
14          교통_정비이용금액  수치형  Eta²  0.1153
15       할부금액_3M_R12M  수치형  Eta²  0.1146
16        쇼핑_편의점_이용금액  수치형  Eta²  0.1109
17   할부금액_무이자_3M_R12M  수치형  Eta²  0.1096
18      _3순위교통업종_이용금액  수치형  Eta²  0.1080
19          납부_기타이용금액  수치형  Eta²  0.0998
20       할부금액_6M_R12M  수치형  Eta²  0.0901
21         쇼핑_기타_이용금액  수치형  Eta²  0.0894
22            이용금액_해외  수치형  Eta²  0.0876
23       할부건수_3M_R12M  수치형  Eta²  0.0822
24      _1순위여유업종_이용금액  수치형  Eta²  0.0820
25   할부금액_무이자_6M_R12M  수치형  Eta²  0.0800
26   할부건수_무이자_3M_R12M  수치형  Eta²  0.0799
27        쇼핑_백화점_이용금액  수치형  Eta²  0.0784
28          교통_택시이용금액  수치형  Eta²  0.0665
29          여유_운동이용금액  수치형  Eta²  0.0607
30       할부건수_6M_R12M  수치형  Eta²  0.0601
31      _1순위납부업종_이용금액  수치형  Eta²  0.0567
32   할부건수_무이자_6M_R12M  수치형  Eta²  0.0559
33      _2순위여유업종_이용금액  수치형  Eta²  0.0479
34   할부금액_유이자_3M_R12M  수치형  Eta²  0.0417
35      _2순위납부업종_이용금액  수치형  Eta²  0.0404
36         납부_통신비이용금액  수치형  Eta²  0.0400
37         납부_보험료이용금액  수치형  Eta²  0.0341
38        교통_철도버스이용금액  수치형  Eta²  0.0336
39          여유_숙박이용금액  수치형  Eta²  0.0325
40        쇼핑_아울렛_이용금액  수치형  Eta²  0.0320
41   할부건수_유이자_3M_R12M  수치형  Eta²  0.0316
42   할부금액_유이자_6M_R12M  수치형  Eta²  0.0296
43          여유_공연이용금액  수치형  Eta²  0.0272
44      _3순위여유업종_이용금액  수치형  Eta²  0.0218
45       교통_버스지하철이용금액  수치형  Eta²  0.0216
46      _3순위납부업종_이용금액  수치형  Eta²  0.0170
47          여유_기타이용금액  수치형  Eta²  0.0163
48   할부건수_유이자_6M_R12M  수치형  Eta²  0.0156
49      할부금액_12M_R12M  수치형  Eta²  0.0137
50  할부금액_무이자_12M_R12M  수치형  Eta²  0.0118
51          여유_항공이용금액  수치형  Eta²  0.0097
52         여유_Pet이용금액  수치형  Eta²  0.0084
53         납부_관리비이용금액  수치형  Eta²  0.0069
54          여유_공원이용금액  수치형  Eta²  0.0054
55  할부금액_유이자_12M_R12M  수치형  Eta²  0.0054
56       납부_가스전기료이용금액  수치형  Eta²  0.0052
57      할부건수_12M_R12M  수치형  Eta²  0.0047
58   할부금액_부분_12M_R12M  수치형  Eta²  0.0044
59  할부건수_무이자_12M_R12M  수치형  Eta²  0.0028
60  할부건수_유이자_12M_R12M  수치형  Eta²  0.0022
61      할부금액_14M_R12M  수치형  Eta²  0.0003
62  할부금액_유이자_14M_R12M  수치형  Eta²  0.0002
63  할부금액_무이자_14M_R12M  수치형  Eta²  0.0001
64   할부건수_부분_12M_R12M  수치형  Eta²  0.0001
65         교통_통행료이용금액  수치형  Eta²  0.0000
66  할부건수_유이자_14M_R12M  수치형  Eta²  0.0000
67      할부건수_14M_R12M  수치형  Eta²  0.0000
68    할부금액_부분_6M_R12M  수치형  Eta²  0.0000
69  할부건수_무이자_14M_R12M  수치형  Eta²  0.0000
70   할부금액_부분_14M_R12M  수치형  Eta²  0.0000
71               기준년월  수치형  Eta²  0.0000

In [ ]:
result_df1

                   변수   유형  계수종류    상관계수
0         _3순위업종_이용금액  수치형  Eta²  0.2549
1         _2순위업종_이용금액  수치형  Eta²  0.2429
2       _2순위쇼핑업종_이용금액  수치형  Eta²  0.2387
3         _1순위업종_이용금액  수치형  Eta²  0.2199
4       _3순위쇼핑업종_이용금액  수치형  Eta²  0.2173
5              이용가맹점수  수치형  Eta²  0.2157
6         쇼핑_도소매_이용금액  수치형  Eta²  0.2048
7       _1순위교통업종_이용금액  수치형  Eta²  0.1715
8          쇼핑_마트_이용금액  수치형  Eta²  0.1575
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  0.1560
10          교통_주유이용금액  수치형  Eta²  0.1534
11      _1순위쇼핑업종_이용금액  수치형  Eta²  0.1416
12      _2순위교통업종_이용금액  수치형  Eta²  0.1265
13        쇼핑_온라인_이용금액  수치형  Eta²  0.1252
14          교통_정비이용금액  수치형  Eta²  0.1153
15       할부금액_3M_R12M  수치형  Eta²  0.1146
16        쇼핑_편의점_이용금액  수치형  Eta²  0.1109
17   할부금액_무이자_3M_R12M  수치형  Eta²  0.1096
18      _3순위교통업종_이용금액  수치형  Eta²  0.1080
19          납부_기타이용금액  수치형  Eta²  0.0998
20       할부금액_6M_R12M  수치형  Eta²  0.0901
21         쇼핑_기타_이용금액  수치형  Eta²  0.0894
22            이용금액_해외  수치형  Eta²  0.0876
23       할부건수_3M_R12M  수치형  Eta²  0.0822
24      _1순위여유업종_이용금액  수치형  Eta²  0.0820
25   할부금액_무이자_6M_R12M  수치형  Eta²  0.0800
26   할부건수_무이자_3M_R12M  수치형  Eta²  0.0799
27        쇼핑_백화점_이용금액  수치형  Eta²  0.0784
28          교통_택시이용금액  수치형  Eta²  0.0665
29          여유_운동이용금액  수치형  Eta²  0.0607
30       할부건수_6M_R12M  수치형  Eta²  0.0601
31      _1순위납부업종_이용금액  수치형  Eta²  0.0567
32   할부건수_무이자_6M_R12M  수치형  Eta²  0.0559
33      _2순위여유업종_이용금액  수치형  Eta²  0.0479
34   할부금액_유이자_3M_R12M  수치형  Eta²  0.0417
35      _2순위납부업종_이용금액  수치형  Eta²  0.0404
36         납부_통신비이용금액  수치형  Eta²  0.0400
37         납부_보험료이용금액  수치형  Eta²  0.0341
38        교통_철도버스이용금액  수치형  Eta²  0.0336
39          여유_숙박이용금액  수치형  Eta²  0.0325
40        쇼핑_아울렛_이용금액  수치형  Eta²  0.0320
41   할부건수_유이자_3M_R12M  수치형  Eta²  0.0316
42   할부금액_유이자_6M_R12M  수치형  Eta²  0.0296
43          여유_공연이용금액  수치형  Eta²  0.0272
44      _3순위여유업종_이용금액  수치형  Eta²  0.0218
45       교통_버스지하철이용금액  수치형  Eta²  0.0216
46      _3순위납부업종_이용금액  수치형  Eta²  0.0170
47          여유_기타이용금액  수치형  Eta²  0.0163
48   할부건수_유이자_6M_R12M  수치형  Eta²  0.0156
49      할부금액_12M_R12M  수치형  Eta²  0.0137
50  할부금액_무이자_12M_R12M  수치형  Eta²  0.0118
51          여유_항공이용금액  수치형  Eta²  0.0097
52         여유_Pet이용금액  수치형  Eta²  0.0084
53         납부_관리비이용금액  수치형  Eta²  0.0069
54          여유_공원이용금액  수치형  Eta²  0.0054
55  할부금액_유이자_12M_R12M  수치형  Eta²  0.0054
56       납부_가스전기료이용금액  수치형  Eta²  0.0052
57      할부건수_12M_R12M  수치형  Eta²  0.0047
58   할부금액_부분_12M_R12M  수치형  Eta²  0.0044
59  할부건수_무이자_12M_R12M  수치형  Eta²  0.0028
60  할부건수_유이자_12M_R12M  수치형  Eta²  0.0022
61      할부금액_14M_R12M  수치형  Eta²  0.0003
62  할부금액_유이자_14M_R12M  수치형  Eta²  0.0002
63  할부금액_무이자_14M_R12M  수치형  Eta²  0.0001
64   할부건수_부분_12M_R12M  수치형  Eta²  0.0001
65         교통_통행료이용금액  수치형  Eta²  0.0000
66  할부건수_유이자_14M_R12M  수치형  Eta²  0.0000
67      할부건수_14M_R12M  수치형  Eta²  0.0000
68    할부금액_부분_6M_R12M  수치형  Eta²  0.0000
69  할부건수_무이자_14M_R12M  수치형  Eta²  0.0000
70   할부금액_부분_14M_R12M  수치형  Eta²  0.0000
71               기준년월  수치형  Eta²  0.0000

In [ ]:
result_df21

                   변수   유형  계수종류    상관계수
0         _3순위업종_이용금액  수치형  Eta²  0.2510
1         _2순위업종_이용금액  수치형  Eta²  0.2390
2       _2순위쇼핑업종_이용금액  수치형  Eta²  0.2346
3       _3순위쇼핑업종_이용금액  수치형  Eta²  0.2150
4         _1순위업종_이용금액  수치형  Eta²  0.2150
5              이용가맹점수  수치형  Eta²  0.2143
6         쇼핑_도소매_이용금액  수치형  Eta²  0.1998
7       _1순위교통업종_이용금액  수치형  Eta²  0.1706
8          쇼핑_마트_이용금액  수치형  Eta²  0.1561
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  0.1546
10          교통_주유이용금액  수치형  Eta²  0.1524
11      _1순위쇼핑업종_이용금액  수치형  Eta²  0.1386
12      _2순위교통업종_이용금액  수치형  Eta²  0.1256
13        쇼핑_온라인_이용금액  수치형  Eta²  0.1224
14          교통_정비이용금액  수치형  Eta²  0.1142
15        쇼핑_편의점_이용금액  수치형  Eta²  0.1102
16       할부금액_3M_R12M  수치형  Eta²  0.1080
17      _3순위교통업종_이용금액  수치형  Eta²  0.1067
18   할부금액_무이자_3M_R12M  수치형  Eta²  0.0998
19          납부_기타이용금액  수치형  Eta²  0.0956
20         쇼핑_기타_이용금액  수치형  Eta²  0.0884
21       할부금액_6M_R12M  수치형  Eta²  0.0884
22            이용금액_해외  수치형  Eta²  0.0836
23       할부건수_3M_R12M  수치형  Eta²  0.0802
24      _1순위여유업종_이용금액  수치형  Eta²  0.0788
25   할부금액_무이자_6M_R12M  수치형  Eta²  0.0779
26   할부건수_무이자_3M_R12M  수치형  Eta²  0.0768
27        쇼핑_백화점_이용금액  수치형  Eta²  0.0761
28          교통_택시이용금액  수치형  Eta²  0.0657
29       할부건수_6M_R12M  수치형  Eta²  0.0595
30          여유_운동이용금액  수치형  Eta²  0.0586
31      _1순위납부업종_이용금액  수치형  Eta²  0.0564
32   할부건수_무이자_6M_R12M  수치형  Eta²  0.0553
33      _2순위여유업종_이용금액  수치형  Eta²  0.0425
34   할부금액_유이자_3M_R12M  수치형  Eta²  0.0417
35      _2순위납부업종_이용금액  수치형  Eta²  0.0401
36         납부_통신비이용금액  수치형  Eta²  0.0397
37         납부_보험료이용금액  수치형  Eta²  0.0338
38        교통_철도버스이용금액  수치형  Eta²  0.0333
39        쇼핑_아울렛_이용금액  수치형  Eta²  0.0316
40   할부건수_유이자_3M_R12M  수치형  Eta²  0.0316
41   할부금액_유이자_6M_R12M  수치형  Eta²  0.0296
42          여유_숙박이용금액  수치형  Eta²  0.0270
43          여유_공연이용금액  수치형  Eta²  0.0267
44       교통_버스지하철이용금액  수치형  Eta²  0.0215
45      _3순위여유업종_이용금액  수치형  Eta²  0.0176
46      _3순위납부업종_이용금액  수치형  Eta²  0.0168
47          여유_기타이용금액  수치형  Eta²  0.0160
48   할부건수_유이자_6M_R12M  수치형  Eta²  0.0155
49      할부금액_12M_R12M  수치형  Eta²  0.0136
50  할부금액_무이자_12M_R12M  수치형  Eta²  0.0116
51         여유_Pet이용금액  수치형  Eta²  0.0083
52          여유_항공이용금액  수치형  Eta²  0.0073
53         납부_관리비이용금액  수치형  Eta²  0.0069
54  할부금액_유이자_12M_R12M  수치형  Eta²  0.0054
55          여유_공원이용금액  수치형  Eta²  0.0054
56       납부_가스전기료이용금액  수치형  Eta²  0.0052
57      할부건수_12M_R12M  수치형  Eta²  0.0046
58   할부금액_부분_12M_R12M  수치형  Eta²  0.0043
59  할부건수_무이자_12M_R12M  수치형  Eta²  0.0027
60  할부건수_유이자_12M_R12M  수치형  Eta²  0.0022
61      할부금액_14M_R12M  수치형  Eta²  0.0003
62  할부금액_유이자_14M_R12M  수치형  Eta²  0.0002
63  할부금액_무이자_14M_R12M  수치형  Eta²  0.0001
64   할부건수_부분_12M_R12M  수치형  Eta²  0.0001
65         교통_통행료이용금액  수치형  Eta²  0.0000
66  할부건수_유이자_14M_R12M  수치형  Eta²  0.0000
67      할부건수_14M_R12M  수치형  Eta²  0.0000
68    할부금액_부분_6M_R12M  수치형  Eta²  0.0000
69  할부건수_무이자_14M_R12M  수치형  Eta²  0.0000
70   할부금액_부분_14M_R12M  수치형  Eta²  0.0000
71               기준년월  수치형  Eta²  0.0000

In [ ]:
ab_df.to_parquet('승인매출ab_df3-2.parquet', index=True)
cde_df.to_parquet('승인매출cde_df3-2.parquet', index=True)
result_df11.to_parquet('승인매출ab_df3-2_설명력.parquet', index=True)
result_df21.to_parquet('승인매출cde_df3-2_설명력.parquet', index=True)

In [38]:
ab_df.to_parquet('승인매출ab_df3-2.parquet', index=False)
cde_df.to_parquet('승인매출cde_df3-2.parquet', index=False)

In [75]:
from scipy.stats import ttest_ind
def cohen_d(x, y):
    """두 그룹 간 효과 크기(Cohen's d) 계산"""
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    pooled_std = np.sqrt(((nx - 1)*x.std()**2 + (ny - 1)*y.std()**2) / dof)
    return (x.mean() - y.mean()) / pooled_std

def ttest_ab_multiple_verbose_abs_sorted(df, feature_cols):
    """
    A vs B 그룹 간 연속형 변수들에 대해 t-test, p-value, Cohen's d, 유의성 표시 포함한 결과 반환
    Cohen's d 절댓값 기준 내림차순 정렬
    """
    results = []

    for col in feature_cols:
        group_a = df[df['Segment'] == 'A'][col].dropna()
        group_b = df[df['Segment'] == 'B'][col].dropna()

        t_stat, p_val = ttest_ind(group_a, group_b, equal_var=False)
        d = cohen_d(group_a, group_b)

        # 유의성 표시
        if p_val < 0.001:
            sig = '***'
        elif p_val < 0.01:
            sig = '**'
        elif p_val < 0.05:
            sig = '*'
        else:
            sig = 'ns'

        results.append({
            'feature': col,
            't-statistic': round(t_stat, 4),
            'p-value': round(p_val, 4),
            'Cohen\'s d': round(d, 4),
            'abs(Cohen\'s d)': abs(round(d, 4)),
            'significance': sig
        })

    df_result = pd.DataFrame(results)
    df_result = df_result.sort_values('abs(Cohen\'s d)', ascending=False).reset_index(drop=True)
    df_result = df_result.drop(columns=['abs(Cohen\'s d)'])  # 필요 없으면 제거

    return df_result

In [79]:
ttest_results = ttest_ab_multiple_verbose_abs_sorted(ab_df, num_cols)
ttest_results

/tmp/ipython-input-75-3725380163.py:7: RuntimeWarning: invalid value encountered in scalar divide
  return (x.mean() - y.mean()) / pooled_std

              feature  t-statistic  p-value  Cohen's d significance
0        할부건수_3M_R12M      -9.9951      0.0    -0.8431          ***
1    할부건수_무이자_3M_R12M      -9.9617      0.0    -0.8387          ***
2        할부금액_3M_R12M      -8.3124      0.0    -0.6618          ***
3    할부금액_무이자_3M_R12M      -8.2449      0.0    -0.6521          ***
4    할부건수_무이자_6M_R12M      -4.3309      0.0    -0.4452          ***
..                ...          ...      ...        ...          ...
66  할부건수_유이자_14M_R12M          NaN      NaN        NaN           ns
67  할부건수_무이자_14M_R12M          NaN      NaN        NaN           ns
68   할부건수_부분_12M_R12M          NaN      NaN        NaN           ns
69    할부금액_부분_6M_R12M          NaN      NaN        NaN           ns
70   할부금액_부분_14M_R12M          NaN      NaN        NaN           ns

[71 rows x 5 columns]

In [80]:

pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² / t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan

In [84]:
def effect_sizes(df):
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            group1 = data[data['Segment'] == data['Segment'].unique()[0]][col]
            group2 = data[data['Segment'] == data['Segment'].unique()[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)

    return result_df1, result_df2

In [83]:
result1, result2 = effect_sizes(ab_df)
display(result1)
display(result2)

                   변수   유형  계수종류    상관계수
0        할부건수_3M_R12M  수치형  Eta² 0.08230
1    할부건수_무이자_3M_R12M  수치형  Eta² 0.08179
2        할부금액_3M_R12M  수치형  Eta² 0.05840
3    할부금액_무이자_3M_R12M  수치형  Eta² 0.05751
4   할부금액_유이자_12M_R12M  수치형  Eta² 0.02655
..                ...  ...   ...     ...
75   할부건수_부분_12M_R12M  수치형  Eta²     NaN
76   할부건수_부분_14M_R12M  수치형  Eta²     NaN
77    할부금액_부분_3M_R12M  수치형  Eta²     NaN
78    할부금액_부분_6M_R12M  수치형  Eta²     NaN
79   할부금액_부분_14M_R12M  수치형  Eta²     NaN

[80 rows x 4 columns]

          변수   유형        계수종류    상관계수
0         ID  범주형  Cramér's V 1.00000
1   _2순위납부업종  범주형  Cramér's V 0.29501
2     _3순위업종  범주형  Cramér's V 0.20882
3     _2순위업종  범주형  Cramér's V 0.15342
4     _1순위업종  범주형  Cramér's V 0.14461
5   _2순위쇼핑업종  범주형  Cramér's V 0.13980
6   _2순위교통업종  범주형  Cramér's V 0.13249
7   _3순위쇼핑업종  범주형  Cramér's V 0.12062
8   _1순위여유업종  범주형  Cramér's V 0.11986
9   _3순위여유업종  범주형  Cramér's V 0.11840
10  _1순위납부업종  범주형  Cramér's V 0.11829
11  _3순위납부업종  범주형  Cramér's V 0.09922
12  _1순위쇼핑업종  범주형  Cramér's V 0.09350
13  _1순위교통업종  범주형  Cramér's V 0.08305
14  _2순위여유업종  범주형  Cramér's V 0.05667
15  _3순위교통업종  범주형  Cramér's V 0.05502

In [85]:
#result1과 result2, 그리고 ttest_results를 각각 parquet으로 저장한다.
result1.to_parquet('/content/drive/MyDrive/승인매출ab_df3-2_설명력.parquet', index=False)
ttest_results.to_parquet('/content/drive/MyDrive/ttest_results3-2.parquet', index=False)