In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False
import gc


# 인코더 추가
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
#상수항추가
from statsmodels.tools.tools import add_constant
# 카이제곱, ANOVA
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
#Turkeyhsd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

### 데이터 불러오기

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# parquet 파일 데이터를 읽어온다.
# x 값으로 쓸 데이터
df1_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201807_train_승인매출정보.parquet')
df2_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201808_train_승인매출정보.parquet')
df3_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201809_train_승인매출정보.parquet')
df4_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201810_train_승인매출정보.parquet')
df5_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201811_train_승인매출정보.parquet')
df6_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201812_train_승인매출정보.parquet')

In [4]:
# 결과데이터를 불러온다.
segment_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
segment_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [5]:
# 데이터프레임의 컬럼 이름을 리스트에 담는다.
column_list = df1_train.columns.tolist()

In [7]:
# 슬라이싱
column_list = column_list[:130]

In [8]:
print(column_list)

['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수']

In [9]:
df1_train = df1_train[column_list]

In [10]:
df2_train = df2_train[column_list]
df3_train = df3_train[column_list]
df4_train = df4_train[column_list]
df5_train = df5_train[column_list]
df6_train = df6_train[column_list]

In [11]:
combined_df = pd.concat([df1_train, df2_train, df3_train, df4_train, df5_train, df6_train],
                         axis=0,        # 행 방향
                         ignore_index=True)  # 인덱스 초기화

In [12]:
segment_df = segment_df['Segment']

In [13]:
# 세그먼트와 데이터를 합쳐준다.

all_df = pd.concat([segment_df,combined_df], axis = 1)
all_df

,Segment,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,...,이용개월수_신판_R3M,이용개월수_일시불_R3M,이용개월수_할부_R3M,이용개월수_할부_유이자_R3M,이용개월수_할부_무이자_R3M,이용개월수_부분무이자_R3M,이용개월수_CA_R3M,이용개월수_체크_R3M,이용개월수_카드론_R3M,이용가맹점수
0,D,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,...,3,3,1,0,1,0,3,0,0,6
1,E,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,...,3,3,0,0,0,0,0,0,0,32
2,C,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,...,3,3,1,0,1,0,2,0,0,27
3,D,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,...,3,3,2,1,1,0,3,0,0,10
4,E,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,E,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,...,0,0,0,0,0,0,0,3,0,3
2399996,D,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,...,3,3,0,0,0,0,0,0,0,15
2399997,C,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,...,3,3,1,0,1,0,0,0,0,27
2399998,E,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,...,0,0,0,0,0,0,0,0,0,0
2399999,E,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,...,3,3,2,1,1,0,0,0,0,3

In [14]:
print(all_df.isna().sum().to_string())

Segment               0
기준년월                  0
ID                    0
최종이용일자_기본             0
최종이용일자_신판             0
최종이용일자_CA             0
최종이용일자_카드론            0
최종이용일자_체크             0
최종이용일자_일시불            0
최종이용일자_할부             0
이용건수_신용_B0M           0
이용건수_신판_B0M           0
이용건수_일시불_B0M          0
이용건수_할부_B0M           0
이용건수_할부_유이자_B0M       0
이용건수_할부_무이자_B0M       0
이용건수_부분무이자_B0M        0
이용건수_CA_B0M           0
이용건수_체크_B0M           0
이용건수_카드론_B0M          0
이용금액_일시불_B0M          0
이용금액_할부_B0M           0
이용금액_할부_유이자_B0M       0
이용금액_할부_무이자_B0M       0
이용금액_부분무이자_B0M        0
이용금액_CA_B0M           0
이용금액_체크_B0M           0
이용금액_카드론_B0M          0
이용후경과월_신용             0
이용후경과월_신판             0
이용후경과월_일시불            0
이용후경과월_할부             0
이용후경과월_할부_유이자         0
이용후경과월_할부_무이자         0
이용후경과월_부분무이자          0
이용후경과월_CA             0
이용후경과월_체크             0
이용후경과월_카드론            0
이용건수_신용_R12M          0
이용건수_신판_R12M          0
이용건수_일시불_R12M         0
이용건수_할부_R12M          0
이용건수_할부_유이자_R12M      0
이용건수_할부_무이자_R12M      0
이용건수_부분무이자_R12M       0
이용건수_CA_R12M          0
이용건수_체크_R12M          0
이용건수_카드론_R12M         0
이용금액_일시불_R12M         0
이용금액_할부_R12M          0
이용금액_할부_유이자_R12M      0
이용금액_할부_무이자_R12M      0
이용금액_부분무이자_R12M       0
이용금액_CA_R12M          0
이용금액_체크_R12M          0
이용금액_카드론_R12M         0
최대이용금액_일시불_R12M       0
최대이용금액_할부_R12M        0
최대이용금액_할부_유이자_R12M    0
최대이용금액_할부_무이자_R12M    0
최대이용금액_부분무이자_R12M     0
최대이용금액_CA_R12M        0
최대이용금액_체크_R12M        0
최대이용금액_카드론_R12M       0
이용개월수_신용_R12M         0
이용개월수_신판_R12M         0
이용개월수_일시불_R12M        0
이용개월수_할부_R12M         0
이용개월수_할부_유이자_R12M     0
이용개월수_할부_무이자_R12M     0
이용개월수_부분무이자_R12M      0
이용개월수_CA_R12M         0
이용개월수_체크_R12M         0
이용개월수_카드론_R12M        0
이용건수_신용_R6M           0
이용건수_신판_R6M           0
이용건수_일시불_R6M          0
이용건수_할부_R6M           0
이용건수_할부_유이자_R6M       0
이용건수_할부_무이자_R6M       0
이용건수_부분무이자_R6M        0
이용건수_CA_R6M           0
이용건수_체크_R6M           0
이용건수_카드론_R6M          0
이용금액_일시불_R6M          0
이용금액_할부_R6M           0
이용금액_할부_유이자_R6M       0
이용금액_할부_무이자_R6M       0
이용금액_부분무이자_R6M        0
이용금액_CA_R6M           0
이용금액_체크_R6M           0
이용금액_카드론_R6M          0
이용개월수_신용_R6M          0
이용개월수_신판_R6M          0
이용개월수_일시불_R6M         0
이용개월수_할부_R6M          0
이용개월수_할부_유이자_R6M      0
이용개월수_할부_무이자_R6M      0
이용개월수_부분무이자_R6M       0
이용개월수_CA_R6M          0
이용개월수_체크_R6M          0
이용개월수_카드론_R6M         0
이용건수_신용_R3M           0
이용건수_신판_R3M           0
이용건수_일시불_R3M          0
이용건수_할부_R3M           0
이용건수_할부_유이자_R3M       0
이용건수_할부_무이자_R3M       0
이용건수_부분무이자_R3M        0
이용건수_CA_R3M           0
이용건수_체크_R3M           0
이용건수_카드론_R3M          0
이용금액_일시불_R3M          0
이용금액_할부_R3M           0
이용금액_할부_유이자_R3M       0
이용금액_할부_무이자_R3M       0
이용금액_부분무이자_R3M        0
이용금액_CA_R3M           0
이용금액_체크_R3M           0
이용금액_카드론_R3M          0
이용개월수_신용_R3M          0
이용개월수_신판_R3M          0
이용개월수_일시불_R3M         0
이용개월수_할부_R3M          0
이용개월수_할부_유이자_R3M      0
이용개월수_할부_무이자_R3M      0
이용개월수_부분무이자_R3M       0
이용개월수_CA_R3M          0
이용개월수_체크_R3M          0
이용개월수_카드론_R3M         0
이용가맹점수                0

In [15]:
for col in column_list:
    try:
        var_value = all_df[col].var()
        print(f"{col}: {var_value:.2f}")
    except TypeError:
        print(f"❌ 분산 계산 불가 (문자열 포함): {col}")

기준년월: 2.92
❌ 분산 계산 불가 (문자열 포함): ID
최종이용일자_기본: 15164506136473.34
최종이용일자_신판: 15290383035759.30
최종이용일자_CA: 88162643539604.62
최종이용일자_카드론: 57709158372772.21
최종이용일자_체크: 94398686619799.09
최종이용일자_일시불: 16014268555037.79
최종이용일자_할부: 81531881958688.75
이용건수_신용_B0M: 397.45
이용건수_신판_B0M: 396.95
이용건수_일시불_B0M: 393.04
이용건수_할부_B0M: 0.20
이용건수_할부_유이자_B0M: 0.03
이용건수_할부_무이자_B0M: 0.14
이용건수_부분무이자_B0M: 0.00
이용건수_CA_B0M: 0.16
이용건수_체크_B0M: 80.43
이용건수_카드론_B0M: 0.00
이용금액_일시불_B0M: 21094276.07
이용금액_할부_B0M: 2220701.16
이용금액_할부_유이자_B0M: 514047.01
이용금액_할부_무이자_B0M: 1354412.20
이용금액_부분무이자_B0M: 0.00
이용금액_CA_B0M: 4662026.63
이용금액_체크_B0M: 3700739.70
이용금액_카드론_B0M: 205861.13
이용후경과월_신용: 17.05
이용후경과월_신판: 17.32
이용후경과월_일시불: 16.10
이용후경과월_할부: 21.31
이용후경과월_할부_유이자: 11.53
이용후경과월_할부_무이자: 20.23
이용후경과월_부분무이자: 1.27
이용후경과월_CA: 8.36
이용후경과월_체크: 17.51
이용후경과월_카드론: 1.80
이용건수_신용_R12M: 51273.49
이용건수_신판_R12M: 51186.08
이용건수_일시불_R12M: 50377.42
이용건수_할부_R12M: 41.24
이용건수_할부_유이자_R12M: 3.98
이용건수_할부_무이자_R12M: 28.52
이용건수_부분무이자_R12M: 0.00
이용건수_CA_R12M: 12.26
이용건수_체크_R12M: 9823.11
이용건수_카드론_R12M: 0.14
이용금액_일시불_R12M: 4661018790.86
이용금액_할부_R12M: 185578253.92
이용금액_할부_유이자_R12M: 25012744.16
이용금액_할부_무이자_R12M: 118076069.03
이용금액_부분무이자_R12M: 1220678.09
이용금액_CA_R12M: 1706686669.04
이용금액_체크_R12M: 248315215.39
이용금액_카드론_R12M: 326326595.46
최대이용금액_일시불_R12M: 207721005.22
최대이용금액_할부_R12M: 29892601.69
최대이용금액_할부_유이자_R12M: 9001648.09
최대이용금액_할부_무이자_R12M: 28324127.91
최대이용금액_부분무이자_R12M: 1076191.91
최대이용금액_CA_R12M: 32949202.37
최대이용금액_체크_R12M: 39629154.86
최대이용금액_카드론_R12M: 334143273.45
이용개월수_신용_R12M: 18.77
이용개월수_신판_R12M: 19.11
이용개월수_일시불_R12M: 19.34
이용개월수_할부_R12M: 7.82
이용개월수_할부_유이자_R12M: 0.93
이용개월수_할부_무이자_R12M: 5.77
이용개월수_부분무이자_R12M: 0.02
이용개월수_CA_R12M: 3.28
이용개월수_체크_R12M: 12.29
이용개월수_카드론_R12M: 0.05
이용건수_신용_R6M: 14549.48
이용건수_신판_R6M: 14527.47
이용건수_일시불_R6M: 14336.95
이용건수_할부_R6M: 9.16
이용건수_할부_유이자_R6M: 0.77
이용건수_할부_무이자_R6M: 6.70
이용건수_부분무이자_R6M: 0.00
이용건수_CA_R6M: 4.02
이용건수_체크_R6M: 2784.48
이용건수_카드론_R6M: 0.02
이용금액_일시불_R6M: 806840654.13
이용금액_할부_R6M: 68237221.58
이용금액_할부_유이자_R6M: 12854036.36
이용금액_할부_무이자_R6M: 41000870.72
이용금액_부분무이자_R6M: 402461.66
이용금액_CA_R6M: 242689575.96
이용금액_체크_R6M: 127025852.41
이용금액_카드론_R6M: 76868802.58
이용개월수_신용_R6M: 5.51
이용개월수_신판_R6M: 5.54
이용개월수_일시불_R6M: 5.59
이용개월수_할부_R6M: 2.35
이용개월수_할부_유이자_R6M: 0.33
이용개월수_할부_무이자_R6M: 1.85
이용개월수_부분무이자_R6M: 0.00
이용개월수_CA_R6M: 1.15
이용개월수_체크_R6M: 3.78
이용개월수_카드론_R6M: 0.02
이용건수_신용_R3M: 3705.42
이용건수_신판_R3M: 3700.39
이용건수_일시불_R3M: 3660.47
이용건수_할부_R3M: 1.79
이용건수_할부_유이자_R3M: 0.22
이용건수_할부_무이자_R3M: 1.24
이용건수_부분무이자_R3M: 0.00
이용건수_CA_R3M: 1.22
이용건수_체크_R3M: 713.21
이용건수_카드론_R3M: 0.00
이용금액_일시불_R3M: 196026376.40
이용금액_할부_R3M: 18598099.15
이용금액_할부_유이자_R3M: 4008521.68
이용금액_할부_무이자_R3M: 11114308.60
이용금액_부분무이자_R3M: 5725.83
이용금액_CA_R3M: 46484380.68
이용금액_체크_R3M: 32720784.19
이용금액_카드론_R3M: 21602956.89
이용개월수_신용_R3M: 1.49
이용개월수_신판_R3M: 1.51
이용개월수_일시불_R3M: 1.52
이용개월수_할부_R3M: 0.66
이용개월수_할부_유이자_R3M: 0.13
이용개월수_할부_무이자_R3M: 0.49
이용개월수_부분무이자_R3M: 0.00
이용개월수_CA_R3M: 0.31
이용개월수_체크_R3M: 0.96
이용개월수_카드론_R3M: 0.00
이용가맹점수: 620.33

- 이용금액_부분무이자_B0M, 이용건수_부분무이자_B0M 컬럼은 제거해야함

- 0 하나만 가진 데이터값은 상관관계 분석이나 추후 학습에 방해되므로 drop

In [16]:
all_df.drop(['이용건수_부분무이자_B0M', '이용금액_부분무이자_B0M'],
            axis=1, inplace=True)

### 변수간 관계파악
Anova -> ETA제곱
카이제곱 -> 크레이머스V

In [17]:
print(column_list)

['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수']

In [18]:
# 크레이머스V와 eta를 구하기 위한 함수
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

def eta_squared(anova_ss_between, total_ss):
    return anova_ss_between / total_ss if total_ss != 0 else np.nan

In [19]:
# 수치형/범주형 자동 구분
num_cols = all_df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = all_df.select_dtypes(exclude=[np.number]).columns.tolist()

In [20]:
print(cat_cols)

['Segment', 'ID']

In [21]:
print(num_cols)

['기준년월', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수']

### 기존의 코드

In [22]:
anova = []
chi = []

for col in all_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = all_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(all_df[col], all_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df1 = pd.DataFrame(anova)
result_df2 = pd.DataFrame(chi)
result_df1 = result_df1.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df2 = result_df2.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df1)
display(result_df2)

                  변수   유형  계수종류      상관계수
0      이용금액_일시불_R12M  수치형  Eta²  0.355606
1       이용금액_일시불_B0M  수치형  Eta²  0.331317
2       이용금액_일시불_R6M  수치형  Eta²  0.324957
3       이용금액_일시불_R3M  수치형  Eta²  0.322906
4       이용건수_신용_R12M  수치형  Eta²  0.240197
..               ...  ...   ...       ...
122  이용건수_부분무이자_R12M  수치형  Eta²  0.000070
123   이용건수_부분무이자_R3M  수치형  Eta²  0.000068
124     이용금액_카드론_B0M  수치형  Eta²  0.000003
125     이용건수_카드론_B0M  수치형  Eta²  0.000002
126             기준년월  수치형  Eta²  0.000000

[127 rows x 4 columns]

   변수   유형        계수종류  상관계수
0  ID  범주형  Cramér's V   1.0

In [ ]:
pd.set_option('display.max_rows', 100)
display(result_df1)

                   변수   유형  계수종류          상관계수
0         _3순위업종_이용금액  수치형  Eta²  2.549372e-01
1         _2순위업종_이용금액  수치형  Eta²  2.429217e-01
2       _2순위쇼핑업종_이용금액  수치형  Eta²  2.387084e-01
3         _1순위업종_이용금액  수치형  Eta²  2.198912e-01
4       _3순위쇼핑업종_이용금액  수치형  Eta²  2.172726e-01
5              이용가맹점수  수치형  Eta²  2.157008e-01
6         쇼핑_도소매_이용금액  수치형  Eta²  2.048195e-01
7       _1순위교통업종_이용금액  수치형  Eta²  1.715343e-01
8          쇼핑_마트_이용금액  수치형  Eta²  1.575289e-01
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  1.560192e-01
10          교통_주유이용금액  수치형  Eta²  1.534422e-01
11      _1순위쇼핑업종_이용금액  수치형  Eta²  1.416423e-01
12      _2순위교통업종_이용금액  수치형  Eta²  1.264717e-01
13        쇼핑_온라인_이용금액  수치형  Eta²  1.251935e-01
14          교통_정비이용금액  수치형  Eta²  1.152910e-01
15       할부금액_3M_R12M  수치형  Eta²  1.146496e-01
16        쇼핑_편의점_이용금액  수치형  Eta²  1.108649e-01
17   할부금액_무이자_3M_R12M  수치형  Eta²  1.095503e-01
18      _3순위교통업종_이용금액  수치형  Eta²  1.079877e-01
19          납부_기타이용금액  수치형  Eta²  9.976501e-02
20       할부금액_6M_R12M  수치형  Eta²  9.011536e-02
21         쇼핑_기타_이용금액  수치형  Eta²  8.941263e-02
22            이용금액_해외  수치형  Eta²  8.759255e-02
23       할부건수_3M_R12M  수치형  Eta²  8.220689e-02
24      _1순위여유업종_이용금액  수치형  Eta²  8.201874e-02
25   할부금액_무이자_6M_R12M  수치형  Eta²  8.003808e-02
26   할부건수_무이자_3M_R12M  수치형  Eta²  7.990661e-02
27        쇼핑_백화점_이용금액  수치형  Eta²  7.842607e-02
28          교통_택시이용금액  수치형  Eta²  6.645548e-02
29          여유_운동이용금액  수치형  Eta²  6.070089e-02
30       할부건수_6M_R12M  수치형  Eta²  6.006017e-02
31      _1순위납부업종_이용금액  수치형  Eta²  5.668454e-02
32   할부건수_무이자_6M_R12M  수치형  Eta²  5.590561e-02
33      _2순위여유업종_이용금액  수치형  Eta²  4.788675e-02
34   할부금액_유이자_3M_R12M  수치형  Eta²  4.166154e-02
35      _2순위납부업종_이용금액  수치형  Eta²  4.044062e-02
36         납부_통신비이용금액  수치형  Eta²  3.997435e-02
37         납부_보험료이용금액  수치형  Eta²  3.406799e-02
38        교통_철도버스이용금액  수치형  Eta²  3.364627e-02
39          여유_숙박이용금액  수치형  Eta²  3.250516e-02
40        쇼핑_아울렛_이용금액  수치형  Eta²  3.197465e-02
41   할부건수_유이자_3M_R12M  수치형  Eta²  3.156948e-02
42   할부금액_유이자_6M_R12M  수치형  Eta²  2.964685e-02
43          여유_공연이용금액  수치형  Eta²  2.720280e-02
44      _3순위여유업종_이용금액  수치형  Eta²  2.183659e-02
45       교통_버스지하철이용금액  수치형  Eta²  2.157895e-02
46      _3순위납부업종_이용금액  수치형  Eta²  1.702915e-02
47          여유_기타이용금액  수치형  Eta²  1.634331e-02
48   할부건수_유이자_6M_R12M  수치형  Eta²  1.555705e-02
49      할부금액_12M_R12M  수치형  Eta²  1.368153e-02
50  할부금액_무이자_12M_R12M  수치형  Eta²  1.182850e-02
51          여유_항공이용금액  수치형  Eta²  9.683946e-03
52         여유_Pet이용금액  수치형  Eta²  8.378419e-03
53         납부_관리비이용금액  수치형  Eta²  6.938032e-03
54          여유_공원이용금액  수치형  Eta²  5.403499e-03
55  할부금액_유이자_12M_R12M  수치형  Eta²  5.388438e-03
56       납부_가스전기료이용금액  수치형  Eta²  5.189205e-03
57      할부건수_12M_R12M  수치형  Eta²  4.687290e-03
58   할부금액_부분_12M_R12M  수치형  Eta²  4.354411e-03
59  할부건수_무이자_12M_R12M  수치형  Eta²  2.828204e-03
60  할부건수_유이자_12M_R12M  수치형  Eta²  2.173066e-03
61      할부금액_14M_R12M  수치형  Eta²  3.384175e-04
62  할부금액_유이자_14M_R12M  수치형  Eta²  2.303228e-04
63  할부금액_무이자_14M_R12M  수치형  Eta²  1.495791e-04
64   할부건수_부분_12M_R12M  수치형  Eta²  7.045953e-05
65         교통_통행료이용금액  수치형  Eta²  4.721707e-05
66  할부건수_유이자_14M_R12M  수치형  Eta²  1.419732e-05
67      할부건수_14M_R12M  수치형  Eta²  1.375602e-05
68    할부금액_부분_6M_R12M  수치형  Eta²  2.446678e-06
69  할부건수_무이자_14M_R12M  수치형  Eta²  3.108322e-07
70   할부금액_부분_14M_R12M  수치형  Eta²  2.398594e-08

In [ ]:
result_df1['상관계수'] = result_df1['상관계수'].round(4)

In [ ]:
display(result_df1)

                   변수   유형  계수종류    상관계수
0         _3순위업종_이용금액  수치형  Eta²  0.2549
1         _2순위업종_이용금액  수치형  Eta²  0.2429
2       _2순위쇼핑업종_이용금액  수치형  Eta²  0.2387
3         _1순위업종_이용금액  수치형  Eta²  0.2199
4       _3순위쇼핑업종_이용금액  수치형  Eta²  0.2173
5              이용가맹점수  수치형  Eta²  0.2157
6         쇼핑_도소매_이용금액  수치형  Eta²  0.2048
7       _1순위교통업종_이용금액  수치형  Eta²  0.1715
8          쇼핑_마트_이용금액  수치형  Eta²  0.1575
9        쇼핑_슈퍼마켓_이용금액  수치형  Eta²  0.1560
10          교통_주유이용금액  수치형  Eta²  0.1534
11      _1순위쇼핑업종_이용금액  수치형  Eta²  0.1416
12      _2순위교통업종_이용금액  수치형  Eta²  0.1265
13        쇼핑_온라인_이용금액  수치형  Eta²  0.1252
14          교통_정비이용금액  수치형  Eta²  0.1153
15       할부금액_3M_R12M  수치형  Eta²  0.1146
16        쇼핑_편의점_이용금액  수치형  Eta²  0.1109
17   할부금액_무이자_3M_R12M  수치형  Eta²  0.1096
18      _3순위교통업종_이용금액  수치형  Eta²  0.1080
19          납부_기타이용금액  수치형  Eta²  0.0998
20       할부금액_6M_R12M  수치형  Eta²  0.0901
21         쇼핑_기타_이용금액  수치형  Eta²  0.0894
22            이용금액_해외  수치형  Eta²  0.0876
23       할부건수_3M_R12M  수치형  Eta²  0.0822
24      _1순위여유업종_이용금액  수치형  Eta²  0.0820
25   할부금액_무이자_6M_R12M  수치형  Eta²  0.0800
26   할부건수_무이자_3M_R12M  수치형  Eta²  0.0799
27        쇼핑_백화점_이용금액  수치형  Eta²  0.0784
28          교통_택시이용금액  수치형  Eta²  0.0665
29          여유_운동이용금액  수치형  Eta²  0.0607
30       할부건수_6M_R12M  수치형  Eta²  0.0601
31      _1순위납부업종_이용금액  수치형  Eta²  0.0567
32   할부건수_무이자_6M_R12M  수치형  Eta²  0.0559
33      _2순위여유업종_이용금액  수치형  Eta²  0.0479
34   할부금액_유이자_3M_R12M  수치형  Eta²  0.0417
35      _2순위납부업종_이용금액  수치형  Eta²  0.0404
36         납부_통신비이용금액  수치형  Eta²  0.0400
37         납부_보험료이용금액  수치형  Eta²  0.0341
38        교통_철도버스이용금액  수치형  Eta²  0.0336
39          여유_숙박이용금액  수치형  Eta²  0.0325
40        쇼핑_아울렛_이용금액  수치형  Eta²  0.0320
41   할부건수_유이자_3M_R12M  수치형  Eta²  0.0316
42   할부금액_유이자_6M_R12M  수치형  Eta²  0.0296
43          여유_공연이용금액  수치형  Eta²  0.0272
44      _3순위여유업종_이용금액  수치형  Eta²  0.0218
45       교통_버스지하철이용금액  수치형  Eta²  0.0216
46      _3순위납부업종_이용금액  수치형  Eta²  0.0170
47          여유_기타이용금액  수치형  Eta²  0.0163
48   할부건수_유이자_6M_R12M  수치형  Eta²  0.0156
49      할부금액_12M_R12M  수치형  Eta²  0.0137
50  할부금액_무이자_12M_R12M  수치형  Eta²  0.0118
51          여유_항공이용금액  수치형  Eta²  0.0097
52         여유_Pet이용금액  수치형  Eta²  0.0084
53         납부_관리비이용금액  수치형  Eta²  0.0069
54          여유_공원이용금액  수치형  Eta²  0.0054
55  할부금액_유이자_12M_R12M  수치형  Eta²  0.0054
56       납부_가스전기료이용금액  수치형  Eta²  0.0052
57      할부건수_12M_R12M  수치형  Eta²  0.0047
58   할부금액_부분_12M_R12M  수치형  Eta²  0.0044
59  할부건수_무이자_12M_R12M  수치형  Eta²  0.0028
60  할부건수_유이자_12M_R12M  수치형  Eta²  0.0022
61      할부금액_14M_R12M  수치형  Eta²  0.0003
62  할부금액_유이자_14M_R12M  수치형  Eta²  0.0002
63  할부금액_무이자_14M_R12M  수치형  Eta²  0.0001
64   할부건수_부분_12M_R12M  수치형  Eta²  0.0001
65         교통_통행료이용금액  수치형  Eta²  0.0000
66  할부건수_유이자_14M_R12M  수치형  Eta²  0.0000
67      할부건수_14M_R12M  수치형  Eta²  0.0000
68    할부금액_부분_6M_R12M  수치형  Eta²  0.0000
69  할부건수_무이자_14M_R12M  수치형  Eta²  0.0000
70   할부금액_부분_14M_R12M  수치형  Eta²  0.0000

In [23]:
cat_cols

['Segment', 'ID']

### A,B 와 CDE나누기

In [24]:
all_df.columns

Index(['Segment', '기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA',
       '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부',
       ...
       '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M',
       '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M',
       '이용개월수_카드론_R3M', '이용가맹점수'],
      dtype='object', length=129)

In [25]:
# A, B 클래스만 필터링
ab_df = all_df[all_df['Segment'].isin(['A', 'B'])]

# C, D, E 클래스만 필터링
cde_df = all_df[all_df['Segment'].isin(['C', 'D', 'E'])]

In [26]:
ab_df

,Segment,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,...,이용개월수_신판_R3M,이용개월수_일시불_R3M,이용개월수_할부_R3M,이용개월수_할부_유이자_R3M,이용개월수_할부_무이자_R3M,이용개월수_부분무이자_R3M,이용개월수_CA_R3M,이용개월수_체크_R3M,이용개월수_카드론_R3M,이용가맹점수
2898,A,201807,TRAIN_002898,20180731,20180731,20180716,20171203,10101,20180731,20180723,...,3,3,3,1,3,0,2,0,0,43
5253,A,201807,TRAIN_005253,20180719,20180719,20180714,20160830,10101,20180711,20180719,...,3,3,3,0,3,0,2,0,0,28
8128,A,201807,TRAIN_008128,20180729,20180729,10101,10101,20171214,20180729,20180719,...,3,3,3,0,3,0,0,0,0,80
10808,A,201807,TRAIN_010808,20180707,20180707,20110306,10101,10101,20180707,20180610,...,3,3,1,0,1,0,0,0,0,82
14951,A,201807,TRAIN_014951,20180731,20180731,20150704,10101,10101,20180731,20180716,...,3,3,2,0,2,0,0,0,0,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2376373,A,201812,TRAIN_376373,20181231,20181231,10101,10101,20150109,20181231,20181224,...,3,3,3,0,3,0,0,0,0,86
2378479,A,201812,TRAIN_378479,20181231,20181231,10101,10101,10101,20181231,20180430,...,3,3,0,0,0,0,0,0,0,102
2390620,B,201812,TRAIN_390620,20181227,20181227,20181222,20171113,10101,20181227,20181216,...,3,3,3,0,3,0,3,0,0,6
2393027,A,201812,TRAIN_393027,20181208,20181208,20130608,10101,20181231,20181208,20180421,...,3,3,0,0,0,0,0,3,0,69
2393888,A,201812,TRAIN_393888,20181231,20181231,10101,10101,10101,20181231,20180613,...,3,3,0,0,0,0,0,0,0,66

In [27]:
cde_df

,Segment,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,...,이용개월수_신판_R3M,이용개월수_일시불_R3M,이용개월수_할부_R3M,이용개월수_할부_유이자_R3M,이용개월수_할부_무이자_R3M,이용개월수_부분무이자_R3M,이용개월수_CA_R3M,이용개월수_체크_R3M,이용개월수_카드론_R3M,이용가맹점수
0,D,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,...,3,3,1,0,1,0,3,0,0,6
1,E,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,...,3,3,0,0,0,0,0,0,0,32
2,C,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,...,3,3,1,0,1,0,2,0,0,27
3,D,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,...,3,3,2,1,1,0,3,0,0,10
4,E,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,E,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,...,0,0,0,0,0,0,0,3,0,3
2399996,D,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,...,3,3,0,0,0,0,0,0,0,15
2399997,C,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,...,3,3,1,0,1,0,0,0,0,27
2399998,E,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,...,0,0,0,0,0,0,0,0,0,0
2399999,E,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,...,3,3,2,1,1,0,0,0,0,3

In [28]:
anova = []
chi = []

for col in ab_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = ab_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(ab_df[col], ab_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df11 = pd.DataFrame(anova)
result_df12 = pd.DataFrame(chi)
result_df11 = result_df11.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df12 = result_df12.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df11)
display(result_df12)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)

                    변수   유형  계수종류          상관계수
0     이용개월수_할부_무이자_R6M  수치형  Eta²  8.608794e-02
1         이용개월수_할부_R6M  수치형  Eta²  8.438067e-02
2     이용개월수_할부_무이자_R3M  수치형  Eta²  8.010630e-02
3    이용개월수_할부_무이자_R12M  수치형  Eta²  7.871694e-02
4      이용건수_할부_무이자_R3M  수치형  Eta²  7.803974e-02
..                 ...  ...   ...           ...
122  최대이용금액_부분무이자_R12M  수치형  Eta²  1.201786e-07
123               기준년월  수치형  Eta²  0.000000e+00
124       이용건수_카드론_B0M  수치형  Eta²           NaN
125       이용금액_카드론_B0M  수치형  Eta²           NaN
126    이용건수_부분무이자_R12M  수치형  Eta²           NaN

[127 rows x 4 columns]

   변수   유형        계수종류  상관계수
0  ID  범주형  Cramér's V   1.0

In [30]:
anova = []
chi = []

for col in cde_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = cde_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(cde_df[col], cde_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df21 = pd.DataFrame(anova)
result_df22 = pd.DataFrame(chi)
result_df21 = result_df21.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df22 = result_df22.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df21)
display(result_df22)

                  변수   유형  계수종류      상관계수
0      이용금액_일시불_R12M  수치형  Eta²  0.349914
1       이용금액_일시불_B0M  수치형  Eta²  0.327886
2       이용금액_일시불_R6M  수치형  Eta²  0.321964
3       이용금액_일시불_R3M  수치형  Eta²  0.319745
4       이용건수_신용_R12M  수치형  Eta²  0.238931
..               ...  ...   ...       ...
122  이용건수_부분무이자_R12M  수치형  Eta²  0.000070
123   이용건수_부분무이자_R3M  수치형  Eta²  0.000062
124     이용금액_카드론_B0M  수치형  Eta²  0.000003
125     이용건수_카드론_B0M  수치형  Eta²  0.000001
126             기준년월  수치형  Eta²  0.000000

[127 rows x 4 columns]

   변수   유형        계수종류  상관계수
0  ID  범주형  Cramér's V   1.0

In [31]:
pd.set_option('display.max_rows', None)

In [32]:
result_df1['상관계수'] = result_df1['상관계수'].round(4)
result_df11['상관계수'] = result_df11['상관계수'].round(4)
result_df21['상관계수'] = result_df21['상관계수'].round(4)

In [33]:
result_df1

                     변수   유형  계수종류    상관계수
0         이용금액_일시불_R12M  수치형  Eta²  0.3556
1          이용금액_일시불_B0M  수치형  Eta²  0.3313
2          이용금액_일시불_R6M  수치형  Eta²  0.3250
3          이용금액_일시불_R3M  수치형  Eta²  0.3229
4          이용건수_신용_R12M  수치형  Eta²  0.2402
5       최대이용금액_일시불_R12M  수치형  Eta²  0.2370
6          이용건수_신판_R12M  수치형  Eta²  0.2365
7         이용건수_일시불_R12M  수치형  Eta²  0.2321
8                이용가맹점수  수치형  Eta²  0.2157
9           이용건수_신용_R6M  수치형  Eta²  0.1969
10          이용건수_신용_B0M  수치형  Eta²  0.1966
11          이용건수_신용_R3M  수치형  Eta²  0.1940
12          이용건수_신판_R6M  수치형  Eta²  0.1937
13          이용건수_신판_B0M  수치형  Eta²  0.1931
14          이용건수_신판_R3M  수치형  Eta²  0.1906
15         이용건수_일시불_R6M  수치형  Eta²  0.1904
16         이용건수_일시불_B0M  수치형  Eta²  0.1904
17         이용건수_일시불_R3M  수치형  Eta²  0.1880
18         이용금액_할부_R12M  수치형  Eta²  0.1272
19     이용금액_할부_무이자_R12M  수치형  Eta²  0.1238
20       최대이용금액_할부_R12M  수치형  Eta²  0.1119
21   최대이용금액_할부_무이자_R12M  수치형  Eta²  0.1115
22       최대이용금액_CA_R12M  수치형  Eta²  0.0978
23        이용개월수_할부_R12M  수치형  Eta²  0.0912
24    이용개월수_할부_무이자_R12M  수치형  Eta²  0.0912
25         이용금액_CA_R12M  수치형  Eta²  0.0877
26         이용건수_할부_R12M  수치형  Eta²  0.0874
27      이용금액_할부_무이자_R6M  수치형  Eta²  0.0861
28        이용개월수_신용_R12M  수치형  Eta²  0.0859
29          이용금액_할부_R6M  수치형  Eta²  0.0851
30        이용개월수_신판_R12M  수치형  Eta²  0.0848
31     이용건수_할부_무이자_R12M  수치형  Eta²  0.0842
32       이용개월수_일시불_R12M  수치형  Eta²  0.0839
33          이용금액_CA_R6M  수치형  Eta²  0.0804
34         이용건수_CA_R12M  수치형  Eta²  0.0777
35          이용금액_CA_R3M  수치형  Eta²  0.0743
36        이용개월수_CA_R12M  수치형  Eta²  0.0736
37        이용후경과월_할부_무이자  수치형  Eta²  0.0721
38          이용금액_CA_B0M  수치형  Eta²  0.0709
39            이용후경과월_할부  수치형  Eta²  0.0703
40         이용개월수_할부_R6M  수치형  Eta²  0.0695
41          이용건수_할부_R6M  수치형  Eta²  0.0689
42     이용개월수_할부_무이자_R6M  수치형  Eta²  0.0680
43      이용건수_할부_무이자_R6M  수치형  Eta²  0.0663
44      이용금액_할부_무이자_R3M  수치형  Eta²  0.0659
45          이용금액_할부_R3M  수치형  Eta²  0.0648
46          이용건수_CA_R6M  수치형  Eta²  0.0616
47          이용건수_할부_R3M  수치형  Eta²  0.0611
48         이용개월수_할부_R3M  수치형  Eta²  0.0608
49         이용개월수_CA_R6M  수치형  Eta²  0.0600
50      이용건수_할부_무이자_R3M  수치형  Eta²  0.0598
51     이용개월수_할부_무이자_R3M  수치형  Eta²  0.0586
52         이용금액_체크_R12M  수치형  Eta²  0.0574
53            이용후경과월_CA  수치형  Eta²  0.0568
54          이용건수_할부_B0M  수치형  Eta²  0.0561
55      이용건수_할부_무이자_B0M  수치형  Eta²  0.0551
56         이용개월수_CA_R3M  수치형  Eta²  0.0543
57      이용금액_할부_무이자_B0M  수치형  Eta²  0.0539
58          이용건수_CA_R3M  수치형  Eta²  0.0533
59          이용금액_체크_R6M  수치형  Eta²  0.0533
60          이용금액_할부_B0M  수치형  Eta²  0.0527
61         이용개월수_신용_R6M  수치형  Eta²  0.0525
62         이용건수_체크_R12M  수치형  Eta²  0.0522
63          이용금액_체크_R3M  수치형  Eta²  0.0518
64            최종이용일자_CA  수치형  Eta²  0.0516
65          이용금액_체크_B0M  수치형  Eta²  0.0507
66         이용개월수_신판_R6M  수치형  Eta²  0.0498
67          이용건수_체크_R6M  수치형  Eta²  0.0497
68        이용개월수_일시불_R6M  수치형  Eta²  0.0494
69          이용건수_CA_B0M  수치형  Eta²  0.0490
70          이용건수_체크_R3M  수치형  Eta²  0.0487
71       최대이용금액_체크_R12M  수치형  Eta²  0.0485
72          이용건수_체크_B0M  수치형  Eta²  0.0481
73            이용후경과월_신용  수치형  Eta²  0.0478
74         이용개월수_신용_R3M  수치형  Eta²  0.0461
75            최종이용일자_할부  수치형  Eta²  0.0461
76     이용금액_할부_유이자_R12M  수치형  Eta²  0.0437
77         이용개월수_신판_R3M  수치형  Eta²  0.0437
78            이용후경과월_신판  수치형  Eta²  0.0435
79        이용개월수_일시불_R3M  수치형  Eta²  0.0433
80   최대이용금액_할부_유이자_R12M  수치형  Eta²  0.0415
81    이용개월수_할부_유이자_R12M  수치형  Eta²  0.0388
82           이용후경과월_일시불  수치형  Eta²  0.0351
83        이용후경과월_할부_유이자  수치형  Eta²  0.0350
84        이용개월수_체크_R12M  수치형  Eta²  0.0349
85     이용건수_할부_유이자_R12M  수치형  Eta²  0.0332
86         이용개월수_체크_R6M  수치형  Eta²  0.0291
87         이용개월수_체크_R3M  수치형  Eta²  0.0282
88            이용후경과월_체크  수치형  Eta²  0.0266
89      이용건수_할부_유이자_R6M  수치형  Eta²  0.0232
90      이용금액_할부_유이자_R6M  수치형  Eta²  0.0230
91     이용개월수_할부_유이자_R6M  수치형  Eta²  0.0227
92            최종이용일자_체크  수치형  Eta²  0.0225
93     이용개월수_할부_유이자_R3M  수치형  Eta²  0.0188
94      이용건수_할부_유이자_R3M  수치형  Eta²  0.0172
95      이용금액_할부_유이자_R3M  수치형  Eta²  0.0165
96           최종이용일자_카드론  수치형  Eta²  0.0161
97      이용건수_할부_유이자_B0M  수치형  Eta²  0.0134
98      이용금액_할부_유이자_B0M  수치형  Eta²  0.0120
99           최종이용일자_일시불  수치형  Eta²  0.0105
100           최종이용일자_신판  수치형  Eta²  0.0099
101           최종이용일자_기본  수치형  Eta²  0.0098
102   최대이용금액_부분무이자_R12M  수치형  Eta²  0.0044
103    이용개월수_부분무이자_R12M  수치형  Eta²  0.0044
104     이용금액_부분무이자_R12M  수치형  Eta²  0.0043
105       이용건수_카드론_R12M  수치형  Eta²  0.0041
106        이용후경과월_부분무이자  수치형  Eta²  0.0038
107      이용개월수_카드론_R12M  수치형  Eta²  0.0034
108      이용금액_부분무이자_R3M  수치형  Eta²  0.0025
109          이용후경과월_카드론  수치형  Eta²  0.0022
110       이용금액_카드론_R12M  수치형  Eta²  0.0019
111     최대이용금액_카드론_R12M  수치형  Eta²  0.0013
112       이용개월수_카드론_R6M  수치형  Eta²  0.0010
113      이용금액_부분무이자_R6M  수치형  Eta²  0.0009
114        이용건수_카드론_R6M  수치형  Eta²  0.0008
115        이용금액_카드론_R6M  수치형  Eta²  0.0007
116     이용개월수_부분무이자_R6M  수치형  Eta²  0.0007
117      이용건수_부분무이자_R6M  수치형  Eta²  0.0006
118       이용개월수_카드론_R3M  수치형  Eta²  0.0001
119        이용금액_카드론_R3M  수치형  Eta²  0.0001
120        이용건수_카드론_R3M  수치형  Eta²  0.0001
121     이용개월수_부분무이자_R3M  수치형  Eta²  0.0001
122     이용건수_부분무이자_R12M  수치형  Eta²  0.0001
123      이용건수_부분무이자_R3M  수치형  Eta²  0.0001
124        이용금액_카드론_B0M  수치형  Eta²  0.0000
125        이용건수_카드론_B0M  수치형  Eta²  0.0000
126                기준년월  수치형  Eta²  0.0000

In [34]:
result_df21

                     변수   유형  계수종류    상관계수
0         이용금액_일시불_R12M  수치형  Eta²  0.3499
1          이용금액_일시불_B0M  수치형  Eta²  0.3279
2          이용금액_일시불_R6M  수치형  Eta²  0.3220
3          이용금액_일시불_R3M  수치형  Eta²  0.3197
4          이용건수_신용_R12M  수치형  Eta²  0.2389
5          이용건수_신판_R12M  수치형  Eta²  0.2353
6       최대이용금액_일시불_R12M  수치형  Eta²  0.2328
7         이용건수_일시불_R12M  수치형  Eta²  0.2309
8                이용가맹점수  수치형  Eta²  0.2143
9           이용건수_신용_R6M  수치형  Eta²  0.1957
10          이용건수_신용_B0M  수치형  Eta²  0.1954
11          이용건수_신용_R3M  수치형  Eta²  0.1927
12          이용건수_신판_R6M  수치형  Eta²  0.1924
13          이용건수_신판_B0M  수치형  Eta²  0.1918
14          이용건수_신판_R3M  수치형  Eta²  0.1894
15         이용건수_일시불_R6M  수치형  Eta²  0.1892
16         이용건수_일시불_B0M  수치형  Eta²  0.1891
17         이용건수_일시불_R3M  수치형  Eta²  0.1867
18         이용금액_할부_R12M  수치형  Eta²  0.1220
19     이용금액_할부_무이자_R12M  수치형  Eta²  0.1157
20       최대이용금액_할부_R12M  수치형  Eta²  0.1090
21   최대이용금액_할부_무이자_R12M  수치형  Eta²  0.1084
22       최대이용금액_CA_R12M  수치형  Eta²  0.0958
23        이용개월수_할부_R12M  수치형  Eta²  0.0902
24    이용개월수_할부_무이자_R12M  수치형  Eta²  0.0900
25         이용건수_할부_R12M  수치형  Eta²  0.0857
26        이용개월수_신용_R12M  수치형  Eta²  0.0857
27         이용금액_CA_R12M  수치형  Eta²  0.0852
28        이용개월수_신판_R12M  수치형  Eta²  0.0846
29       이용개월수_일시불_R12M  수치형  Eta²  0.0837
30          이용금액_할부_R6M  수치형  Eta²  0.0829
31      이용금액_할부_무이자_R6M  수치형  Eta²  0.0825
32     이용건수_할부_무이자_R12M  수치형  Eta²  0.0816
33          이용금액_CA_R6M  수치형  Eta²  0.0781
34         이용건수_CA_R12M  수치형  Eta²  0.0768
35        이용개월수_CA_R12M  수치형  Eta²  0.0729
36          이용금액_CA_R3M  수치형  Eta²  0.0724
37        이용후경과월_할부_무이자  수치형  Eta²  0.0715
38            이용후경과월_할부  수치형  Eta²  0.0698
39          이용금액_CA_B0M  수치형  Eta²  0.0693
40         이용개월수_할부_R6M  수치형  Eta²  0.0684
41          이용건수_할부_R6M  수치형  Eta²  0.0674
42     이용개월수_할부_무이자_R6M  수치형  Eta²  0.0666
43      이용건수_할부_무이자_R6M  수치형  Eta²  0.0642
44          이용금액_할부_R3M  수치형  Eta²  0.0631
45      이용금액_할부_무이자_R3M  수치형  Eta²  0.0630
46          이용건수_CA_R6M  수치형  Eta²  0.0607
47         이용개월수_할부_R3M  수치형  Eta²  0.0599
48          이용건수_할부_R3M  수치형  Eta²  0.0598
49         이용개월수_CA_R6M  수치형  Eta²  0.0592
50      이용건수_할부_무이자_R3M  수치형  Eta²  0.0579
51         이용금액_체크_R12M  수치형  Eta²  0.0574
52     이용개월수_할부_무이자_R3M  수치형  Eta²  0.0572
53            이용후경과월_CA  수치형  Eta²  0.0564
54          이용건수_할부_B0M  수치형  Eta²  0.0549
55         이용개월수_CA_R3M  수치형  Eta²  0.0536
56      이용건수_할부_무이자_B0M  수치형  Eta²  0.0533
57          이용금액_체크_R6M  수치형  Eta²  0.0533
58          이용건수_CA_R3M  수치형  Eta²  0.0525
59         이용개월수_신용_R6M  수치형  Eta²  0.0524
60         이용건수_체크_R12M  수치형  Eta²  0.0522
61          이용금액_체크_R3M  수치형  Eta²  0.0518
62      이용금액_할부_무이자_B0M  수치형  Eta²  0.0515
63            최종이용일자_CA  수치형  Eta²  0.0514
64          이용금액_할부_B0M  수치형  Eta²  0.0513
65          이용금액_체크_B0M  수치형  Eta²  0.0507
66          이용건수_체크_R6M  수치형  Eta²  0.0497
67         이용개월수_신판_R6M  수치형  Eta²  0.0497
68        이용개월수_일시불_R6M  수치형  Eta²  0.0493
69          이용건수_체크_R3M  수치형  Eta²  0.0488
70       최대이용금액_체크_R12M  수치형  Eta²  0.0485
71          이용건수_CA_B0M  수치형  Eta²  0.0484
72          이용건수_체크_B0M  수치형  Eta²  0.0482
73            이용후경과월_신용  수치형  Eta²  0.0476
74         이용개월수_신용_R3M  수치형  Eta²  0.0460
75            최종이용일자_할부  수치형  Eta²  0.0459
76     이용금액_할부_유이자_R12M  수치형  Eta²  0.0437
77         이용개월수_신판_R3M  수치형  Eta²  0.0436
78            이용후경과월_신판  수치형  Eta²  0.0434
79        이용개월수_일시불_R3M  수치형  Eta²  0.0432
80   최대이용금액_할부_유이자_R12M  수치형  Eta²  0.0415
81    이용개월수_할부_유이자_R12M  수치형  Eta²  0.0388
82           이용후경과월_일시불  수치형  Eta²  0.0350
83        이용후경과월_할부_유이자  수치형  Eta²  0.0350
84        이용개월수_체크_R12M  수치형  Eta²  0.0349
85     이용건수_할부_유이자_R12M  수치형  Eta²  0.0332
86         이용개월수_체크_R6M  수치형  Eta²  0.0290
87         이용개월수_체크_R3M  수치형  Eta²  0.0282
88            이용후경과월_체크  수치형  Eta²  0.0266
89      이용건수_할부_유이자_R6M  수치형  Eta²  0.0232
90      이용금액_할부_유이자_R6M  수치형  Eta²  0.0230
91     이용개월수_할부_유이자_R6M  수치형  Eta²  0.0227
92            최종이용일자_체크  수치형  Eta²  0.0225
93     이용개월수_할부_유이자_R3M  수치형  Eta²  0.0188
94      이용건수_할부_유이자_R3M  수치형  Eta²  0.0172
95      이용금액_할부_유이자_R3M  수치형  Eta²  0.0165
96           최종이용일자_카드론  수치형  Eta²  0.0160
97      이용건수_할부_유이자_B0M  수치형  Eta²  0.0135
98      이용금액_할부_유이자_B0M  수치형  Eta²  0.0120
99           최종이용일자_일시불  수치형  Eta²  0.0104
100           최종이용일자_신판  수치형  Eta²  0.0099
101           최종이용일자_기본  수치형  Eta²  0.0098
102   최대이용금액_부분무이자_R12M  수치형  Eta²  0.0044
103    이용개월수_부분무이자_R12M  수치형  Eta²  0.0044
104     이용금액_부분무이자_R12M  수치형  Eta²  0.0043
105       이용건수_카드론_R12M  수치형  Eta²  0.0041
106        이용후경과월_부분무이자  수치형  Eta²  0.0038
107      이용개월수_카드론_R12M  수치형  Eta²  0.0034
108      이용금액_부분무이자_R3M  수치형  Eta²  0.0025
109          이용후경과월_카드론  수치형  Eta²  0.0022
110       이용금액_카드론_R12M  수치형  Eta²  0.0018
111     최대이용금액_카드론_R12M  수치형  Eta²  0.0013
112       이용개월수_카드론_R6M  수치형  Eta²  0.0010
113      이용금액_부분무이자_R6M  수치형  Eta²  0.0009
114        이용건수_카드론_R6M  수치형  Eta²  0.0008
115        이용금액_카드론_R6M  수치형  Eta²  0.0007
116     이용개월수_부분무이자_R6M  수치형  Eta²  0.0007
117      이용건수_부분무이자_R6M  수치형  Eta²  0.0006
118       이용개월수_카드론_R3M  수치형  Eta²  0.0001
119        이용금액_카드론_R3M  수치형  Eta²  0.0001
120        이용건수_카드론_R3M  수치형  Eta²  0.0001
121     이용개월수_부분무이자_R3M  수치형  Eta²  0.0001
122     이용건수_부분무이자_R12M  수치형  Eta²  0.0001
123      이용건수_부분무이자_R3M  수치형  Eta²  0.0001
124        이용금액_카드론_B0M  수치형  Eta²  0.0000
125        이용건수_카드론_B0M  수치형  Eta²  0.0000
126                기준년월  수치형  Eta²  0.0000

In [35]:

ab_df.to_parquet('승인매출ab_df3-1.parquet', index=True)
cde_df.to_parquet('승인매출cde_df3-1.parquet', index=True)

result_df21.to_parquet('승인매출cde_df3-1_설명력.parquet', index=True)

In [36]:
ab_df.to_parquet('승인매출ab_df3-1.parquet', index=False)
cde_df.to_parquet('승인매출cde_df3-1.parquet', index=False)

In [37]:
from scipy.stats import ttest_ind
def cohen_d(x, y):
    """두 그룹 간 효과 크기(Cohen's d) 계산"""
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    pooled_std = np.sqrt(((nx - 1)*x.std()**2 + (ny - 1)*y.std()**2) / dof)
    return (x.mean() - y.mean()) / pooled_std

def ttest_ab_multiple_verbose_abs_sorted(df, feature_cols):
    """
    A vs B 그룹 간 연속형 변수들에 대해 t-test, p-value, Cohen's d, 유의성 표시 포함한 결과 반환
    Cohen's d 절댓값 기준 내림차순 정렬
    """
    results = []

    for col in feature_cols:
        group_a = df[df['Segment'] == 'A'][col].dropna()
        group_b = df[df['Segment'] == 'B'][col].dropna()

        t_stat, p_val = ttest_ind(group_a, group_b, equal_var=False)
        d = cohen_d(group_a, group_b)

        # 유의성 표시
        if p_val < 0.001:
            sig = '***'
        elif p_val < 0.01:
            sig = '**'
        elif p_val < 0.05:
            sig = '*'
        else:
            sig = 'ns'

        results.append({
            'feature': col,
            't-statistic': round(t_stat, 4),
            'p-value': round(p_val, 4),
            'Cohen\'s d': round(d, 4),
            'abs(Cohen\'s d)': abs(round(d, 4)),
            'significance': sig
        })

    df_result = pd.DataFrame(results)
    df_result = df_result.sort_values('abs(Cohen\'s d)', ascending=False).reset_index(drop=True)
    df_result = df_result.drop(columns=['abs(Cohen\'s d)'])  # 필요 없으면 제거

    return df_result

In [38]:
ttest_results = ttest_ab_multiple_verbose_abs_sorted(ab_df, num_cols)
ttest_results

/tmp/ipython-input-37-1371196798.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return (x.mean() - y.mean()) / pooled_std
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                feature  t-statistic  p-value  Cohen's d significance
0      이용개월수_할부_무이자_R6M     -13.5899   0.0000    -0.9147          ***
1          이용개월수_할부_R6M     -14.4447   0.0000    -0.9047          ***
2      이용개월수_할부_무이자_R3M     -12.8663   0.0000    -0.8795          ***
3     이용개월수_할부_무이자_R12M     -17.5522   0.0000    -0.8712          ***
4       이용건수_할부_무이자_R3M     -11.9087   0.0000    -0.8671          ***
5       이용건수_할부_무이자_R6M     -11.0264   0.0000    -0.8513          ***
6          이용개월수_할부_R3M     -13.0551   0.0000    -0.8483          ***
7         이용개월수_할부_R12M     -15.8418   0.0000    -0.8462          ***
8       이용건수_할부_무이자_B0M     -11.0421   0.0000    -0.8438          ***
9           이용건수_할부_R3M     -11.5094   0.0000    -0.8371          ***
10          이용건수_할부_R6M     -10.7816   0.0000    -0.8274          ***
11          이용건수_할부_B0M     -10.7345   0.0000    -0.8220          ***
12         이용개월수_체크_R3M      -6.0212   0.0000    -0.7889          ***
13     이용건수_할부_무이자_R12M      -9.5418   0.0000    -0.7780          ***
14         이용건수_할부_R12M      -9.3172   0.0000    -0.7705          ***
15         이용개월수_체크_R6M      -5.8036   0.0000    -0.7640          ***
16      이용금액_할부_무이자_R3M     -10.4933   0.0000    -0.7459          ***
17      이용금액_할부_무이자_B0M     -10.0468   0.0000    -0.7433          ***
18      이용금액_할부_무이자_R6M     -11.3210   0.0000    -0.7425          ***
19        이용후경과월_할부_무이자      18.4393   0.0000     0.7191          ***
20            이용후경과월_할부      18.0753   0.0000     0.7078          ***
21            이용후경과월_체크       5.2488   0.0000     0.6908          ***
22          이용금액_할부_B0M      -9.5735   0.0000    -0.6901          ***
23        이용개월수_체크_R12M      -5.2461   0.0000    -0.6855          ***
24          이용금액_할부_R3M      -9.8680   0.0000    -0.6818          ***
25          이용금액_할부_R6M     -10.4312   0.0000    -0.6793          ***
26     이용금액_할부_무이자_R12M      -8.2578   0.0000    -0.5782          ***
27         이용금액_할부_R12M      -8.2685   0.0000    -0.5729          ***
28          이용건수_체크_B0M      -4.3174   0.0000    -0.5177          ***
29          이용건수_체크_R3M      -4.2077   0.0000    -0.5053          ***
30          이용금액_체크_B0M      -4.3503   0.0000    -0.5034          ***
31          이용금액_체크_R3M      -4.1832   0.0000    -0.4856          ***
32          이용건수_체크_R6M      -3.9206   0.0001    -0.4721          ***
33         이용금액_체크_R12M      -3.7126   0.0003    -0.4682          ***
34   최대이용금액_할부_무이자_R12M      -8.4326   0.0000    -0.4613          ***
35            최종이용일자_체크      -4.8435   0.0000    -0.4533          ***
36       최대이용금액_할부_R12M      -8.0527   0.0000    -0.4448          ***
37          이용금액_체크_R6M      -3.8066   0.0002    -0.4419          ***
38         이용건수_체크_R12M      -3.4572   0.0007    -0.4221          ***
39      최대이용금액_일시불_R12M       6.2165   0.0000     0.4066          ***
40           최종이용일자_카드론      -3.8108   0.0002    -0.3655          ***
41            이용후경과월_CA       3.8300   0.0002     0.3617          ***
42         이용개월수_CA_R6M      -3.8098   0.0002    -0.3559          ***
43        이용개월수_CA_R12M      -3.7594   0.0002    -0.3554          ***
44         이용개월수_CA_R3M      -3.5046   0.0006    -0.3281          ***
45        이용금액_일시불_R12M       3.3803   0.0009     0.2925          ***
46         이용건수_CA_R12M      -3.1195   0.0021    -0.2848           **
47          이용건수_CA_B0M      -2.9028   0.0042    -0.2735           **
48          이용건수_CA_R3M      -2.9286   0.0038    -0.2687           **
49          이용건수_CA_R6M      -2.9070   0.0041    -0.2621           **
50       최대이용금액_체크_R12M      -3.0309   0.0028    -0.2599           **
51         이용금액_일시불_R6M       2.6293   0.0093     0.2557           **
52         이용금액_일시불_B0M       2.6001   0.0101     0.2523            *
53         이용금액_일시불_R3M       2.5709   0.0110     0.2482            *
54        이용개월수_카드론_R6M       7.1022   0.0000     0.2440          ***
55            최종이용일자_CA      -2.7529   0.0065    -0.2285           **
56         이용건수_카드론_R6M       6.5392   0.0000     0.2247          ***
57         이용금액_카드론_R6M       6.5168   0.0000     0.2239          ***
58          이용금액_CA_B0M      -2.3058   0.0222    -0.2116            *
59            최종이용일자_할부      -6.1467   0.0000    -0.2112          ***
60       이용개월수_일시불_R12M      -6.0642   0.0000    -0.2083          ***
61        이용개월수_신판_R12M      -5.9214   0.0000    -0.2034          ***
62          이용금액_CA_R3M      -2.1262   0.0348    -0.1964            *
63       최대이용금액_CA_R12M      -2.4176   0.0165    -0.1958            *
64            이용후경과월_신판       4.0559   0.0001     0.1955          ***
65       이용금액_부분무이자_R3M      -1.2988   0.1959    -0.1760           ns
66      이용금액_할부_유이자_R3M       5.1171   0.0000     0.1758          ***
67          이용금액_CA_R6M      -1.9850   0.0486    -0.1732            *
68        이용개월수_일시불_R6M      -4.9977   0.0000    -0.1717          ***
69         이용개월수_신판_R6M      -4.7832   0.0000    -0.1643          ***
70     이용개월수_할부_유이자_R6M       2.9541   0.0033     0.1526           **
71         이용금액_CA_R12M      -1.7988   0.0736    -0.1525           ns
72        이용개월수_신용_R12M      -4.3563   0.0000    -0.1497          ***
73      이용금액_할부_유이자_R6M       2.4927   0.0132     0.1495            *
74        이용개월수_일시불_R3M      -4.1956   0.0000    -0.1441          ***
75      이용금액_할부_유이자_B0M       4.1389   0.0000     0.1422          ***
76     이용건수_할부_유이자_R12M      -1.3634   0.1745    -0.1410           ns
77         이용개월수_신판_R3M      -3.8703   0.0001    -0.1330          ***
78           최종이용일자_일시불       0.7935   0.4288     0.1308           ns
79           이용후경과월_카드론      -2.2310   0.0264    -0.1305            *
80       이용건수_부분무이자_R6M      -1.0874   0.2785    -0.1298           ns
81        이용개월수_카드론_R3M       3.7670   0.0002     0.1294          ***
82         이용금액_카드론_R3M       3.6221   0.0003     0.1244          ***
83         이용건수_카드론_R3M       3.4839   0.0005     0.1197          ***
84       이용금액_부분무이자_R6M      -1.0140   0.3121    -0.1175           ns
85     이용개월수_할부_유이자_R3M       2.1305   0.0338     0.1148            *
86        이용건수_카드론_R12M      -1.1673   0.2446    -0.1094           ns
87          이용건수_신용_R6M      -1.1024   0.2717    -0.0972           ns
88         이용건수_신용_R12M      -1.0947   0.2751    -0.0967           ns
89       이용건수_부분무이자_R3M      -0.6888   0.4920    -0.0943           ns
90         이용개월수_신용_R6M      -2.6207   0.0089    -0.0900           **
91               이용가맹점수      -1.0221   0.3080    -0.0898           ns
92          이용건수_신판_R6M      -0.9732   0.3317    -0.0863           ns
93         이용건수_신판_R12M      -0.9574   0.3396    -0.0851           ns
94       이용개월수_카드론_R12M      -0.8681   0.3865    -0.0802           ns
95         이용개월수_신용_R3M      -2.2017   0.0279    -0.0756            *
96          이용건수_신용_R3M      -0.8426   0.4005    -0.0746           ns
97          이용건수_신용_B0M      -0.8363   0.4041    -0.0737           ns
98      이용개월수_부분무이자_R6M      -0.6813   0.4966    -0.0737           ns
99      이용개월수_부분무이자_R3M      -0.5382   0.5912    -0.0645           ns
100         이용건수_신판_R3M      -0.7175   0.4739    -0.0639           ns
101         이용건수_신판_B0M      -0.7052   0.4816    -0.0625           ns
102   이용개월수_할부_유이자_R12M      -0.6437   0.5205    -0.0571           ns
103        이용건수_일시불_R6M      -0.6207   0.5355    -0.0557           ns
104  최대이용금액_할부_유이자_R12M      -0.6284   0.5304    -0.0527           ns
105       이용후경과월_할부_유이자       0.5946   0.5528     0.0514           ns
106     이용건수_할부_유이자_R6M       0.7017   0.4836     0.0509           ns
107       이용건수_일시불_R12M      -0.5266   0.5991    -0.0475           ns
108           이용후경과월_신용       0.6416   0.5217     0.0457           ns
109    이용금액_할부_유이자_R12M      -0.5347   0.5934    -0.0428           ns
110        이용건수_일시불_R3M      -0.4333   0.6653    -0.0389           ns
111        이용건수_일시불_B0M      -0.4096   0.6825    -0.0366           ns
112       이용금액_카드론_R12M      -0.3719   0.7104    -0.0359           ns
113           최종이용일자_신판      -0.3956   0.6928    -0.0340           ns
114     이용건수_할부_유이자_R3M       0.3737   0.7090     0.0291           ns
115     최대이용금액_카드론_R12M      -0.2661   0.7905    -0.0283           ns
116     이용건수_할부_유이자_B0M      -0.1822   0.8556    -0.0170           ns
117          이용후경과월_일시불       0.0714   0.9432     0.0081           ns
118    이용개월수_부분무이자_R12M       0.0860   0.9315     0.0076           ns
119           최종이용일자_기본      -0.0757   0.9398    -0.0067           ns
120        이용후경과월_부분무이자       0.0565   0.9550     0.0052           ns
121     이용금액_부분무이자_R12M       0.0503   0.9599     0.0045           ns
122   최대이용금액_부분무이자_R12M       0.0114   0.9909     0.0010           ns
123                기준년월       0.0000   1.0000     0.0000           ns
124        이용건수_카드론_B0M          NaN      NaN        NaN           ns
125        이용금액_카드론_B0M          NaN      NaN        NaN           ns
126     이용건수_부분무이자_R12M          NaN      NaN        NaN           ns

In [39]:

pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² / t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan

In [40]:
def effect_sizes(df):
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            group1 = data[data['Segment'] == data['Segment'].unique()[0]][col]
            group2 = data[data['Segment'] == data['Segment'].unique()[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)

    return result_df1, result_df2

In [41]:
result1, result2 = effect_sizes(ab_df)
display(result1)
display(result2)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                     변수   유형  계수종류    상관계수
0         이용후경과월_할부_무이자  수치형  Eta² 0.23384
1             이용후경과월_할부  수치형  Eta² 0.22677
2     이용개월수_할부_무이자_R12M  수치형  Eta² 0.21664
3         이용개월수_할부_R12M  수치형  Eta² 0.18386
4          이용개월수_할부_R6M  수치형  Eta² 0.15775
5      이용개월수_할부_무이자_R6M  수치형  Eta² 0.14221
6          이용개월수_할부_R3M  수치형  Eta² 0.13269
7      이용개월수_할부_무이자_R3M  수치형  Eta² 0.12938
8       이용건수_할부_무이자_R3M  수치형  Eta² 0.11293
9           이용건수_할부_R3M  수치형  Eta² 0.10627
10      이용금액_할부_무이자_R6M  수치형  Eta² 0.10318
11      이용건수_할부_무이자_B0M  수치형  Eta² 0.09865
12      이용건수_할부_무이자_R6M  수치형  Eta² 0.09840
13          이용건수_할부_R6M  수치형  Eta² 0.09449
14          이용건수_할부_B0M  수치형  Eta² 0.09374
15      이용금액_할부_무이자_R3M  수치형  Eta² 0.08995
16          이용금액_할부_R6M  수치형  Eta² 0.08898
17      이용금액_할부_무이자_B0M  수치형  Eta² 0.08308
18          이용금액_할부_R3M  수치형  Eta² 0.08039
19          이용금액_할부_B0M  수치형  Eta² 0.07602
20     이용건수_할부_무이자_R12M  수치형  Eta² 0.07555
21         이용건수_할부_R12M  수치형  Eta² 0.07229
22   최대이용금액_할부_무이자_R12M  수치형  Eta² 0.06000
23         이용금액_할부_R12M  수치형  Eta² 0.05782
24     이용금액_할부_무이자_R12M  수치형  Eta² 0.05768
25       최대이용금액_할부_R12M  수치형  Eta² 0.05501
26        이용개월수_카드론_R6M  수치형  Eta² 0.04332
27         이용건수_카드론_R6M  수치형  Eta² 0.03697
28         이용금액_카드론_R6M  수치형  Eta² 0.03672
29      최대이용금액_일시불_R12M  수치형  Eta² 0.03353
30            최종이용일자_할부  수치형  Eta² 0.03280
31       이용개월수_일시불_R12M  수치형  Eta² 0.03196
32         이용개월수_체크_R3M  수치형  Eta² 0.03152
33        이용개월수_신판_R12M  수치형  Eta² 0.03051
34         이용개월수_체크_R6M  수치형  Eta² 0.02935
35            이용후경과월_체크  수치형  Eta² 0.02413
36        이용개월수_체크_R12M  수치형  Eta² 0.02411
37      이용금액_할부_유이자_R3M  수치형  Eta² 0.02297
38        이용개월수_일시불_R6M  수치형  Eta² 0.02193
39            최종이용일자_체크  수치형  Eta² 0.02062
40         이용개월수_신판_R6M  수치형  Eta² 0.02012
41        이용개월수_신용_R12M  수치형  Eta² 0.01675
42          이용금액_체크_B0M  수치형  Eta² 0.01670
43          이용건수_체크_B0M  수치형  Eta² 0.01646
44          이용건수_체크_R3M  수치형  Eta² 0.01564
45        이용개월수_일시불_R3M  수치형  Eta² 0.01556
46          이용금액_체크_R3M  수치형  Eta² 0.01547
47      이용금액_할부_유이자_B0M  수치형  Eta² 0.01514
48            이용후경과월_신판  수치형  Eta² 0.01455
49          이용건수_체크_R6M  수치형  Eta² 0.01361
50         이용개월수_신판_R3M  수치형  Eta² 0.01327
51            이용후경과월_CA  수치형  Eta² 0.01300
52           최종이용일자_카드론  수치형  Eta² 0.01287
53         이용개월수_CA_R6M  수치형  Eta² 0.01286
54          이용금액_체크_R6M  수치형  Eta² 0.01284
55        이용개월수_카드론_R3M  수치형  Eta² 0.01258
56        이용개월수_CA_R12M  수치형  Eta² 0.01253
57         이용금액_체크_R12M  수치형  Eta² 0.01222
58         이용금액_카드론_R3M  수치형  Eta² 0.01164
59         이용개월수_CA_R3M  수치형  Eta² 0.01090
60         이용건수_카드론_R3M  수치형  Eta² 0.01078
61         이용건수_체크_R12M  수치형  Eta² 0.01062
62        이용금액_일시불_R12M  수치형  Eta² 0.01015
63         이용건수_CA_R12M  수치형  Eta² 0.00866
64       최대이용금액_체크_R12M  수치형  Eta² 0.00818
65     이용개월수_할부_유이자_R6M  수치형  Eta² 0.00777
66          이용건수_CA_R3M  수치형  Eta² 0.00764
67          이용건수_CA_R6M  수치형  Eta² 0.00753
68          이용건수_CA_B0M  수치형  Eta² 0.00751
69            최종이용일자_CA  수치형  Eta² 0.00676
70         이용금액_일시불_R6M  수치형  Eta² 0.00617
71         이용개월수_신용_R6M  수치형  Eta² 0.00613
72         이용금액_일시불_B0M  수치형  Eta² 0.00603
73         이용금액_일시불_R3M  수치형  Eta² 0.00590
74      이용금액_할부_유이자_R6M  수치형  Eta² 0.00555
75       최대이용금액_CA_R12M  수치형  Eta² 0.00522
76          이용금액_CA_B0M  수치형  Eta² 0.00475
77           이용후경과월_카드론  수치형  Eta² 0.00445
78         이용개월수_신용_R3M  수치형  Eta² 0.00433
79     이용개월수_할부_유이자_R3M  수치형  Eta² 0.00406
80          이용금액_CA_R3M  수치형  Eta² 0.00404
81          이용금액_CA_R6M  수치형  Eta² 0.00352
82         이용금액_CA_R12M  수치형  Eta² 0.00290
83     이용건수_할부_유이자_R12M  수치형  Eta² 0.00167
84       이용금액_부분무이자_R3M  수치형  Eta² 0.00151
85        이용건수_카드론_R12M  수치형  Eta² 0.00122
86          이용건수_신용_R6M  수치형  Eta² 0.00109
87         이용건수_신용_R12M  수치형  Eta² 0.00107
88       이용건수_부분무이자_R6M  수치형  Eta² 0.00106
89               이용가맹점수  수치형  Eta² 0.00094
90       이용금액_부분무이자_R6M  수치형  Eta² 0.00092
91          이용건수_신판_R6M  수치형  Eta² 0.00085
92         이용건수_신판_R12M  수치형  Eta² 0.00082
93       이용개월수_카드론_R12M  수치형  Eta² 0.00068
94          이용건수_신용_R3M  수치형  Eta² 0.00064
95          이용건수_신용_B0M  수치형  Eta² 0.00063
96           최종이용일자_일시불  수치형  Eta² 0.00056
97          이용건수_신판_R3M  수치형  Eta² 0.00046
98          이용건수_신판_B0M  수치형  Eta² 0.00045
99      이용건수_할부_유이자_R6M  수치형  Eta² 0.00044
100      이용건수_부분무이자_R3M  수치형  Eta² 0.00043
101     이용개월수_부분무이자_R6M  수치형  Eta² 0.00042
102   이용개월수_할부_유이자_R12M  수치형  Eta² 0.00037
103           이용후경과월_신용  수치형  Eta² 0.00037
104  최대이용금액_할부_유이자_R12M  수치형  Eta² 0.00035
105        이용건수_일시불_R6M  수치형  Eta² 0.00035
106       이용후경과월_할부_유이자  수치형  Eta² 0.00032
107     이용개월수_부분무이자_R3M  수치형  Eta² 0.00026
108    이용금액_할부_유이자_R12M  수치형  Eta² 0.00026
109       이용건수_일시불_R12M  수치형  Eta² 0.00025
110        이용건수_일시불_R3M  수치형  Eta² 0.00017
111        이용건수_일시불_B0M  수치형  Eta² 0.00015
112           최종이용일자_신판  수치형  Eta² 0.00014
113     이용건수_할부_유이자_R3M  수치형  Eta² 0.00013
114       이용금액_카드론_R12M  수치형  Eta² 0.00012
115     최대이용금액_카드론_R12M  수치형  Eta² 0.00006
116     이용건수_할부_유이자_B0M  수치형  Eta² 0.00003
117    이용개월수_부분무이자_R12M  수치형  Eta² 0.00001
118           최종이용일자_기본  수치형  Eta² 0.00001
119          이용후경과월_일시불  수치형  Eta² 0.00000
120        이용후경과월_부분무이자  수치형  Eta² 0.00000
121     이용금액_부분무이자_R12M  수치형  Eta² 0.00000
122   최대이용금액_부분무이자_R12M  수치형  Eta² 0.00000
123                기준년월  수치형  Eta² 0.00000
124        이용건수_카드론_B0M  수치형  Eta²     NaN
125        이용금액_카드론_B0M  수치형  Eta²     NaN
126     이용건수_부분무이자_R12M  수치형  Eta²     NaN

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000

In [43]:
#result1과 result2, 그리고 ttest_results를 각각 parquet으로 저장한다.
result1.to_parquet('/content/drive/MyDrive/승인매출ab_df3-1_설명력.parquet', index=False)
ttest_results.to_parquet('/content/drive/MyDrive/ttest_results3-1.parquet', index=False)