In [2]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False
import gc


# 인코더 추가
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
#VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
#상수항추가
from statsmodels.tools.tools import add_constant
# 카이제곱, ANOVA
from scipy.stats import chi2_contingency
from scipy.stats import f_oneway
#Turkeyhsd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 데이터 불러오기

In [3]:
# parquet 파일 데이터를 읽어온다.
# x 값으로 쓸 데이터
df1_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201807_train_승인매출정보.parquet')
df2_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201808_train_승인매출정보.parquet')
df3_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201809_train_승인매출정보.parquet')
df4_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201810_train_승인매출정보.parquet')
df5_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201811_train_승인매출정보.parquet')
df6_train = pd.read_parquet('/content/drive/MyDrive/3.승인매출정보/201812_train_승인매출정보.parquet')

In [16]:
# 결과데이터를 불러온다.
segment_df = pd.read_csv('/content/drive/MyDrive/Segment.csv')
segment_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [5]:
# 데이터프레임의 컬럼 이름을 리스트에 담는다.
column_list = df1_train.columns.tolist()

In [6]:
print(column_list)

['기준년월', 'ID', '최종이용일자_기본', '최종이용일자_신판', '최종이용일자_CA', '최종이용일자_카드론', '최종이용일자_체크', '최종이용일자_일시불', '최종이용일자_할부', '이용건수_신용_B0M', '이용건수_신판_B0M', '이용건수_일시불_B0M', '이용건수_할부_B0M', '이용건수_할부_유이자_B0M', '이용건수_할부_무이자_B0M', '이용건수_부분무이자_B0M', '이용건수_CA_B0M', '이용건수_체크_B0M', '이용건수_카드론_B0M', '이용금액_일시불_B0M', '이용금액_할부_B0M', '이용금액_할부_유이자_B0M', '이용금액_할부_무이자_B0M', '이용금액_부분무이자_B0M', '이용금액_CA_B0M', '이용금액_체크_B0M', '이용금액_카드론_B0M', '이용후경과월_신용', '이용후경과월_신판', '이용후경과월_일시불', '이용후경과월_할부', '이용후경과월_할부_유이자', '이용후경과월_할부_무이자', '이용후경과월_부분무이자', '이용후경과월_CA', '이용후경과월_체크', '이용후경과월_카드론', '이용건수_신용_R12M', '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_할부_R12M', '이용건수_할부_유이자_R12M', '이용건수_할부_무이자_R12M', '이용건수_부분무이자_R12M', '이용건수_CA_R12M', '이용건수_체크_R12M', '이용건수_카드론_R12M', '이용금액_일시불_R12M', '이용금액_할부_R12M', '이용금액_할부_유이자_R12M', '이용금액_할부_무이자_R12M', '이용금액_부분무이자_R12M', '이용금액_CA_R12M', '이용금액_체크_R12M', '이용금액_카드론_R12M', '최대이용금액_일시불_R12M', '최대이용금액_할부_R12M', '최대이용금액_할부_유이자_R12M', '최대이용금액_할부_무이자_R12M', '최대이용금액_부분무이자_R12M', '최대이용금액_CA_R12M', '최대이용금액_체크_R12M', '최대이용금액_카드론_R12M', '이용개월수_신용_R12M', '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_할부_유이자_R12M', '이용개월수_할부_무이자_R12M', '이용개월수_부분무이자_R12M', '이용개월수_CA_R12M', '이용개월수_체크_R12M', '이용개월수_카드론_R12M', '이용건수_신용_R6M', '이용건수_신판_R6M', '이용건수_일시불_R6M', '이용건수_할부_R6M', '이용건수_할부_유이자_R6M', '이용건수_할부_무이자_R6M', '이용건수_부분무이자_R6M', '이용건수_CA_R6M', '이용건수_체크_R6M', '이용건수_카드론_R6M', '이용금액_일시불_R6M', '이용금액_할부_R6M', '이용금액_할부_유이자_R6M', '이용금액_할부_무이자_R6M', '이용금액_부분무이자_R6M', '이용금액_CA_R6M', '이용금액_체크_R6M', '이용금액_카드론_R6M', '이용개월수_신용_R6M', '이용개월수_신판_R6M', '이용개월수_일시불_R6M', '이용개월수_할부_R6M', '이용개월수_할부_유이자_R6M', '이용개월수_할부_무이자_R6M', '이용개월수_부분무이자_R6M', '이용개월수_CA_R6M', '이용개월수_체크_R6M', '이용개월수_카드론_R6M', '이용건수_신용_R3M', '이용건수_신판_R3M', '이용건수_일시불_R3M', '이용건수_할부_R3M', '이용건수_할부_유이자_R3M', '이용건수_할부_무이자_R3M', '이용건수_부분무이자_R3M', '이용건수_CA_R3M', '이용건수_체크_R3M', '이용건수_카드론_R3M', '이용금액_일시불_R3M', '이용금액_할부_R3M', '이용금액_할부_유이자_R3M', '이용금액_할부_무이자_R3M', '이용금액_부분무이자_R3M', '이용금액_CA_R3M', '이용금액_체크_R3M', '이용금액_카드론_R3M', '이용개월수_신용_R3M', '이용개월수_신판_R3M', '이용개월수_일시불_R3M', '이용개월수_할부_R3M', '이용개월수_할부_유이자_R3M', '이용개월수_할부_무이자_R3M', '이용개월수_부분무이자_R3M', '이용개월수_CA_R3M', '이용개월수_체크_R3M', '이용개월수_카드론_R3M', '이용가맹점수', '이용금액_해외', '쇼핑_도소매_이용금액', '쇼핑_백화점_이용금액', '쇼핑_마트_이용금액', '쇼핑_슈퍼마켓_이용금액', '쇼핑_편의점_이용금액', '쇼핑_아울렛_이용금액', '쇼핑_온라인_이용금액', '쇼핑_기타_이용금액', '교통_주유이용금액', '교통_정비이용금액', '교통_통행료이용금액', '교통_버스지하철이용금액', '교통_택시이용금액', '교통_철도버스이용금액', '여유_운동이용금액', '여유_Pet이용금액', '여유_공연이용금액', '여유_공원이용금액', '여유_숙박이용금액', '여유_여행이용금액', '여유_항공이용금액', '여유_기타이용금액', '납부_통신비이용금액', '납부_관리비이용금액', '납부_렌탈료이용금액', '납부_가스전기료이용금액', '납부_보험료이용금액', '납부_유선방송이용금액', '납부_건강연금이용금액', '납부_기타이용금액', '_1순위업종', '_1순위업종_이용금액', '_2순위업종', '_2순위업종_이용금액', '_3순위업종', '_3순위업종_이용금액', '_1순위쇼핑업종', '_1순위쇼핑업종_이용금액', '_2순위쇼핑업종', '_2순위쇼핑업종_이용금액', '_3순위쇼핑업종', '_3순위쇼핑업종_이용금액', '_1순위교통업종', '_1순위교통업종_이용금액', '_2순위교통업종', '_2순위교통업종_이용금액', '_3순위교통업종', '_3순위교통업종_이용금액', '_1순위여유업종', '_1순위여유업종_이용금액', '_2순위여유업종', '_2순위여유업종_이용금액', '_3순위여유업종', '_3순위여유업종_이용금액', '_1순위납부업종', '_1순위납부업종_이용금액', '_2순위납부업종', '_2순위납부업종_이용금액', '_3순위납부업종', '_3순위납부업종_이용금액', '할부건수_3M_R12M', '할부건수_6M_R12M', '할부건수_12M_R12M', '할부건수_14M_R12M', '할부금액_3M_R12M', '할부금액_6M_R12M', '할부금액_12M_R12M', '할부금액_14M_R12M', '할부건수_유이자_3M_R12M', '할부건수_유이자_6M_R12M', '할부건수_유이자_12M_R12M', '할부건수_유이자_14M_R12M', '할부금액_유이자_3M_R12M', '할부금액_유이자_6M_R12M', '할부금액_유이자_12M_R12M', '할부금액_유이자_14M_R12M', '할부건수_무이자_3M_R12M', '할부건수_무이자_6M_R12M', '할부건수_무이자_12M_R12M', '할부건수_무이자_14M_R12M', '할부금액_무이자_3M_R12M', '할부금액_무이자_6M_R12M', '할부금액_무이자_12M_R12M', '할부금액_무이자_14M_R12M', '할부건수_부분_3M_R12M', '할부건수_부분_6M_R12M', '할부건수_부분_12M_R12M', '할부건수_부분_14M_R12M', '할부금액_부분_3M_R12M', '할부금액_부분_6M_R12M', '할부금액_부분_12M_R12M', '할부금액_부분_14M_R12M', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M', '이용금액_간편결제_R6M', '이용금액_당사페이_R6M', '이용금액_당사기타_R6M', '이용금액_A페이_R6M', '이용금액_B페이_R6M', '이용금액_C페이_R6M', '이용금액_D페이_R6M', '이용건수_간편결제_R6M', '이용건수_당사페이_R6M', '이용건수_당사기타_R6M', '이용건수_A페이_R6M', '이용건수_B페이_R6M', '이용건수_C페이_R6M', '이용건수_D페이_R6M', '이용금액_간편결제_R3M', '이용금액_당사페이_R3M', '이용금액_당사기타_R3M', '이용금액_A페이_R3M', '이용금액_B페이_R3M', '이용금액_C페이_R3M', '이용금액_D페이_R3M', '이용건수_간편결제_R3M', '이용건수_당사페이_R3M', '이용건수_당사기타_R3M', '이용건수_A페이_R3M', '이용건수_B페이_R3M', '이용건수_C페이_R3M', '이용건수_D페이_R3M', '이용금액_간편결제_B0M', '이용금액_당사페이_B0M', '이용금액_당사기타_B0M', '이용금액_A페이_B0M', '이용금액_B페이_B0M', '이용금액_C페이_B0M', '이용금액_D페이_B0M', '이용건수_간편결제_B0M', '이용건수_당사페이_B0M', '이용건수_당사기타_B0M', '이용건수_A페이_B0M', '이용건수_B페이_B0M', '이용건수_C페이_B0M', '이용건수_D페이_B0M', '이용개월수_선결제_R6M', '이용횟수_선결제_R6M', '이용금액_선결제_R6M', '이용건수_선결제_R6M', '이용횟수_선결제_R3M', '이용금액_선결제_R3M', '이용건수_선결제_R3M', '이용횟수_선결제_B0M', '이용금액_선결제_B0M', '이용건수_선결제_B0M', '이용횟수_연체_R6M', '이용금액_연체_R6M', '이용횟수_연체_R3M', '이용금액_연체_R3M', '이용횟수_연체_B0M', '이용금액_연체_B0M', '이용개월수_전체_R6M', '이용개월수_전체_R3M', '이용개월수_결제일_R6M', '이용개월수_결제일_R3M', '가맹점매출금액_B1M', '가맹점매출금액_B2M', '정상청구원금_B0M', '선입금원금_B0M', '정상입금원금_B0M', '연체입금원금_B0M', '정상청구원금_B2M', '선입금원금_B2M', '정상입금원금_B2M', '연체입금원금_B2M', '정상청구원금_B5M', '선입금원금_B5M', '정상입금원금_B5M', '연체입금원금_B5M', '건수_할부전환_R6M', '건수_할부전환_R3M', '금액_할부전환_R6M', '금액_할부전환_R3M', '연속무실적개월수_기본_24M_카드', '연속유실적개월수_기본_24M_카드', '신청건수_ATM_CA_B0', '신청건수_ATM_CL_B0', '신청건수_ATM_CA_R6M', '신청건수_ATM_CL_R6M', '승인거절건수_B0M', '승인거절건수_한도초과_B0M', '승인거절건수_BL_B0M', '승인거절건수_입력오류_B0M', '승인거절건수_기타_B0M', '승인거절건수_R3M', '승인거절건수_한도초과_R3M', '승인거절건수_BL_R3M', '승인거절건수_입력오류_R3M', '승인거절건수_기타_R3M', '이용금액대']

In [7]:
# 슬라이싱
column_list = column_list[223:309]

- 이용개월수_D페이_R6M까지 슬라이싱 되어야함

In [8]:
print(column_list)

['RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M']

In [9]:
df1_train = df1_train[column_list]

In [10]:
df2_train = df2_train[column_list]
df3_train = df3_train[column_list]
df4_train = df4_train[column_list]
df5_train = df5_train[column_list]
df6_train = df6_train[column_list]

In [11]:
combined_df = pd.concat([df1_train, df2_train, df3_train, df4_train, df5_train, df6_train],
                         axis=0,        # 행 방향
                         ignore_index=True)  # 인덱스 초기화

In [17]:
segment_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [18]:
# 세그먼트와 데이터를 합쳐준다.

all_df = pd.concat([segment_df,combined_df], axis = 1)
all_df

,기준년월,ID,Segment,RP건수_B0M,RP금액_B0M,RP유형건수_B0M,RP건수_통신_B0M,RP건수_아파트_B0M,RP건수_제휴사서비스직접판매_B0M,RP건수_렌탈_B0M,...,이용금액_페이_오프라인_B0M,이용건수_페이_온라인_B0M,이용건수_페이_오프라인_B0M,이용개월수_간편결제_R6M,이용개월수_당사페이_R6M,이용개월수_당사기타_R6M,이용개월수_A페이_R6M,이용개월수_B페이_R6M,이용개월수_C페이_R6M,이용개월수_D페이_R6M
0,201807,TRAIN_000000,D,2,147,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,201807,TRAIN_000001,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,201807,TRAIN_000002,C,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
3,201807,TRAIN_000003,D,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,201807,TRAIN_000004,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,D,2,196,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,201812,TRAIN_399997,C,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399998,201812,TRAIN_399998,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
print(all_df.isna().sum().to_string())

기준년월                           0
ID                             0
Segment                        0
RP건수_B0M                       0
RP금액_B0M                       0
RP유형건수_B0M                     0
RP건수_통신_B0M                    0
RP건수_아파트_B0M                   0
RP건수_제휴사서비스직접판매_B0M            0
RP건수_렌탈_B0M                    0
RP건수_가스_B0M                    0
RP건수_전기_B0M                    0
RP건수_보험_B0M                    0
RP건수_학습비_B0M                   0
RP건수_유선방송_B0M                  0
RP건수_건강_B0M                    0
RP건수_교통_B0M                    0
RP후경과월                         0
RP후경과월_통신                      0
RP후경과월_아파트                     0
RP후경과월_제휴사서비스직접판매              0
RP후경과월_렌탈                      0
RP후경과월_가스                      0
RP후경과월_전기                      0
RP후경과월_보험                      0
RP후경과월_학습비                     0
RP후경과월_유선방송                    0
RP후경과월_건강                      0
RP후경과월_교통                      0
증감_RP건수_전월                     0
증감_RP유형건수_전월                   0
증감_RP건수_통신_전월                  0
증감_RP건수_아파트_전월                 0
증감_RP건수_제휴사서비스직접판매_전월          0
증감_RP건수_렌탈_전월                  0
증감_RP건수_가스_전월                  0
증감_RP건수_전기_전월                  0
증감_RP건수_보험_전월                  0
증감_RP건수_학습비_전월                 0
증감_RP건수_유선방송_전월                0
증감_RP건수_건강_전월                  0
증감_RP건수_교통_전월                  0
최초카드론이용경과월                     0
최종카드론이용경과월                     0
카드론이용건수_누적                     0
카드론이용월수_누적                     0
카드론이용금액_누적                     0
최종카드론_금융상환방식코드           1958126
최종카드론_신청경로코드             1958226
최종카드론_대출이율                     0
최종카드론_대출일자               1988330
최종카드론_대출월수                     0
최종카드론_거치개월수                    0
최종카드론_대출금액                     0
이용개월수_온라인_R6M                  0
이용개월수_오프라인_R6M                 0
이용금액_온라인_R6M                   0
이용금액_오프라인_R6M                  0
이용건수_온라인_R6M                   0
이용건수_오프라인_R6M                  0
이용금액_온라인_R3M                   0
이용금액_오프라인_R3M                  0
이용건수_온라인_R3M                   0
이용건수_오프라인_R3M                  0
이용금액_온라인_B0M                   0
이용금액_오프라인_B0M                  0
이용건수_온라인_B0M                   0
이용건수_오프라인_B0M                  0
이용개월수_페이_온라인_R6M               0
이용개월수_페이_오프라인_R6M              0
이용금액_페이_온라인_R6M                0
이용금액_페이_오프라인_R6M               0
이용건수_페이_온라인_R6M                0
이용건수_페이_오프라인_R6M               0
이용금액_페이_온라인_R3M                0
이용금액_페이_오프라인_R3M               0
이용건수_페이_온라인_R3M                0
이용건수_페이_오프라인_R3M               0
이용금액_페이_온라인_B0M                0
이용금액_페이_오프라인_B0M               0
이용건수_페이_온라인_B0M                0
이용건수_페이_오프라인_B0M               0
이용개월수_간편결제_R6M                 0
이용개월수_당사페이_R6M                 0
이용개월수_당사기타_R6M                 0
이용개월수_A페이_R6M                  0
이용개월수_B페이_R6M                  0
이용개월수_C페이_R6M                  0
이용개월수_D페이_R6M                  0

In [12]:
for col in column_list:
    try:
        var_value = all_df[col].var()
        print(f"{col}: {var_value:.2f}")
    except TypeError:
        print(f"❌ 분산 계산 불가 (문자열 포함): {col}")

RP건수_B0M: 1.25
RP금액_B0M: 785702.14
RP유형건수_B0M: 0.71
RP건수_통신_B0M: 0.36
RP건수_아파트_B0M: 0.03
RP건수_제휴사서비스직접판매_B0M: 0.10
RP건수_렌탈_B0M: 0.00
RP건수_가스_B0M: 0.01
RP건수_전기_B0M: 0.00
RP건수_보험_B0M: 0.01
RP건수_학습비_B0M: 0.00
RP건수_유선방송_B0M: 0.00
RP건수_건강_B0M: 0.00
RP건수_교통_B0M: 0.55
RP후경과월: 8.64
RP후경과월_통신: 6.89
RP후경과월_아파트: 1.10
RP후경과월_제휴사서비스직접판매: 3.46
RP후경과월_렌탈: 0.18
RP후경과월_가스: 0.30
RP후경과월_전기: 0.14
RP후경과월_보험: 0.39
RP후경과월_학습비: 0.03
RP후경과월_유선방송: 0.00
RP후경과월_건강: 0.00
RP후경과월_교통: 6.08
증감_RP건수_전월: 0.08
증감_RP유형건수_전월: 0.02
증감_RP건수_통신_전월: 0.01
증감_RP건수_아파트_전월: 0.00
증감_RP건수_제휴사서비스직접판매_전월: 0.00
증감_RP건수_렌탈_전월: 0.00
증감_RP건수_가스_전월: 0.00
증감_RP건수_전기_전월: 0.00
증감_RP건수_보험_전월: 0.00
증감_RP건수_학습비_전월: 0.00
증감_RP건수_유선방송_전월: 0.00
증감_RP건수_건강_전월: 0.00
증감_RP건수_교통_전월: 0.05
최초카드론이용경과월: 133672.76
최종카드론이용경과월: 134678.57
카드론이용건수_누적: 3.80
카드론이용월수_누적: 2.74
카드론이용금액_누적: 7299260051.79
최종카드론_금융상환방식코드: 1.70
❌ 분산 계산 불가 (문자열 포함): 최종카드론_신청경로코드
최종카드론_대출이율: 35.65
최종카드론_대출일자: 170896323.05
최종카드론_대출월수: 84.71
최종카드론_거치개월수: 1.13
최종카드론_대출금액: 622323454.95
이용개월수_온라인_R6M: 5.96
이용개월수_오프라인_R6M: 5.83
이용금액_온라인_R6M: 73641570.72
이용금액_오프라인_R6M: 1155934504.21
이용건수_온라인_R6M: 214.65
이용건수_오프라인_R6M: 11633.19
이용금액_온라인_R3M: 12434024.54
이용금액_오프라인_R3M: 228934717.91
이용건수_온라인_R3M: 52.84
이용건수_오프라인_R3M: 2447.63
이용금액_온라인_B0M: 887617.86
이용금액_오프라인_B0M: 19636209.09
이용건수_온라인_B0M: 6.21
이용건수_오프라인_B0M: 228.45
이용개월수_페이_온라인_R6M: 5.23
이용개월수_페이_오프라인_R6M: 1.66
이용금액_페이_온라인_R6M: 53901254.94
이용금액_페이_오프라인_R6M: 8883269.83
이용건수_페이_온라인_R6M: 17.03
이용건수_페이_오프라인_R6M: 1.73
이용금액_페이_온라인_R3M: 9530670.53
이용금액_페이_오프라인_R3M: 1604542.58
이용건수_페이_온라인_R3M: 3.72
이용건수_페이_오프라인_R3M: 0.49
이용금액_페이_온라인_B0M: 808496.24
이용금액_페이_오프라인_B0M: 151478.78
이용건수_페이_온라인_B0M: 0.35
이용건수_페이_오프라인_B0M: 0.06
이용개월수_간편결제_R6M: 5.65
이용개월수_당사페이_R6M: 0.00
이용개월수_당사기타_R6M: 0.15
이용개월수_A페이_R6M: 1.74
이용개월수_B페이_R6M: 0.09
이용개월수_C페이_R6M: 0.09
이용개월수_D페이_R6M: 0.04

In [13]:
def print_value_counts(df, columns=None, dropna=False):

    if columns is None:
        columns = df.columns.tolist()

    for col in columns:
        print(f"\n[🔢 Value Counts for '{col}']\n")
        print(df[col].value_counts(dropna=dropna))

In [14]:
zero_variance_cols  = []
# 각 컬럼별 분산 계산
for col in column_list:
    try:
        var_value = all_df[col].var()
        if var_value == 0:
            zero_variance_cols.append(col)
    except TypeError:
        # 숫자형이 아닌 경우 무시
        pass

# 결과 출력
print("📌 분산이 0인 컬럼:")
for col in zero_variance_cols:
    print(f"{col}")

📌 분산이 0인 컬럼:
RP건수_유선방송_B0M
RP건수_건강_B0M
RP후경과월_유선방송
RP후경과월_건강
증감_RP건수_유선방송_전월
증감_RP건수_건강_전월
이용개월수_당사페이_R6M

In [15]:
print_value_counts(all_df, columns=zero_variance_cols)

[🔢 Value Counts for 'RP건수_유선방송_B0M']

RP건수_유선방송_B0M
0    2400000
Name: count, dtype: int64

[🔢 Value Counts for 'RP건수_건강_B0M']

RP건수_건강_B0M
0    2400000
Name: count, dtype: int64

[🔢 Value Counts for 'RP후경과월_유선방송']

RP후경과월_유선방송
6    2400000
Name: count, dtype: int64

[🔢 Value Counts for 'RP후경과월_건강']

RP후경과월_건강
6    2400000
Name: count, dtype: int64

[🔢 Value Counts for '증감_RP건수_유선방송_전월']

증감_RP건수_유선방송_전월
0    2400000
Name: count, dtype: int64

[🔢 Value Counts for '증감_RP건수_건강_전월']

증감_RP건수_건강_전월
0    2400000
Name: count, dtype: int64

[🔢 Value Counts for '이용개월수_당사페이_R6M']

이용개월수_당사페이_R6M
0    2400000
Name: count, dtype: int64

- 값을 하나만 가진 데이터값은 상관관계 분석이나 추후 학습에 방해되므로 drop
- 빼야할 컬럼 []

In [ ]:
10/0

In [20]:
all_df.drop(['RP건수_유선방송_B0M','RP건수_건강_B0M','RP후경과월_유선방송',
'RP후경과월_건강','증감_RP건수_유선방송_전월','증감_RP건수_건강_전월','이용개월수_당사페이_R6M'], axis=1, inplace=True)

### 변수간 관계파악
Anova -> ETA제곱
카이제곱 -> 크레이머스V

In [17]:
print(column_list)

['RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_유선방송_B0M', 'RP건수_건강_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_유선방송', 'RP후경과월_건강', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_유선방송_전월', '증감_RP건수_건강_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_신청경로코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사페이_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M']

In [14]:
# 크레머V와 eta를 구하기 위한 함수
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

def eta_squared(anova_ss_between, total_ss):
    return anova_ss_between / total_ss if total_ss != 0 else np.nan

In [21]:
# 수치형/범주형 자동 구분
num_cols = all_df.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = all_df.select_dtypes(exclude=[np.number]).columns.tolist()

In [22]:
print(cat_cols)

['ID', 'Segment', '최종카드론_신청경로코드']

In [ ]:
del cat_cols[0]

In [23]:
print(cat_cols)

['ID', 'Segment', '최종카드론_신청경로코드']

In [24]:
print(num_cols)

['기준년월', 'RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M']

In [ ]:
del num_cols[0]

In [ ]:
print(num_cols)

['RP건수_B0M', 'RP금액_B0M', 'RP유형건수_B0M', 'RP건수_통신_B0M', 'RP건수_아파트_B0M', 'RP건수_제휴사서비스직접판매_B0M', 'RP건수_렌탈_B0M', 'RP건수_가스_B0M', 'RP건수_전기_B0M', 'RP건수_보험_B0M', 'RP건수_학습비_B0M', 'RP건수_교통_B0M', 'RP후경과월', 'RP후경과월_통신', 'RP후경과월_아파트', 'RP후경과월_제휴사서비스직접판매', 'RP후경과월_렌탈', 'RP후경과월_가스', 'RP후경과월_전기', 'RP후경과월_보험', 'RP후경과월_학습비', 'RP후경과월_교통', '증감_RP건수_전월', '증감_RP유형건수_전월', '증감_RP건수_통신_전월', '증감_RP건수_아파트_전월', '증감_RP건수_제휴사서비스직접판매_전월', '증감_RP건수_렌탈_전월', '증감_RP건수_가스_전월', '증감_RP건수_전기_전월', '증감_RP건수_보험_전월', '증감_RP건수_학습비_전월', '증감_RP건수_교통_전월', '최초카드론이용경과월', '최종카드론이용경과월', '카드론이용건수_누적', '카드론이용월수_누적', '카드론이용금액_누적', '최종카드론_금융상환방식코드', '최종카드론_대출이율', '최종카드론_대출일자', '최종카드론_대출월수', '최종카드론_거치개월수', '최종카드론_대출금액', '이용개월수_온라인_R6M', '이용개월수_오프라인_R6M', '이용금액_온라인_R6M', '이용금액_오프라인_R6M', '이용건수_온라인_R6M', '이용건수_오프라인_R6M', '이용금액_온라인_R3M', '이용금액_오프라인_R3M', '이용건수_온라인_R3M', '이용건수_오프라인_R3M', '이용금액_온라인_B0M', '이용금액_오프라인_B0M', '이용건수_온라인_B0M', '이용건수_오프라인_B0M', '이용개월수_페이_온라인_R6M', '이용개월수_페이_오프라인_R6M', '이용금액_페이_온라인_R6M', '이용금액_페이_오프라인_R6M', '이용건수_페이_온라인_R6M', '이용건수_페이_오프라인_R6M', '이용금액_페이_온라인_R3M', '이용금액_페이_오프라인_R3M', '이용건수_페이_온라인_R3M', '이용건수_페이_오프라인_R3M', '이용금액_페이_온라인_B0M', '이용금액_페이_오프라인_B0M', '이용건수_페이_온라인_B0M', '이용건수_페이_오프라인_B0M', '이용개월수_간편결제_R6M', '이용개월수_당사기타_R6M', '이용개월수_A페이_R6M', '이용개월수_B페이_R6M', '이용개월수_C페이_R6M', '이용개월수_D페이_R6M']

In [ ]:
anova = []
chi = []

for col in all_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = all_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(all_df[col], all_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df1 = pd.DataFrame(anova)
result_df2 = pd.DataFrame(chi)
result_df1 = result_df1.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df2 = result_df2.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df1)
display(result_df2)

                변수   유형  계수종류      상관계수
0    이용금액_오프라인_B0M  수치형  Eta²  0.328568
1    이용금액_오프라인_R3M  수치형  Eta²  0.293962
2    이용금액_오프라인_R6M  수치형  Eta²  0.291066
3    이용건수_오프라인_B0M  수치형  Eta²  0.215746
4    이용건수_오프라인_R6M  수치형  Eta²  0.205766
..             ...  ...   ...       ...
73   증감_RP건수_렌탈_전월  수치형  Eta²  0.000012
74   증감_RP건수_보험_전월  수치형  Eta²  0.000006
75   증감_RP건수_통신_전월  수치형  Eta²  0.000005
76   증감_RP건수_가스_전월  수치형  Eta²  0.000004
77  증감_RP건수_학습비_전월  수치형  Eta²  0.000003

[78 rows x 4 columns]

             변수   유형        계수종류      상관계수
0  최종카드론_신청경로코드  범주형  Cramér's V  0.072631

In [ ]:
pd.set_option('display.max_rows', 100)
display(result_df1)

                       변수   유형  계수종류      상관계수
0           이용금액_오프라인_B0M  수치형  Eta²  0.328568
1           이용금액_오프라인_R3M  수치형  Eta²  0.293962
2           이용금액_오프라인_R6M  수치형  Eta²  0.291066
3           이용건수_오프라인_B0M  수치형  Eta²  0.215746
4           이용건수_오프라인_R6M  수치형  Eta²  0.205766
5           이용건수_오프라인_R3M  수치형  Eta²  0.205711
6            이용금액_온라인_B0M  수치형  Eta²  0.152713
7         이용금액_페이_온라인_B0M  수치형  Eta²  0.145210
8            이용건수_온라인_R6M  수치형  Eta²  0.137876
9            이용건수_온라인_R3M  수치형  Eta²  0.134742
10        이용금액_페이_온라인_R3M  수치형  Eta²  0.133788
11           이용건수_온라인_B0M  수치형  Eta²  0.130485
12        이용금액_페이_온라인_R6M  수치형  Eta²  0.129134
13           이용금액_온라인_R3M  수치형  Eta²  0.126538
14           이용금액_온라인_R6M  수치형  Eta²  0.124220
15        이용건수_페이_온라인_R6M  수치형  Eta²  0.121751
16        이용건수_페이_온라인_R3M  수치형  Eta²  0.115238
17        이용건수_페이_온라인_B0M  수치형  Eta²  0.111395
18          이용개월수_온라인_R6M  수치형  Eta²  0.111048
19       이용개월수_페이_온라인_R6M  수치형  Eta²  0.111030
20         이용개월수_간편결제_R6M  수치형  Eta²  0.108246
21         이용개월수_오프라인_R6M  수치형  Eta²  0.052806
22               RP건수_B0M  수치형  Eta²  0.050463
23             RP유형건수_B0M  수치형  Eta²  0.040798
24              RP후경과월_교통  수치형  Eta²  0.035495
25            RP건수_통신_B0M  수치형  Eta²  0.034883
26              RP후경과월_통신  수치형  Eta²  0.027494
27            RP건수_교통_B0M  수치형  Eta²  0.027230
28                 RP후경과월  수치형  Eta²  0.024597
29       이용금액_페이_오프라인_B0M  수치형  Eta²  0.024199
30             카드론이용월수_누적  수치형  Eta²  0.023926
31             카드론이용건수_누적  수치형  Eta²  0.023219
32       이용금액_페이_오프라인_R3M  수치형  Eta²  0.022845
33      이용개월수_페이_오프라인_R6M  수치형  Eta²  0.022580
34               RP금액_B0M  수치형  Eta²  0.021808
35          이용개월수_A페이_R6M  수치형  Eta²  0.021156
36       이용건수_페이_오프라인_R6M  수치형  Eta²  0.021043
37       이용금액_페이_오프라인_R6M  수치형  Eta²  0.020805
38             최종카드론_대출이율  수치형  Eta²  0.020801
39       이용건수_페이_오프라인_B0M  수치형  Eta²  0.020333
40       이용건수_페이_오프라인_R3M  수치형  Eta²  0.020259
41             최초카드론이용경과월  수치형  Eta²  0.017262
42             최종카드론이용경과월  수치형  Eta²  0.016157
43          이용개월수_C페이_R6M  수치형  Eta²  0.012740
44             카드론이용금액_누적  수치형  Eta²  0.012103
45          이용개월수_D페이_R6M  수치형  Eta²  0.010856
46             최종카드론_대출월수  수치형  Eta²  0.010055
47             최종카드론_대출금액  수치형  Eta²  0.008340
48           RP건수_아파트_B0M  수치형  Eta²  0.007170
49             RP후경과월_아파트  수치형  Eta²  0.007168
50          이용개월수_B페이_R6M  수치형  Eta²  0.007098
51         최종카드론_금융상환방식코드  수치형  Eta²  0.006843
52         이용개월수_당사기타_R6M  수치형  Eta²  0.004989
53             최종카드론_대출일자  수치형  Eta²  0.001757
54              RP후경과월_가스  수치형  Eta²  0.001527
55              RP후경과월_전기  수치형  Eta²  0.001236
56            RP건수_가스_B0M  수치형  Eta²  0.000992
57              RP후경과월_보험  수치형  Eta²  0.000926
58            RP건수_전기_B0M  수치형  Eta²  0.000746
59            RP건수_보험_B0M  수치형  Eta²  0.000579
60           증감_RP유형건수_전월  수치형  Eta²  0.000541
61            최종카드론_거치개월수  수치형  Eta²  0.000352
62      RP후경과월_제휴사서비스직접판매  수치형  Eta²  0.000252
63    RP건수_제휴사서비스직접판매_B0M  수치형  Eta²  0.000219
64           RP건수_학습비_B0M  수치형  Eta²  0.000211
65          증감_RP건수_교통_전월  수치형  Eta²  0.000189
66             RP후경과월_학습비  수치형  Eta²  0.000128
67             증감_RP건수_전월  수치형  Eta²  0.000115
68              RP후경과월_렌탈  수치형  Eta²  0.000096
69            RP건수_렌탈_B0M  수치형  Eta²  0.000052
70         증감_RP건수_아파트_전월  수치형  Eta²  0.000024
71          증감_RP건수_전기_전월  수치형  Eta²  0.000022
72  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²  0.000018
73          증감_RP건수_렌탈_전월  수치형  Eta²  0.000012
74          증감_RP건수_보험_전월  수치형  Eta²  0.000006
75          증감_RP건수_통신_전월  수치형  Eta²  0.000005
76          증감_RP건수_가스_전월  수치형  Eta²  0.000004
77         증감_RP건수_학습비_전월  수치형  Eta²  0.000003

In [ ]:
result_df1['상관계수'] = result_df1['상관계수'].round(4)

In [ ]:
display(result_df1)

                       변수   유형  계수종류    상관계수
0           이용금액_오프라인_B0M  수치형  Eta²  0.3286
1           이용금액_오프라인_R3M  수치형  Eta²  0.2940
2           이용금액_오프라인_R6M  수치형  Eta²  0.2911
3           이용건수_오프라인_B0M  수치형  Eta²  0.2157
4           이용건수_오프라인_R6M  수치형  Eta²  0.2058
5           이용건수_오프라인_R3M  수치형  Eta²  0.2057
6            이용금액_온라인_B0M  수치형  Eta²  0.1527
7         이용금액_페이_온라인_B0M  수치형  Eta²  0.1452
8            이용건수_온라인_R6M  수치형  Eta²  0.1379
9            이용건수_온라인_R3M  수치형  Eta²  0.1347
10        이용금액_페이_온라인_R3M  수치형  Eta²  0.1338
11           이용건수_온라인_B0M  수치형  Eta²  0.1305
12        이용금액_페이_온라인_R6M  수치형  Eta²  0.1291
13           이용금액_온라인_R3M  수치형  Eta²  0.1265
14           이용금액_온라인_R6M  수치형  Eta²  0.1242
15        이용건수_페이_온라인_R6M  수치형  Eta²  0.1218
16        이용건수_페이_온라인_R3M  수치형  Eta²  0.1152
17        이용건수_페이_온라인_B0M  수치형  Eta²  0.1114
18          이용개월수_온라인_R6M  수치형  Eta²  0.1110
19       이용개월수_페이_온라인_R6M  수치형  Eta²  0.1110
20         이용개월수_간편결제_R6M  수치형  Eta²  0.1082
21         이용개월수_오프라인_R6M  수치형  Eta²  0.0528
22               RP건수_B0M  수치형  Eta²  0.0505
23             RP유형건수_B0M  수치형  Eta²  0.0408
24              RP후경과월_교통  수치형  Eta²  0.0355
25            RP건수_통신_B0M  수치형  Eta²  0.0349
26              RP후경과월_통신  수치형  Eta²  0.0275
27            RP건수_교통_B0M  수치형  Eta²  0.0272
28                 RP후경과월  수치형  Eta²  0.0246
29       이용금액_페이_오프라인_B0M  수치형  Eta²  0.0242
30             카드론이용월수_누적  수치형  Eta²  0.0239
31             카드론이용건수_누적  수치형  Eta²  0.0232
32       이용금액_페이_오프라인_R3M  수치형  Eta²  0.0228
33      이용개월수_페이_오프라인_R6M  수치형  Eta²  0.0226
34               RP금액_B0M  수치형  Eta²  0.0218
35          이용개월수_A페이_R6M  수치형  Eta²  0.0212
36       이용건수_페이_오프라인_R6M  수치형  Eta²  0.0210
37       이용금액_페이_오프라인_R6M  수치형  Eta²  0.0208
38             최종카드론_대출이율  수치형  Eta²  0.0208
39       이용건수_페이_오프라인_B0M  수치형  Eta²  0.0203
40       이용건수_페이_오프라인_R3M  수치형  Eta²  0.0203
41             최초카드론이용경과월  수치형  Eta²  0.0173
42             최종카드론이용경과월  수치형  Eta²  0.0162
43          이용개월수_C페이_R6M  수치형  Eta²  0.0127
44             카드론이용금액_누적  수치형  Eta²  0.0121
45          이용개월수_D페이_R6M  수치형  Eta²  0.0109
46             최종카드론_대출월수  수치형  Eta²  0.0101
47             최종카드론_대출금액  수치형  Eta²  0.0083
48           RP건수_아파트_B0M  수치형  Eta²  0.0072
49             RP후경과월_아파트  수치형  Eta²  0.0072
50          이용개월수_B페이_R6M  수치형  Eta²  0.0071
51         최종카드론_금융상환방식코드  수치형  Eta²  0.0068
52         이용개월수_당사기타_R6M  수치형  Eta²  0.0050
53             최종카드론_대출일자  수치형  Eta²  0.0018
54              RP후경과월_가스  수치형  Eta²  0.0015
55              RP후경과월_전기  수치형  Eta²  0.0012
56            RP건수_가스_B0M  수치형  Eta²  0.0010
57              RP후경과월_보험  수치형  Eta²  0.0009
58            RP건수_전기_B0M  수치형  Eta²  0.0007
59            RP건수_보험_B0M  수치형  Eta²  0.0006
60           증감_RP유형건수_전월  수치형  Eta²  0.0005
61            최종카드론_거치개월수  수치형  Eta²  0.0004
62      RP후경과월_제휴사서비스직접판매  수치형  Eta²  0.0003
63    RP건수_제휴사서비스직접판매_B0M  수치형  Eta²  0.0002
64           RP건수_학습비_B0M  수치형  Eta²  0.0002
65          증감_RP건수_교통_전월  수치형  Eta²  0.0002
66             RP후경과월_학습비  수치형  Eta²  0.0001
67             증감_RP건수_전월  수치형  Eta²  0.0001
68              RP후경과월_렌탈  수치형  Eta²  0.0001
69            RP건수_렌탈_B0M  수치형  Eta²  0.0001
70         증감_RP건수_아파트_전월  수치형  Eta²  0.0000
71          증감_RP건수_전기_전월  수치형  Eta²  0.0000
72  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²  0.0000
73          증감_RP건수_렌탈_전월  수치형  Eta²  0.0000
74          증감_RP건수_보험_전월  수치형  Eta²  0.0000
75          증감_RP건수_통신_전월  수치형  Eta²  0.0000
76          증감_RP건수_가스_전월  수치형  Eta²  0.0000
77         증감_RP건수_학습비_전월  수치형  Eta²  0.0000

### ab와 cde를 나눈다

In [25]:
# all_df를 세그먼트 별로 나눠서 ab_df와 cde_df로 나눈다.
ab_df = all_df[all_df['Segment'].isin(['A', 'B'])]
cde_df = all_df[all_df['Segment'].isin(['C', 'D', 'E'])]

In [26]:
ab_df

,기준년월,ID,Segment,RP건수_B0M,RP금액_B0M,RP유형건수_B0M,RP건수_통신_B0M,RP건수_아파트_B0M,RP건수_제휴사서비스직접판매_B0M,RP건수_렌탈_B0M,...,이용금액_페이_온라인_B0M,이용금액_페이_오프라인_B0M,이용건수_페이_온라인_B0M,이용건수_페이_오프라인_B0M,이용개월수_간편결제_R6M,이용개월수_당사기타_R6M,이용개월수_A페이_R6M,이용개월수_B페이_R6M,이용개월수_C페이_R6M,이용개월수_D페이_R6M
2898,201807,TRAIN_002898,A,2,171,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5253,201807,TRAIN_005253,A,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
8128,201807,TRAIN_008128,A,3,637,0,2,0,0,0,...,5492,0,2,0,6,0,0,1,0,0
10808,201807,TRAIN_010808,A,4,4099,2,2,0,0,1,...,3640,0,2,0,6,0,0,0,1,0
14951,201807,TRAIN_014951,A,1,99,1,0,0,0,0,...,5481,0,2,0,6,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2376373,201812,TRAIN_376373,A,2,422,1,2,0,0,0,...,6260,0,2,0,6,0,0,0,6,0
2378479,201812,TRAIN_378479,A,1,814,1,1,0,0,0,...,4734,0,2,0,6,0,0,0,0,0
2390620,201812,TRAIN_390620,B,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2393027,201812,TRAIN_393027,A,1,184,2,0,0,0,0,...,0,0,0,0,5,0,0,0,0,0
2393888,201812,TRAIN_393888,A,2,345,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
cde_df

,기준년월,ID,Segment,RP건수_B0M,RP금액_B0M,RP유형건수_B0M,RP건수_통신_B0M,RP건수_아파트_B0M,RP건수_제휴사서비스직접판매_B0M,RP건수_렌탈_B0M,...,이용금액_페이_온라인_B0M,이용금액_페이_오프라인_B0M,이용건수_페이_온라인_B0M,이용건수_페이_오프라인_B0M,이용개월수_간편결제_R6M,이용개월수_당사기타_R6M,이용개월수_A페이_R6M,이용개월수_B페이_R6M,이용개월수_C페이_R6M,이용개월수_D페이_R6M
0,201807,TRAIN_000000,D,2,147,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,201807,TRAIN_000001,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,201807,TRAIN_000002,C,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
3,201807,TRAIN_000003,D,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,201807,TRAIN_000004,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,D,2,196,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,201812,TRAIN_399997,C,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399998,201812,TRAIN_399998,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [20]:
anova = []
chi = []

for col in ab_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = ab_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(ab_df[col], ab_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df11 = pd.DataFrame(anova)
result_df12 = pd.DataFrame(chi)
result_df11 = result_df11.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df12 = result_df12.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df11)
display(result_df12)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)

                       변수   유형  계수종류          상관계수
0               RP후경과월_보험  수치형  Eta²  7.642963e-02
1             RP건수_보험_B0M  수치형  Eta²  5.561850e-02
2            RP건수_학습비_B0M  수치형  Eta²  3.648649e-02
3              RP후경과월_학습비  수치형  Eta²  3.648649e-02
4           이용개월수_D페이_R6M  수치형  Eta²  3.635828e-02
..                    ...  ...   ...           ...
74             증감_RP건수_전월  수치형  Eta²  8.880591e-07
75                   기준년월  수치형  Eta²  0.000000e+00
76         증감_RP건수_아파트_전월  수치형  Eta²           NaN
77  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²           NaN
78         증감_RP건수_학습비_전월  수치형  Eta²           NaN

[79 rows x 4 columns]

             변수   유형        계수종류      상관계수
0            ID  범주형  Cramér's V  1.000000
1  최종카드론_신청경로코드  범주형  Cramér's V  0.205381

In [21]:
anova = []
chi = []

for col in cde_df.columns:
    if col == 'Segment':
        continue

    if col in num_cols:
        data = cde_df[[col, 'Segment']].dropna()
        groups = [data[data['Segment'] == val][col] for val in data['Segment'].unique()]
        try:
            stat = f_oneway(*groups).statistic
            ss_between = sum([(g.mean() - data[col].mean())**2 * len(g) for g in groups])
            ss_total = sum((data[col] - data[col].mean())**2)
            eta2 = eta_squared(ss_between, ss_total)
            anova.append({'변수': col, '유형': '수치형', '계수종류': 'Eta²', '상관계수': eta2})
        except:
            continue

    elif col in cat_cols:
        contingency = pd.crosstab(cde_df[col], cde_df['Segment'])
        if contingency.shape[0] > 1 and contingency.shape[1] > 1:
            try:
                v = cramers_v(contingency)
                chi.append({'변수': col, '유형': '범주형', '계수종류': "Cramér's V", '상관계수': v})
            except:
                continue

# 결과 정리
result_df21 = pd.DataFrame(anova)
result_df22 = pd.DataFrame(chi)
result_df21 = result_df21.sort_values(by='상관계수', ascending=False).reset_index(drop=True)
result_df22 = result_df22.sort_values(by='상관계수', ascending=False).reset_index(drop=True)

# 결과 출력
display(result_df21)
display(result_df22)

                변수   유형  계수종류          상관계수
0    이용금액_오프라인_B0M  수치형  Eta²  3.252013e-01
1    이용금액_오프라인_R3M  수치형  Eta²  2.899735e-01
2    이용금액_오프라인_R6M  수치형  Eta²  2.854770e-01
3    이용건수_오프라인_B0M  수치형  Eta²  2.142835e-01
4    이용건수_오프라인_R3M  수치형  Eta²  2.041667e-01
..             ...  ...   ...           ...
74   증감_RP건수_보험_전월  수치형  Eta²  3.247430e-06
75  증감_RP건수_학습비_전월  수치형  Eta²  2.476006e-06
76   증감_RP건수_가스_전월  수치형  Eta²  2.330520e-06
77   증감_RP건수_렌탈_전월  수치형  Eta²  2.312852e-07
78            기준년월  수치형  Eta²  0.000000e+00

[79 rows x 4 columns]

             변수   유형        계수종류      상관계수
0            ID  범주형  Cramér's V  1.000000
1  최종카드론_신청경로코드  범주형  Cramér's V  0.100056

In [23]:
result_df11['상관계수'] = result_df11['상관계수'].round(4)
result_df21['상관계수'] = result_df21['상관계수'].round(4)

In [31]:
pd.set_option('display.max_rows', None)

In [32]:
result_df11

                       변수   유형  계수종류    상관계수
0               RP후경과월_보험  수치형  Eta²  0.0764
1             RP건수_보험_B0M  수치형  Eta²  0.0556
2            RP건수_학습비_B0M  수치형  Eta²  0.0365
3              RP후경과월_학습비  수치형  Eta²  0.0365
4           이용개월수_D페이_R6M  수치형  Eta²  0.0364
5              최종카드론_대출금액  수치형  Eta²  0.0215
6            이용건수_온라인_B0M  수치형  Eta²  0.0199
7            이용건수_온라인_R6M  수치형  Eta²  0.0197
8          이용개월수_당사기타_R6M  수치형  Eta²  0.0184
9            이용건수_온라인_R3M  수치형  Eta²  0.0184
10        이용건수_페이_온라인_B0M  수치형  Eta²  0.0183
11        이용건수_페이_온라인_R3M  수치형  Eta²  0.0153
12             최종카드론이용경과월  수치형  Eta²  0.0148
13          이용개월수_온라인_R6M  수치형  Eta²  0.0142
14           이용금액_온라인_B0M  수치형  Eta²  0.0131
15               RP금액_B0M  수치형  Eta²  0.0130
16        이용건수_페이_온라인_R6M  수치형  Eta²  0.0121
17              RP후경과월_가스  수치형  Eta²  0.0116
18       이용금액_페이_오프라인_R6M  수치형  Eta²  0.0108
19          이용금액_오프라인_B0M  수치형  Eta²  0.0105
20        이용금액_페이_온라인_B0M  수치형  Eta²  0.0104
21             최초카드론이용경과월  수치형  Eta²  0.0101
22       이용금액_페이_오프라인_R3M  수치형  Eta²  0.0098
23       이용금액_페이_오프라인_B0M  수치형  Eta²  0.0089
24       이용건수_페이_오프라인_R6M  수치형  Eta²  0.0086
25           이용금액_온라인_R3M  수치형  Eta²  0.0079
26       이용건수_페이_오프라인_R3M  수치형  Eta²  0.0076
27       이용건수_페이_오프라인_B0M  수치형  Eta²  0.0075
28      이용개월수_페이_오프라인_R6M  수치형  Eta²  0.0069
29             최종카드론_대출이율  수치형  Eta²  0.0065
30           이용금액_온라인_R6M  수치형  Eta²  0.0063
31       이용개월수_페이_온라인_R6M  수치형  Eta²  0.0062
32         이용개월수_간편결제_R6M  수치형  Eta²  0.0058
33              RP후경과월_전기  수치형  Eta²  0.0057
34         최종카드론_금융상환방식코드  수치형  Eta²  0.0056
35          이용금액_오프라인_R3M  수치형  Eta²  0.0056
36          이용금액_오프라인_R6M  수치형  Eta²  0.0056
37            최종카드론_거치개월수  수치형  Eta²  0.0055
38        이용금액_페이_온라인_R3M  수치형  Eta²  0.0054
39            RP건수_전기_B0M  수치형  Eta²  0.0051
40             최종카드론_대출월수  수치형  Eta²  0.0049
41          이용개월수_A페이_R6M  수치형  Eta²  0.0033
42             RP후경과월_아파트  수치형  Eta²  0.0033
43           RP건수_아파트_B0M  수치형  Eta²  0.0033
44         이용개월수_오프라인_R6M  수치형  Eta²  0.0032
45              RP후경과월_교통  수치형  Eta²  0.0031
46            RP건수_가스_B0M  수치형  Eta²  0.0029
47             카드론이용건수_누적  수치형  Eta²  0.0025
48            RP건수_교통_B0M  수치형  Eta²  0.0021
49        이용금액_페이_온라인_R6M  수치형  Eta²  0.0021
50             RP유형건수_B0M  수치형  Eta²  0.0021
51          증감_RP건수_보험_전월  수치형  Eta²  0.0018
52             카드론이용금액_누적  수치형  Eta²  0.0014
53             카드론이용월수_누적  수치형  Eta²  0.0014
54          증감_RP건수_전기_전월  수치형  Eta²  0.0013
55          증감_RP건수_가스_전월  수치형  Eta²  0.0012
56          증감_RP건수_렌탈_전월  수치형  Eta²  0.0011
57           증감_RP유형건수_전월  수치형  Eta²  0.0011
58            RP건수_렌탈_B0M  수치형  Eta²  0.0007
59             최종카드론_대출일자  수치형  Eta²  0.0004
60          이용건수_오프라인_R6M  수치형  Eta²  0.0003
61              RP후경과월_통신  수치형  Eta²  0.0003
62                 RP후경과월  수치형  Eta²  0.0003
63          증감_RP건수_통신_전월  수치형  Eta²  0.0002
64               RP건수_B0M  수치형  Eta²  0.0002
65            RP건수_통신_B0M  수치형  Eta²  0.0002
66      RP후경과월_제휴사서비스직접판매  수치형  Eta²  0.0001
67    RP건수_제휴사서비스직접판매_B0M  수치형  Eta²  0.0001
68          이용건수_오프라인_R3M  수치형  Eta²  0.0001
69          이용건수_오프라인_B0M  수치형  Eta²  0.0001
70          이용개월수_C페이_R6M  수치형  Eta²  0.0001
71              RP후경과월_렌탈  수치형  Eta²  0.0000
72          증감_RP건수_교통_전월  수치형  Eta²  0.0000
73          이용개월수_B페이_R6M  수치형  Eta²  0.0000
74             증감_RP건수_전월  수치형  Eta²  0.0000
75                   기준년월  수치형  Eta²  0.0000
76         증감_RP건수_아파트_전월  수치형  Eta²     NaN
77  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²     NaN
78         증감_RP건수_학습비_전월  수치형  Eta²     NaN

In [33]:
result_df21

                       변수   유형  계수종류    상관계수
0           이용금액_오프라인_B0M  수치형  Eta²  0.3252
1           이용금액_오프라인_R3M  수치형  Eta²  0.2900
2           이용금액_오프라인_R6M  수치형  Eta²  0.2855
3           이용건수_오프라인_B0M  수치형  Eta²  0.2143
4           이용건수_오프라인_R3M  수치형  Eta²  0.2042
5           이용건수_오프라인_R6M  수치형  Eta²  0.2040
6            이용금액_온라인_B0M  수치형  Eta²  0.1498
7         이용금액_페이_온라인_B0M  수치형  Eta²  0.1434
8            이용건수_온라인_R6M  수치형  Eta²  0.1365
9            이용건수_온라인_R3M  수치형  Eta²  0.1335
10        이용금액_페이_온라인_R3M  수치형  Eta²  0.1320
11           이용건수_온라인_B0M  수치형  Eta²  0.1293
12        이용금액_페이_온라인_R6M  수치형  Eta²  0.1270
13           이용금액_온라인_R3M  수치형  Eta²  0.1240
14           이용금액_온라인_R6M  수치형  Eta²  0.1213
15        이용건수_페이_온라인_R6M  수치형  Eta²  0.1212
16        이용건수_페이_온라인_R3M  수치형  Eta²  0.1147
17        이용건수_페이_온라인_B0M  수치형  Eta²  0.1108
18       이용개월수_페이_온라인_R6M  수치형  Eta²  0.1107
19          이용개월수_온라인_R6M  수치형  Eta²  0.1106
20         이용개월수_간편결제_R6M  수치형  Eta²  0.1079
21         이용개월수_오프라인_R6M  수치형  Eta²  0.0526
22               RP건수_B0M  수치형  Eta²  0.0503
23             RP유형건수_B0M  수치형  Eta²  0.0407
24              RP후경과월_교통  수치형  Eta²  0.0354
25            RP건수_통신_B0M  수치형  Eta²  0.0347
26              RP후경과월_통신  수치형  Eta²  0.0274
27            RP건수_교통_B0M  수치형  Eta²  0.0272
28                 RP후경과월  수치형  Eta²  0.0245
29       이용금액_페이_오프라인_B0M  수치형  Eta²  0.0242
30             카드론이용월수_누적  수치형  Eta²  0.0234
31       이용금액_페이_오프라인_R3M  수치형  Eta²  0.0228
32             카드론이용건수_누적  수치형  Eta²  0.0227
33      이용개월수_페이_오프라인_R6M  수치형  Eta²  0.0226
34               RP금액_B0M  수치형  Eta²  0.0217
35          이용개월수_A페이_R6M  수치형  Eta²  0.0211
36       이용건수_페이_오프라인_R6M  수치형  Eta²  0.0210
37       이용금액_페이_오프라인_R6M  수치형  Eta²  0.0208
38             최종카드론_대출이율  수치형  Eta²  0.0206
39       이용건수_페이_오프라인_B0M  수치형  Eta²  0.0203
40       이용건수_페이_오프라인_R3M  수치형  Eta²  0.0202
41             최초카드론이용경과월  수치형  Eta²  0.0171
42             최종카드론이용경과월  수치형  Eta²  0.0161
43          이용개월수_C페이_R6M  수치형  Eta²  0.0126
44             카드론이용금액_누적  수치형  Eta²  0.0117
45          이용개월수_D페이_R6M  수치형  Eta²  0.0108
46             최종카드론_대출월수  수치형  Eta²  0.0100
47             최종카드론_대출금액  수치형  Eta²  0.0082
48           RP건수_아파트_B0M  수치형  Eta²  0.0072
49             RP후경과월_아파트  수치형  Eta²  0.0072
50          이용개월수_B페이_R6M  수치형  Eta²  0.0071
51         최종카드론_금융상환방식코드  수치형  Eta²  0.0068
52         이용개월수_당사기타_R6M  수치형  Eta²  0.0049
53             최종카드론_대출일자  수치형  Eta²  0.0017
54              RP후경과월_가스  수치형  Eta²  0.0015
55              RP후경과월_전기  수치형  Eta²  0.0011
56            RP건수_가스_B0M  수치형  Eta²  0.0010
57              RP후경과월_보험  수치형  Eta²  0.0008
58            RP건수_전기_B0M  수치형  Eta²  0.0006
59           증감_RP유형건수_전월  수치형  Eta²  0.0005
60            RP건수_보험_B0M  수치형  Eta²  0.0005
61            최종카드론_거치개월수  수치형  Eta²  0.0003
62      RP후경과월_제휴사서비스직접판매  수치형  Eta²  0.0002
63    RP건수_제휴사서비스직접판매_B0M  수치형  Eta²  0.0002
64          증감_RP건수_교통_전월  수치형  Eta²  0.0002
65             증감_RP건수_전월  수치형  Eta²  0.0001
66         증감_RP건수_아파트_전월  수치형  Eta²  0.0000
67            RP건수_렌탈_B0M  수치형  Eta²  0.0000
68          증감_RP건수_전기_전월  수치형  Eta²  0.0000
69             RP후경과월_학습비  수치형  Eta²  0.0000
70           RP건수_학습비_B0M  수치형  Eta²  0.0000
71  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²  0.0000
72              RP후경과월_렌탈  수치형  Eta²  0.0000
73          증감_RP건수_통신_전월  수치형  Eta²  0.0000
74          증감_RP건수_보험_전월  수치형  Eta²  0.0000
75         증감_RP건수_학습비_전월  수치형  Eta²  0.0000
76          증감_RP건수_가스_전월  수치형  Eta²  0.0000
77          증감_RP건수_렌탈_전월  수치형  Eta²  0.0000
78                   기준년월  수치형  Eta²  0.0000

In [34]:
result_df22

             변수   유형        계수종류      상관계수
0            ID  범주형  Cramér's V  1.000000
1  최종카드론_신청경로코드  범주형  Cramér's V  0.100056

하지만 신청경로코드는 결측치

In [38]:
# ab_df, cde_df, result_df11, result_df21을 parquet파일로 저장한다.
ab_df.to_parquet('승인매출ab_df3-3.parquet', index=False)
cde_df.to_parquet('승인매출cde_df3-3.parquet', index=False)
result_df11.to_parquet('승인매출ab_df3-3_설명력.parquet', index=False)
result_df21.to_parquet('승인매출cde_df3-3_설명력.parquet', index=False)

In [40]:
hw = pd.read_parquet('승인매출cde_df3-3.parquet')
hw.head()

,기준년월,ID,Segment,RP건수_B0M,RP금액_B0M,RP유형건수_B0M,RP건수_통신_B0M,RP건수_아파트_B0M,RP건수_제휴사서비스직접판매_B0M,RP건수_렌탈_B0M,...,이용금액_페이_온라인_B0M,이용금액_페이_오프라인_B0M,이용건수_페이_온라인_B0M,이용건수_페이_오프라인_B0M,이용개월수_간편결제_R6M,이용개월수_당사기타_R6M,이용개월수_A페이_R6M,이용개월수_B페이_R6M,이용개월수_C페이_R6M,이용개월수_D페이_R6M
0,201807,TRAIN_000000,D,2,147,2,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,201807,TRAIN_000001,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,201807,TRAIN_000002,C,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
3,201807,TRAIN_000003,D,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,201807,TRAIN_000004,E,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
from scipy.stats import ttest_ind
def cohen_d(x, y):
    """두 그룹 간 효과 크기(Cohen's d) 계산"""
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    pooled_std = np.sqrt(((nx - 1)*x.std()**2 + (ny - 1)*y.std()**2) / dof)
    return (x.mean() - y.mean()) / pooled_std

def ttest_ab_multiple_verbose_abs_sorted(df, feature_cols):
    """
    A vs B 그룹 간 연속형 변수들에 대해 t-test, p-value, Cohen's d, 유의성 표시 포함한 결과 반환
    Cohen's d 절댓값 기준 내림차순 정렬
    """
    results = []

    for col in feature_cols:
        group_a = df[df['Segment'] == 'A'][col].dropna()
        group_b = df[df['Segment'] == 'B'][col].dropna()

        t_stat, p_val = ttest_ind(group_a, group_b, equal_var=False)
        d = cohen_d(group_a, group_b)

        # 유의성 표시
        if p_val < 0.001:
            sig = '***'
        elif p_val < 0.01:
            sig = '**'
        elif p_val < 0.05:
            sig = '*'
        else:
            sig = 'ns'

        results.append({
            'feature': col,
            't-statistic': round(t_stat, 4),
            'p-value': round(p_val, 4),
            'Cohen\'s d': round(d, 4),
            'abs(Cohen\'s d)': abs(round(d, 4)),
            'significance': sig
        })

    df_result = pd.DataFrame(results)
    df_result = df_result.sort_values('abs(Cohen\'s d)', ascending=False).reset_index(drop=True)
    df_result = df_result.drop(columns=['abs(Cohen\'s d)'])  # 필요 없으면 제거

    return df_result

In [31]:
ttest_results = ttest_ab_multiple_verbose_abs_sorted(ab_df, num_cols)
ttest_results

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/tmp/ipython-input-30-1371196798.py:8: RuntimeWarning: invalid value encountered in scalar divide
  return (x.mean() - y.mean()) / pooled_std

                  feature  t-statistic  p-value  Cohen's d significance
0               RP후경과월_보험       4.6099   0.0000     0.8573          ***
1             RP건수_보험_B0M      -3.5822   0.0005    -0.7233          ***
2              RP후경과월_학습비       2.4935   0.0138     0.5800            *
3            RP건수_학습비_B0M      -2.4935   0.0138    -0.5800            *
4           이용개월수_D페이_R6M      -4.0248   0.0001    -0.5789          ***
..                    ...          ...      ...        ...          ...
74             증감_RP건수_전월      -0.0287   0.9771    -0.0028           ns
75                   기준년월       0.0000   1.0000     0.0000           ns
76         증감_RP건수_아파트_전월          NaN      NaN        NaN           ns
77  증감_RP건수_제휴사서비스직접판매_전월          NaN      NaN        NaN           ns
78         증감_RP건수_학습비_전월          NaN      NaN        NaN           ns

[79 rows x 5 columns]

In [32]:
pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² / t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan


def effect_sizes(df):
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            group1 = data[data['Segment'] == data['Segment'].unique()[0]][col]
            group2 = data[data['Segment'] == data['Segment'].unique()[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)

    return result_df1, result_df2

In [33]:
result1, result2 = effect_sizes(ab_df)
display(result1)
display(result2)

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:586: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)

                       변수   유형  계수종류    상관계수
0            이용건수_온라인_B0M  수치형  Eta² 0.02166
1            RP건수_아파트_B0M  수치형  Eta² 0.02159
2              RP후경과월_아파트  수치형  Eta² 0.02159
3          이용개월수_오프라인_R6M  수치형  Eta² 0.02128
4           이용개월수_온라인_R6M  수치형  Eta² 0.02014
..                    ...  ...   ...     ...
74             증감_RP건수_전월  수치형  Eta² 0.00000
75                   기준년월  수치형  Eta² 0.00000
76         증감_RP건수_아파트_전월  수치형  Eta²     NaN
77  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²     NaN
78         증감_RP건수_학습비_전월  수치형  Eta²     NaN

[79 rows x 4 columns]

             변수   유형        계수종류    상관계수
0            ID  범주형  Cramér's V 1.00000
1  최종카드론_신청경로코드  범주형  Cramér's V 0.20538

In [34]:
# result1과 ttest_result를 parquet으로 저장한다
result1.to_parquet('/content/drive/MyDrive/승인매출ab_df3-3_설명력.parquet', index=False)
ttest_results.to_parquet('/content/drive/MyDrive/ttest_results3-3.parquet', index=False)