In [1]:
# 기본
import pandas as pd  # 데이터프레임 처리
import numpy as np  # 수치 계산
import matplotlib.pyplot as plt  # 데이터 시각화
import seaborn as sns  # 고급 시각화

# 경고 뜨지 않게 설정
import warnings  # 경고 무시 설정
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'  # 한글 폰트 설정
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6  # 그래프 크기 설정
plt.rcParams['font.size'] = 14  # 글자 크기
plt.rcParams['axes.unicode_minus'] = False  # 마이너스 깨짐 방지

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### 데이터 준비

In [8]:
# parquet 파일 데이터를 읽어온다.
df1_test = pd.read_parquet('/content/drive/MyDrive/test데이터/신용카드데이터_test.parquet')

In [9]:
df2_test = pd.read_parquet('/content/drive/MyDrive/test데이터/test07.parquet')

In [10]:
df2_test.columns

Index(['기준년월', 'ID', '이용가능여부_해외겸용_본인', '보유여부_해외겸용_본인', '수신거부여부_TM',
       '수신거부여부_메일', '수신거부여부_DM', '이용금액_R3M_신용체크', '이용금액_R3M_신용', '_1순위카드이용금액',
       '이용카드수_신용체크', '_2순위카드이용금액', '_1순위카드이용건수', '_2순위카드이용건수', '이용카드수_신용',
       '상향가능한도금액', '상향가능CA한도금액', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M',
       '이용금액_일시불_R12M', '이용금액_일시불_B0M', '이용금액_오프라인_B0M', '이용금액_일시불_R6M',
       '이용금액_일시불_R3M', '정상입금원금_B5M', '정상입금원금_B0M', '이용금액_오프라인_R3M',
       '이용금액_오프라인_R6M', '정상입금원금_B2M', '_3순위업종_이용금액', '_2순위업종_이용금액',
       '이용건수_신용_R12M', '_2순위쇼핑업종_이용금액', '최대이용금액_일시불_R12M', '이용건수_신판_R12M',
       '이용건수_일시불_R12M', '_1순위업종_이용금액', '_3순위쇼핑업종_이용금액', '이용가맹점수',
       '이용건수_오프라인_B0M', '이용건수_오프라인_R6M', '이용건수_오프라인_R3M', '쇼핑_도소매_이용금액',
       '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M', '이용건수_신판_R6M',
       '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_일시불_R6M', '이용건수_일시불_B0M',
       '이용건수_일시불_R3M', '_1순위교통업종_이용금액', '연체입금원금_B0M', '쇼핑_마트_이용금액',
       '쇼핑_슈퍼마켓_이용금액', '교통_주유이용금액', '이용금액_온라인_B0M', '연체입금원금_B5M', '연체입금원금_B2M',
       '이용금액_페이_온라인_B0M', '_1순위쇼핑업종_이용금액', '연속유실적개월수_기본_24M_카드', '이용금액대',
       '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '할인건수_R3M', '월중평잔_일시불_B0M',
       '월중평잔_일시불', '평잔_일시불_3M', '잔액_일시불_B0M', '잔액_일시불_B1M', '잔액_일시불_B2M',
       '인입횟수_ARS_R6M'],
      dtype='object')

In [6]:
df1_test

,기준년월,ID,이용가능여부_해외겸용_본인,보유여부_해외겸용_본인,수신거부여부_TM,수신거부여부_메일,수신거부여부_DM,이용금액_R3M_신용체크,이용금액_R3M_신용,_1순위카드이용금액,...,청구금액_R3M,청구금액_B0,할인건수_R3M,월중평잔_일시불_B0M,월중평잔_일시불,평잔_일시불_3M,잔액_일시불_B0M,잔액_일시불_B1M,잔액_일시불_B2M,인입횟수_ARS_R6M
0,201807,TEST_00000,1,1,1,1,1,21458,21458,13852,...,11441,4931,1회 이상,6412,5187,3841,4802,2277,0,1회 이상
1,201807,TEST_00001,1,1,0,0,0,18681,10759,11065,...,20522,10152,1회 이상,1010,865,844,1201,1467,544,1회 이상
2,201807,TEST_00002,0,0,0,0,0,40758,40758,27071,...,50508,13223,1회 이상,4407,5591,5606,3046,2496,3096,1회 이상
3,201807,TEST_00003,1,1,0,0,0,5255,5255,4827,...,4604,2112,1회 이상,1107,1545,1510,768,675,1035,1회 이상
4,201807,TEST_00004,1,1,1,1,1,16148,14290,8011,...,6788,4406,1회 이상,1072,1462,1373,637,1395,620,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,0,0,...,0,0,1회 이상,0,0,0,0,0,0,1회 이상
599996,201812,TEST_99996,0,0,0,0,0,3110,3110,1231,...,1256,359,1회 이상,260,256,237,191,180,238,1회 이상
599997,201812,TEST_99997,0,0,0,0,0,0,0,0,...,0,0,1회 이상,0,0,0,0,0,0,1회 이상
599998,201812,TEST_99998,1,1,1,1,1,173263,113786,63592,...,48141,21273,1회 이상,16911,14005,17039,17916,18779,14586,1회 이상
599999,201812,TEST_99999,1,1,0,0,0,3016,3016,-574,...,56,18,1회 이상,37,10,9,44,27,17,1회 이상

In [14]:
columns = ['기준년월', 'ID', '이용가능여부_해외겸용_본인', '보유여부_해외겸용_본인', '수신거부여부_TM','수신거부여부_메일', '수신거부여부_DM', '이용금액_R3M_신용체크', '이용금액_R3M_신용', '_1순위카드이용금액',
       '이용카드수_신용체크', '_2순위카드이용금액', '_1순위카드이용건수', '_2순위카드이용건수', '이용카드수_신용',
       '상향가능한도금액', '상향가능CA한도금액', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M',
       '이용금액_일시불_R12M', '이용금액_일시불_B0M', '이용금액_오프라인_B0M', '이용금액_일시불_R6M',
       '이용금액_일시불_R3M', '정상입금원금_B5M', '정상입금원금_B0M', '이용금액_오프라인_R3M',
       '이용금액_오프라인_R6M', '정상입금원금_B2M', '_3순위업종_이용금액', '_2순위업종_이용금액',
       '이용건수_신용_R12M', '_2순위쇼핑업종_이용금액', '최대이용금액_일시불_R12M', '이용건수_신판_R12M',
       '이용건수_일시불_R12M', '_1순위업종_이용금액', '_3순위쇼핑업종_이용금액', '이용가맹점수',
       '이용건수_오프라인_B0M', '이용건수_오프라인_R6M', '이용건수_오프라인_R3M', '쇼핑_도소매_이용금액',
       '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M', '이용건수_신판_R6M',
       '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_일시불_R6M', '이용건수_일시불_B0M',
       '이용건수_일시불_R3M', '_1순위교통업종_이용금액', '연체입금원금_B0M', '쇼핑_마트_이용금액',
       '쇼핑_슈퍼마켓_이용금액', '교통_주유이용금액', '이용금액_온라인_B0M', '연체입금원금_B5M', '연체입금원금_B2M',
       '이용금액_페이_온라인_B0M', '_1순위쇼핑업종_이용금액', '연속유실적개월수_기본_24M_카드', '이용금액대',
       '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '할인건수_R3M', '월중평잔_일시불_B0M',
       '월중평잔_일시불', '평잔_일시불_3M', '잔액_일시불_B0M', '잔액_일시불_B1M', '잔액_일시불_B2M',
       '인입횟수_ARS_R6M']
df1_test[columns]

,기준년월,ID,이용가능여부_해외겸용_본인,보유여부_해외겸용_본인,수신거부여부_TM,수신거부여부_메일,수신거부여부_DM,이용금액_R3M_신용체크,이용금액_R3M_신용,_1순위카드이용금액,...,청구금액_R3M,청구금액_B0,할인건수_R3M,월중평잔_일시불_B0M,월중평잔_일시불,평잔_일시불_3M,잔액_일시불_B0M,잔액_일시불_B1M,잔액_일시불_B2M,인입횟수_ARS_R6M
0,201807,TEST_00000,1,1,1,1,1,21458,21458,13852,...,11441,4931,1회 이상,6412,5187,3841,4802,2277,0,1회 이상
1,201807,TEST_00001,1,1,0,0,0,18681,10759,11065,...,20522,10152,1회 이상,1010,865,844,1201,1467,544,1회 이상
2,201807,TEST_00002,0,0,0,0,0,40758,40758,27071,...,50508,13223,1회 이상,4407,5591,5606,3046,2496,3096,1회 이상
3,201807,TEST_00003,1,1,0,0,0,5255,5255,4827,...,4604,2112,1회 이상,1107,1545,1510,768,675,1035,1회 이상
4,201807,TEST_00004,1,1,1,1,1,16148,14290,8011,...,6788,4406,1회 이상,1072,1462,1373,637,1395,620,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,0,0,0,0,...,0,0,1회 이상,0,0,0,0,0,0,1회 이상
599996,201812,TEST_99996,0,0,0,0,0,3110,3110,1231,...,1256,359,1회 이상,260,256,237,191,180,238,1회 이상
599997,201812,TEST_99997,0,0,0,0,0,0,0,0,...,0,0,1회 이상,0,0,0,0,0,0,1회 이상
599998,201812,TEST_99998,1,1,1,1,1,173263,113786,63592,...,48141,21273,1회 이상,16911,14005,17039,17916,18779,14586,1회 이상
599999,201812,TEST_99999,1,1,0,0,0,3016,3016,-574,...,56,18,1회 이상,37,10,9,44,27,17,1회 이상

In [15]:
all_df = df1_test[columns]

In [16]:
all_df.columns

Index(['기준년월', 'ID', '이용가능여부_해외겸용_본인', '보유여부_해외겸용_본인', '수신거부여부_TM',
       '수신거부여부_메일', '수신거부여부_DM', '이용금액_R3M_신용체크', '이용금액_R3M_신용', '_1순위카드이용금액',
       '이용카드수_신용체크', '_2순위카드이용금액', '_1순위카드이용건수', '_2순위카드이용건수', '이용카드수_신용',
       '상향가능한도금액', '상향가능CA한도금액', '정상청구원금_B5M', '정상청구원금_B0M', '정상청구원금_B2M',
       '이용금액_일시불_R12M', '이용금액_일시불_B0M', '이용금액_오프라인_B0M', '이용금액_일시불_R6M',
       '이용금액_일시불_R3M', '정상입금원금_B5M', '정상입금원금_B0M', '이용금액_오프라인_R3M',
       '이용금액_오프라인_R6M', '정상입금원금_B2M', '_3순위업종_이용금액', '_2순위업종_이용금액',
       '이용건수_신용_R12M', '_2순위쇼핑업종_이용금액', '최대이용금액_일시불_R12M', '이용건수_신판_R12M',
       '이용건수_일시불_R12M', '_1순위업종_이용금액', '_3순위쇼핑업종_이용금액', '이용가맹점수',
       '이용건수_오프라인_B0M', '이용건수_오프라인_R6M', '이용건수_오프라인_R3M', '쇼핑_도소매_이용금액',
       '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M', '이용건수_신판_R6M',
       '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_일시불_R6M', '이용건수_일시불_B0M',
       '이용건수_일시불_R3M', '_1순위교통업종_이용금액', '연체입금원금_B0M', '쇼핑_마트_이용금액',
       '쇼핑_슈퍼마켓_이용금액', '교통_주유이용금액', '이용금액_온라인_B0M', '연체입금원금_B5M', '연체입금원금_B2M',
       '이용금액_페이_온라인_B0M', '_1순위쇼핑업종_이용금액', '연속유실적개월수_기본_24M_카드', '이용금액대',
       '청구금액_R6M', '청구금액_R3M', '청구금액_B0', '할인건수_R3M', '월중평잔_일시불_B0M',
       '월중평잔_일시불', '평잔_일시불_3M', '잔액_일시불_B0M', '잔액_일시불_B1M', '잔액_일시불_B2M',
       '인입횟수_ARS_R6M'],
      dtype='object')

In [17]:
 all_df12 = all_df.query('기준년월 == 201812')

In [18]:
all_df12.to_parquet("test12.parquet", index=False)