In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

### 데이터 01

In [14]:
df11=pd.read_parquet(r'train/1.회원정보/201807_train_.parquet')
df12=pd.read_parquet(r'train/1.회원정보/201808_train_.parquet')
df13=pd.read_parquet(r'train/1.회원정보/201809_train_.parquet')
df14=pd.read_parquet(r'train/1.회원정보/201810_train_.parquet')
df15=pd.read_parquet(r'train/1.회원정보/201811_train_.parquet')
df16=pd.read_parquet(r'train/1.회원정보/201812_train_.parquet')

In [15]:
tg_df = pd.concat([df11['Segment'], df12['Segment'], df13['Segment'], df14['Segment'], df15['Segment'], df16['Segment']])
tg_df.reset_index(inplace=True, drop=True)
tg_df

0          D
1          E
2          C
3          D
4          E
          ..
2399995    E
2399996    D
2399997    C
2399998    E
2399999    E
Name: Segment, Length: 2400000, dtype: object

In [18]:
all_df1['Segment'].value_counts()

Segment
E    1922052
D     349242
C     127590
A        972
B        144
Name: count, dtype: int64

In [17]:
all_df1 = pd.concat([df11, df12, df13, df14, df15, df16])
all_df1.reset_index(inplace=True, drop=True)
all_df1

,기준년월,ID,남녀구분코드,연령,Segment,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,소지여부_신용,소지카드수_유효_신용,...,할인금액_제휴연회비_B0M,청구금액_기본연회비_B0M,청구금액_제휴연회비_B0M,상품관련면제카드수_B0M,임직원면제카드수_B0M,우수회원면제카드수_B0M,기타면제카드수_B0M,카드신청건수,Life_Stage,최종카드발급경과월
0,201807,TRAIN_000000,2,40대,D,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),22
1,201807,TRAIN_000001,1,30대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18
2,201807,TRAIN_000002,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,20
3,201807,TRAIN_000003,2,40대,D,1,1,0,1,2,...,0,0,0,0개,0개,0개,0개,1,자녀성장(2),17
4,201807,TRAIN_000004,2,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,1,자녀성장(1),15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,2,70대이상,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,노년생활,39
2399996,201812,TRAIN_399996,2,50대,D,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(2),24
2399997,201812,TRAIN_399997,1,30대,C,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀출산기,18
2399998,201812,TRAIN_399998,1,40대,E,1,1,1,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),27
2399999,201812,TRAIN_399999,2,40대,E,1,1,0,1,1,...,0,0,0,0개,0개,0개,0개,0,자녀성장(1),18

In [21]:
pd.set_option('display.max_rows', None)  # 행 생략 없이 모두 출력
pd.set_option('display.max_columns', None)  # 열 생략 없이 모두 출력

In [23]:
all_df1.isna().sum()[lambda x: x > 0]

가입통신회사코드          387570
직장시도명             244969
_1순위신용체크구분         27950
_2순위신용체크구분        958115
최종유효년월_신용_이용가능    210447
최종유효년월_신용_이용      534231
최종카드발급일자           41965
dtype: int64

In [5]:
all_df12=all_df1.copy()
all_df12 = all_df1[~all_df1['Segment'].isin(['C', 'D', 'E'])]

In [4]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, ttest_ind

pd.set_option('display.float_format', '{:.5f}'.format)

# Cramér's V
def cramers_v(confusion_matrix):
    chi2 = chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    r, k = confusion_matrix.shape
    return np.sqrt(chi2 / (n * (min(k, r) - 1)))

# Eta² from t-test
def eta_squared_from_t(t, n1, n2):
    df = n1 + n2 - 2
    return t**2 / (t**2 + df) if df > 0 else np.nan

# t-test 기반 효과 크기 계산 함수
def effect_sizes(df):
    num_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    cat_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

    num_cols = [col for col in num_cols if col != 'Segment']
    cat_cols = [col for col in cat_cols if col != 'Segment']

    ttest_results = []
    chi_results = []

    for col in df.columns:
        if col == 'Segment':
            continue

        # 수치형 변수 → t-test + eta²
        if col in num_cols:
            data = df[[col, 'Segment']].dropna()
            unique_segments = sorted(data['Segment'].unique())
            if len(unique_segments) != 2:
                continue  # t-test는 2개 그룹일 때만 가능

            group1 = data[data['Segment'] == unique_segments[0]][col]
            group2 = data[data['Segment'] == unique_segments[1]][col]
            try:
                t_stat, _ = ttest_ind(group1, group2, equal_var=False)
                eta2 = eta_squared_from_t(t_stat, len(group1), len(group2))
                ttest_results.append({
                    '변수': col, '유형': '수치형',
                    '계수종류': 'Eta²',
                    '상관계수': eta2
                })
            except:
                continue

        # 범주형 변수 → Cramér's V
        elif col in cat_cols:
            contingency = pd.crosstab(df[col], df['Segment'])
            if contingency.shape[0] > 1 and contingency.shape[1] > 1:
                try:
                    v = cramers_v(contingency)
                    chi_results.append({
                        '변수': col, '유형': '범주형',
                        '계수종류': "Cramér's V",
                        '상관계수': v
                    })
                except:
                    continue

    if ttest_results:
        result_df1 = pd.DataFrame(ttest_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    else:
        result_df1 = pd.DataFrame(columns=['변수', '유형', '계수종류', '상관계수'])

    if chi_results:
        result_df2 = pd.DataFrame(chi_results).sort_values(by='상관계수', ascending=False).reset_index(drop=True)
    else:
        result_df2 = pd.DataFrame(columns=['변수', '유형', '계수종류', '상관계수'])

    return result_df1, result_df2

In [7]:
result11, result12 = effect_sizes(all_df12)
display(result11)
display(result12)

                변수   유형  계수종류    상관계수
0          입회일자_신용  수치형  Eta² 0.09269
1       입회경과개월수_신용  수치형  Eta² 0.08974
2         이용카드수_체크  수치형  Eta² 0.03587
3         유효카드수_체크  수치형  Eta² 0.02822
4       이용가능카드수_체크  수치형  Eta² 0.02427
..             ...  ...   ...     ...
59       제휴연회비_B0M  수치형  Eta²     NaN
60  할인금액_기본연회비_B0M  수치형  Eta²     NaN
61  할인금액_제휴연회비_B0M  수치형  Eta²     NaN
62  청구금액_기본연회비_B0M  수치형  Eta²     NaN
63  청구금액_제휴연회비_B0M  수치형  Eta²     NaN

[64 rows x 4 columns]

             변수   유형        계수종류    상관계수
0            ID  범주형  Cramér's V 1.00000
1         거주시도명  범주형  Cramér's V 0.31949
2         직장시도명  범주형  Cramér's V 0.31786
3    _2순위신용체크구분  범주형  Cramér's V 0.31281
4            연령  범주형  Cramér's V 0.28483
5    Life_Stage  범주형  Cramér's V 0.24120
6      가입통신회사코드  범주형  Cramér's V 0.10281
7  연회비발생카드수_B0M  범주형  Cramér's V 0.00000

In [8]:
with pd.ExcelWriter('1.회원정보_A,B.xlsx') as writer:
    result11.to_excel(writer, sheet_name='아노바', index=False)
    result12.to_excel(writer, sheet_name='카이제곱', index=False)

### 2번 데이터

In [2]:
df21=pd.read_parquet(r'train/2.신용정보/201807_train_.parquet')
df22=pd.read_parquet(r'train/2.신용정보/201808_train_.parquet')
df23=pd.read_parquet(r'train/2.신용정보/201809_train_.parquet')
df24=pd.read_parquet(r'train/2.신용정보/201810_train_.parquet')
df25=pd.read_parquet(r'train/2.신용정보/201811_train_.parquet')
df26=pd.read_parquet(r'train/2.신용정보/201812_train_.parquet')

In [3]:
all_df2 = pd.concat([df21, df22, df23, df24, df25, df26])
all_df2.reset_index(inplace=True, drop=True)
all_df2

,기준년월,ID,최초한도금액,카드이용한도금액,CA한도금액,일시상환론한도금액,월상환론한도금액,CA이자율_할인전,CL이자율_할인전,RV일시불이자율_할인전,...,연체감액여부_R3M,한도심사요청건수,한도요청거절건수,한도심사요청후경과월,한도심사거절후경과월,시장단기연체여부_R6M,시장단기연체여부_R3M,시장연체상환여부_R6M,시장연체상환여부_R3M,rv최초시작후경과일
0,201807,TRAIN_000000,0,19354,7270,0,0,22.995207,18.254978,17.264967,...,0,0회,0,3,3,0,0,0,0,99999999
1,201807,TRAIN_000001,0,9996,5718,41996,90611,14.793821,14.834873,10.622446,...,0,0회,0,3,3,0,0,0,0,322
2,201807,TRAIN_000002,0,88193,35207,0,0,22.014276,17.875321,17.155829,...,0,0회,0,3,3,0,0,0,0,2378
3,201807,TRAIN_000003,0,19062,6531,0,0,22.998014,22.999453,19.293674,...,0,0회,0,3,3,0,0,0,0,99999999
4,201807,TRAIN_000004,0,177222,47149,48000,155020,14.661948,10.897410,10.654587,...,0,0회,0,3,3,0,0,0,0,99999999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,20070,10167,0,54445,15.243670,11.900516,10.545876,...,0,0회,0,3,3,0,0,0,0,99999999
2399996,201812,TRAIN_399996,0,84217,31159,0,156800,14.843464,15.652063,11.102726,...,0,0회,0,3,3,0,0,0,0,99999999
2399997,201812,TRAIN_399997,0,52612,19429,0,0,17.038599,17.966213,13.278475,...,0,0회,0,3,3,0,0,0,0,99999999
2399998,201812,TRAIN_399998,0,10002,4228,90004,180906,15.182880,11.901089,10.594124,...,0,0회,0,3,3,0,0,0,0,99999999
2399999,201812,TRAIN_399999,0,86094,25133,0,0,14.841102,15.287120,11.406823,...,0,0회,0,3,3,0,0,0,0,99999999

In [4]:
all_df2.isna().sum()[lambda x: x > 0]

RV신청일자      1951236
RV전환가능여부      29473
dtype: int64

In [12]:
all_df2['Segment'] = tg_df

In [13]:
all_df2 = all_df2[~all_df2['Segment'].isin(['C', 'D', 'E'])]

In [14]:
result21, result22 = effect_sizes(all_df2)
display(result21)
display(result22)

                변수   유형  계수종류    상관계수
0     카드이용한도금액_B2M  수치형  Eta² 0.18018
1     카드이용한도금액_B1M  수치형  Eta² 0.17956
2         카드이용한도금액  수치형  Eta² 0.17024
3           CA한도금액  수치형  Eta² 0.14492
4           RV신청일자  수치형  Eta² 0.08682
5    일시불ONLY전환가능여부  수치형  Eta² 0.05777
6   RV현금서비스이자율_할인전  수치형  Eta² 0.03986
7     RV일시불이자율_할인전  수치형  Eta² 0.03576
8           최초한도금액  수치형  Eta² 0.03282
9        CA이자율_할인전  수치형  Eta² 0.02846
10    월상환론상향가능한도금액  수치형  Eta² 0.02763
11       CL이자율_할인전  수치형  Eta² 0.02425
12        월상환론한도금액  수치형  Eta² 0.01773
13        RV최소결제비율  수치형  Eta² 0.01326
14         RV약정청구율  수치형  Eta² 0.01170
15      rv최초시작후경과일  수치형  Eta² 0.01046
16       일시상환론한도금액  수치형  Eta² 0.00861
17   강제한도감액금액_R12M  수치형  Eta² 0.00239
18      강제한도감액후경과월  수치형  Eta² 0.00172
19        한도증액후경과월  수치형  Eta² 0.00101
20     한도증액금액_R12M  수치형  Eta² 0.00074
21      상향가능CA한도금액  수치형  Eta² 0.00033
22   강제한도감액횟수_R12M  수치형  Eta² 0.00033
23        상향가능한도금액  수치형  Eta² 0.00026
24            기준년월  수치형  Eta² 0.00000
25   자발한도감액금액_R12M  수치형  Eta²     NaN
26      자발한도감액후경과월  수치형  Eta²     NaN
27    특별한도보유여부_R3M  수치형  Eta²     NaN
28      연체감액여부_R3M  수치형  Eta²     NaN
29        한도요청거절건수  수치형  Eta²     NaN
30      한도심사요청후경과월  수치형  Eta²     NaN
31      한도심사거절후경과월  수치형  Eta²     NaN
32    시장단기연체여부_R6M  수치형  Eta²     NaN
33    시장단기연체여부_R3M  수치형  Eta²     NaN
34    시장연체상환여부_R6M  수치형  Eta²     NaN
35    시장연체상환여부_R3M  수치형  Eta²     NaN

            변수   유형        계수종류    상관계수
0           ID  범주형  Cramér's V 1.00000
1     RV전환가능여부  범주형  Cramér's V 0.29625
2      카드론동의여부  범주형  Cramér's V 0.08355
3  한도증액횟수_R12M  범주형  Cramér's V 0.00905

In [15]:
with pd.ExcelWriter('2.신용정보_A,B.xlsx') as writer:
    result21.to_excel(writer, sheet_name='아노바', index=False)
    result22.to_excel(writer, sheet_name='카이제곱', index=False)

### 3번 (1~70번)

In [5]:
df311=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, :70]
df312=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, :70]
df313=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, :70]
df314=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, :70]
df315=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, :70]
df316=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, :70]

In [6]:
all_df31 = pd.concat([df311, df312, df313, df314, df315, df316])
all_df31.reset_index(inplace=True, drop=True)
all_df31

,기준년월,ID,최종이용일자_기본,최종이용일자_신판,최종이용일자_CA,최종이용일자_카드론,최종이용일자_체크,최종이용일자_일시불,최종이용일자_할부,이용건수_신용_B0M,...,최대이용금액_CA_R12M,최대이용금액_체크_R12M,최대이용금액_카드론_R12M,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,이용개월수_할부_R12M,이용개월수_할부_유이자_R12M,이용개월수_할부_무이자_R12M,이용개월수_부분무이자_R12M
0,201807,TRAIN_000000,20180719,20180713,20180719,10101,20180203,20180709,20180713,11,...,11710,1020,0,12,12,12,5,1,4,0
1,201807,TRAIN_000001,20180719,20180719,20170728,20170327,10101,20180719,20171231,13,...,3377,0,41320,12,12,12,2,1,1,0
2,201807,TRAIN_000002,20180706,20180706,20180706,20151119,20141230,20180706,20180627,12,...,65977,0,0,9,9,9,2,0,2,0
3,201807,TRAIN_000003,20180721,20180715,20180721,10101,20141111,20180704,20180715,6,...,19698,0,0,12,12,7,8,4,5,0
4,201807,TRAIN_000004,20180124,20180124,10101,10101,20180512,20180124,10101,-2,...,0,3324,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,20181220,20181220,10101,10101,20181212,20181220,20160501,2,...,0,5072,0,3,0,0,0,0,0,0
2399996,201812,TRAIN_399996,20181202,20181202,10101,20170112,10101,20181202,20180112,10,...,0,0,0,12,12,12,1,0,1,0
2399997,201812,TRAIN_399997,20181230,20181230,10101,10101,20131124,20181230,20180919,10,...,0,0,0,12,12,12,4,0,4,0
2399998,201812,TRAIN_399998,20161224,20161224,10101,10101,10101,20161224,20150122,-2,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,20180831,20180831,10101,10101,10101,20180831,20180713,-1,...,0,0,0,9,8,7,7,3,5,0

In [7]:
all_df31.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [18]:
all_df31['Segment'] = tg_df

In [19]:
all_df31 = all_df31[~all_df31['Segment'].isin(['C', 'D', 'E'])]

In [20]:
result1, result2 = effect_sizes(all_df31)
display(result1)
display(result2)

                   변수   유형  계수종류    상관계수
0       이용후경과월_할부_무이자  수치형  Eta² 0.23384
1           이용후경과월_할부  수치형  Eta² 0.22677
2   이용개월수_할부_무이자_R12M  수치형  Eta² 0.21664
3       이용개월수_할부_R12M  수치형  Eta² 0.18386
4     이용건수_할부_무이자_B0M  수치형  Eta² 0.09865
..                ...  ...   ...     ...
64     이용건수_부분무이자_B0M  수치형  Eta²     NaN
65       이용건수_카드론_B0M  수치형  Eta²     NaN
66     이용금액_부분무이자_B0M  수치형  Eta²     NaN
67       이용금액_카드론_B0M  수치형  Eta²     NaN
68    이용건수_부분무이자_R12M  수치형  Eta²     NaN

[69 rows x 4 columns]

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000

In [21]:
with pd.ExcelWriter('3.승인매출정보(1)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

### 3번 데이터 (71 ~ 140번)

In [8]:
df321=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 71:140]
df322=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 71:140]
df323=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 71:140]
df324=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 71:140]
df325=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 71:140]
df326=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 71:140]

In [9]:
all_df32 = pd.concat([df321, df322, df323, df324, df325, df326])
all_df32.reset_index(inplace=True, drop=True)
all_df32

,이용개월수_체크_R12M,이용개월수_카드론_R12M,이용건수_신용_R6M,이용건수_신판_R6M,이용건수_일시불_R6M,이용건수_할부_R6M,이용건수_할부_유이자_R6M,이용건수_할부_무이자_R6M,이용건수_부분무이자_R6M,이용건수_CA_R6M,...,이용금액_해외,쇼핑_도소매_이용금액,쇼핑_백화점_이용금액,쇼핑_마트_이용금액,쇼핑_슈퍼마켓_이용금액,쇼핑_편의점_이용금액,쇼핑_아울렛_이용금액,쇼핑_온라인_이용금액,쇼핑_기타_이용금액,교통_주유이용금액
0,3,0,77,67,64,3,0,3,0,10,...,0,0,0,0,0,0,0,0,242,0
1,0,1,81,81,81,0,0,0,0,0,...,0,645,0,0,435,315,0,272,289,1215
2,0,0,62,56,54,2,0,2,0,6,...,0,1038,751,924,504,239,0,6094,0,1362
3,0,0,42,32,26,6,4,2,0,10,...,0,0,0,801,487,0,0,0,0,0
4,8,0,-2,-2,-2,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,8,0,7,7,7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,0,0,101,101,101,0,0,0,0,0,...,0,1496,0,0,714,0,0,0,346,0
2399997,0,0,68,68,66,2,0,2,0,0,...,0,0,0,0,400,300,0,1458,305,1925
2399998,0,0,-7,-7,-7,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,2,2,1,1,0,1,0,0,...,0,0,985,0,0,0,0,0,0,0

In [10]:
all_df32.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [24]:
all_df32['Segment'] = tg_df

In [25]:
all_df32 = all_df32[~all_df32['Segment'].isin(['C', 'D', 'E'])]

In [26]:
result1, result2 = effect_sizes(all_df32)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(2)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                  변수   유형  계수종류    상관계수
0       이용개월수_할부_R6M  수치형  Eta² 0.15775
1   이용개월수_할부_무이자_R6M  수치형  Eta² 0.14221
2       이용개월수_할부_R3M  수치형  Eta² 0.13269
3   이용개월수_할부_무이자_R3M  수치형  Eta² 0.12938
4    이용건수_할부_무이자_R3M  수치형  Eta² 0.11293
..               ...  ...   ...     ...
64   이용개월수_부분무이자_R3M  수치형  Eta² 0.00026
65      이용건수_일시불_R3M  수치형  Eta² 0.00017
66        쇼핑_마트_이용금액  수치형  Eta² 0.00016
67   이용건수_할부_유이자_R3M  수치형  Eta² 0.00013
68      쇼핑_슈퍼마켓_이용금액  수치형  Eta² 0.00000

[69 rows x 4 columns]

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (141~210번)

In [11]:
df331=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 141:210]
df332=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 141:210]
df333=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 141:210]
df334=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 141:210]
df335=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 141:210]
df336=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 141:210]

In [12]:
all_df33 = pd.concat([df331, df332, df333, df334, df335, df336])
all_df33.reset_index(inplace=True, drop=True)
all_df33

,교통_통행료이용금액,교통_버스지하철이용금액,교통_택시이용금액,교통_철도버스이용금액,여유_운동이용금액,여유_Pet이용금액,여유_공연이용금액,여유_공원이용금액,여유_숙박이용금액,여유_여행이용금액,...,할부건수_유이자_6M_R12M,할부건수_유이자_12M_R12M,할부건수_유이자_14M_R12M,할부금액_유이자_3M_R12M,할부금액_유이자_6M_R12M,할부금액_유이자_12M_R12M,할부금액_유이자_14M_R12M,할부건수_무이자_3M_R12M,할부건수_무이자_6M_R12M,할부건수_무이자_12M_R12M
0,0,105,200,0,0,0,0,0,0,0,...,0,0,0,3602,0,0,0,0,3,0
1,0,0,0,443,0,0,0,0,0,0,...,0,0,0,0,0,0,4058,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,3,0
3,0,0,208,0,0,0,0,0,0,0,...,0,0,0,10031,0,0,0,6,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,0,632,192,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,0,0,0,0,834,0,0,0,0,0,...,0,0,0,0,0,0,0,5,0,0
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,10156,0,0,0,6,0,0

In [13]:
all_df33.isna().sum()[lambda x: x > 0]

_1순위업종       539992
_2순위업종       912725
_3순위업종      1107898
_1순위쇼핑업종     922663
_2순위쇼핑업종    1135042
_3순위쇼핑업종    1312267
_1순위교통업종    1164494
_2순위교통업종    1656423
_3순위교통업종    2045455
_1순위여유업종    1987260
_2순위여유업종    2302286
_3순위여유업종    2377725
_1순위납부업종    1216263
_2순위납부업종    2033640
_3순위납부업종    2310187
dtype: int64

In [29]:
all_df33['Segment'] = tg_df

In [30]:
all_df33 = all_df33[~all_df33['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df33)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(3)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                   변수   유형  계수종류    상관계수
0        할부건수_3M_R12M  수치형  Eta² 0.08230
1    할부건수_무이자_3M_R12M  수치형  Eta² 0.08179
2        할부금액_3M_R12M  수치형  Eta² 0.05840
3   할부금액_유이자_12M_R12M  수치형  Eta² 0.02655
4          납부_관리비이용금액  수치형  Eta² 0.01887
5    할부건수_무이자_6M_R12M  수치형  Eta² 0.01656
6        할부건수_6M_R12M  수치형  Eta² 0.01408
7          납부_보험료이용금액  수치형  Eta² 0.01346
8          납부_통신비이용금액  수치형  Eta² 0.01274
9       _1순위납부업종_이용금액  수치형  Eta² 0.01247
10      할부건수_12M_R12M  수치형  Eta² 0.01207
11        _3순위업종_이용금액  수치형  Eta² 0.01053
12      _2순위납부업종_이용금액  수치형  Eta² 0.01036
13  할부건수_무이자_12M_R12M  수치형  Eta² 0.00901
14        _2순위업종_이용금액  수치형  Eta² 0.00866
15        _1순위업종_이용금액  수치형  Eta² 0.00670
16      _3순위납부업종_이용금액  수치형  Eta² 0.00654
17      _1순위쇼핑업종_이용금액  수치형  Eta² 0.00626
18       납부_가스전기료이용금액  수치형  Eta² 0.00584
19  할부건수_유이자_12M_R12M  수치형  Eta² 0.00533
20      _3순위교통업종_이용금액  수치형  Eta² 0.00490
21      _2순위교통업종_이용금액  수치형  Eta² 0.00393
22   할부건수_유이자_3M_R12M  수치형  Eta² 0.00326
23   할부금액_유이자_3M_R12M  수치형  Eta² 0.00323
24       할부금액_6M_R12M  수치형  Eta² 0.00319
25      _2순위쇼핑업종_이용금액  수치형  Eta² 0.00279
26      할부금액_12M_R12M  수치형  Eta² 0.00265
27       교통_버스지하철이용금액  수치형  Eta² 0.00218
28          여유_숙박이용금액  수치형  Eta² 0.00214
29      _1순위교통업종_이용금액  수치형  Eta² 0.00200
30      _3순위쇼핑업종_이용금액  수치형  Eta² 0.00184
31  할부금액_유이자_14M_R12M  수치형  Eta² 0.00159
32          여유_운동이용금액  수치형  Eta² 0.00142
33      할부금액_14M_R12M  수치형  Eta² 0.00133
34          여유_공원이용금액  수치형  Eta² 0.00126
35          여유_항공이용금액  수치형  Eta² 0.00123
36      _2순위여유업종_이용금액  수치형  Eta² 0.00077
37          여유_공연이용금액  수치형  Eta² 0.00059
38        교통_철도버스이용금액  수치형  Eta² 0.00054
39      _1순위여유업종_이용금액  수치형  Eta² 0.00034
40          납부_기타이용금액  수치형  Eta² 0.00029
41   할부건수_유이자_6M_R12M  수치형  Eta² 0.00018
42          여유_기타이용금액  수치형  Eta² 0.00014
43      _3순위여유업종_이용금액  수치형  Eta² 0.00011
44   할부금액_유이자_6M_R12M  수치형  Eta² 0.00007
45          교통_택시이용금액  수치형  Eta² 0.00003
46         여유_Pet이용금액  수치형  Eta² 0.00001
47         교통_통행료이용금액  수치형  Eta²     NaN
48          여유_여행이용금액  수치형  Eta²     NaN
49         납부_렌탈료이용금액  수치형  Eta²     NaN
50        납부_유선방송이용금액  수치형  Eta²     NaN
51        납부_건강연금이용금액  수치형  Eta²     NaN
52      할부건수_14M_R12M  수치형  Eta²     NaN
53  할부건수_유이자_14M_R12M  수치형  Eta²     NaN

          변수   유형        계수종류    상관계수
0   _2순위납부업종  범주형  Cramér's V 0.29501
1     _3순위업종  범주형  Cramér's V 0.20882
2     _2순위업종  범주형  Cramér's V 0.15342
3     _1순위업종  범주형  Cramér's V 0.14461
4   _2순위쇼핑업종  범주형  Cramér's V 0.13980
5   _2순위교통업종  범주형  Cramér's V 0.13249
6   _3순위쇼핑업종  범주형  Cramér's V 0.12062
7   _1순위여유업종  범주형  Cramér's V 0.11986
8   _3순위여유업종  범주형  Cramér's V 0.11840
9   _1순위납부업종  범주형  Cramér's V 0.11829
10  _3순위납부업종  범주형  Cramér's V 0.09922
11  _1순위쇼핑업종  범주형  Cramér's V 0.09350
12  _1순위교통업종  범주형  Cramér's V 0.08305
13  _2순위여유업종  범주형  Cramér's V 0.05667
14  _3순위교통업종  범주형  Cramér's V 0.05502

### 3번 데이터 (211 ~ 280번)

In [14]:
df341=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 211:280]
df342=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 211:280]
df343=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 211:280]
df344=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 211:280]
df345=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 211:280]
df346=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 211:280]

In [15]:
all_df34 = pd.concat([df341, df342, df343, df344, df345, df346])
all_df34.reset_index(inplace=True, drop=True)
all_df34

,할부금액_무이자_3M_R12M,할부금액_무이자_6M_R12M,할부금액_무이자_12M_R12M,할부금액_무이자_14M_R12M,할부건수_부분_3M_R12M,할부건수_부분_6M_R12M,할부건수_부분_12M_R12M,할부건수_부분_14M_R12M,할부금액_부분_3M_R12M,할부금액_부분_6M_R12M,...,최종카드론_대출일자,최종카드론_대출월수,최종카드론_거치개월수,최종카드론_대출금액,이용개월수_온라인_R6M,이용개월수_오프라인_R6M,이용금액_온라인_R6M,이용금액_오프라인_R6M,이용건수_온라인_R6M,이용건수_오프라인_R6M
0,1314,4514,0,0,0,0,0,0,0,0,...,NaN,0,0,0,1,6,847,11097,0,54
1,2076,0,0,0,0,0,0,0,0,0,...,20170327.0,24,6,76723,1,6,281,18638,4,95
2,0,10561,0,0,0,0,0,0,0,0,...,20151119.0,36,6,95094,3,6,12559,29192,7,76
3,12098,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,0,18056,0,39
4,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,1,0,787,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,0,0,0,0,0
2399996,1888,0,0,0,0,0,0,0,0,0,...,20170112.0,36,6,108036,0,6,0,60373,0,57
2399997,27617,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,3998,32036,0,69
2399998,0,0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,0,0,0,0,0
2399999,13847,4309,0,0,0,0,0,0,0,0,...,NaN,0,0,0,0,6,0,4537,0,43

In [16]:
all_df34 .isna().sum()[lambda x: x > 0]

최종카드론_금융상환방식코드    1958126
최종카드론_신청경로코드      1958226
최종카드론_대출일자        1988330
dtype: int64

In [33]:
all_df34['Segment'] = tg_df

In [34]:
all_df34 = all_df34[~all_df34['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df34)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(4)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                       변수   유형  계수종류    상관계수
0        할부금액_무이자_3M_R12M  수치형  Eta² 0.05751
1            RP건수_아파트_B0M  수치형  Eta² 0.02159
2              RP후경과월_아파트  수치형  Eta² 0.02159
3          이용개월수_오프라인_R6M  수치형  Eta² 0.02128
4           이용개월수_온라인_R6M  수치형  Eta² 0.02014
..                    ...  ...   ...     ...
63         증감_RP건수_아파트_전월  수치형  Eta²     NaN
64  증감_RP건수_제휴사서비스직접판매_전월  수치형  Eta²     NaN
65         증감_RP건수_학습비_전월  수치형  Eta²     NaN
66        증감_RP건수_유선방송_전월  수치형  Eta²     NaN
67          증감_RP건수_건강_전월  수치형  Eta²     NaN

[68 rows x 4 columns]

             변수   유형        계수종류    상관계수
0  최종카드론_신청경로코드  범주형  Cramér's V 0.20538

### 3번 데이터 (281~350번)

In [2]:
df351=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 281:350]
df352=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 281:350]
df353=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 281:350]
df354=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 281:350]
df355=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 281:350]
df356=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 281:350]

In [3]:
all_df35 = pd.concat([df351, df352, df353, df354, df355, df356])
all_df35.reset_index(inplace=True, drop=True)
all_df35

,이용금액_오프라인_R3M,이용건수_온라인_R3M,이용건수_오프라인_R3M,이용금액_온라인_B0M,이용금액_오프라인_B0M,이용건수_온라인_B0M,이용건수_오프라인_B0M,이용개월수_페이_온라인_R6M,이용개월수_페이_오프라인_R6M,이용금액_페이_온라인_R6M,...,이용금액_A페이_B0M,이용금액_B페이_B0M,이용금액_C페이_B0M,이용금액_D페이_B0M,이용건수_간편결제_B0M,이용건수_당사페이_B0M,이용건수_당사기타_B0M,이용건수_A페이_B0M,이용건수_B페이_B0M,이용건수_C페이_B0M
0,4131,0,17,0,4043,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,14339,0,51,0,3980,0,15,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,12250,7,33,1625,4524,0,12,2,0,5311,...,0,0,0,0,0,0,0,0,0,0
3,10408,0,19,0,3975,0,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,25205,0,24,0,4676,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399997,13267,0,32,671,4516,0,13,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,0,0,21,0,0,0,7,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
all_df35.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [37]:
all_df35['Segment'] = tg_df

In [38]:
all_df35 = all_df35[~all_df35['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df35)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(5)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

               변수   유형  계수종류    상관계수
0    이용건수_온라인_B0M  수치형  Eta² 0.02166
1    이용건수_온라인_R3M  수치형  Eta² 0.01948
2    이용금액_D페이_R6M  수치형  Eta² 0.01808
3    이용건수_D페이_R6M  수치형  Eta² 0.01578
4   이용금액_오프라인_B0M  수치형  Eta² 0.01487
..            ...  ...   ...     ...
64  이용건수_당사기타_R3M  수치형  Eta²     NaN
65  이용금액_당사페이_B0M  수치형  Eta²     NaN
66  이용금액_당사기타_B0M  수치형  Eta²     NaN
67  이용건수_당사페이_B0M  수치형  Eta²     NaN
68  이용건수_당사기타_B0M  수치형  Eta²     NaN

[69 rows x 4 columns]

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 3번 데이터 (351번 ~)

In [2]:
df361=pd.read_parquet(r'train/3.승인매출정보/201807_train_.parquet').iloc[:, 351:]
df362=pd.read_parquet(r'train/3.승인매출정보/201808_train_.parquet').iloc[:, 351:]
df363=pd.read_parquet(r'train/3.승인매출정보/201809_train_.parquet').iloc[:, 351:]
df364=pd.read_parquet(r'train/3.승인매출정보/201810_train_.parquet').iloc[:, 351:]
df365=pd.read_parquet(r'train/3.승인매출정보/201811_train_.parquet').iloc[:, 351:]
df366=pd.read_parquet(r'train/3.승인매출정보/201812_train_.parquet').iloc[:, 351:]

In [3]:
all_df36 = pd.concat([df361, df362, df363, df364, df365, df366])
all_df36.reset_index(inplace=True, drop=True)
all_df36

,이용개월수_선결제_R6M,이용횟수_선결제_R6M,이용금액_선결제_R6M,이용건수_선결제_R6M,이용횟수_선결제_R3M,이용금액_선결제_R3M,이용건수_선결제_R3M,이용횟수_선결제_B0M,이용금액_선결제_B0M,이용건수_선결제_B0M,...,승인거절건수_한도초과_B0M,승인거절건수_BL_B0M,승인거절건수_입력오류_B0M,승인거절건수_기타_B0M,승인거절건수_R3M,승인거절건수_한도초과_R3M,승인거절건수_BL_R3M,승인거절건수_입력오류_R3M,승인거절건수_기타_R3M,이용금액대
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,01.100만원+
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,03.30만원+
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,01.100만원+
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,3,3,0,0,0,01.100만원+
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
2399996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,01.100만원+
2399997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,02.50만원+
2399998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,09.미사용
2399999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,04.10만원+

In [4]:
all_df36.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [7]:
all_df36['Segment'] = tg_df

In [8]:
all_df36 = all_df36[~all_df36['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df36)
display(result1)
display(result2)

with pd.ExcelWriter('3.승인매출정보(6)_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                    변수   유형  계수종류    상관계수
0            선입금원금_B2M  수치형  Eta² 0.05191
1            선입금원금_B0M  수치형  Eta² 0.05123
2         이용횟수_선결제_R6M  수치형  Eta² 0.05112
3           연체입금원금_B5M  수치형  Eta² 0.04956
4            선입금원금_B5M  수치형  Eta² 0.04809
5        이용개월수_결제일_R6M  수치형  Eta² 0.04582
6        이용개월수_선결제_R6M  수치형  Eta² 0.04398
7         이용건수_선결제_R6M  수치형  Eta² 0.04392
8        이용개월수_결제일_R3M  수치형  Eta² 0.04284
9         이용횟수_선결제_R3M  수치형  Eta² 0.04174
10        이용금액_선결제_B0M  수치형  Eta² 0.04103
11        이용금액_선결제_R3M  수치형  Eta² 0.04039
12        이용금액_선결제_R6M  수치형  Eta² 0.03932
13          연체입금원금_B0M  수치형  Eta² 0.03925
14        이용횟수_선결제_B0M  수치형  Eta² 0.03815
15          연체입금원금_B2M  수치형  Eta² 0.03745
16         가맹점매출금액_B1M  수치형  Eta² 0.03601
17         가맹점매출금액_B2M  수치형  Eta² 0.03396
18        이용건수_선결제_R3M  수치형  Eta² 0.03216
19          정상입금원금_B0M  수치형  Eta² 0.02647
20          정상입금원금_B5M  수치형  Eta² 0.02065
21          정상입금원금_B2M  수치형  Eta² 0.01916
22        이용건수_선결제_B0M  수치형  Eta² 0.01816
23      신청건수_ATM_CA_B0  수치형  Eta² 0.01310
24     승인거절건수_한도초과_R3M  수치형  Eta² 0.00901
25          승인거절건수_R3M  수치형  Eta² 0.00861
26         건수_할부전환_R6M  수치형  Eta² 0.00777
27         금액_할부전환_R6M  수치형  Eta² 0.00773
28         건수_할부전환_R3M  수치형  Eta² 0.00710
29         금액_할부전환_R3M  수치형  Eta² 0.00709
30         이용횟수_연체_R6M  수치형  Eta² 0.00582
31         이용금액_연체_R6M  수치형  Eta² 0.00519
32         이용금액_연체_R3M  수치형  Eta² 0.00453
33         이용횟수_연체_R3M  수치형  Eta² 0.00435
34         이용금액_연체_B0M  수치형  Eta² 0.00232
35         이용횟수_연체_B0M  수치형  Eta² 0.00227
36     승인거절건수_입력오류_R3M  수치형  Eta² 0.00180
37  연속무실적개월수_기본_24M_카드  수치형  Eta² 0.00177
38          정상청구원금_B5M  수치형  Eta² 0.00168
39       승인거절건수_기타_R3M  수치형  Eta² 0.00164
40       승인거절건수_BL_R3M  수치형  Eta² 0.00111
41        이용개월수_전체_R3M  수치형  Eta² 0.00098
42     신청건수_ATM_CL_R6M  수치형  Eta² 0.00090
43          승인거절건수_B0M  수치형  Eta² 0.00090
44     승인거절건수_한도초과_B0M  수치형  Eta² 0.00090
45          정상청구원금_B0M  수치형  Eta² 0.00056
46  연속유실적개월수_기본_24M_카드  수치형  Eta² 0.00036
47          정상청구원금_B2M  수치형  Eta² 0.00017
48        이용개월수_전체_R6M  수치형  Eta² 0.00000
49     신청건수_ATM_CA_R6M  수치형  Eta² 0.00000
50      신청건수_ATM_CL_B0  수치형  Eta²     NaN
51       승인거절건수_BL_B0M  수치형  Eta²     NaN
52     승인거절건수_입력오류_B0M  수치형  Eta²     NaN
53       승인거절건수_기타_B0M  수치형  Eta²     NaN

Empty DataFrame
Columns: [변수, 유형, 계수종류, 상관계수]
Index: []

### 4번 데이터

In [5]:
df41=pd.read_parquet(r'train/4.청구입금정보/201807_train_.parquet')
df42=pd.read_parquet(r'train/4.청구입금정보/201808_train_.parquet')
df43=pd.read_parquet(r'train/4.청구입금정보/201809_train_.parquet')
df44=pd.read_parquet(r'train/4.청구입금정보/201810_train_.parquet')
df45=pd.read_parquet(r'train/4.청구입금정보/201811_train_.parquet')
df46=pd.read_parquet(r'train/4.청구입금정보/201812_train_.parquet')

In [6]:
all_df4 = pd.concat([df41, df42, df43, df44, df45, df46])
all_df4.reset_index(inplace=True, drop=True)
all_df4

,기준년월,ID,대표결제일,대표결제방법코드,대표청구지고객주소구분코드,대표청구서수령지구분코드,청구서수령방법,청구서발송여부_B0,청구서발송여부_R3M,청구서발송여부_R6M,...,할인금액_청구서_B0M,상환개월수_결제일_R6M,상환개월수_결제일_R3M,선결제건수_R6M,선결제건수_R3M,연체건수_R6M,연체건수_R3M,혜택수혜금액_R3M,포인트_마일리지_환산_B0M,혜택수혜금액
0,201807,TRAIN_000000,27,자동이체,미확인,당사페이앱+이메일,문자메세지,1,1,1,...,0,5,3,0,0,1,0,3,0,0
1,201807,TRAIN_000001,13,자동이체,주거지,우편,우편,1,1,1,...,163,6,3,0,0,0,0,0,0,0
2,201807,TRAIN_000002,1,자동이체,미확인,이메일,이메일,1,1,1,...,0,6,3,0,0,0,0,121,0,50
3,201807,TRAIN_000003,5,자동이체,주거지,우편,우편,1,1,1,...,0,5,3,2,0,0,0,3,0,2
4,201807,TRAIN_000004,13,자동이체,주거지,우편,우편,0,1,1,...,0,1,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,25,자동이체,주거지,우편,우편,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,20,자동이체,미확인,이메일,이메일,1,1,1,...,0,6,3,0,0,0,0,164,0,53
2399997,201812,TRAIN_399997,20,자동이체,회사,우편,우편,1,1,1,...,0,6,3,0,0,0,0,0,0,0
2399998,201812,TRAIN_399998,20,자동이체,주거지,우편,우편,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,23,자동이체,주거지,우편,우편,1,1,1,...,0,6,3,0,0,0,0,0,0,0

In [9]:
all_df4.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [46]:
all_df4['Segment'] = tg_df

In [47]:
all_df4 = all_df4[~all_df1['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df4)
display(result1)
display(result2)

with pd.ExcelWriter('4.청구입금정보_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                  변수   유형  계수종류    상관계수
0      상환개월수_결제일_R6M  수치형  Eta² 0.06913
1      상환개월수_결제일_R3M  수치형  Eta² 0.06347
2          선결제건수_R6M  수치형  Eta² 0.06003
3          선결제건수_R3M  수치형  Eta² 0.05703
4       마일_잔여포인트_B0M  수치형  Eta² 0.05461
5   포인트_마일리지_월적립_R3M  수치형  Eta² 0.04337
6   포인트_마일리지_월적립_B0M  수치형  Eta² 0.04048
7       할인금액_청구서_B0M  수치형  Eta² 0.01588
8       할인금액_청구서_R3M  수치형  Eta² 0.01498
9              대표결제일  수치형  Eta² 0.01271
10          할인금액_B0M  수치형  Eta² 0.01090
11          연체건수_R3M  수치형  Eta² 0.01080
12       청구서발송여부_R6M  수치형  Eta² 0.01078
13          할인금액_R3M  수치형  Eta² 0.01042
14     포인트_적립포인트_R3M  수치형  Eta² 0.00762
15   포인트_포인트_월적립_R3M  수치형  Eta² 0.00722
16       청구서발송여부_R3M  수치형  Eta² 0.00718
17          연체건수_R6M  수치형  Eta² 0.00686
18     포인트_이용포인트_R3M  수치형  Eta² 0.00605
19      마일_적립포인트_R3M  수치형  Eta² 0.00604
20   포인트_포인트_월적립_B0M  수치형  Eta² 0.00509
21    포인트_이용포인트_R12M  수치형  Eta² 0.00471
22        혜택수혜금액_R3M  수치형  Eta² 0.00312
23            혜택수혜금액  수치형  Eta² 0.00275
24    포인트_적립포인트_R12M  수치형  Eta² 0.00273
25   포인트_마일리지_환산_B0M  수치형  Eta² 0.00207
26    포인트_포인트_건별_B0M  수치형  Eta² 0.00174
27    포인트_포인트_건별_R3M  수치형  Eta² 0.00140
28     마일_적립포인트_R12M  수치형  Eta² 0.00069
29           청구금액_B0  수치형  Eta² 0.00053
30      마일_이용포인트_R3M  수치형  Eta² 0.00048
31     마일_이용포인트_R12M  수치형  Eta² 0.00037
32   포인트_마일리지_건별_R3M  수치형  Eta² 0.00025
33   포인트_마일리지_건별_B0M  수치형  Eta² 0.00024
34          청구금액_R3M  수치형  Eta² 0.00019
35          청구금액_R6M  수치형  Eta² 0.00000
36              기준년월  수치형  Eta² 0.00000
37        청구서발송여부_B0  수치형  Eta²     NaN
38     포인트_잔여포인트_B0M  수치형  Eta²     NaN

              변수   유형        계수종류    상관계수
0             ID  범주형  Cramér's V 1.00000
1   대표청구서수령지구분코드  범주형  Cramér's V 0.13633
2        청구서수령방법  범주형  Cramér's V 0.13633
3       할인건수_R3M  범주형  Cramér's V 0.10021
4  대표청구지고객주소구분코드  범주형  Cramér's V 0.07936
5       할인건수_B0M  범주형  Cramér's V 0.00000

### 5번 데이터

In [10]:
df51=pd.read_parquet(r'train/5.잔액정보/201807_train_.parquet')
df52=pd.read_parquet(r'train/5.잔액정보/201808_train_.parquet')
df53=pd.read_parquet(r'train/5.잔액정보/201809_train_.parquet')
df54=pd.read_parquet(r'train/5.잔액정보/201810_train_.parquet')
df55=pd.read_parquet(r'train/5.잔액정보/201811_train_.parquet')
df56=pd.read_parquet(r'train/5.잔액정보/201812_train_.parquet')

In [11]:
all_df5 = pd.concat([df51, df52, df53, df54, df55, df56])
all_df5.reset_index(inplace=True, drop=True)
all_df5

,기준년월,ID,잔액_일시불_B0M,잔액_할부_B0M,잔액_현금서비스_B0M,잔액_리볼빙일시불이월_B0M,잔액_리볼빙CA이월_B0M,잔액_카드론_B0M,월중평잔_일시불_B0M,월중평잔_할부_B0M,...,평잔_6M,평잔_일시불_6M,평잔_일시불_해외_6M,평잔_RV일시불_6M,평잔_RV일시불_해외_6M,평잔_할부_6M,평잔_할부_해외_6M,평잔_CA_6M,평잔_CA_해외_6M,평잔_카드론_6M
0,201807,TRAIN_000000,998,962,22971,0,0,0,1084,547,...,15988,2440,0,0,0,572,0,17008,0,0
1,201807,TRAIN_000001,2565,2390,0,0,0,0,4090,2553,...,7045,2677,0,2830,0,2736,0,0,0,0
2,201807,TRAIN_000002,5312,5113,21531,6795,0,0,5006,8778,...,66549,9118,0,8870,0,4429,0,43351,0,0
3,201807,TRAIN_000003,730,5025,26284,0,0,0,487,5607,...,30139,884,0,0,0,5097,0,30697,0,0
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,28,21,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399996,201812,TRAIN_399996,3351,0,0,0,0,27337,4412,0,...,67826,12524,0,0,0,0,0,0,0,23031
2399997,201812,TRAIN_399997,2524,2960,0,0,0,0,2694,3374,...,8627,3241,0,0,0,3995,0,0,0,0
2399998,201812,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2399999,201812,TRAIN_399999,1148,3452,0,0,0,0,980,1839,...,5463,1053,0,0,0,4373,0,0,0,0

In [12]:
all_df5.isna().sum()[lambda x: x > 0]

연체일자_B0M    2394336
dtype: int64

In [50]:
all_df5['Segment'] = tg_df

In [51]:
all_df5 = all_df5[~all_df5['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df5)
display(result1)
display(result2)

with pd.ExcelWriter('5.잔액정보_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                변수   유형  계수종류    상관계수
0    잔액_할부_무이자_B0M  수치형  Eta² 0.03814
1        잔액_할부_B0M  수치형  Eta² 0.03764
2        평잔_일시불_6M  수치형  Eta² 0.03632
3   평잔_RV일시불_해외_3M  수치형  Eta² 0.01405
4   평잔_RV일시불_해외_6M  수치형  Eta² 0.01213
..             ...  ...   ...     ...
75  연체잔액_할부_해외_B0M  수치형  Eta²     NaN
76     연체잔액_CA_B0M  수치형  Eta²     NaN
77  연체잔액_CA_해외_B0M  수치형  Eta²     NaN
78     평잔_할부_해외_3M  수치형  Eta²     NaN
79     평잔_할부_해외_6M  수치형  Eta²     NaN

[80 rows x 4 columns]

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000

### 6번 데이터

In [7]:
df61=pd.read_parquet(r'train/6.채널정보/201807_train_.parquet')
df62=pd.read_parquet(r'train/6.채널정보/201808_train_.parquet')
df63=pd.read_parquet(r'train/6.채널정보/201809_train_.parquet')
df64=pd.read_parquet(r'train/6.채널정보/201810_train_.parquet')
df65=pd.read_parquet(r'train/6.채널정보/201811_train_.parquet')
df66=pd.read_parquet(r'train/6.채널정보/201812_train_.parquet')

In [8]:
all_df6 = pd.concat([df61, df62, df63, df64, df65, df66])
all_df6.reset_index(inplace=True, drop=True)
all_df6

,기준년월,ID,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,인입일수_ARS_R6M,인입월수_ARS_R6M,인입후경과월_ARS,인입횟수_ARS_B0M,이용메뉴건수_ARS_B0M,인입일수_ARS_B0M,...,당사PAY_방문횟수_R6M,당사PAY_방문월수_R6M,당사멤버쉽_방문횟수_B0M,당사멤버쉽_방문횟수_R6M,당사멤버쉽_방문월수_R6M,OS구분코드,홈페이지_금융건수_R6M,홈페이지_선결제건수_R6M,홈페이지_금융건수_R3M,홈페이지_선결제건수_R3M
0,201807,TRAIN_000000,10회 이상,10회 이상,8,6,0,2,6,2,...,0,0,22,221,6,Android,0,0,0,0
1,201807,TRAIN_000001,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2,201807,TRAIN_000002,1회 이상,1회 이상,1,1,0,2,5,1,...,0,0,0,0,0,Android,11,6,5,5
3,201807,TRAIN_000003,10회 이상,10회 이상,10,6,0,2,6,2,...,0,0,23,219,6,Android,0,0,0,0
4,201807,TRAIN_000004,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,Android,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399996,201812,TRAIN_399996,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,1,None,0,0,0,0
2399997,201812,TRAIN_399997,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399998,201812,TRAIN_399998,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0
2399999,201812,TRAIN_399999,1회 이상,1회 이상,0,0,0,0,0,0,...,0,0,0,0,0,None,0,0,0,0

In [9]:
all_df6.isna().sum()[lambda x: x > 0]

OS구분코드    1633566
dtype: int64

In [7]:
all_df6['Segment'] = tg_df

In [8]:
all_df6 = all_df6[~all_df6['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df6)
display(result1)
display(result2)

with pd.ExcelWriter('6.채널정보_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                변수   유형  계수종류    상관계수
0     방문후경과월_앱_R6M  수치형  Eta² 0.05640
1       방문월수_앱_R6M  수치형  Eta² 0.04999
2       방문일수_앱_B0M  수치형  Eta² 0.04993
3       방문일수_앱_R6M  수치형  Eta² 0.04763
4       방문횟수_앱_B0M  수치형  Eta² 0.04695
..             ...  ...   ...     ...
93      불만제기건수_B0M  수치형  Eta²     NaN
94     불만제기건수_R12M  수치형  Eta²     NaN
95  당사PAY_방문횟수_B0M  수치형  Eta²     NaN
96  당사PAY_방문횟수_R6M  수치형  Eta²     NaN
97  당사PAY_방문월수_R6M  수치형  Eta²     NaN

[98 rows x 4 columns]

               변수   유형        계수종류    상관계수
0              ID  범주형  Cramér's V 1.00000
1      방문횟수_앱_R6M  범주형  Cramér's V 0.34220
2    인입횟수_ARS_R6M  범주형  Cramér's V 0.14604
3  이용메뉴건수_ARS_R6M  범주형  Cramér's V 0.14019
4     방문일수_PC_R6M  범주형  Cramér's V 0.11137
5     방문횟수_PC_R6M  범주형  Cramér's V 0.10636
6          OS구분코드  범주형  Cramér's V 0.05144

### 7번 데이터

In [10]:
df71=pd.read_parquet(r'train/7.마케팅정보/201807_train_.parquet')
df72=pd.read_parquet(r'train/7.마케팅정보/201808_train_.parquet')
df73=pd.read_parquet(r'train/7.마케팅정보/201809_train_.parquet')
df74=pd.read_parquet(r'train/7.마케팅정보/201810_train_.parquet')
df75=pd.read_parquet(r'train/7.마케팅정보/201811_train_.parquet')
df76=pd.read_parquet(r'train/7.마케팅정보/201812_train_.parquet')

In [11]:
all_df7 = pd.concat([df71, df72, df73, df74, df75, df76])
all_df7.reset_index(inplace=True, drop=True)
all_df7

,기준년월,ID,컨택건수_카드론_TM_B0M,컨택건수_리볼빙_TM_B0M,컨택건수_CA_TM_B0M,컨택건수_이용유도_TM_B0M,컨택건수_신용발급_TM_B0M,컨택건수_부대서비스_TM_B0M,컨택건수_포인트소진_TM_B0M,컨택건수_보험_TM_B0M,...,컨택건수_카드론_당사앱_R6M,컨택건수_CA_당사앱_R6M,컨택건수_리볼빙_당사앱_R6M,컨택건수_이용유도_당사앱_R6M,컨택건수_채권_B0M,컨택건수_FDS_B0M,컨택건수_채권_R6M,컨택건수_FDS_R6M,캠페인접촉건수_R12M,캠페인접촉일수_R12M
0,201807,TRAIN_000000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
1,201807,TRAIN_000001,3,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,15회 이상,10일 이상
2,201807,TRAIN_000002,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
3,201807,TRAIN_000003,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
4,201807,TRAIN_000004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399996,201812,TRAIN_399996,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,20회 이상,15일 이상
2399997,201812,TRAIN_399997,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399998,201812,TRAIN_399998,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상
2399999,201812,TRAIN_399999,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1회 이상,1일 이상

In [12]:
all_df7.isna().sum()[lambda x: x > 0]

Series([], dtype: int64)

In [11]:
all_df7['Segment'] = tg_df

In [12]:
all_df7 = all_df7[~all_df7['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df7)
display(result1)
display(result2)

with pd.ExcelWriter('7.마케팅정보_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                   변수   유형  계수종류    상관계수
0   컨택건수_이용유도_LMS_B0M  수치형  Eta² 0.01945
1   컨택건수_이용유도_LMS_R6M  수치형  Eta² 0.01623
2    컨택건수_이용유도_EM_R6M  수치형  Eta² 0.01620
3    컨택건수_이용유도_EM_B0M  수치형  Eta² 0.01161
4    컨택건수_이용유도_TM_R6M  수치형  Eta² 0.01111
..                ...  ...   ...     ...
56    컨택건수_CA_당사앱_R6M  수치형  Eta²     NaN
57   컨택건수_리볼빙_당사앱_R6M  수치형  Eta²     NaN
58  컨택건수_이용유도_당사앱_R6M  수치형  Eta²     NaN
59       컨택건수_FDS_B0M  수치형  Eta²     NaN
60       컨택건수_FDS_R6M  수치형  Eta²     NaN

[61 rows x 4 columns]

             변수   유형        계수종류    상관계수
0            ID  범주형  Cramér's V 1.00000
1  캠페인접촉건수_R12M  범주형  Cramér's V 0.14529
2  캠페인접촉일수_R12M  범주형  Cramér's V 0.11757

### 8번 데이터

In [13]:
df81=pd.read_parquet(r'train/8.성과정보/201807_train_.parquet')
df82=pd.read_parquet(r'train/8.성과정보/201808_train_.parquet')
df83=pd.read_parquet(r'train/8.성과정보/201809_train_.parquet')
df84=pd.read_parquet(r'train/8.성과정보/201810_train_.parquet')
df85=pd.read_parquet(r'train/8.성과정보/201811_train_.parquet')
df86=pd.read_parquet(r'train/8.성과정보/201812_train_.parquet')

In [14]:
all_df8 = pd.concat([df81, df82, df83, df84, df85, df86])
all_df8.reset_index(inplace=True, drop=True)
all_df8

,기준년월,ID,증감율_이용건수_신용_전월,증감율_이용건수_신판_전월,증감율_이용건수_일시불_전월,증감율_이용건수_할부_전월,증감율_이용건수_CA_전월,증감율_이용건수_체크_전월,증감율_이용건수_카드론_전월,증감율_이용금액_신용_전월,...,변동률_RV일시불평잔,변동률_할부평잔,변동률_CA평잔,변동률_RVCA평잔,변동률_카드론평잔,변동률_잔액_B1M,변동률_잔액_일시불_B1M,변동률_잔액_CA_B1M,혜택수혜율_R3M,혜택수혜율_B0M
0,201807,TRAIN_000000,0.454548,0.454548,0.364727,1.999996,0.0,0.000000,0.0,0.409766,...,0.999998,1.042805,0.999700,0.999998,0.999998,0.261886,0.270752,0.000000,1.044401,1.280543
1,201807,TRAIN_000001,-0.511808,-0.511808,-0.511808,0.000000,0.0,0.000000,0.0,-1.010817,...,1.092698,0.905663,0.999998,0.999998,0.999998,-0.563388,-0.670348,0.000000,0.000000,0.000000
2,201807,TRAIN_000002,-0.062716,-0.062716,0.067843,-1.999996,0.0,0.000000,0.0,-0.902166,...,1.006124,1.993590,0.852567,0.999998,0.999998,-0.046516,0.058114,-0.014191,0.524159,1.208420
3,201807,TRAIN_000003,0.135707,0.135707,0.153975,-1.999996,0.0,0.000000,0.0,-0.866052,...,0.999998,1.050646,0.999877,0.999998,0.999998,0.023821,0.258943,0.000000,0.880925,1.657124
4,201807,TRAIN_000004,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000028,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,0.000000,0.000000,0.000000,0.000000,0.0,-0.081943,0.0,0.000027,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399996,201812,TRAIN_399996,0.073804,0.073804,0.073804,0.000000,0.0,0.000000,0.0,0.207099,...,0.999998,0.999998,0.999998,0.999998,0.921733,-0.203251,-0.159143,0.000000,1.377071,2.533815
2399997,201812,TRAIN_399997,-0.040432,-0.040432,-0.040432,0.000000,0.0,0.000000,0.0,0.254495,...,0.999998,0.345027,0.999998,0.999998,0.999998,0.027319,0.126581,0.000000,0.000000,0.000000
2399998,201812,TRAIN_399998,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000034,...,0.999998,0.999998,0.999998,0.999998,0.999998,0.000000,0.000000,0.000000,NaN,NaN
2399999,201812,TRAIN_399999,0.187598,0.187598,0.187598,0.000000,0.0,0.000000,0.0,0.332268,...,0.999998,0.593160,0.999998,0.999998,0.999998,-0.039845,-0.002659,0.000000,0.000000,0.000000

In [15]:
all_df8.isna().sum()[lambda x: x > 0]

혜택수혜율_R3M    488746
혜택수혜율_B0M    555522
dtype: int64

In [15]:
all_df8['Segment'] = tg_df

In [16]:
all_df8 = all_df8[~all_df8['Segment'].isin(['C', 'D', 'E'])]

result1, result2 = effect_sizes(all_df8)
display(result1)
display(result2)

with pd.ExcelWriter('8.성과정보_A,B.xlsx') as writer:
    result1.to_excel(writer, sheet_name='아노바', index=False)
    result2.to_excel(writer, sheet_name='카이제곱', index=False)

                    변수   유형  계수종류    상관계수
0     잔액_신판평균한도소진율_r3m  수치형  Eta² 0.07562
1   잔액_신판ca평균한도소진율_r6m  수치형  Eta² 0.07277
2   잔액_신판ca최대한도소진율_r3m  수치형  Eta² 0.07167
3     잔액_신판평균한도소진율_r6m  수치형  Eta² 0.07089
4   잔액_신판ca평균한도소진율_r3m  수치형  Eta² 0.07017
5   잔액_신판ca최대한도소진율_r6m  수치형  Eta² 0.06359
6     잔액_신판최대한도소진율_r3m  수치형  Eta² 0.05925
7     잔액_신판최대한도소진율_r6m  수치형  Eta² 0.04220
8       증감율_이용건수_체크_전월  수치형  Eta² 0.01248
9       증감율_이용건수_체크_분기  수치형  Eta² 0.01074
10     증감율_이용건수_카드론_분기  수치형  Eta² 0.01059
11      증감율_이용금액_체크_분기  수치형  Eta² 0.01022
12     증감율_이용금액_카드론_분기  수치형  Eta² 0.01021
13           변동률_카드론평잔  수치형  Eta² 0.00999
14          변동률_잔액_B1M  수치형  Eta² 0.00931
15     증감율_이용금액_일시불_전월  수치형  Eta² 0.00876
16      증감율_이용건수_할부_분기  수치형  Eta² 0.00789
17      변동률_잔액_일시불_B1M  수치형  Eta² 0.00527
18          변동률_RVCA평잔  수치형  Eta² 0.00504
19         변동률_RV일시불평잔  수치형  Eta² 0.00490
20     증감율_이용금액_카드론_전월  수치형  Eta² 0.00449
21      증감율_이용금액_할부_분기  수치형  Eta² 0.00433
22      증감율_이용건수_할부_전월  수치형  Eta² 0.00418
23      증감율_이용금액_신판_전월  수치형  Eta² 0.00416
24            변동률_할부평잔  수치형  Eta² 0.00413
25     증감율_이용건수_카드론_전월  수치형  Eta² 0.00359
26      증감율_이용금액_신용_분기  수치형  Eta² 0.00260
27      증감율_이용건수_CA_전월  수치형  Eta² 0.00252
28      증감율_이용금액_체크_전월  수치형  Eta² 0.00104
29       변동률_잔액_CA_B1M  수치형  Eta² 0.00083
30      증감율_이용건수_신판_전월  수치형  Eta² 0.00076
31      증감율_이용금액_CA_전월  수치형  Eta² 0.00074
32      증감율_이용건수_신용_전월  수치형  Eta² 0.00072
33      증감율_이용건수_신용_분기  수치형  Eta² 0.00053
34            변동률_CA평잔  수치형  Eta² 0.00052
35     증감율_이용건수_일시불_분기  수치형  Eta² 0.00046
36           변동률_일시불평잔  수치형  Eta² 0.00045
37     증감율_이용금액_일시불_분기  수치형  Eta² 0.00022
38      증감율_이용금액_CA_분기  수치형  Eta² 0.00021
39      증감율_이용금액_신용_전월  수치형  Eta² 0.00013
40      증감율_이용금액_할부_전월  수치형  Eta² 0.00012
41      증감율_이용건수_신판_분기  수치형  Eta² 0.00010
42     증감율_이용건수_일시불_전월  수치형  Eta² 0.00009
43           혜택수혜율_R3M  수치형  Eta² 0.00009
44      증감율_이용금액_신판_분기  수치형  Eta² 0.00006
45      증감율_이용건수_CA_분기  수치형  Eta² 0.00005
46           혜택수혜율_B0M  수치형  Eta² 0.00002
47                기준년월  수치형  Eta² 0.00000

   변수   유형        계수종류    상관계수
0  ID  범주형  Cramér's V 1.00000