In [3]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

In [2]:
cols_to_load1 = [
    "ID",
    "_2순위카드이용건수",
    "이용금액_R3M_신용",
    "이용금액_R3M_신용체크",
    "_2순위카드이용금액",
    "_1순위카드이용금액",
    'Life_Stage',
    '연회비발생카드수_B0M'
]

In [3]:
cols_to_load2 = [
    "ID",
    'RV전환가능여부',
    '자발한도감액횟수_R12M',
    '한도증액횟수_R12M',
    '카드론동의여부',
    '한도심사요청건수'
]

In [4]:
cols_to_load3 = [
    "ID",
    "최대이용금액_할부_R12M",
    "이용금액_일시불_B0M",
    "이용금액_일시불_R12M",
    "이용금액_일시불_R3M",
    "이용금액_일시불_R6M",
    "_3순위교통업종_이용금액",
    "_3순위업종_이용금액",
    "_1순위업종_이용금액",
    "_2순위업종_이용금액",
    "이용금액_오프라인_B0M",
    "연체입금원금_B0M",
    "연체입금원금_B5M",
]

In [5]:
cols_to_load4 = [
    "ID",
    "혜택수혜금액",
    '할인건수_R3M',
    '대표청구서수령지구분코드',
    '청구서수령방법',
    '대표청구지고객주소구분코드',
    '할인건수_B0M',
    '대표결제방법코드'
]

In [6]:
cols_to_load5 = [
    "ID",
    "월중평잔_일시불",
]

In [7]:
cols_to_load6 = [
    "ID",
    '방문횟수_PC_R6M',
    '방문일수_PC_R6M',
    '이용메뉴건수_ARS_R6M',
    '인입횟수_ARS_R6M'
]

In [8]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet', columns=cols_to_load1)
df21=pd.read_parquet(r'data/train/2.신용정보/201807_train_.parquet', columns=cols_to_load2)
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet', columns=cols_to_load3)
df41=pd.read_parquet(r'data/train/4.청구입금정보/201807_train_.parquet', columns=cols_to_load4)

In [9]:
df51=pd.read_parquet(r'data/train/5.잔액정보/201807_train_.parquet', columns=cols_to_load5)
df61=pd.read_parquet(r'data/train/6.채널정보/201807_train_.parquet', columns=cols_to_load6)
df71=pd.read_parquet(r'data/train/7.마케팅정보/201807_train_.parquet')
df81=pd.read_parquet(r'data/train/8.성과정보/201807_train_.parquet')

In [10]:
# 1. 먼저 기준이 되는 df1부터 시작
merged_df = df11.copy()

# 2. ID & 기준년월 기준으로 순차 병합
merged_df = merged_df.merge(df21, on=['ID'], how='inner')
merged_df = merged_df.merge(df31, on=['ID'], how='inner')
merged_df = merged_df.merge(df41, on=['ID'], how='inner')
merged_df = merged_df.merge(df51, on=['ID'], how='inner')
merged_df = merged_df.merge(df61, on=['ID'], how='inner')

In [11]:
merged_df

,ID,_2순위카드이용건수,이용금액_R3M_신용,이용금액_R3M_신용체크,_2순위카드이용금액,_1순위카드이용금액,Life_Stage,연회비발생카드수_B0M,RV전환가능여부,자발한도감액횟수_R12M,...,대표청구서수령지구분코드,청구서수령방법,대표청구지고객주소구분코드,할인건수_B0M,대표결제방법코드,월중평잔_일시불,방문횟수_PC_R6M,방문일수_PC_R6M,이용메뉴건수_ARS_R6M,인입횟수_ARS_R6M
0,TRAIN_000000,0,196,196,0,3681,자녀성장(2),0개,N,0회,...,당사페이앱+이메일,문자메세지,미확인,1회 이상,자동이체,1503,1회 이상,1회 이상,10회 이상,10회 이상
1,TRAIN_000001,0,13475,13475,0,13323,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,4447,1회 이상,1회 이상,1회 이상,1회 이상
2,TRAIN_000002,0,23988,23988,0,24493,자녀출산기,0개,N,0회,...,이메일,이메일,미확인,1회 이상,자동이체,5540,10회 이상,10회 이상,1회 이상,1회 이상
3,TRAIN_000003,0,3904,3904,0,5933,자녀성장(2),0개,N,0회,...,우편,우편,주거지,1회 이상,자동이체,606,1회 이상,1회 이상,10회 이상,10회 이상
4,TRAIN_000004,0,0,1190,0,0,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,TRAIN_399995,0,0,2091,0,0,노년생활,0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
399996,TRAIN_399996,0,55111,55111,0,51615,자녀성장(2),0개,Z,0회,...,이메일,이메일,미확인,1회 이상,자동이체,11321,1회 이상,1회 이상,1회 이상,1회 이상
399997,TRAIN_399997,0,14172,14172,0,12996,자녀출산기,0개,N,0회,...,우편,우편,회사,1회 이상,자동이체,2144,1회 이상,1회 이상,1회 이상,1회 이상
399998,TRAIN_399998,0,0,0,0,0,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
399999,TRAIN_399999,41,22796,22796,11023,10250,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,736,1회 이상,1회 이상,1회 이상,1회 이상

In [15]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400000 entries, 0 to 399999
Data columns (total 37 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID              400000 non-null  object
 1   _2순위카드이용건수      400000 non-null  int64
 2   이용금액_R3M_신용     400000 non-null  int64
 3   이용금액_R3M_신용체크   400000 non-null  int64
 4   _2순위카드이용금액      400000 non-null  int64
 5   _1순위카드이용금액      400000 non-null  int64
 6   Life_Stage      400000 non-null  object
 7   연회비발생카드수_B0M    400000 non-null  object
 8   RV전환가능여부        400000 non-null  object
 9   자발한도감액횟수_R12M   400000 non-null  object
 10  한도증액횟수_R12M     400000 non-null  object
 11  카드론동의여부         400000 non-null  object
 12  한도심사요청건수        400000 non-null  object
 13  최대이용금액_할부_R12M  400000 non-null  int64
 14  이용금액_일시불_B0M    400000 non-null  int64
 15  이용금액_일시불_R12M   400000 non-null  int64
 16  이용금액_일시불_R3M    400000 non-null  int64
 17  이용금액_일시불_R6M    400000 non-null  int64
 18  _3순위교통업종_이용금액   400000 non-null  int64
 19  _3순위업종_이용금액     400000 non-null  int64
 20  _1순위업종_이용금액     400000 non-null  int64
 21  _2순위업종_이용금액     400000 non-null  int64
 22  이용금액_오프라인_B0M   400000 non-null  int64
 23  연체입금원금_B0M      400000 non-null  int64
 24  연체입금원금_B5M      400000 non-null  int64
 25  혜택수혜금액          400000 non-null  int64
 26  할인건수_R3M        400000 non-null  object
 27  대표청구서수령지구분코드    400000 non-null  object
 28  청구서수령방법         400000 non-null  object
 29  대표청구지고객주소구분코드   400000 non-null  object
 30  할인건수_B0M        400000 non-null  object
 31  대표결제방법코드        400000 non-null  object
 32  월중평잔_일시불        400000 non-null  int64
 33  방문횟수_PC_R6M     400000 non-null  object
 34  방문일수_PC_R6M     400000 non-null  object
 35  이용메뉴건수_ARS_R6M  400000 non-null  object
 36  인입횟수_ARS_R6M    400000 non-null  object
dtypes: int64(19), object(18)
memory usage: 112.9+ MB

In [28]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calculate_vif(df, drop_cols=None):
    if drop_cols is None:
        drop_cols = []

    # 필요 없는 열 제거
    df = df.drop(columns=drop_cols)

    # 수치형, 범주형 분리
    num_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
    cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

    # One-hot encoding (drop='first' 설정)
    ct = ColumnTransformer(
        transformers=[('cat', OneHotEncoder(drop='first', sparse_output=False, handle_unknown='ignore'), cat_cols)],
        remainder='passthrough'
    )

    df_encoded = ct.fit_transform(df)
    encoded_feature_names = ct.get_feature_names_out()

    # VIF 계산용 데이터프레임 생성 (const 포함)
    X = pd.DataFrame(df_encoded, columns=encoded_feature_names)
    X = sm.add_constant(X)

    vif_data = pd.DataFrame()
    vif_data['feature'] = X.columns
    vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return vif_data

In [50]:
vif_result = calculate_vif(merged_df, drop_cols=['ID','대표청구서수령지구분코드','청구서수령방법','이용금액_R3M_신용',
                                                 '이용금액_일시불_R3M','이용금액_일시불_B0M',
                                                 '이용금액_일시불_R6M', '_2순위카드이용금액', '방문일수_PC_R6M', '_1순위카드이용금액'
                                                ])

In [51]:
# 데이터프레임 출력 생략 없이 전체 표시
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [52]:
display(vif_result)

                      feature          VIF
0                       const  1103.187834
1        cat__Life_Stage_노년생활     2.002043
2          cat__Life_Stage_독신     1.345483
3       cat__Life_Stage_자녀독립기     1.813265
4     cat__Life_Stage_자녀성장(1)     2.944236
5     cat__Life_Stage_자녀성장(2)     2.808678
6       cat__Life_Stage_자녀출산기     1.818818
7      cat__연회비발생카드수_B0M_1개이상     1.013163
8             cat__RV전환가능여부_Z     1.136888
9       cat__자발한도감액횟수_R12M_1회     1.012414
10      cat__한도증액횟수_R12M_1회이상     1.079035
11             cat__카드론동의여부_Y     1.034619
12         cat__한도심사요청건수_1회이상     1.001206
13        cat__할인건수_R3M_1회 이상     1.692304
14       cat__할인건수_R3M_20회 이상     1.405001
15       cat__할인건수_R3M_30회 이상     4.272614
16     cat__대표청구지고객주소구분코드_주거지     1.340574
17      cat__대표청구지고객주소구분코드_회사     1.161459
18        cat__할인건수_B0M_1회 이상     4.197894
19     cat__방문횟수_PC_R6M_1회 이상     2.082941
20    cat__방문횟수_PC_R6M_20회 이상     1.855404
21    cat__방문횟수_PC_R6M_30회 이상     1.169046
22    cat__방문횟수_PC_R6M_40회 이상     1.005201
23  cat__이용메뉴건수_ARS_R6M_1회 이상     6.228631
24    cat__인입횟수_ARS_R6M_1회 이상     6.159373
25      remainder___2순위카드이용건수     2.171706
26   remainder__이용금액_R3M_신용체크     6.895448
27  remainder__최대이용금액_할부_R12M     1.486915
28   remainder__이용금액_일시불_R12M     5.181088
29   remainder___3순위교통업종_이용금액     1.601856
30     remainder___3순위업종_이용금액     5.874633
31     remainder___1순위업종_이용금액     2.784981
32     remainder___2순위업종_이용금액     5.296611
33   remainder__이용금액_오프라인_B0M     5.106539
34      remainder__연체입금원금_B0M     2.360305
35      remainder__연체입금원금_B5M     2.255828
36          remainder__혜택수혜금액     2.145622
37        remainder__월중평잔_일시불     2.316288

In [53]:
pd.set_option('display.max_rows', None)
vif_sorted = vif_result.sort_values(by='VIF', ascending=False)
display(vif_sorted)

                      feature          VIF
0                       const  1103.187834
26   remainder__이용금액_R3M_신용체크     6.895448
23  cat__이용메뉴건수_ARS_R6M_1회 이상     6.228631
24    cat__인입횟수_ARS_R6M_1회 이상     6.159373
30     remainder___3순위업종_이용금액     5.874633
32     remainder___2순위업종_이용금액     5.296611
28   remainder__이용금액_일시불_R12M     5.181088
33   remainder__이용금액_오프라인_B0M     5.106539
15       cat__할인건수_R3M_30회 이상     4.272614
18        cat__할인건수_B0M_1회 이상     4.197894
4     cat__Life_Stage_자녀성장(1)     2.944236
5     cat__Life_Stage_자녀성장(2)     2.808678
31     remainder___1순위업종_이용금액     2.784981
34      remainder__연체입금원금_B0M     2.360305
37        remainder__월중평잔_일시불     2.316288
35      remainder__연체입금원금_B5M     2.255828
25      remainder___2순위카드이용건수     2.171706
36          remainder__혜택수혜금액     2.145622
19     cat__방문횟수_PC_R6M_1회 이상     2.082941
1        cat__Life_Stage_노년생활     2.002043
20    cat__방문횟수_PC_R6M_20회 이상     1.855404
6       cat__Life_Stage_자녀출산기     1.818818
3       cat__Life_Stage_자녀독립기     1.813265
13        cat__할인건수_R3M_1회 이상     1.692304
29   remainder___3순위교통업종_이용금액     1.601856
27  remainder__최대이용금액_할부_R12M     1.486915
14       cat__할인건수_R3M_20회 이상     1.405001
2          cat__Life_Stage_독신     1.345483
16     cat__대표청구지고객주소구분코드_주거지     1.340574
21    cat__방문횟수_PC_R6M_30회 이상     1.169046
17      cat__대표청구지고객주소구분코드_회사     1.161459
8             cat__RV전환가능여부_Z     1.136888
10      cat__한도증액횟수_R12M_1회이상     1.079035
11             cat__카드론동의여부_Y     1.034619
7      cat__연회비발생카드수_B0M_1개이상     1.013163
9       cat__자발한도감액횟수_R12M_1회     1.012414
22    cat__방문횟수_PC_R6M_40회 이상     1.005201
12         cat__한도심사요청건수_1회이상     1.001206

---

In [14]:
drop_cols = [
    '이용금액_R3M_신용','이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R6M',
    '연체입금원금_B5M', '_2순위카드이용건수', '_2순위카드이용금액', '이용금액_오프라인_B0M', '_1순위카드이용금액'
]

merged_df2 = merged_df.drop(columns=drop_cols)

In [13]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# vif 표를 출력한 후 vif 계수가 높다고 생각되는 컬럼들을 추가하여 계속 돌려보요요
# vif_X = train_df2.drop(['Transported'], axis=1)
# vif_X = train_df2.drop(['Transported', 'NumberInGroup'], axis=1)
vif_X = merged_df.drop(['ID'], axis=1)

# vif를 계산하기 위해 상수항을 추가한다.
vif_X2 = sm.add_constant(vif_X)

vif_X2

,const,_2순위카드이용건수,이용금액_R3M_신용,이용금액_R3M_신용체크,_2순위카드이용금액,_1순위카드이용금액,Life_Stage,연회비발생카드수_B0M,RV전환가능여부,자발한도감액횟수_R12M,...,대표청구서수령지구분코드,청구서수령방법,대표청구지고객주소구분코드,할인건수_B0M,대표결제방법코드,월중평잔_일시불,방문횟수_PC_R6M,방문일수_PC_R6M,이용메뉴건수_ARS_R6M,인입횟수_ARS_R6M
0,1.0,0,196,196,0,3681,자녀성장(2),0개,N,0회,...,당사페이앱+이메일,문자메세지,미확인,1회 이상,자동이체,1503,1회 이상,1회 이상,10회 이상,10회 이상
1,1.0,0,13475,13475,0,13323,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,4447,1회 이상,1회 이상,1회 이상,1회 이상
2,1.0,0,23988,23988,0,24493,자녀출산기,0개,N,0회,...,이메일,이메일,미확인,1회 이상,자동이체,5540,10회 이상,10회 이상,1회 이상,1회 이상
3,1.0,0,3904,3904,0,5933,자녀성장(2),0개,N,0회,...,우편,우편,주거지,1회 이상,자동이체,606,1회 이상,1회 이상,10회 이상,10회 이상
4,1.0,0,0,1190,0,0,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
399995,1.0,0,0,2091,0,0,노년생활,0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
399996,1.0,0,55111,55111,0,51615,자녀성장(2),0개,Z,0회,...,이메일,이메일,미확인,1회 이상,자동이체,11321,1회 이상,1회 이상,1회 이상,1회 이상
399997,1.0,0,14172,14172,0,12996,자녀출산기,0개,N,0회,...,우편,우편,회사,1회 이상,자동이체,2144,1회 이상,1회 이상,1회 이상,1회 이상
399998,1.0,0,0,0,0,0,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,0,1회 이상,1회 이상,1회 이상,1회 이상
399999,1.0,41,22796,22796,11023,10250,자녀성장(1),0개,Z,0회,...,우편,우편,주거지,1회 이상,자동이체,736,1회 이상,1회 이상,1회 이상,1회 이상

In [ ]:
# vif를 계산한다.
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]
vif

In [ ]:
pd.set_option('display.max_rows', None)
vif_sorted = vif.sort_values(by='VIF', ascending=False)
display(vif_sorted)

In [ ]:
10/0

In [ ]:
# 상관계수 계산
corr = vif_X.corr()

# 상삼각형 마스크 생성 (중복 제거용)
mask = np.triu(np.ones_like(corr, dtype=bool))

# 시각화
plt.figure(figsize=(18, 15))
sns.heatmap(
    corr,
    mask=mask,
    cmap='RdBu_r',
    annot=True,
    fmt=".2f",
    annot_kws={"size": 8},
    linewidths=0.5,
    cbar_kws={"shrink": 0.5}
)

# 축 글씨 회전
plt.xticks(rotation=45, ha='right', fontsize=8)
plt.yticks(rotation=0, fontsize=8)

plt.title("변수 간 상관계수 히트맵", fontsize=14, pad=20)
plt.tight_layout()
plt.show()

---

In [1]:
cols_to_load1=['ID','기준년월','이용금액_R3M_신용체크', '소지카드수_이용가능_신용', 'Life_Stage','_1순위카드이용금액']
cols_to_load2=['ID','기준년월','RV전환가능여부', '자발한도감액횟수_R12M','한도증액횟수_R12M','카드론동의여부','한도심사요청건수','카드이용한도금액_B2M']
cols_to_load3=['ID','기준년월','최대이용금액_할부_R12M', '이용금액_일시불_R12M', '_3순위업종_이용금액', '이용금액_오프라인_B0M', '연체입금원금_B0M', '이용금액대','이용후경과월_할부_무이자']
cols_to_load4=['ID','기준년월','혜택수혜금액','할인건수_R3M','대표청구지고객주소구분코드', '대표결제방법코드','청구금액_R6M']
cols_to_load5=['ID','기준년월','월중평잔_일시불']
cols_to_load6=['ID','기준년월','방문횟수_PC_R6M','이용메뉴건수_ARS_R6M','인입횟수_ARS_R6M']

In [4]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet', columns=cols_to_load1)
df12=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet', columns=cols_to_load1)
df13=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet', columns=cols_to_load1)
df14=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet', columns=cols_to_load1)
df15=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet', columns=cols_to_load1)
df16=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet', columns=cols_to_load1)

In [5]:
df21=pd.read_parquet(r'data/train/2.신용정보/201807_train_.parquet', columns=cols_to_load2)
df22=pd.read_parquet(r'data/train/2.신용정보/201808_train_.parquet', columns=cols_to_load2)
df23=pd.read_parquet(r'data/train/2.신용정보/201809_train_.parquet', columns=cols_to_load2)
df24=pd.read_parquet(r'data/train/2.신용정보/201810_train_.parquet', columns=cols_to_load2)
df25=pd.read_parquet(r'data/train/2.신용정보/201811_train_.parquet', columns=cols_to_load2)
df26=pd.read_parquet(r'data/train/2.신용정보/201812_train_.parquet', columns=cols_to_load2)

In [6]:
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet', columns=cols_to_load3)
df32=pd.read_parquet(r'data/train/3.승인매출정보/201808_train_.parquet', columns=cols_to_load3)
df33=pd.read_parquet(r'data/train/3.승인매출정보/201809_train_.parquet', columns=cols_to_load3)
df34=pd.read_parquet(r'data/train/3.승인매출정보/201810_train_.parquet', columns=cols_to_load3)
df35=pd.read_parquet(r'data/train/3.승인매출정보/201811_train_.parquet', columns=cols_to_load3)
df36=pd.read_parquet(r'data/train/3.승인매출정보/201812_train_.parquet', columns=cols_to_load3)

In [7]:
df41=pd.read_parquet(r'data/train/4.청구입금정보/201807_train_.parquet', columns=cols_to_load4)
df42=pd.read_parquet(r'data/train/4.청구입금정보/201808_train_.parquet', columns=cols_to_load4)
df43=pd.read_parquet(r'data/train/4.청구입금정보/201809_train_.parquet', columns=cols_to_load4)
df44=pd.read_parquet(r'data/train/4.청구입금정보/201810_train_.parquet', columns=cols_to_load4)
df45=pd.read_parquet(r'data/train/4.청구입금정보/201811_train_.parquet', columns=cols_to_load4)
df46=pd.read_parquet(r'data/train/4.청구입금정보/201812_train_.parquet', columns=cols_to_load4)

In [8]:
df51=pd.read_parquet(r'data/train/5.잔액정보/201807_train_.parquet', columns=cols_to_load5)
df52=pd.read_parquet(r'data/train/5.잔액정보/201808_train_.parquet', columns=cols_to_load5)
df53=pd.read_parquet(r'data/train/5.잔액정보/201809_train_.parquet', columns=cols_to_load5)
df54=pd.read_parquet(r'data/train/5.잔액정보/201810_train_.parquet', columns=cols_to_load5)
df55=pd.read_parquet(r'data/train/5.잔액정보/201811_train_.parquet', columns=cols_to_load5)
df56=pd.read_parquet(r'data/train/5.잔액정보/201812_train_.parquet', columns=cols_to_load5)

In [9]:
df61=pd.read_parquet(r'data/train/6.채널정보/201807_train_.parquet', columns=cols_to_load6)
df62=pd.read_parquet(r'data/train/6.채널정보/201808_train_.parquet', columns=cols_to_load6)
df63=pd.read_parquet(r'data/train/6.채널정보/201809_train_.parquet', columns=cols_to_load6)
df64=pd.read_parquet(r'data/train/6.채널정보/201810_train_.parquet', columns=cols_to_load6)
df65=pd.read_parquet(r'data/train/6.채널정보/201811_train_.parquet', columns=cols_to_load6)
df66=pd.read_parquet(r'data/train/6.채널정보/201812_train_.parquet', columns=cols_to_load6)

In [10]:
df_test11=pd.read_parquet(r'data/test/1.회원정보/201807_test_.parquet', columns=cols_to_load1)
df_test12=pd.read_parquet(r'data/test/1.회원정보/201808_test_.parquet', columns=cols_to_load1)
df_test13=pd.read_parquet(r'data/test/1.회원정보/201809_test_.parquet', columns=cols_to_load1)
df_test14=pd.read_parquet(r'data/test/1.회원정보/201810_test_.parquet', columns=cols_to_load1)
df_test15=pd.read_parquet(r'data/test/1.회원정보/201811_test_.parquet', columns=cols_to_load1)
df_test16=pd.read_parquet(r'data/test/1.회원정보/201812_test_.parquet', columns=cols_to_load1)

In [11]:
df_test21=pd.read_parquet(r'data/test/2.신용정보/201807_test_.parquet', columns=cols_to_load2)
df_test22=pd.read_parquet(r'data/test/2.신용정보/201808_test_.parquet', columns=cols_to_load2)
df_test23=pd.read_parquet(r'data/test/2.신용정보/201809_test_.parquet', columns=cols_to_load2)
df_test24=pd.read_parquet(r'data/test/2.신용정보/201810_test_.parquet', columns=cols_to_load2)
df_test25=pd.read_parquet(r'data/test/2.신용정보/201811_test_.parquet', columns=cols_to_load2)
df_test26=pd.read_parquet(r'data/test/2.신용정보/201812_test_.parquet', columns=cols_to_load2)

In [12]:
df_test31=pd.read_parquet(r'data/test/3.승인매출정보/201807_test_.parquet', columns=cols_to_load3)
df_test32=pd.read_parquet(r'data/test/3.승인매출정보/201808_test_.parquet', columns=cols_to_load3)
df_test33=pd.read_parquet(r'data/test/3.승인매출정보/201809_test_.parquet', columns=cols_to_load3)
df_test34=pd.read_parquet(r'data/test/3.승인매출정보/201810_test_.parquet', columns=cols_to_load3)
df_test35=pd.read_parquet(r'data/test/3.승인매출정보/201811_test_.parquet', columns=cols_to_load3)
df_test36=pd.read_parquet(r'data/test/3.승인매출정보/201812_test_.parquet', columns=cols_to_load3)

In [13]:
df_test41=pd.read_parquet(r'data/test/4.청구입금정보/201807_test_.parquet', columns=cols_to_load4)
df_test42=pd.read_parquet(r'data/test/4.청구입금정보/201808_test_.parquet', columns=cols_to_load4)
df_test43=pd.read_parquet(r'data/test/4.청구입금정보/201809_test_.parquet', columns=cols_to_load4)
df_test44=pd.read_parquet(r'data/test/4.청구입금정보/201810_test_.parquet', columns=cols_to_load4)
df_test45=pd.read_parquet(r'data/test/4.청구입금정보/201811_test_.parquet', columns=cols_to_load4)
df_test46=pd.read_parquet(r'data/test/4.청구입금정보/201812_test_.parquet', columns=cols_to_load4)

In [14]:
df_test51=pd.read_parquet(r'data/test/5.잔액정보/201807_test_.parquet', columns=cols_to_load5)
df_test52=pd.read_parquet(r'data/test/5.잔액정보/201808_test_.parquet', columns=cols_to_load5)
df_test53=pd.read_parquet(r'data/test/5.잔액정보/201809_test_.parquet', columns=cols_to_load5)
df_test54=pd.read_parquet(r'data/test/5.잔액정보/201810_test_.parquet', columns=cols_to_load5)
df_test55=pd.read_parquet(r'data/test/5.잔액정보/201811_test_.parquet', columns=cols_to_load5)
df_test56=pd.read_parquet(r'data/test/5.잔액정보/201812_test_.parquet', columns=cols_to_load5)

In [15]:
df_test61=pd.read_parquet(r'data/test/6.채널정보/201807_test_.parquet', columns=cols_to_load6)
df_test62=pd.read_parquet(r'data/test/6.채널정보/201808_test_.parquet', columns=cols_to_load6)
df_test63=pd.read_parquet(r'data/test/6.채널정보/201809_test_.parquet', columns=cols_to_load6)
df_test64=pd.read_parquet(r'data/test/6.채널정보/201810_test_.parquet', columns=cols_to_load6)
df_test65=pd.read_parquet(r'data/test/6.채널정보/201811_test_.parquet', columns=cols_to_load6)
df_test66=pd.read_parquet(r'data/test/6.채널정보/201812_test_.parquet', columns=cols_to_load6)

In [19]:
# 1. 회원정보
train1 = pd.concat([df11, df12, df13, df14, df15, df16], ignore_index=True)

# 2.신용정보
train2 = pd.concat([df21, df22, df23, df24, df25, df26], ignore_index=True)

# 3. 승인매출정보
train3 = pd.concat([df31, df32, df33, df34, df35, df36], ignore_index=True)

# 4. 청구입금정보
train4 = pd.concat([df41, df42, df43, df44, df45, df46], ignore_index=True)

# 5. 잔액정보
train5 = pd.concat([df51, df52, df53, df54, df55, df56], ignore_index=True)

# 6.채널정보
train6 = pd.concat([df61, df62, df63, df64, df65, df66], ignore_index=True)

In [20]:
# 1. 회원정보
test2_1 = pd.concat([df_test11, df_test12, df_test13, df_test14, df_test15, df_test16], ignore_index=True)

# 2.신용정보
test2_2 = pd.concat([df_test21, df_test22, df_test23, df_test24, df_test25, df_test26], ignore_index=True)

# 3. 승인매출정보
test2_3 = pd.concat([df_test31, df_test32, df_test33, df_test34, df_test35, df_test36], ignore_index=True)

# 4. 청구입금정보
test2_4 = pd.concat([df_test41, df_test42, df_test43, df_test44, df_test45, df_test46], ignore_index=True)

# 5. 잔액정보
test2_5 = pd.concat([df_test51, df_test52, df_test53, df_test54, df_test55, df_test56], ignore_index=True)

# 6.채널정보
test2_6 = pd.concat([df_test61, df_test62, df_test63, df_test64, df_test65, df_test66], ignore_index=True)

In [21]:
# 기준이 되는 데이터프레임부터 시작
VIF_merge_train = train1.copy()

# ID와 기준년월 기준으로 병합
VIF_merge_train = VIF_merge_train.merge(train2, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train3, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train4, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train5, on=['ID', '기준년월'], how='inner')
VIF_merge_train = VIF_merge_train.merge(train6, on=['ID', '기준년월'], how='inner')

In [22]:
# 기준이 되는 데이터프레임부터 시작
VIF_merge_test = test2_1.copy()

# ID와 기준년월 기준으로 순차 병합
VIF_merge_test = VIF_merge_test.merge(test2_2, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_3, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_4, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_5, on=['ID', '기준년월'], how='inner')
VIF_merge_test = VIF_merge_test.merge(test2_6, on=['ID', '기준년월'], how='inner')

In [23]:
VIF_merge_test=VIF_merge_test.drop(columns=['ID','기준년월'])
VIF_merge_train=VIF_merge_train.drop(columns=['ID', '기준년월'])

In [24]:
VIF_merge_train.to_csv('train_VIF5.csv', index=False, encoding='utf-8-sig')

In [25]:
VIF_merge_test.to_csv('test_VIF5.csv', index=False, encoding='utf-8-sig')