In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 데이터를 불러온다.

In [3]:
train_df = pd.read_parquet('Seleted(C_D)_delecteABE_all_train.parquet')
test_df = pd.read_parquet('Seleted(C_D)_delecteABE_all_test.parquet')

display(train_df)
display(test_df)

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,D,196,3681,196,1,자녀성장(2),12,12,...,46588,12226,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,201807,TRAIN_000002,C,23988,24493,23988,1,자녀출산기,9,9,...,85931,21866,1,1회 이상,1회 이상,30회 이상,10회 이상,10회 이상,1회 이상,1회 이상
2,201807,TRAIN_000003,D,3904,5933,3904,1,자녀성장(2),12,12,...,61518,16356,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
3,201807,TRAIN_000008,C,124967,68078,121279,5,자녀출산기,12,12,...,62715,20512,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TRAIN_000010,D,21001,18796,21001,1,자녀성장(1),12,12,...,30449,22512,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476827,201812,TRAIN_399979,D,31187,27337,31187,2,자녀성장(2),12,12,...,41812,11817,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476828,201812,TRAIN_399987,C,42492,35751,42492,1,자녀성장(2),12,12,...,68356,17859,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,30회 이상
476829,201812,TRAIN_399993,C,72348,27792,72348,4,자녀성장(1),12,12,...,34890,10810,1,20회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
476830,201812,TRAIN_399996,D,27636,26357,27636,1,자녀성장(2),12,12,...,37515,14402,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476831,201812,TRAIN_399997,C,23187,17171,23187,1,자녀출산기,12,12,...,22274,5731,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,21458,13852,21458,2,자녀성장(1),10,10,10,...,11441,4931,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,18681,11065,10759,2,자녀독립기,9,9,9,...,20522,10152,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,40758,27071,40758,2,자녀성장(1),12,12,12,...,50508,13223,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,5255,4827,5255,1,자녀성장(1),9,9,9,...,4604,2112,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,16148,8011,14290,3,자녀성장(1),12,12,12,...,6788,4406,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,0,노년생활,0,0,0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,3110,1231,3110,1,자녀출산기,10,9,9,...,1256,359,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599997,201812,TEST_99997,0,0,0,0,자녀성장(1),0,0,0,...,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,173263,63592,113786,6,가족구축기,12,12,12,...,48141,21273,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599999,201812,TEST_99999,3016,-574,3016,2,자녀출산기,12,12,12,...,56,18,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

### 범주형 컬럼 인코딩

In [ ]:
# train 데이터를 복사 (원본 보존)
train_df2 = train_df.copy()
test_df2 = test_df.copy()

In [ ]:
# train 데이터에서 Group 컬럼 제거 (VIF 분석용)
train_df2.drop(columns=['Segment'], inplace=True)

In [ ]:
# 인코딩할 범주형 컬럼 목록
categorical_columns = [
    '할인건수_R3M', '방문횟수_앱_R6M', '방문횟수_PC_R6M', '방문일수_PC_R6M',
    '이용메뉴건수_ARS_R6M', '인입횟수_ARS_R6M', '할인건수_B0M', 'Life_Stage'
]

# 각 범주형 컬럼 factorize
for col in categorical_columns:
    # train 기준으로 인코딩
    train_df2[col], uniques = train_df2[col].factorize()

    # test에도 동일한 매핑 적용
    mapping = {category: code for code, category in enumerate(uniques)}

    # test 데이터 매핑
    test_df2[col] = test_df2[col].map(mapping)

    # test에 없는 새로운 값 처리 (예: NaN이면 -1로)
    test_df2[col] = test_df2[col].fillna(-1).astype(int)

# 결과 확인
display(train_df2.head())
display(test_df2.head())

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,196,3681,196,1,0,12,12,12,...,46588,12226,1,0,0,0,0,0,0,0
1,201807,TRAIN_000002,23988,24493,23988,1,1,9,9,9,...,85931,21866,1,0,0,1,1,1,1,1
2,201807,TRAIN_000003,3904,5933,3904,1,0,12,12,7,...,61518,16356,1,0,0,0,0,0,0,0
3,201807,TRAIN_000008,124967,68078,121279,5,1,12,12,12,...,62715,20512,1,1,0,0,0,0,1,1
4,201807,TRAIN_000010,21001,18796,21001,1,2,12,12,12,...,30449,22512,1,0,0,0,0,0,1,1

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용개월수_신판_R12M,이용개월수_일시불_R12M,...,청구금액_R3M,청구금액_B0,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,21458,13852,21458,2,2,10,10,10,...,11441,4931,1,0,0,0,0,0,1,1
1,201807,TEST_00001,18681,11065,10759,2,4,9,9,9,...,20522,10152,1,0,0,0,0,0,1,1
2,201807,TEST_00002,40758,27071,40758,2,2,12,12,12,...,50508,13223,1,0,0,0,0,0,1,1
3,201807,TEST_00003,5255,4827,5255,1,2,9,9,9,...,4604,2112,1,0,0,0,0,0,1,1
4,201807,TEST_00004,16148,8011,14290,3,2,12,12,12,...,6788,4406,1,0,0,0,0,0,1,1

# Train_VIF

In [ ]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# '기준년월'과 'ID' 컬럼 제외한 나머지 컬럼을 선택
vif_X = train_df2.drop(['기준년월', 'ID'], axis=1)

# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# 결과 출력
vif

                    변수           VIF
0                const    121.592928
1        이용금액_R3M_신용체크      7.256359
2           _1순위카드이용금액     26.910526
3          이용금액_R3M_신용     18.524571
4           이용카드수_신용체크      3.193119
5           Life_Stage      1.015693
6        이용개월수_신용_R12M     26.087722
7        이용개월수_신판_R12M     63.751342
8       이용개월수_일시불_R12M     52.151167
9         이용금액_일시불_R6M     74.444149
10        이용금액_일시불_B0M     78.389810
11        이용금액_일시불_R3M    104.777085
12       이용금액_일시불_R12M     13.490132
13        이용개월수_신용_R6M     15.484332
14         이용건수_신용_R6M  61638.942750
15         이용건수_신용_B0M  19679.510047
16         이용건수_신판_R6M  79792.792108
17         이용건수_신용_R3M  45045.063203
18         이용건수_신판_B0M  33564.670195
19        이용건수_일시불_R6M  18313.840621
20         이용건수_신판_R3M  71654.540729
21        이용건수_일시불_B0M  14197.352756
22        이용개월수_신판_R6M     71.266297
23        이용건수_일시불_R3M  27741.351011
24       이용개월수_일시불_R6M     55.215666
25           이용후경과월_신판     11.620488
26        이용건수_신용_R12M  35516.134403
27        이용건수_신판_R12M  42288.868001
28       이용건수_일시불_R12M   6978.048112
29              이용가맹점수     27.193310
30           이용후경과월_신용      9.774340
31       이용금액_오프라인_B0M      6.708925
32       이용금액_오프라인_R3M      6.336536
33       이용건수_오프라인_B0M     36.446008
34         _3순위업종_이용금액      4.591614
35       _3순위쇼핑업종_이용금액      6.983928
36         _2순위업종_이용금액      4.473424
37      이용개월수_오프라인_R6M      7.759871
38       이용금액_오프라인_R6M      6.224551
39       _2순위쇼핑업종_이용금액      7.119707
40          정상청구원금_B5M     16.651039
41          정상청구원금_B2M     24.683479
42  연속유실적개월수_기본_24M_카드      2.819745
43          정상청구원금_B0M     28.530723
44          정상입금원금_B0M     14.088042
45          정상입금원금_B5M     10.972399
46          정상입금원금_B2M     12.990802
47        이용개월수_전체_R6M     14.520244
48        이용개월수_전체_R3M     15.263460
49            청구금액_R6M      8.154076
50            청구금액_R3M     16.714852
51             청구금액_B0     11.380467
52          청구서발송여부_B0      4.137988
53            할인건수_R3M      2.034136
54            할인건수_B0M      1.321251
55          방문횟수_앱_R6M      1.312043
56         방문횟수_PC_R6M     10.033655
57         방문일수_PC_R6M     10.003538
58        인입횟수_ARS_R6M      1.479163
59      이용메뉴건수_ARS_R6M      1.282606

In [ ]:
# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수           VIF
16         이용건수_신판_R6M  79792.792108
20         이용건수_신판_R3M  71654.540729
14         이용건수_신용_R6M  61638.942750
17         이용건수_신용_R3M  45045.063203
27        이용건수_신판_R12M  42288.868001
26        이용건수_신용_R12M  35516.134403
18         이용건수_신판_B0M  33564.670195
23        이용건수_일시불_R3M  27741.351011
15         이용건수_신용_B0M  19679.510047
19        이용건수_일시불_R6M  18313.840621
21        이용건수_일시불_B0M  14197.352756
28       이용건수_일시불_R12M   6978.048112
0                const    121.592928
11        이용금액_일시불_R3M    104.777085
10        이용금액_일시불_B0M     78.389810
9         이용금액_일시불_R6M     74.444149
22        이용개월수_신판_R6M     71.266297
7        이용개월수_신판_R12M     63.751342
24       이용개월수_일시불_R6M     55.215666
8       이용개월수_일시불_R12M     52.151167
33       이용건수_오프라인_B0M     36.446008
43          정상청구원금_B0M     28.530723
29              이용가맹점수     27.193310
2           _1순위카드이용금액     26.910526
6        이용개월수_신용_R12M     26.087722
41          정상청구원금_B2M     24.683479
3          이용금액_R3M_신용     18.524571
50            청구금액_R3M     16.714852
40          정상청구원금_B5M     16.651039
13        이용개월수_신용_R6M     15.484332
48        이용개월수_전체_R3M     15.263460
47        이용개월수_전체_R6M     14.520244
44          정상입금원금_B0M     14.088042
12       이용금액_일시불_R12M     13.490132
46          정상입금원금_B2M     12.990802
25           이용후경과월_신판     11.620488
51             청구금액_B0     11.380467
45          정상입금원금_B5M     10.972399
56         방문횟수_PC_R6M     10.033655
57         방문일수_PC_R6M     10.003538
30           이용후경과월_신용      9.774340
49            청구금액_R6M      8.154076
37      이용개월수_오프라인_R6M      7.759871
1        이용금액_R3M_신용체크      7.256359
39       _2순위쇼핑업종_이용금액      7.119707
35       _3순위쇼핑업종_이용금액      6.983928
31       이용금액_오프라인_B0M      6.708925
32       이용금액_오프라인_R3M      6.336536
38       이용금액_오프라인_R6M      6.224551
34         _3순위업종_이용금액      4.591614
36         _2순위업종_이용금액      4.473424
52          청구서발송여부_B0      4.137988
4           이용카드수_신용체크      3.193119
42  연속유실적개월수_기본_24M_카드      2.819745
53            할인건수_R3M      2.034136
58        인입횟수_ARS_R6M      1.479163
54            할인건수_B0M      1.321251
55          방문횟수_앱_R6M      1.312043
59      이용메뉴건수_ARS_R6M      1.282606
5           Life_Stage      1.015693

In [ ]:
# train 데이터를 복사 (원본 보존)
train_df3 = train_df2.copy()

In [ ]:
# '기준년월'과 'ID' 컬럼을 제외한 나머지 컬럼을 선택
vif_X = train_df3.drop(['기준년월', 'ID',
                        '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M',
                        '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M',
                        '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R12M',
                        '이용개월수_신용_R6M', '이용개월수_일시불_R6M', '이용개월수_전체_R3M',
                        '정상청구원금_B2M', '정상청구원금_B0M'

                       ], axis=1)


# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수         VIF
0                const  117.564792
7        이용개월수_신판_R12M   62.042787
8       이용개월수_일시불_R12M   45.399618
6        이용개월수_신용_R12M   24.729500
2           _1순위카드이용금액   19.318406
3          이용금액_R3M_신용   17.411877
30            청구금액_R3M   16.257921
13              이용가맹점수   14.673956
10        이용개월수_신판_R6M   14.054833
9         이용금액_일시불_R6M   12.249097
31             청구금액_B0   10.976783
36         방문횟수_PC_R6M   10.023995
37         방문일수_PC_R6M    9.985343
11           이용후경과월_신판    9.815870
25          정상입금원금_B0M    8.651132
14           이용후경과월_신용    7.971745
12        이용건수_신용_R12M    7.901711
29            청구금액_R6M    7.741126
23          정상청구원금_B5M    7.554819
20      이용개월수_오프라인_R6M    7.507328
26          정상입금원금_B5M    7.199898
1        이용금액_R3M_신용체크    7.041503
22       _2순위쇼핑업종_이용금액    6.828675
18       _3순위쇼핑업종_이용금액    6.806402
27          정상입금원금_B2M    6.563780
15       이용금액_오프라인_B0M    6.363133
16       이용금액_오프라인_R3M    5.889756
28        이용개월수_전체_R6M    5.550984
21       이용금액_오프라인_R6M    5.470361
17         _3순위업종_이용금액    4.439285
19         _2순위업종_이용금액    4.239334
32          청구서발송여부_B0    3.471529
4           이용카드수_신용체크    3.041364
24  연속유실적개월수_기본_24M_카드    2.712041
33            할인건수_R3M    2.013193
38        인입횟수_ARS_R6M    1.455343
34            할인건수_B0M    1.314034
39      이용메뉴건수_ARS_R6M    1.266103
35          방문횟수_앱_R6M    1.225117
5           Life_Stage    1.013790

In [ ]:
# train 데이터를 복사 (원본 보존)
train_df4 = train_df3.copy()

In [ ]:
# '기준년월'과 'ID' 컬럼을 제외한 나머지 컬럼을 선택
vif_X = train_df4.drop(['기준년월', 'ID',
                        '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M',
                        '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M',
                        '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R12M','이용금액_R3M_신용',
                        '이용개월수_신용_R6M', '이용개월수_일시불_R6M', '이용개월수_전체_R3M','이용개월수_신판_R6M',
                        '이용개월수_신판_R12M', '이용개월수_일시불_R12M',
                        '정상청구원금_B2M', '정상청구원금_B0M',
                        '청구금액_R3M', '청구금액_B0', '이용가맹점수', '방문일수_PC_R6M'

                       ], axis=1)



# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수         VIF
0                const  113.624891
2           _1순위카드이용금액   16.351509
6         이용금액_일시불_R6M   10.927452
7            이용후경과월_신판    8.690157
18          정상청구원금_B5M    7.006476
9            이용후경과월_신용    6.963808
17       _2순위쇼핑업종_이용금액    6.803407
13       _3순위쇼핑업종_이용금액    6.341549
21          정상입금원금_B5M    6.259119
5        이용개월수_신용_R12M    6.245612
1        이용금액_R3M_신용체크    6.079433
10       이용금액_오프라인_B0M    6.047886
20          정상입금원금_B0M    5.983304
11       이용금액_오프라인_R3M    5.844718
23        이용개월수_전체_R6M    5.339584
16       이용금액_오프라인_R6M    5.333175
22          정상입금원금_B2M    5.290960
15      이용개월수_오프라인_R6M    4.981553
12         _3순위업종_이용금액    4.349615
14         _2순위업종_이용금액    4.198154
24            청구금액_R6M    3.565982
25          청구서발송여부_B0    3.370477
8         이용건수_신용_R12M    3.136988
3           이용카드수_신용체크    2.639950
19  연속유실적개월수_기본_24M_카드    2.627204
26            할인건수_R3M    1.768244
30        인입횟수_ARS_R6M    1.446308
27            할인건수_B0M    1.311450
31      이용메뉴건수_ARS_R6M    1.264890
28          방문횟수_앱_R6M    1.209162
29         방문횟수_PC_R6M    1.067025
4           Life_Stage    1.013672

# 컬럼 제거

In [4]:
# 제거할 컬럼 리스트
drop_cols = [
                        '이용건수_신판_R12M', '이용건수_일시불_R12M', '이용건수_오프라인_B0M', '이용건수_신용_R6M', '이용건수_신용_B0M',
                        '이용건수_신판_R6M', '이용건수_신용_R3M', '이용건수_신판_B0M', '이용건수_일시불_R6M', '이용건수_신판_R3M', '이용건수_일시불_B0M', '이용건수_일시불_R3M',
                        '이용금액_일시불_B0M', '이용금액_일시불_R3M', '이용금액_일시불_R12M','이용금액_R3M_신용',
                        '이용개월수_신용_R6M', '이용개월수_일시불_R6M', '이용개월수_전체_R3M','이용개월수_신판_R6M',
                        '이용개월수_신판_R12M', '이용개월수_일시불_R12M',
                        '정상청구원금_B2M', '정상청구원금_B0M',
                        '청구금액_R3M', '청구금액_B0', '이용가맹점수', '방문일수_PC_R6M'
]

# train_df 컬럼 제거
train_df.drop(columns=drop_cols, axis=1, inplace=True)

# test_df 컬럼 제거
test_df.drop(columns=drop_cols, axis=1, inplace=True)

# 확인
display(train_df)
display(test_df)

,기준년월,ID,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,D,196,3681,1,자녀성장(2),12,8380,0,...,16125,6,88693,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,201807,TRAIN_000002,C,23988,24493,1,자녀출산기,9,35136,0,...,14448,5,165221,1,1회 이상,1회 이상,30회 이상,10회 이상,1회 이상,1회 이상
2,201807,TRAIN_000003,D,3904,5933,1,자녀성장(2),12,-7031,0,...,13043,6,127371,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
3,201807,TRAIN_000008,C,124967,68078,5,자녀출산기,12,131028,0,...,11685,6,94241,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TRAIN_000010,D,21001,18796,1,자녀성장(1),12,19802,0,...,0,6,35723,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
476827,201812,TRAIN_399979,D,31187,27337,2,자녀성장(2),12,42049,0,...,13157,6,74153,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476828,201812,TRAIN_399987,C,42492,35751,1,자녀성장(2),12,53815,0,...,17814,6,132623,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,30회 이상
476829,201812,TRAIN_399993,C,72348,27792,4,자녀성장(1),12,94922,0,...,11092,6,72474,1,20회 이상,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상
476830,201812,TRAIN_399996,D,27636,26357,1,자녀성장(2),12,58916,0,...,10764,6,99849,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
476831,201812,TRAIN_399997,C,23187,17171,1,자녀출산기,12,26974,1,...,6106,6,41073,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,이용건수_신용_R12M,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TEST_00000,21458,13852,2,자녀성장(1),10,26595,0,150,...,1172,5,22151,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
1,201807,TEST_00001,18681,11065,2,자녀독립기,9,-7578,0,28,...,4509,6,32878,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TEST_00002,40758,27071,2,자녀성장(1),12,48483,1,650,...,11366,6,71867,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
3,201807,TEST_00003,5255,4827,1,자녀성장(1),9,403,0,361,...,875,4,4986,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,201807,TEST_00004,16148,8011,3,자녀성장(1),12,1238,0,227,...,1618,6,10758,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,0,0,0,노년생활,0,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599996,201812,TEST_99996,3110,1231,1,자녀출산기,10,3,0,7,...,252,6,2237,1,1회 이상,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상
599997,201812,TEST_99997,0,0,0,자녀성장(1),0,0,12,0,...,0,0,0,0,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
599998,201812,TEST_99998,173263,63592,6,가족구축기,12,133431,0,933,...,2751,6,108420,1,1회 이상,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상
599999,201812,TEST_99999,3016,-574,2,자녀출산기,12,-4731,2,40,...,18,6,105,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

# 전처리 완료 데이터 저장

In [19]:
train_df.to_csv('/content/drive/MyDrive/파이널 프로젝트/C_D/(C_D)_VIF_train.csv', index=False)
test_df.to_csv('/content/drive/MyDrive/파이널 프로젝트/C_D/(C_D)_VIF_test.csv', index=False)

In [22]:
train_df2 = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/C_D/(C_D)_VIF_train.csv')
test_df2 = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/C_D/(C_D)_VIF_test.csv')
train_df2.head()

,Segment,이용금액_R3M_신용체크,_1순위카드이용금액,이용카드수_신용체크,Life_Stage,이용개월수_신용_R12M,이용금액_일시불_R6M,이용후경과월_신판,이용건수_신용_R12M,이용후경과월_신용,...,정상입금원금_B2M,이용개월수_전체_R6M,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,할인건수_B0M,방문횟수_앱_R6M,방문횟수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,D,196,3681,1,자녀성장(2),12,8380,0,165,0,...,16125,6,88693,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,C,23988,24493,1,자녀출산기,9,35136,0,148,0,...,14448,5,165221,1,1회 이상,1회 이상,30회 이상,10회 이상,1회 이상,1회 이상
2,D,3904,5933,1,자녀성장(2),12,-7031,0,105,0,...,13043,6,127371,1,1회 이상,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
3,C,124967,68078,5,자녀출산기,12,131028,0,863,0,...,11685,6,94241,1,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
4,D,21001,18796,1,자녀성장(1),12,19802,0,34,0,...,0,6,35723,1,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

In [5]:
train_df.to_csv('(C_D)_VIF_train(2).csv', index=False)
test_df.to_csv('(C_D)_VIF_test(2).csv', index=False)