In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings 
warnings.filterwarnings('ignore')

sns.set() 

plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['figure.figsize'] = 12, 6 
plt.rcParams['font.size'] = 14 
plt.rcParams['axes.unicode_minus'] = False 

# 결측치 시각화를 위한 라이브러리
import missingno 

# 데이터 전처리 알고리즘 
from sklearn.preprocessing import LabelEncoder 
from sklearn.preprocessing import StandardScaler 

# 학습용과 검증용으로 나누는  함수 
from sklearn.model_selection import train_test_split 

# 교차검증 
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한도구 
from sklearn.model_selection import GridSearchCV 

# 머신러닝 알고리즘 - 분류 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression 
from sklearn.svm import SVC 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier 
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.ensemble import GradientBoostingClassifier 
from lightgbm import LGBMClassifier 
from xgboost import XGBClassifier 
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀 
from sklearn.neighbors import KNeighborsRegressor 
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import Ridge 
from sklearn.linear_model import Lasso 
from sklearn.linear_model import ElasticNet 
from sklearn.svm import SVR 
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor 
from sklearn.ensemble import GradientBoostingRegressor 
from lightgbm import LGBMRegressor 
from xgboost import XGBRegressor 
from sklearn.ensemble import VotingRegressor 

# 학습 모델 저장을 위한 라이브러리
import pickle

In [15]:
train_df = pd.read_parquet(r"C:\Users\SAMSUNG\OneDrive\바탕 화면\Feature Importance\파생변수포함_Top20_전체_train.parquet")
test_df = pd.read_parquet(r"C:\Users\SAMSUNG\OneDrive\바탕 화면\Feature Importance\파생변수포함_Top20_전체.parquet")
target_df = pd.read_csv(r"C:\Users\SAMSUNG\OneDrive\바탕 화면\PCA안한데이터\Segment\Segment.csv")


display(train_df.columns)
display(test_df.columns)

Index(['정상청구원금_B5M', '이용금액_오프라인_B0M', '연속유실적개월수_기본_24M_카드', '이용금액_R3M_신용체크',
       '이용금액대', '이용금액_R3M_신용', '보유여부_해외겸용_본인', '연체입금원금_B5M', '이용카드수_신용체크',
       '이용건수_신용_R12M', '소비집중도_신용', '정상청구원금_B0M', '상향가능한도금액', '최대이용금액_일시불_R12M',
       '이용금액_일시불_R12M', '이용건수_일시불_R6M', '소지카드수_유효_신용', '상향가능CA한도금액',
       '정상청구원금_B2M', '가맹점_카드당비율'],
      dtype='object')

Index(['정상청구원금_B5M', '이용금액_오프라인_B0M', '연속유실적개월수_기본_24M_카드', '이용금액_R3M_신용체크',
       '이용금액대', '이용금액_R3M_신용', '보유여부_해외겸용_본인', '연체입금원금_B5M', '이용카드수_신용체크',
       '이용건수_신용_R12M', '소비집중도_신용', '정상청구원금_B0M', '상향가능한도금액', '최대이용금액_일시불_R12M',
       '이용금액_일시불_R12M', '이용건수_일시불_R6M', '소지카드수_유효_신용', '상향가능CA한도금액',
       '정상청구원금_B2M', '가맹점_카드당비율'],
      dtype='object')

In [16]:
target_df

           기준년월            ID Segment
0        201807  TRAIN_000000       D
1        201807  TRAIN_000001       E
2        201807  TRAIN_000002       C
3        201807  TRAIN_000003       D
4        201807  TRAIN_000004       E
...         ...           ...     ...
2399995  201812  TRAIN_399995       E
2399996  201812  TRAIN_399996       D
2399997  201812  TRAIN_399997       C
2399998  201812  TRAIN_399998       E
2399999  201812  TRAIN_399999       E

[2400000 rows x 3 columns]

In [17]:
# Scaler 학습
scalerX = StandardScaler()
scalerX.fit(train_df)

StandardScaler()

In [18]:
encoder1 = LabelEncoder()
Seg = encoder1.fit_transform(target_df['Segment'])

In [19]:
Seg

array([3, 4, 2, ..., 2, 4, 4])

In [20]:

# 입력과 결과로 나눈다.
X = train_df
y = Seg

In [21]:
train_X = X
train_y = y

기본모델

In [22]:
print(pd.Series(train_y).unique())

[3 4 2 0 1]

In [23]:
print(pd.Series(train_y).value_counts())

4    1922052
3     349242
2     127590
0        972
1        144
Name: count, dtype: int64

In [24]:

model = XGBClassifier(tree_method='hist', predictor='cpu_predictor',
                       n_jobs=-1, verbosity=0, use_label_encoder=False)

# 교차 검증
kfold = KFold(n_splits=10, shuffle=True, random_state=1)

r2 = cross_val_score(model, train_X, train_y, scoring='f1_micro', cv=kfold)
print(f'평균 f1 Score : {r2.mean()}')

평균 f1 Score : 0.8896820833333331

예측수행

In [59]:
# 예측할 데이터를 읽어온다.
df1 = pd.read_parquet(r"C:\Users\SAMSUNG\OneDrive\바탕 화면\Feature Importance\파생변수포함_Top20_전체_test.parquet")
df1

,정상청구원금_B5M,이용금액_오프라인_B0M,연속유실적개월수_기본_24M_카드,이용금액_R3M_신용체크,이용금액대,이용금액_R3M_신용,보유여부_해외겸용_본인,연체입금원금_B5M,이용카드수_신용체크,이용건수_신용_R12M,소비집중도_신용,정상청구원금_B0M,상향가능한도금액,최대이용금액_일시불_R12M,이용금액_일시불_R12M,이용건수_일시불_R6M,소지카드수_유효_신용,상향가능CA한도금액,정상청구원금_B2M,가맹점_카드당비율
0,3919,9877,5,21458,2,21458,1,2414,2,150,0.417891,6495,7,21700,49063,72,1,2,2012,21.499893
1,5723,4006,8,18681,2,10759,1,2959,2,28,-0.235748,9644,0,2423,7771,10,1,0,5273,9.999950
2,11267,11298,24,40758,3,40758,0,0,2,650,0.345534,11519,0,12667,73003,354,1,0,11366,39.499803
3,0,976,5,5255,4,5255,1,0,1,361,0.359790,1375,3,1661,7421,221,2,1,1072,22.999770
4,1347,4017,20,16148,5,14290,1,0,3,227,0.284189,3951,2,1082,10493,112,1,0,1618,9.333302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,0,0,0,0,0,0,0,0,0.000000,0,0,0,0,-4,1,0,0,0.000000
599996,992,407,8,3110,1,3110,0,689,1,7,-0.250095,205,8,1067,2631,12,1,2,3736,2.999970
599997,0,0,0,0,0,0,0,0,0,0,0.000000,0,5,0,0,2,2,1,186,200000.000000
599998,27335,15388,24,173263,3,113786,1,12448,6,933,0.157490,26308,9,64459,423882,465,1,2,23261,16.999972
599999,25,8,24,3016,1,3016,1,8,2,40,2.856497,20,10,21,-885,9,1,3,18,0.000000

In [60]:
model.fit(train_X, train_y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=-1, num_parallel_tree=None, ...)

In [61]:
# 예측한다
y_pred1 = model.predict(df1)

In [69]:
# 결과 데이터를 복원한다.
result_data1 = encoder1.inverse_transform(y_pred1)

In [ ]:
"C:\Users\SAMSUNG\OneDrive\바탕 화면\Feature Importance\파생변수_신용카드데이터_기준년월ID포함_test.parquet"

In [70]:
# 예측 결과데이터를 만들기 위해 ID와 기준년월이 있는 테스트파일을 불러온다.
submission_df = pd.read_parquet(r"C:\Users\SAMSUNG\OneDrive\바탕 화면\Feature Importance\파생변수_신용카드데이터_기준년월ID포함_test.parquet")
submission_df1 = submission_df.copy()

In [71]:
submission_df1

,정상청구원금_B5M,이용금액_오프라인_B0M,연속유실적개월수_기본_24M_카드,이용금액_R3M_신용체크,이용금액대,이용금액_R3M_신용,보유여부_해외겸용_본인,연체입금원금_B5M,이용카드수_신용체크,이용건수_신용_R12M,...,상향가능한도금액,최대이용금액_일시불_R12M,이용금액_일시불_R12M,이용건수_일시불_R6M,소지카드수_유효_신용,상향가능CA한도금액,정상청구원금_B2M,가맹점_카드당비율,ID,기준년월
0,3919,9877,5,21458,2,21458,1,2414,2,150,...,7,21700,49063,72,1,2,2012,21.499893,TEST_00000,201807
1,5723,4006,8,18681,2,10759,1,2959,2,28,...,0,2423,7771,10,1,0,5273,9.999950,TEST_00001,201807
2,11267,11298,24,40758,3,40758,0,0,2,650,...,0,12667,73003,354,1,0,11366,39.499803,TEST_00002,201807
3,0,976,5,5255,4,5255,1,0,1,361,...,3,1661,7421,221,2,1,1072,22.999770,TEST_00003,201807
4,1347,4017,20,16148,5,14290,1,0,3,227,...,2,1082,10493,112,1,0,1618,9.333302,TEST_00004,201807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,-4,1,0,0,0.000000,TEST_99995,201812
599996,992,407,8,3110,1,3110,0,689,1,7,...,8,1067,2631,12,1,2,3736,2.999970,TEST_99996,201812
599997,0,0,0,0,0,0,0,0,0,0,...,5,0,0,2,2,1,186,200000.000000,TEST_99997,201812
599998,27335,15388,24,173263,3,113786,1,12448,6,933,...,9,64459,423882,465,1,2,23261,16.999972,TEST_99998,201812
599999,25,8,24,3016,1,3016,1,8,2,40,...,10,21,-885,9,1,3,18,0.000000,TEST_99999,201812

In [72]:
# 원하는 컬럼만 불러온다
submission_df1 = submission_df1[['ID','기준년월']]

In [73]:
# 예측 결과를 저장한다.
submission_df1['Segment'] = result_data1

In [74]:

submission_df1['Segment'].value_counts()

Segment
E    496403
D     78326
C     25251
A        18
B         2
Name: count, dtype: int64

In [75]:
submission_df1

                ID    기준년월 Segment
0       TEST_00000  201807       E
1       TEST_00001  201807       E
2       TEST_00002  201807       D
3       TEST_00003  201807       E
4       TEST_00004  201807       E
...            ...     ...     ...
599995  TEST_99995  201812       E
599996  TEST_99996  201812       E
599997  TEST_99997  201812       E
599998  TEST_99998  201812       C
599999  TEST_99999  201812       E

[600000 rows x 3 columns]

In [76]:
# 일단 csv파일로 저장해둔다.
submission_df1.to_csv("C:/Users/SAMSUNG/OneDrive/바탕 화면/학습완료/파생변수포함3_전체_Top_20", index=False)

In [77]:
submission_df1

                ID    기준년월 Segment
0       TEST_00000  201807       E
1       TEST_00001  201807       E
2       TEST_00002  201807       D
3       TEST_00003  201807       E
4       TEST_00004  201807       E
...            ...     ...     ...
599995  TEST_99995  201812       E
599996  TEST_99996  201812       E
599997  TEST_99997  201812       E
599998  TEST_99998  201812       C
599999  TEST_99999  201812       E

[600000 rows x 3 columns]

In [78]:
# 예측 결과데이터의 예시를 보면 10만개의 데이터행으로 이루어져있으므로
# 12월 데이터만 만들어준다.
submission_df1_12 = submission_df1[submission_df1['기준년월'] == 201812].reset_index(drop=True)
submission_df1_12

               ID    기준년월 Segment
0      TEST_00000  201812       E
1      TEST_00001  201812       E
2      TEST_00002  201812       E
3      TEST_00003  201812       E
4      TEST_00004  201812       E
...           ...     ...     ...
99995  TEST_99995  201812       E
99996  TEST_99996  201812       E
99997  TEST_99997  201812       E
99998  TEST_99998  201812       C
99999  TEST_99999  201812       E

[100000 rows x 3 columns]

In [79]:
submission_df1_12['Segment'].value_counts()

Segment
E    82643
D    13008
C     4347
A        2
Name: count, dtype: int64

In [80]:

submission_df1_12.drop(['기준년월'], axis=1, inplace=True)
# 제대로 나누어졌는지 확인해본다.
submission_df1_12

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       E
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [54]:
submission_df1_12

               ID Segment
0      TEST_00000       E
1      TEST_00001       E
2      TEST_00002       E
3      TEST_00003       E
4      TEST_00004       E
...           ...     ...
99995  TEST_99995       E
99996  TEST_99996       E
99997  TEST_99997       E
99998  TEST_99998       C
99999  TEST_99999       E

[100000 rows x 2 columns]

In [82]:
# 12월 데이터만 제출하기로 정해졌으므로 12월 데이터만 내보낸다.
submission_df1_12.to_csv("C:/Users/SAMSUNG/OneDrive/바탕 화면/Kaggle용 12월 데이터/model9.csv", index=False, encoding="utf-8-sig")