In [17]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 평가함수
# 분류용
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

# 회귀용
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

# 모델의 최적의 하이퍼 파라미터를 찾기 위한 도구
from sklearn.model_selection import GridSearchCV

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from sklearn.ensemble import VotingClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from sklearn.ensemble import VotingRegressor

# 차원 축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift
from sklearn.cluster import estimate_bandwidth

# 학습 모델 저장을 위한 라이브러리
import pickle

### train

In [3]:
df11=pd.read_parquet(r'data/train/1.회원정보/201807_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])
df12=pd.read_parquet(r'data/train/1.회원정보/201808_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])
df13=pd.read_parquet(r'data/train/1.회원정보/201809_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])
df14=pd.read_parquet(r'data/train/1.회원정보/201810_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])
df15=pd.read_parquet(r'data/train/1.회원정보/201811_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])
df16=pd.read_parquet(r'data/train/1.회원정보/201812_train_.parquet',columns=['ID','기준년월','_1순위카드이용금액','Segment'])

In [4]:
all_df1 = pd.concat([df11, df12, df13, df14, df15, df16])
all_df1.reset_index(inplace=True, drop=True)
all_df1

                   ID    기준년월  _1순위카드이용금액 Segment
0        TRAIN_000000  201807        3681       D
1        TRAIN_000001  201807       13323       E
2        TRAIN_000002  201807       24493       C
3        TRAIN_000003  201807        5933       D
4        TRAIN_000004  201807           0       E
...               ...     ...         ...     ...
2399995  TRAIN_399995  201812        5640       E
2399996  TRAIN_399996  201812       26357       D
2399997  TRAIN_399997  201812       17171       C
2399998  TRAIN_399998  201812           0       E
2399999  TRAIN_399999  201812        6984       E

[2400000 rows x 4 columns]

In [5]:
all_df1 = all_df1[all_df1['Segment'] != 'E']

all_df1['Segment'] = all_df1['Segment'].apply(
    lambda x: x if x in ['C', 'D'] else 'not CD'
)

In [6]:
all_df1

                   ID    기준년월  _1순위카드이용금액 Segment
0        TRAIN_000000  201807        3681       D
2        TRAIN_000002  201807       24493       C
3        TRAIN_000003  201807        5933       D
8        TRAIN_000008  201807       68078       C
10       TRAIN_000010  201807       18796       D
...               ...     ...         ...     ...
2399979  TRAIN_399979  201812       27337       D
2399987  TRAIN_399987  201812       35751       C
2399993  TRAIN_399993  201812       27792       C
2399996  TRAIN_399996  201812       26357       D
2399997  TRAIN_399997  201812       17171       C

[477948 rows x 4 columns]

In [7]:
df31=pd.read_parquet(r'data/train/3.승인매출정보/201807_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])
df32=pd.read_parquet(r'data/train/3.승인매출정보/201808_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])
df33=pd.read_parquet(r'data/train/3.승인매출정보/201809_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])
df34=pd.read_parquet(r'data/train/3.승인매출정보/201810_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])
df35=pd.read_parquet(r'data/train/3.승인매출정보/201811_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])
df36=pd.read_parquet(r'data/train/3.승인매출정보/201812_train_.parquet',columns=['ID','기준년월','이용금액_일시불_R12M','이용금액대'])

In [8]:
all_df3 = pd.concat([df31, df32, df33, df34, df35, df36])
all_df3.reset_index(inplace=True, drop=True)
all_df3

                   ID    기준년월  이용금액_일시불_R12M      이용금액대
0        TRAIN_000000  201807          20667  01.100만원+
1        TRAIN_000001  201807          54341   03.30만원+
2        TRAIN_000002  201807          55656  01.100만원+
3        TRAIN_000003  201807          10753  01.100만원+
4        TRAIN_000004  201807          -2129     09.미사용
...               ...     ...            ...        ...
2399995  TRAIN_399995  201812              0     09.미사용
2399996  TRAIN_399996  201812         148106  01.100만원+
2399997  TRAIN_399997  201812          52233   02.50만원+
2399998  TRAIN_399998  201812              0     09.미사용
2399999  TRAIN_399999  201812          12962   04.10만원+

[2400000 rows x 4 columns]

In [9]:
df41=pd.read_parquet(r'data/train/4.청구입금정보/201807_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])
df42=pd.read_parquet(r'data/train/4.청구입금정보/201808_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])
df43=pd.read_parquet(r'data/train/4.청구입금정보/201809_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])
df44=pd.read_parquet(r'data/train/4.청구입금정보/201810_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])
df45=pd.read_parquet(r'data/train/4.청구입금정보/201811_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])
df46=pd.read_parquet(r'data/train/4.청구입금정보/201812_train_.parquet',columns=['ID','기준년월','청구금액_R6M','청구금액_R3M','청구금액_B0'])

In [10]:
all_df4 = pd.concat([df41, df42, df43, df44, df45, df46])
all_df4.reset_index(inplace=True, drop=True)
all_df4

                   ID    기준년월  청구금액_R6M  청구금액_R3M  청구금액_B0
0        TRAIN_000000  201807     88693     46588    12226
1        TRAIN_000001  201807     16861     10530     5834
2        TRAIN_000002  201807    165221     85931    21866
3        TRAIN_000003  201807    127371     61518    16356
4        TRAIN_000004  201807       155         0        0
...               ...     ...       ...       ...      ...
2399995  TRAIN_399995  201812         0         0        0
2399996  TRAIN_399996  201812     99849     37515    14402
2399997  TRAIN_399997  201812     41073     22274     5731
2399998  TRAIN_399998  201812         0         0        0
2399999  TRAIN_399999  201812     19948      9704     3422

[2400000 rows x 5 columns]

In [11]:
merged_df = all_df1.merge(all_df3, on=['ID', '기준년월'], how='inner')
merged_df = merged_df.merge(all_df4, on=['ID', '기준년월'], how='inner')

In [15]:
merged_df

,ID,기준년월,_1순위카드이용금액,이용금액_일시불_R12M,이용금액대,청구금액_R6M,청구금액_R3M,청구금액_B0
0,TRAIN_000000,201807,3681,20667,01.100만원+,88693,46588,12226
1,TRAIN_000002,201807,24493,55656,01.100만원+,165221,85931,21866
2,TRAIN_000003,201807,5933,10753,01.100만원+,127371,61518,16356
3,TRAIN_000008,201807,68078,360859,01.100만원+,94241,62715,20512
4,TRAIN_000010,201807,18796,34884,01.100만원+,35723,30449,22512
...,...,...,...,...,...,...,...,...
477943,TRAIN_399979,201812,27337,85901,01.100만원+,74153,41812,11817
477944,TRAIN_399987,201812,35751,90222,01.100만원+,132623,68356,17859
477945,TRAIN_399993,201812,27792,169672,01.100만원+,72474,34890,10810
477946,TRAIN_399996,201812,26357,148106,01.100만원+,99849,37515,14402
477947,TRAIN_399997,201812,17171,52233,02.50만원+,41073,22274,5731

In [14]:
merged_df=merged_df.drop(columns=['Segment'])

In [16]:
merged_df.to_csv('train_C,D,notCD (변수선택).csv', index=False, encoding='utf-8-sig')

### test

In [18]:
merged_test_df=pd.read_parquet(r'data/ab_cde_test.parquet',columns=['ID','기준년월','청구금액_R6M', '청구금액_R3M', '청구금액_B0',
                                                             '이용금액_일시불_R12M','_1순위카드이용금액','이용금액대'])

In [19]:
merged_test_df

,ID,기준년월,청구금액_R6M,청구금액_R3M,청구금액_B0,이용금액_일시불_R12M,_1순위카드이용금액,이용금액대
0,TEST_00000,201807,22151,11441,4931,49063,13852,02.50만원+
1,TEST_00001,201807,32878,20522,10152,7771,11065,02.50만원+
2,TEST_00002,201807,71867,50508,13223,73003,27071,01.100만원+
3,TEST_00003,201807,4986,4604,2112,7421,4827,04.10만원+
4,TEST_00004,201807,10758,6788,4406,10493,8011,03.30만원+
...,...,...,...,...,...,...,...,...
599995,TEST_99995,201812,0,0,0,0,0,09.미사용
599996,TEST_99996,201812,2237,1256,359,2631,1231,05.10만원-
599997,TEST_99997,201812,0,0,0,0,0,09.미사용
599998,TEST_99998,201812,108420,48141,21273,423882,63592,01.100만원+
599999,TEST_99999,201812,105,56,18,-885,-574,05.10만원-

In [20]:
merged_test_df.to_csv('test_C,D,notCD (변수선택).csv', index=False, encoding='utf-8-sig')