In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob

# 경고 뜨지 않게 설정
import warnings
warnings.filterwarnings('ignore')

# 그래프 설정
sns.set()

# 그래프 기본 설정
plt.rc('font', family='NanumGothic')  # Colab용

plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 데이터 전처리 알고리즘
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 학습용과 검증용으로 나누는 함수
from sklearn.model_selection import train_test_split

# 교차 검증
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 데이터를 불러온다.

In [3]:
train_df = pd.read_parquet('/content/drive/MyDrive/파이널 프로젝트/E_NotE/selected(E_NotE)_all_train.parquet')
test_df = pd.read_parquet('/content/drive/MyDrive/파이널 프로젝트/E_NotE/selected(E_NotE)_all_test.parquet')

display(train_df)
display(test_df)

,기준년월,ID,Group,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수,청구금액_R6M,...,정상입금원금_B0M,이용개월수_전체_R3M,정상입금원금_B2M,정상입금원금_B5M,이용금액대,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,Not_E,196,3681,196,1,1,26,88693,...,6335,3,16125,9205,01.100만원+,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
1,201807,TRAIN_000001,E,13475,13323,13475,1,1,46,16861,...,5198,3,2420,2546,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2,201807,TRAIN_000002,Not_E,23988,24493,23988,1,1,28,165221,...,12564,3,14448,16949,01.100만원+,30회 이상,10회 이상,10회 이상,1회 이상,1회 이상
3,201807,TRAIN_000003,Not_E,3904,5933,3904,1,1,1,127371,...,7639,3,13043,8418,01.100만원+,1회 이상,1회 이상,1회 이상,10회 이상,10회 이상
4,201807,TRAIN_000004,E,1190,0,0,1,0,-2,155,...,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,201812,TRAIN_399995,E,10755,5640,7267,1,0,3,0,...,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2399996,201812,TRAIN_399996,Not_E,27636,26357,27636,1,1,38,99849,...,9705,3,10764,21831,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2399997,201812,TRAIN_399997,Not_E,23187,17171,23187,1,1,33,41073,...,5346,3,6106,3269,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2399998,201812,TRAIN_399998,E,0,0,0,0,0,-2,0,...,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상
2399999,201812,TRAIN_399999,E,21463,6984,21463,2,2,-2,19948,...,2662,3,3173,3647,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상

,기준년월,ID,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,이용금액_오프라인_B0M,...,청구서발송여부_B0,이용개월수_전체_R3M,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,이용카드수_신용,정상입금원금_B5M,_1순위카드이용건수
0,201807,TEST_00000,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,9877,...,1,2,48,0,2713,5,1172,2,1504,51
1,201807,TEST_00001,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,4006,...,1,3,14,0,1321,6,4509,1,2763,40
2,201807,TEST_00002,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,11298,...,1,3,151,1,7271,6,11366,2,11267,154
3,201807,TEST_00003,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,976,...,1,3,27,0,2043,5,875,1,0,105
4,201807,TEST_00004,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,4017,...,1,3,31,0,1364,6,1618,2,1347,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,201812,TEST_99995,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,...,0,0,0,12,0,0,0,0,0,-2
599996,201812,TEST_99996,05.10만원-,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,1회 이상,407,...,1,3,13,0,0,6,252,1,302,4
599997,201812,TEST_99997,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,...,0,0,0,12,0,0,0,0,0,6
599998,201812,TEST_99998,01.100만원+,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,1회 이상,15388,...,1,3,197,0,16296,6,2751,4,6215,185
599999,201812,TEST_99999,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,8,...,1,3,4,2,0,6,18,2,16,0

### 범주형 컬럼 인코딩

In [4]:
# train 데이터를 복사 (원본 보존)
train_df2 = train_df.copy()
test_df2 = test_df.copy()

In [5]:
# train 데이터에서 Group 컬럼 제거 (VIF 분석용)
train_df2.drop(columns=['Group'], inplace=True)

In [6]:
# 인코딩할 범주형 컬럼 목록
categorical_columns = [
    '이용금액대', '할인건수_R3M', '방문횟수_앱_R6M', '방문횟수_PC_R6M',
    '방문일수_PC_R6M', '인입횟수_ARS_R6M', '이용메뉴건수_ARS_R6M'
]

# 각 범주형 컬럼 factorize
for col in categorical_columns:
    # train 기준으로 인코딩
    train_df2[col], uniques = train_df2[col].factorize()

    # test에도 동일한 매핑 적용
    mapping = {category: code for code, category in enumerate(uniques)}

    # test 데이터 매핑
    test_df2[col] = test_df2[col].map(mapping)

    # test에 없는 새로운 값 처리 (예: NaN이면 -1로)
    test_df2[col] = test_df2[col].fillna(-1).astype(int)

# 결과 확인
display(train_df2.head())
display(test_df2.head())

,기준년월,ID,이용금액_R3M_신용체크,_1순위카드이용금액,이용금액_R3M_신용,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수,청구금액_R6M,청구금액_R3M,...,정상입금원금_B0M,이용개월수_전체_R3M,정상입금원금_B2M,정상입금원금_B5M,이용금액대,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,201807,TRAIN_000000,196,3681,196,1,1,26,88693,46588,...,6335,3,16125,9205,0,0,0,0,0,0
1,201807,TRAIN_000001,13475,13323,13475,1,1,46,16861,10530,...,5198,3,2420,2546,1,0,0,0,1,1
2,201807,TRAIN_000002,23988,24493,23988,1,1,28,165221,85931,...,12564,3,14448,16949,0,1,1,1,1,1
3,201807,TRAIN_000003,3904,5933,3904,1,1,1,127371,61518,...,7639,3,13043,8418,0,0,0,0,0,0
4,201807,TRAIN_000004,1190,0,0,1,0,-2,155,0,...,0,0,0,0,2,0,0,0,1,1

,기준년월,ID,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문횟수_PC_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,이용금액_오프라인_B0M,...,청구서발송여부_B0,이용개월수_전체_R3M,이용건수_오프라인_R3M,이용후경과월_신용,_2순위업종_이용금액,이용개월수_신용_R6M,정상입금원금_B2M,이용카드수_신용,정상입금원금_B5M,_1순위카드이용건수
0,201807,TEST_00000,4,0,0,0,0,1,1,9877,...,1,2,48,0,2713,5,1172,2,1504,51
1,201807,TEST_00001,4,0,0,0,0,1,1,4006,...,1,3,14,0,1321,6,4509,1,2763,40
2,201807,TEST_00002,0,0,0,0,0,1,1,11298,...,1,3,151,1,7271,6,11366,2,11267,154
3,201807,TEST_00003,3,0,0,0,0,1,1,976,...,1,3,27,0,2043,5,875,1,0,105
4,201807,TEST_00004,1,0,0,0,0,1,1,4017,...,1,3,31,0,1364,6,1618,2,1347,52

# Train_VIF

In [7]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# '기준년월'과 'ID' 컬럼 제외한 나머지 컬럼을 선택
vif_X = train_df2.drop(['기준년월', 'ID'], axis=1)

# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# 결과 출력
vif

                    변수            VIF
0                const      80.769126
1        이용금액_R3M_신용체크      14.302210
2           _1순위카드이용금액      42.377954
3          이용금액_R3M_신용      36.301227
4           이용카드수_신용체크      10.875651
5             이용카드수_신용      14.594127
6           _1순위카드이용건수      66.377201
7             청구금액_R6M      12.653692
8             청구금액_R3M      25.800947
9              청구금액_B0      17.275878
10          청구서발송여부_B0       8.021022
11            할인건수_R3M       1.550223
12       이용금액_오프라인_B0M      11.078891
13       이용금액_오프라인_R3M      12.274992
14       이용금액_오프라인_R6M       9.761961
15       이용건수_오프라인_B0M      37.154498
16       _2순위쇼핑업종_이용금액       9.179971
17       _3순위쇼핑업종_이용금액       8.742899
18         _3순위업종_이용금액       6.454840
19       이용건수_오프라인_R3M      21.065283
20         _2순위업종_이용금액       5.997765
21       이용개월수_신용_R12M     110.515779
22       이용개월수_신판_R12M     173.968807
23      이용개월수_일시불_R12M     125.851067
24        이용금액_일시불_R6M      64.646419
25        이용금액_일시불_R3M      91.685676
26        이용금액_일시불_B0M      70.715513
27        이용건수_신용_R12M   51842.251548
28        이용건수_신판_R12M   61086.855973
29       이용건수_일시불_R12M    9227.726014
30              이용가맹점수      27.792712
31       이용금액_일시불_R12M      15.461214
32         이용건수_신용_R6M   85214.633695
33         이용건수_신용_B0M   26883.571481
34         이용건수_신판_R6M  108287.559605
35         이용건수_신용_R3M   60650.133839
36         이용건수_신판_B0M   43263.334226
37        이용건수_일시불_R6M   23092.484223
38         이용건수_신판_R3M   91785.664013
39        이용건수_일시불_B0M   16471.286945
40        이용건수_일시불_R3M   31674.874665
41           이용후경과월_신용       4.000993
42        이용개월수_신용_R6M      14.754443
43          정상청구원금_B5M      20.471176
44          정상청구원금_B0M      33.783570
45          정상청구원금_B2M      30.137941
46  연속유실적개월수_기본_24M_카드       3.984263
47        이용개월수_전체_R6M      22.600292
48          정상입금원금_B0M      17.845190
49        이용개월수_전체_R3M      26.797938
50          정상입금원금_B2M      15.585754
51          정상입금원금_B5M      11.634673
52               이용금액대       1.886307
53          방문횟수_앱_R6M       1.248139
54         방문횟수_PC_R6M      10.593546
55         방문일수_PC_R6M      10.541761
56        인입횟수_ARS_R6M       1.404087
57      이용메뉴건수_ARS_R6M       1.245765

In [8]:
# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수            VIF
34         이용건수_신판_R6M  108287.559605
38         이용건수_신판_R3M   91785.664013
32         이용건수_신용_R6M   85214.633695
28        이용건수_신판_R12M   61086.855973
35         이용건수_신용_R3M   60650.133839
27        이용건수_신용_R12M   51842.251548
36         이용건수_신판_B0M   43263.334226
40        이용건수_일시불_R3M   31674.874665
33         이용건수_신용_B0M   26883.571481
37        이용건수_일시불_R6M   23092.484223
39        이용건수_일시불_B0M   16471.286945
29       이용건수_일시불_R12M    9227.726014
22       이용개월수_신판_R12M     173.968807
23      이용개월수_일시불_R12M     125.851067
21       이용개월수_신용_R12M     110.515779
25        이용금액_일시불_R3M      91.685676
0                const      80.769126
26        이용금액_일시불_B0M      70.715513
6           _1순위카드이용건수      66.377201
24        이용금액_일시불_R6M      64.646419
2           _1순위카드이용금액      42.377954
15       이용건수_오프라인_B0M      37.154498
3          이용금액_R3M_신용      36.301227
44          정상청구원금_B0M      33.783570
45          정상청구원금_B2M      30.137941
30              이용가맹점수      27.792712
49        이용개월수_전체_R3M      26.797938
8             청구금액_R3M      25.800947
47        이용개월수_전체_R6M      22.600292
19       이용건수_오프라인_R3M      21.065283
43          정상청구원금_B5M      20.471176
48          정상입금원금_B0M      17.845190
9              청구금액_B0      17.275878
50          정상입금원금_B2M      15.585754
31       이용금액_일시불_R12M      15.461214
42        이용개월수_신용_R6M      14.754443
5             이용카드수_신용      14.594127
1        이용금액_R3M_신용체크      14.302210
7             청구금액_R6M      12.653692
13       이용금액_오프라인_R3M      12.274992
51          정상입금원금_B5M      11.634673
12       이용금액_오프라인_B0M      11.078891
4           이용카드수_신용체크      10.875651
54         방문횟수_PC_R6M      10.593546
55         방문일수_PC_R6M      10.541761
14       이용금액_오프라인_R6M       9.761961
16       _2순위쇼핑업종_이용금액       9.179971
17       _3순위쇼핑업종_이용금액       8.742899
10          청구서발송여부_B0       8.021022
18         _3순위업종_이용금액       6.454840
20         _2순위업종_이용금액       5.997765
41           이용후경과월_신용       4.000993
46  연속유실적개월수_기본_24M_카드       3.984263
52               이용금액대       1.886307
11            할인건수_R3M       1.550223
56        인입횟수_ARS_R6M       1.404087
53          방문횟수_앱_R6M       1.248139
57      이용메뉴건수_ARS_R6M       1.245765

In [9]:
# train 데이터를 복사 (원본 보존)
train_df3 = train_df2.copy()

In [10]:
# '기준년월'과 'ID' 컬럼을 제외한 나머지 컬럼을 선택
vif_X = train_df3.drop(['기준년월', 'ID',
                        '이용건수_신판_R6M', '이용건수_신판_B0M', '이용건수_신판_R3M',
                        '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M',
                        '이용건수_일시불_R6M', '이용건수_일시불_B0M', '이용건수_일시불_R3M',
                        '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용금액_일시불_R12M',
                        '_1순위카드이용건수',
                        '이용건수_오프라인_R3M',
                        '정상청구원금_B0M', '정상청구원금_B2M',
                        '청구금액_R3M', '청구금액_B0',
                        '정상입금원금_B2M', '정상입금원금_B5M',

                       ], axis=1)


# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수           VIF
22        이용건수_신판_R12M  11371.727709
21        이용건수_신용_R12M   9489.046389
23       이용건수_일시불_R12M   2547.132610
18       이용개월수_신판_R12M    172.139010
19      이용개월수_일시불_R12M    124.883225
17       이용개월수_신용_R12M    108.930590
0                const     79.232786
3          이용금액_R3M_신용     34.860310
2           _1순위카드이용금액     30.516549
31        이용개월수_전체_R3M     26.287392
24              이용가맹점수     23.631674
12       이용건수_오프라인_B0M     23.095296
29        이용개월수_전체_R6M     21.864406
20        이용금액_일시불_R6M     20.426059
1        이용금액_R3M_신용체크     14.118900
5             이용카드수_신용     13.747995
26        이용개월수_신용_R6M     12.570038
10       이용금액_오프라인_R3M     10.799999
4           이용카드수_신용체크     10.704588
34         방문횟수_PC_R6M     10.577989
35         방문일수_PC_R6M     10.524984
9        이용금액_오프라인_B0M     10.322777
13       _2순위쇼핑업종_이용금액      9.111132
14       _3순위쇼핑업종_이용금액      8.674008
11       이용금액_오프라인_R6M      8.537213
7           청구서발송여부_B0      7.821161
27          정상청구원금_B5M      7.644681
15         _3순위업종_이용금액      6.308836
6             청구금액_R6M      5.953752
16         _2순위업종_이용금액      5.771764
30          정상입금원금_B0M      4.549098
28  연속유실적개월수_기본_24M_카드      3.939787
25           이용후경과월_신용      3.936536
32               이용금액대      1.831417
8             할인건수_R3M      1.543084
36        인입횟수_ARS_R6M      1.382145
37      이용메뉴건수_ARS_R6M      1.234158
33          방문횟수_앱_R6M      1.205915

In [11]:
# Nanum Gothic 폰트 설치
!apt-get update -qq
!apt-get install -y fonts-nanum

# matplotlib 한글 폰트 설정
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# matplotlib 폰트 캐시 재생성
fm._load_fontmanager(try_read_cache=False)

plt.rc('font', family='NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

print("✅ 한글 폰트 설정 완료!")

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-nanum is already the newest version (20200506-1).
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.

WARNING:matplotlib.font_manager:Matplotlib is building the font cache; this may take a moment.

✅ 한글 폰트 설정 완료!

In [14]:
# train 데이터를 복사 (원본 보존)
train_df4 = train_df3.copy()

In [17]:
# '기준년월'과 'ID' 컬럼을 제외한 나머지 컬럼을 선택
vif_X = train_df4.drop(['기준년월', 'ID',
                        '이용건수_신판_R6M', '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_신판_R12M',
                        '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M',
                        '이용건수_일시불_R6M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '이용건수_일시불_R12M',
                        '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용금액_일시불_R12M',
                        '_1순위카드이용건수',
                        '이용건수_오프라인_R3M','이용건수_오프라인_B0M',
                        '정상청구원금_B0M', '정상청구원금_B2M',
                        '청구금액_R3M', '청구금액_B0',
                        '정상입금원금_B2M', '정상입금원금_B5M',
                        '이용개월수_신판_R12M', '이용개월수_일시불_R12M'

                       ], axis=1)


# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수        VIF
0                const  76.119240
3          이용금액_R3M_신용  34.693804
2           _1순위카드이용금액  28.147180
26        이용개월수_전체_R3M  26.244835
24        이용개월수_전체_R6M  21.523794
16       이용개월수_신용_R12M  14.426485
1        이용금액_R3M_신용체크  14.110293
17        이용금액_일시불_R6M  14.054961
19              이용가맹점수  13.972208
5             이용카드수_신용  13.713250
21        이용개월수_신용_R6M  12.090296
4           이용카드수_신용체크  10.673342
10       이용금액_오프라인_R3M  10.648980
29         방문횟수_PC_R6M  10.574546
30         방문일수_PC_R6M  10.522085
9        이용금액_오프라인_B0M  10.038383
12       _2순위쇼핑업종_이용금액   8.830445
13       _3순위쇼핑업종_이용금액   8.609984
11       이용금액_오프라인_R6M   8.298837
7           청구서발송여부_B0   7.645658
18        이용건수_신용_R12M   7.253589
22          정상청구원금_B5M   6.524171
14         _3순위업종_이용금액   6.268473
15         _2순위업종_이용금액   5.632425
6             청구금액_R6M   5.190899
25          정상입금원금_B0M   4.459832
20           이용후경과월_신용   3.869730
23  연속유실적개월수_기본_24M_카드   3.803066
27               이용금액대   1.762738
8             할인건수_R3M   1.537210
31        인입횟수_ARS_R6M   1.353501
32      이용메뉴건수_ARS_R6M   1.234102
28          방문횟수_앱_R6M   1.173201

In [20]:
# train 데이터를 복사 (원본 보존)
train_df5 = train_df4.copy()

In [24]:
# '기준년월'과 'ID' 컬럼을 제외한 나머지 컬럼을 선택
vif_X = train_df4.drop(['기준년월', 'ID',
                        '이용건수_신판_R6M', '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_신판_R12M',
                        '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M',
                        '이용건수_일시불_R6M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '이용건수_일시불_R12M',
                        '이용금액_R3M_신용',
                        '이용금액_오프라인_R3M',
                        '이용금액_일시불_R3M', '이용금액_일시불_B0M', '이용금액_일시불_R12M','이용금액_일시불_R6M',
                        '_1순위카드이용건수','_1순위카드이용금액',
                        '이용건수_오프라인_R3M','이용건수_오프라인_B0M',
                        '정상청구원금_B0M', '정상청구원금_B2M',
                        '청구금액_R3M', '청구금액_B0',
                        '정상입금원금_B2M', '정상입금원금_B5M',
                        '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_전체_R3M', '이용개월수_신용_R6M',
                        '이용가맹점수', '방문일수_PC_R6M'

                       ], axis=1)


# 상수항 추가 (VIF 계산을 위한 준비)
vif_X2 = sm.add_constant(vif_X)

# VIF 계산
vif = pd.DataFrame()
vif['변수'] = vif_X2.columns
vif['VIF'] = [variance_inflation_factor(vif_X2.values, i) for i in range(vif_X2.shape[1])]

# pandas 출력 옵션 설정
pd.set_option('display.max_rows', None)  # 모든 행을 출력

# VIF 값을 기준으로 내림차순 정렬
vif_sorted = vif.sort_values(by='VIF', ascending=False)

# VIF 결과 출력
print(vif_sorted)

                    변수        VIF
0                const  72.978726
2           이용카드수_신용체크   8.777212
13       이용개월수_신용_R12M   8.582676
3             이용카드수_신용   8.560699
9        _2순위쇼핑업종_이용금액   8.515973
18        이용개월수_전체_R6M   7.880812
10       _3순위쇼핑업종_이용금액   7.865674
7        이용금액_오프라인_B0M   7.110249
1        이용금액_R3M_신용체크   6.460732
11         _3순위업종_이용금액   5.982093
16          정상청구원금_B5M   5.891049
5           청구서발송여부_B0   5.396280
8        이용금액_오프라인_R6M   5.378480
12         _2순위업종_이용금액   5.350287
4             청구금액_R6M   5.130077
19          정상입금원금_B0M   4.327861
17  연속유실적개월수_기본_24M_카드   3.718332
15           이용후경과월_신용   3.462953
14        이용건수_신용_R12M   3.309877
20               이용금액대   1.688882
6             할인건수_R3M   1.350977
23        인입횟수_ARS_R6M   1.334619
24      이용메뉴건수_ARS_R6M   1.233537
21          방문횟수_앱_R6M   1.147786
22         방문횟수_PC_R6M   1.069283

# 컬럼 제거

In [7]:
# 제거할 컬럼 리스트
drop_cols = [
    '기준년월', 'ID',
    '이용건수_신판_R6M', '이용건수_신판_B0M', '이용건수_신판_R3M', '이용건수_신판_R12M',
    '이용건수_신용_R6M', '이용건수_신용_B0M', '이용건수_신용_R3M',
    '이용건수_일시불_R6M', '이용건수_일시불_B0M', '이용건수_일시불_R3M', '이용건수_일시불_R12M',
    '이용금액_R3M_신용', '이용금액_오프라인_R3M', '이용금액_일시불_R3M', '이용금액_일시불_R12M', '이용금액_일시불_R6M',
    '_1순위카드이용금액', '이용건수_오프라인_R3M', '이용금액_오프라인_B0M',
    '정상청구원금_B0M', '정상청구원금_B2M', '청구금액_R3M', '청구금액_B0',
    '정상입금원금_B2M', '정상입금원금_B5M',
    '이용개월수_신판_R12M', '이용개월수_일시불_R12M', '이용개월수_전체_R3M', '이용개월수_신용_R6M',
    '이용가맹점수', '방문횟수_PC_R6M'
]

# train_df 컬럼 제거
train_df.drop(columns=drop_cols, axis=1, inplace=True)

# test_df 컬럼 제거
test_df.drop(columns=drop_cols, axis=1, inplace=True)

# 확인
display(train_df)
display(test_df)

,Group,이용금액_R3M_신용체크,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,이용금액_오프라인_R6M,이용건수_오프라인_B0M,...,이용후경과월_신용,정상청구원금_B5M,연속유실적개월수_기본_24M_카드,이용개월수_전체_R6M,정상입금원금_B0M,이용금액대,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,Not_E,196,1,1,26,88693,1,1회 이상,11097,7,...,0,14958,13,6,6335,01.100만원+,1회 이상,1회 이상,10회 이상,10회 이상
1,E,13475,1,1,46,16861,1,1회 이상,18638,15,...,0,3367,12,6,5198,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상
2,Not_E,23988,1,1,28,165221,1,1회 이상,29192,12,...,0,23963,8,5,12564,01.100만원+,30회 이상,10회 이상,1회 이상,1회 이상
3,Not_E,3904,1,1,1,127371,1,1회 이상,18056,8,...,0,19614,5,6,7639,01.100만원+,1회 이상,1회 이상,10회 이상,10회 이상
4,E,1190,1,0,-2,155,0,1회 이상,787,0,...,6,0,0,1,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,E,10755,1,0,3,0,0,1회 이상,0,0,...,8,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
2399996,Not_E,27636,1,1,38,99849,1,1회 이상,60373,7,...,0,23742,17,6,9705,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상
2399997,Not_E,23187,1,1,33,41073,1,1회 이상,32036,13,...,1,4125,24,6,5346,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상
2399998,E,0,0,0,-2,0,0,1회 이상,0,0,...,12,507,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
2399999,E,21463,2,2,-2,19948,1,1회 이상,4537,7,...,0,4514,5,6,2662,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상

,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,정상청구원금_B5M,이용금액_R3M_신용체크,이용개월수_신용_R12M,연속유실적개월수_기본_24M_카드,...,_2순위쇼핑업종_이용금액,이용카드수_신용체크,_3순위쇼핑업종_이용금액,정상입금원금_B0M,_3순위업종_이용금액,청구서발송여부_B0,이용후경과월_신용,_2순위업종_이용금액,이용카드수_신용,_1순위카드이용건수
0,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,3919,21458,10,5,...,854,2,643,3680,1880,1,0,2713,2,51
1,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,5723,18681,9,8,...,1154,2,1033,8726,1278,1,0,1321,1,40
2,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,11267,40758,12,24,...,1178,2,1094,11297,2680,1,1,7271,2,154
3,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,5255,9,5,...,804,1,634,1375,605,1,0,2043,1,105
4,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1347,16148,12,20,...,774,3,760,3951,1054,1,0,1364,2,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,-2
599996,05.10만원-,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,992,3110,10,8,...,0,1,0,205,0,1,0,0,1,4
599997,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,6
599998,01.100만원+,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,27335,173263,12,24,...,2208,6,1965,0,4612,1,0,16296,4,185
599999,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,25,3016,12,24,...,0,2,0,20,0,1,2,0,2,0

# 전처리 완료 데이터 저장

In [8]:
train_df.to_csv('/content/drive/MyDrive/파이널 프로젝트/E_NotE/(E_NotE)_train.csv', index=False)
test_df.to_csv('/content/drive/MyDrive/파이널 프로젝트/E_NotE/(E_NotE)_test.csv', index=False)

In [9]:
train_df2 = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/E_NotE/(E_NotE)_train.csv')
test_df2 = pd.read_csv('/content/drive/MyDrive/파이널 프로젝트/E_NotE/(E_NotE)_test.csv')
display(train_df2)
display(test_df2)

,Group,이용금액_R3M_신용체크,이용카드수_신용체크,이용카드수_신용,_1순위카드이용건수,청구금액_R6M,청구서발송여부_B0,할인건수_R3M,이용금액_오프라인_R6M,이용건수_오프라인_B0M,...,이용후경과월_신용,정상청구원금_B5M,연속유실적개월수_기본_24M_카드,이용개월수_전체_R6M,정상입금원금_B0M,이용금액대,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M
0,Not_E,196,1,1,26,88693,1,1회 이상,11097,7,...,0,14958,13,6,6335,01.100만원+,1회 이상,1회 이상,10회 이상,10회 이상
1,E,13475,1,1,46,16861,1,1회 이상,18638,15,...,0,3367,12,6,5198,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상
2,Not_E,23988,1,1,28,165221,1,1회 이상,29192,12,...,0,23963,8,5,12564,01.100만원+,30회 이상,10회 이상,1회 이상,1회 이상
3,Not_E,3904,1,1,1,127371,1,1회 이상,18056,8,...,0,19614,5,6,7639,01.100만원+,1회 이상,1회 이상,10회 이상,10회 이상
4,E,1190,1,0,-2,155,0,1회 이상,787,0,...,6,0,0,1,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2399995,E,10755,1,0,3,0,0,1회 이상,0,0,...,8,0,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
2399996,Not_E,27636,1,1,38,99849,1,1회 이상,60373,7,...,0,23742,17,6,9705,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상
2399997,Not_E,23187,1,1,33,41073,1,1회 이상,32036,13,...,1,4125,24,6,5346,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상
2399998,E,0,0,0,-2,0,0,1회 이상,0,0,...,12,507,0,0,0,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상
2399999,E,21463,2,2,-2,19948,1,1회 이상,4537,7,...,0,4514,5,6,2662,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상

,이용금액대,할인건수_R3M,방문횟수_앱_R6M,방문일수_PC_R6M,인입횟수_ARS_R6M,이용메뉴건수_ARS_R6M,정상청구원금_B5M,이용금액_R3M_신용체크,이용개월수_신용_R12M,연속유실적개월수_기본_24M_카드,...,_2순위쇼핑업종_이용금액,이용카드수_신용체크,_3순위쇼핑업종_이용금액,정상입금원금_B0M,_3순위업종_이용금액,청구서발송여부_B0,이용후경과월_신용,_2순위업종_이용금액,이용카드수_신용,_1순위카드이용건수
0,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,3919,21458,10,5,...,854,2,643,3680,1880,1,0,2713,2,51
1,02.50만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,5723,18681,9,8,...,1154,2,1033,8726,1278,1,0,1321,1,40
2,01.100만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,11267,40758,12,24,...,1178,2,1094,11297,2680,1,1,7271,2,154
3,04.10만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,5255,9,5,...,804,1,634,1375,605,1,0,2043,1,105
4,03.30만원+,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,1347,16148,12,20,...,774,3,760,3951,1054,1,0,1364,2,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
599995,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,-2
599996,05.10만원-,1회 이상,10회 이상,1회 이상,1회 이상,1회 이상,992,3110,10,8,...,0,1,0,205,0,1,0,0,1,4
599997,09.미사용,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,0,0,0,0,...,0,0,0,0,0,0,12,0,0,6
599998,01.100만원+,1회 이상,40회 이상,1회 이상,1회 이상,1회 이상,27335,173263,12,24,...,2208,6,1965,0,4612,1,0,16296,4,185
599999,05.10만원-,1회 이상,1회 이상,1회 이상,1회 이상,1회 이상,25,3016,12,24,...,0,2,0,20,0,1,2,0,2,0